### ISSUE TITLE
Reject attempts to create API keys with duplicate tokens

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1005]
Since users can now specify API key tokens explicitly, we might as well reject attempts to create multiple keys with the same token. As things stand today, first-in will win, but the second, ignored key will likely create confusion.

We should consider rejecting attempts to create keys with duplicated _titles_, however it's possible some workflows already take advantage of this and will be broken by a change to the default behavior.

**Comment by coderpatros** [comment]
Something I have been thinking about is automated rolling of tokens.

So I do envisage the duplicate titles scenario being a normal workflow. i.e. create the new "Service X" token, update the secret for consumption by service x, remove old "Service X" token.
