### ISSUE TITLE
Connection_IdleTimeOut in System32/LogFiles/HttpErr

### ISSUE THREAD

**Issue by seFausto** [datalust/seq-tickets#1016]
**Describe the bug**
Our seq server has run out of space due to windows logging many Connection Idle timeouts in HttpErr folder. We have gone in and deleted around 50 gb worth of log files.

**To Reproduce**
1. Log events using Serilog NuGet Package in C#
2. Wait to have many in connection_idletimeouts logged
3. See error

**Expected behavior**
Seq should not log Connection Idle timeouts for every connection that is open.

**Environment (please complete the following information):**
 - OS: Windows 
 - Browser: Chrome
 - Seq Version  - Seq 2020.1.4292 (But has happened on previous versions)
 - Using Docker? No

**Additional context**
A solution that we found is to turn off IIS logging using RegEdit using the details in this [link](https://docs.microsoft.com/nl-be/troubleshoot/aspnet/error-logging-http-apis)

**Comment by nblumhardt** [comment]
As these are the Windows HTTP stack's own log files, we're not confident we should take ownership of them/delete them in case they're required for auditing purposes. For now we're closing this as "a Windows sysadmin" task, but we're also looking for ways to avoid emitting them in the first place (such as switching away from HTTP.sys, by default) and will keep our eye on this in future.

Thanks for the feedback, @seFausto !
