### ISSUE TITLE
Limit Seq cache size to when available RAM is less than 4GiB

### ISSUE THREAD

**Issue by larenelg** [datalust/seq-tickets#1020]
Since the release of 2020.1 we've had several reports of `System.OutOfMemory` exceptions being thrown during various operations, particularly on machines with lower available RAM.

We're aiming to improve Seq's stability on smaller machines in 2020.2 by defaulting target system memory utilization to a maximum of 80% of total memory (0.8) for machines with less than 4 GiB of RAM, and 70% for machines with less than 3 GiB.

This default can be overridden by explicitly specifying a RAM target, e.g. to a higher value:

```
seq config set -k cache.systemRamTarget -v 0.9
seq restart
```

This setting can also be applied through the `SEQ_CACHE_SYSTEMRAMTARGET` environment variable.

**Comment by svrooij** [comment]
@larenelg @nblumhardt We are running this new version 2020.2 inside a docker container on virtual server with 4 gb of ram, and we still have a lot of memory issues.
How do I generate and send you goods logs that actually help?

And is seems that this issue isn't fixed in the new version.

**Comment by nblumhardt** [comment]
Hi @svrooij - thanks for the heads-up.

Do you have memory and swap set explicitly for the container, e.g. `--memory=3g --memory-swap=3g` (or some similar limit that is within the available resources?) Without this, Seq will sometimes "see" more memory available than it is allowed to use.

Setting `-e SEQ_CACHE_SYSTEMRAMTARGET=0.7` may also help if the above does not (but setting the memory and swap limits is usually necessary in all cases).

If neither of the above helps, can you please send more information about your container hosting environment, and a diagnostic report, to `support@`? Thanks!
