### ISSUE TITLE
Helm deployment template uses deprecated apiVersion

### ISSUE THREAD

**Issue by mburumaxwell** [datalust/seq-tickets#1021]
**Describe the bug**
Helm chart attempts to deploy a `Deployment` using `apiVersion` set to `v1` which is deprecated.

**To Reproduce**
Run `helm install stable/seq` on a Kubernetes cluster running version 1.16.10. You get the error below:

```console
Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Resources: v1.ResourceRequirements.Requests: Limits: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|mory":"1g"},"request|..., bigger context ...|utSeconds":1},"resources":{"limits":{"memory":"1g"},"requests":{"memory":"256M"}},"startupProbe":{"f|...
```

**Expected behavior**
The templates/deployment.yaml file should fix apiVersion to `apps/v1`

**Screenshots**
None

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Seq Version: 2020.1
 - Using Docker? Yes / No
 - Helm Package version: 2.2.0 (August 25, 2020)

**Additional context**
N/A

**Comment by mburumaxwell** [comment]
Turns out the issue is elsewhere. Copied resource limits from docs written as `4g` while it should be `4Gi`. Closing the issue

**Comment by KodrAus** [comment]
Thanks for pointing that out @mburumaxwell! I've fixed up the docs to use the correct units.
