### ISSUE TITLE
Invalid API keys should not be recorded in the Ingestion Log

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1026]
When events arrive at Seq's ingestion endpoint with invalid API keys, the events and keys are recorded for diagnostic purposes in the Ingestion Log, so that administrative users can track down the source of the events and fix the configuration problem.

Although this is benign from the standpoint of a single Seq instance (the keys are invalid), this could lead to unintended information leakage if, for example, a production application is accidentally pointed at a test/non-production log server, and so on.

In line with treatment of valid API keys, these should be recorded only as four-character prefixes.

**Comment by nblumhardt** [comment]
Fixed in 2020.3

**Comment by andymac4182** [comment]
Is there a way to turn this off? When setting up a new server I use this to find the apps using old keys.

**Comment by nblumhardt** [comment]
Thanks for the note. The log entries will still include the four character API key prefix - will that be enough to track them down?

**Comment by andymac4182** [comment]
I was loading them in with an attached property so I could find the logs as sometimes people put them in places they aren't meant to haha

**Comment by andymac4182** [comment]
I would be happy if I could attach properties to Invalid API keys in the same way I could Unauthenticated API keys. The main thing I would be trying to solve is finding the exact logs that caused that issue
