### ISSUE TITLE
Ingestion Pipeline

### ISSUE THREAD

**Issue by CrossBound** [datalust/seq-tickets#1028]
Maybe this is asking too much (but then again... Seq is one of the best quality products I've seen) but it would be fantastic if it were possible to have a data ingestion pipeline which would allow custom middleware components to  filter/operate on incoming logs in sequence. In concept this is identical to the way ASP.NET Core handles HTTP requests, but this would be for operating on logs. Basically at the start of the pipeline would be the input (native API or custom input app), then one or more middleware components in an ordered sequence, then finally the logs land in the log stream. 

Right now Seq already supports custom apps as a _source_  of logs, but once the logs are created by the app there is not a hook to be able to support custom processes. Example usages might be attaching custom properties based on the event (not currently possible), filtering based on the data (possible if you can make it an expression), and transforming the data before it reaches the stream. 

In fact, combined with the ability to install middleware from nuget (like we can install input apps from nuget) middleware would enable virtually any data source to be pointed at Seq and then turned into structured logging through middleware apps.

Use Case 1:
Right now we can ingest Syslog via the Seq.Input.Syslog package, but any custom data in the message body is not treated as structured data so it requires text processing (a performance hit I assume) to query it. A middleware component could access the event data & properties and parse out the necessary fields. I know issue https://github.com/datalust/squiflog/issues/23 already suggests one possible option, but it has a very focused solution. Middleware would enable many additional scenarios. 

Use Case 2:
An incoming stream needs to have a different property attached based on the data, Going back to the Syslog input example, we have a WAF outputting logs for multiple applications that are behind it. We would need a way to sort them into different buckets (in my case we tag each log with a "System" property which identifies the application) based on which application the log is for. Currently this is only possible by running multiple instances of the Syslog input app with different filters and the same stream being replicated to all of them (very impractical especially with a high volume input stream).

**Comment by nblumhardt** [comment]
Thanks, @CrossBound - we've had similar thoughts recently and will explore this further 👍

**Comment by nblumhardt** [comment]
We're very keen to support this feature, but don't expect it will make it into one of the near-future milestones, so to keep the issue list manageable we're closing the ticket for now. We'll definitely revisit this down the track.

Thanks for the feedback, @CrossBound !
