### ISSUE TITLE
If no Seq theme preference is set, Seq will match user's OS light/dark preference dynamically.

### ISSUE THREAD

**Issue by larenelg** [datalust/seq-tickets#1030]
Further enhancement to https://github.com/datalust/seq-tickets/issues/996

Currently, only sets user's light/dark preference according to their OS preference, on first login.

Proposing to enhanced the light/dark theme to match the user's OS preference dynamically, e.g. for macOS which switched from light mode in the day to dark mode in the night, Seq should do the same.

This should be the behaviour unless a user deliberately chooses their preferred theme (Seq dark theme is pretty awesome 😎)

**Comment by andymac4182** [comment]
That would be amazing :)

**Comment by nblumhardt** [comment]
When we do this, we should add a `Default` or `Dynamic` option to the theme selector under user theme preferences so that users can undo an explicit selection (it'd just be a label for what is currently the `null` option).
