### ISSUE TITLE
Filters / query string are lost when going through Azure Active Directory login process.

### ISSUE THREAD

**Issue by oliverholliday** [datalust/seq-tickets#1041]
When you're given a link containing a query to a particular set of results the authentication process loses the filters and redirects you back to the 'homepage' dashboard with no filters.

**To Reproduce**
1. Use Seq configured to use Azure Active Directory login integration
2. Log out of Seq
3. Visit a link containing search parameters to a particular set of results 
e.g. http://seq.local/#/events?filter=Stack%20%3D%20%22test%22
4. You are redirected via the login process
5. Once logged in the query is lost and you are sent to the unfiltered home page
e.g. http://seq.local/#/events

**Expected behavior**
The login process would preserve the filters to display the results expected for the link that was clicked.

**Context**
We use Seq very heavily internally and being able to link to a certain application stack / installation is very important to us. We repeatedly get confusion from users who have clicked a link and see a set of results entirely different to that seen by everybody else - because they went through the login process.

**Comment by nblumhardt** [comment]
Thanks for the note; this is a longstanding issue, it's time we gave it another look 👍

**Comment by nblumhardt** [comment]
Hi folks - unfortunately we're going to need to drop this from next week's 2021.2 release.

In the current 2021.2 preview release, however, we've added an experimental feature flag that we hope may offer some clues as to how to reduce the number of logouts for people using AAD with Seq.

It's enabled with:

```
seq config set -k features.enabled -v oidcsavetokens
seq service restart
```

or by setting the `SEQ_FEATURES_ENABLED` environment variable to `oidcsavetokens`.

It would be great if anyone experiencing issues with AAD logouts could try this and let us know whether it helps. Thanks!

cc @janpieterz

**Comment by nblumhardt** [comment]
We're moving this out of the 2021.3 milestone, there are a lot of improvements ready to ship and unfortunately we don't have time remaining to squeeze this one in.

Sorry about postponing this for a second time! We'll consider this a bump up the priority list in our next round of planning.

**Comment by nblumhardt** [comment]
Great news, this one is in 2021.4! Sorry it's taken so long 😅
