### ISSUE TITLE
Distinct tuples of property values

### ISSUE THREAD

**Issue by larenelg** [datalust/seq-tickets#1042]
To be able see all distinct pairings of property values in a query.

```
select distinct(Prop1, Prop2) from stream where Prop='Value'
```

**Comment by nblumhardt** [comment]
This should possibly look like:

```sql
select distinct([Prop1, Prop2]) from stream where Prop='Value'
```

Unfortunately, `distinct` over an array value is special-cased today (retrieves distinct values from within the array), so this doesn't work as expected.

```sql
select distinct({p1: Prop1, p2: Prop2}) from stream where Prop='Value'
```

also seems like it should work, but doesn't ... yet :-D

**Comment by nblumhardt** [comment]
Turns out that distinct over objects does in fact work; we'll leave this as-is, because extending the same behavior to arrays would be a breaking change for existing queries.

![image](https://user-images.githubusercontent.com/342712/98066249-36ed7900-1ea2-11eb-86d2-79453fdd157b.png)
