### ISSUE TITLE
redirectHttpToHttps will only redirect to 443

### ISSUE THREAD

**Issue by iainrobins** [datalust/seq-tickets#1044]
**Describe the bug**
The redirectHttpToHttps setting appears to only redirect to 443 of the host, as opposed to the documented behaviour.

**To Reproduce**
1. Register an SSL Certificate on port 5342 
`seq bind-ssl --port=5342 --thumbprint="‎thumbprint"`
2. Configure an HTTPS and HTTP endpoint - `seq config -k api.listenUris -v https://localhost:5342,http://localhost:5341`
3. Configure HTTPS to HTTP redirect - `seq config -k api.redirectHttpToHttps -v true`
4. Restart Seq to 
5. Navigate to http://localhost:5341, which will attempt to redirect you to https://localhost

**Expected behavior**
The [documentation](https://docs.datalust.co/docs/json-config#apiredirecthttptohttps) suggests it should redirect you to the first HTTPS endpoint listed, however the [feature request](https://github.com/datalust/seq-tickets/issues/541) suggests the current behaviour is what was implemented. The documented behaviour would be preferred.

**Screenshots**
No screenshots

**Environment (please complete the following information):**
 - OS: Windows Server 2016
 - Browser: Chrome, Internet Explorer
 - Seq version: Confirmed on Seq 2020.1.4292 and 2020.3.4761
 - Using Docker? No

**Comment by nblumhardt** [comment]
Thanks Iain, we'll take a look and see what we can do.
