### ISSUE TITLE
Table in dashboard throws “ngRepeat:dupes” error

### ISSUE THREAD

**Issue by yu-jingfeng** [datalust/seq-tickets#1048]
**Describe the bug**
Throws the “ngRepeat:dupes” error when a table column in the dashboard has the same data.
I think you forgot to add `track by $index` to the “ng-repeat” component.
This issue is present in both 5.1 and 2020.3 versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/50724541/97842089-04b50d80-1d22-11eb-844f-22fdfb6bc8ef.png)

**Environment (please complete the following information):**
 - OS: [e.g. Docker]
 - Browser [e.g. Edge 86.0.622.58]
 - Seq Version [e.g. 5.1, 2020.3]
 - Using Docker? Yes

**Comment by nblumhardt** [comment]
Thank you, @yu-jingfeng - great catch 👍
