### ISSUE TITLE
Surface retention policy processing and indexing errors as server status messages

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1051]
In rare instances, storage problems (or bugs!) might cause retention policy processing or indexing to fail.

Currently, these only become visible either through the internal diagnostic report, or through side effects like poor performance or running out of disk space.

When a retention policy processing or indexing attempt fails, Seq should present an error in the server status indicator (that appears as either a warning or error icon in the main navigation bar).

**Comment by DanAvni** [comment]
Nick,

I would even go as far as saying that when an error like this occurs an email should be sent to me.

Also I would like to suggest a page under settings where I can see the list of span files and the status of each one (once it is detected as corrupt it is marked there). I then should be able to go into the file and see some info on the type(s) of corruptions in it and be able to fix them from the UI (e.g. delete the whole file, salvage the readable parts or other possible fixes)

**Comment by nblumhardt** [comment]
Thanks for your thoughts, Dani. At this point we only plan to show a message if a problem has occurred, but we may be able to extend this to more scenarios in future, including via #978 Storage View.

Corruptions are/should be extremely rare events though, so identifying the root cause (e.g. a disk problem, driver configuration issue, etc.) will always be our main aim - working around them is a non-goal for us at this point, as we want to avoid the slippery slope down to accepting/ignoring reliability issues.
