### ISSUE TITLE
Option to copy raw JSON representation of an event directly to the clipboard

### ISSUE THREAD

**Issue by kristofferlindvall** [datalust/seq-tickets#1052]
We have customers with limited read access to logs relating to their systems. Sometimes, they want to bring our attention to a specific event, but they can't seem to make permalinks. This causes the event to sometimes expire before we get to it, or simply be slow to find.

It would be useful if I could give them access to creating permalinks without ability to modify signals and dashboards etc.

**Comment by nblumhardt** [comment]
Hi Kristoffer, thanks for the feedback.

Customizing user roles is something we might address in future, but the work involved is significant right now.

Would it improve your workflow if users could copy the complete raw JSON for an event from the UI? This would be essentially a shortcut to what is exposed as "Download raw JSON" right now.

**Comment by kristofferlindvall** [comment]
Yes, that would be good enough for now

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/98632389-29853280-236b-11eb-87bd-70f5f9cb3405.png)
