### ISSUE TITLE
Support backup to network share

### ISSUE THREAD

**Issue by nskerl** [datalust/seq-tickets#1060]
Is it possible to configure Seq to write backup files to a network share? I was able to configure the path with a share `\\my-server\myshare` but the backups present in the share are not read into the UI and it doesn't appear to write any new backups.

I don't see any errors in the log.

**Comment by nblumhardt** [comment]
I don't know of any issues writing backups to network shares - this should work fine as far as I know. It's strange not to have errors reported in the internal log - are there any entries in there mentioning backups being created? They'd look like:

```
{"@t":"2020-11-10T04:12:14.6032617Z","@mt":"Backing up to {BackupFile}","BackupFile":"C:\\ProgramData\\Seq\\Backups\\seq_20201110.seqbac"}
{"@t":"2020-11-10T04:12:15.0301257Z","@mt":"Backup complete; {DocumentCount} documents exported","DocumentCount":1111}
```

**Comment by nskerl** [comment]
Ok. I think I see my mistake now. I was copying **manually** triggered backup files (_immediate-8d88c198aef74a2.seqbac, etc._) into the share directory to validate Seq's read succeeding and not seeing those appear in the UI. I just copied in a few scheduled backups (_seq_20201112.seqbac, etc._) and they are visible in the UI.

The lack of new backups is likely due to me not being patient enough :P 

Thanks Nick.
