### ISSUE TITLE
Save button in dashboard should enable after typing

### ISSUE THREAD

**Issue by jason-hess** [datalust/seq-tickets#1061]
When typing in the Order By textbox the Save button should enable.  Instead it seems I have to change focus to another text box and then click Save.

![image](https://user-images.githubusercontent.com/2180332/99752380-f6436000-2b2f-11eb-9020-1e9df7d6b2cf.png)

**Comment by nblumhardt** [comment]
Thanks for the note, we could definitely improve on this 👍
