### ISSUE TITLE
"Collapse all" on JSON properties of log messages

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#1076]
On JSON properties of log messages, you can click on "Expand all" to expand the whole JSON-String an display it intented or collapsed.
![grafik](https://user-images.githubusercontent.com/10319545/104484170-40454100-55c9-11eb-8e17-9d18e9207368.png)
![grafik](https://user-images.githubusercontent.com/10319545/104483577-91086a00-55c8-11eb-8ee2-27ab2d8b2265.png)

Currently you can
- Collapse the entire log message by clicking on it, so no properties are displayed at all. This will collapse JSON properties as well. However this will collapse _all_ JSON propertys, if there are multiple in this log message. 
- Click on "Display inline" to get a compact view. 
![grafik](https://user-images.githubusercontent.com/10319545/104484390-8a2e2700-55c9-11eb-9473-1791c6f9aa01.png)
![grafik](https://user-images.githubusercontent.com/10319545/104484449-9dd98d80-55c9-11eb-9486-ebad7a2b7b06.png)
This view is much more verbose than the initial view.

I would like to see some kind of "undo expand all" functionality to restore the "compact" default view of the JSON property. Currently "Expand all" is always displayed, even when the property is already expanded.
This would be usefull for me when analyzing log messages with multiple json properties which are deeply nested.
![grafik](https://user-images.githubusercontent.com/10319545/104483771-c745e980-55c8-11eb-9d5d-9163a1af4272.png)

**Comment by nblumhardt** [comment]
![collapse-all](https://user-images.githubusercontent.com/342712/107180139-d41cf800-6a23-11eb-9a2d-0a98ff59594a.gif)
