### ISSUE TITLE
interval() and dashboard

### ISSUE THREAD

**Issue by dazinator** [datalust/seq-tickets#1122]
Hello,

Stemming from [this](https://docs.datalust.co/v4/discuss/5a58df0b086a05001c4322ee) and [this](https://github.com/datalust/seq-tickets/issues/950) I can't seem to get `interval()` to work in a dashboard scenario:

![image](https://user-images.githubusercontent.com/3176632/107028232-2ef4ec00-67a5-11eb-86bc-a7a39fc5be9a.png)

I was hoping `interval()` would return the time range selected by the user but I can't seem to get it to work.
I am trying to define a simple chart that shows count of events per second. If the user selects "per hour" in the dashboard, I need to divide the total count by the number of seconds in an hour. If they chose per 8 hours, I need to divide the total count, by the number of seconds in 8 hours - to give me the rate - therefore the time range they select is a variable in my equation. Unless I am being stupid - this isn't really my strong point.

Thanks

**Comment by nblumhardt** [comment]
Hi @dazinator - thanks for getting in touch. Your query looks fine; `interval()` was only added in 2020.1 - it looks like you may be running a 5.x version?

**Comment by dazinator** [comment]
Ah ok - that explains it then!

**Comment by nblumhardt** [comment]
Great! 👍
