### ISSUE TITLE
Seq SDK stopped connecting - 401 - Please log in.

### ISSUE THREAD

**Issue by gagwithgaffer** [datalust/seq-tickets#1143]
**Describe the bug**
it seems that since installing Seq ver. 2021.1.5307 onto Windows 10 two days ago, my .NET Web API can no longer connect to Seq using the Seq SDK package, I receive a 401 - Please log in response from Seq.

Previously I had Seq running in Docker for Windows Container and was working fine, but to facilitate working on an Seq custom App this weekend, I decided to delete the docker instance and install a fresh copy of Seq into Windows 10 directly and hadn't tried using the SDK since then, I also hadn't changed any code in my app for connecting with Seq.

Below is a screenshot of my Web API and the response it receives back from Seq:

![image](https://user-images.githubusercontent.com/51385414/108640288-b2465b00-7490-11eb-8176-a3e45aaf60d1.png)

Things I've tried so far:

Updated the Nuget package for the SDK to ver. 2021.1.0
Turned off my Windows firewall.
Re-installed Seq in Windows (but found that the original settings were still present so it seems this wasn't a full clean re-install :(
Created numerous new API keys with no success:

![image](https://user-images.githubusercontent.com/51385414/108640365-208b1d80-7491-11eb-9ecf-6a6d2342ad03.png)

![image](https://user-images.githubusercontent.com/51385414/108640388-3862a180-7491-11eb-9979-ee0e7f480d37.png)

![image](https://user-images.githubusercontent.com/51385414/108640432-78c21f80-7491-11eb-8a6d-028e5f70d0ad.png)

I'm able to write logs to Seq using Serilog in another NET Core App so it seems to be just the Seq SDK that's having the issue.

**Comment by gagwithgaffer** [comment]
Hello Support, I ended up doing another clean install of Seq on Windows and this time deleted the files from the Windows Program Data folder to force a clean install.

I've come to realize that as soon as I enable authentication for the built in Administrator then I can no longer connect to the system with the Seq SDK. I had again double checked that the API keys were configured under the main settings and in .Net Core so unsure why this happening. I also tried creating an API key under my account as well.

It could be that when I had the previous installation running in a docker container, I may not have enabled authentication so could be I wouldn't have come across this until now. 

I've looked again at the Seq SDK docs but it would seem that sending the API key should be enough. Thanks

**Comment by nblumhardt** [comment]
Thanks for the heads-up! This is a bit of a puzzle - an API key should be sufficient, do you have any more luck if you insert `&apiKey=.....` into your request URL?

Being on `localhost` I can't imagine you're hitting a proxy, but if there's one involved there could be a chance it's stripping off the `X-Seq-ApiKey` header.

**Comment by gagwithgaffer** [comment]
Hi Nick, I can definitely try this but quick question:
If we enable authentication is there any way in reversing it back to default without losing all the configuration of the custom apps I setup, yesterday I had to re-install Seq before I could use it again without authentication so I could carry on with my project, thanks

**Comment by nblumhardt** [comment]
Hi @gagwithgaffer, thanks for your reply. It's possible to disable auth, but requires using the Seq API (there's no UI for it, and we'd really strongly recommend keeping auth enabled if there's any possibility whatsoever of untrusted traffic reaching Seq). If you do need to take that route please drop us a line via `support@` and we'll assist, though.

**Comment by nblumhardt** [comment]
Any further clues/progress on this at your end @gagwithgaffer ?

**Comment by nblumhardt** [comment]
Closing as stale, but please drop us a line if you're still having any trouble with this.
