### ISSUE TITLE
Milestone 2021.1.5307 is named incorrect

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#1144]
Hi,
the name of [this](https://github.com/datalust/seq-tickets/milestone/115) milestone should be 2021.1.5307, but it is 2020.1.5307.
Nothing serious, but I was confused :)

**Comment by larenelg** [comment]
Hey Sebastian, oh yes that is confusing! Thanks so much, I've just changed it to the right year 🙏
