### ISSUE TITLE
Expressions containing the wildcard `?` indexer are incorrectly interpreted in 2021.1

### ISSUE THREAD

**Issue by alexb5dh** [datalust/seq-tickets#1150]
**Describe the bug**
And/Or operators seems to apply both conditions even if it's redundant which leads to some queries returning different results compared to 2020.5. Some filters can not be applied at all.

Example below tries to find events that either doesn't have `Scope` property at all or doesn't have `Audit` entry in `Scope` array.

**To Reproduce**
- Log any event that doesn't have `Scope` property to Seq
- Apply any of the following filters in the web UI:
  - `not (has(Scope)) or not (Scope[?] == 'Audit')`
  - `not (has(Scope) and Scope[?] == 'Audit')`
  - `(not (has(Scope)) or not (Scope[?] == 'Audit')) and not has(Scope)`

**Expected behavior**
Each of the filters should include this event. They do in 2020.5.

**Actual behavior**
None of the filters includes it. Third one doesn't include **any** event.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Seq Version: 2021.1
 - Using Docker: Yes

**Comment by nblumhardt** [comment]
Thanks for the report, Oleksii. We'll take a look and let you know what we find!

**Comment by nblumhardt** [comment]
I've reproduced this; it's an issue in the interpretation of the `?` wildcard.

```sql
not (has(Scope)) or not (Scope[?] = 'Audit')
```

ends up translated (incorrectly) into:

```sql
any(Scope, |s| not (has(Scope)) or not (s = 'Audit'))
```

The initial `any` is not evaluated if `Scope` is undefined.

The correct translation is:

```sql
not (has(Scope)) or any(Scope, |s| not (s = 'Audit'))
```

We'll review this on Monday and consider releasing a patch if we can make the fix non-disruptively.

**Comment by nblumhardt** [comment]
For the very curious :-) .. a mostly-similar issue exists in _Serilog.Expressions_ (same wildcard syntax); the fix there is https://github.com/serilog/serilog-expressions/pull/26#pullrequestreview-605797682, and I think the fix in Seq will be along the same lines.
