### ISSUE TITLE
Copy doesn't work in Safari

### ISSUE THREAD

**Issue by timgaunt** [datalust/seq-tickets#1161]
**Describe the bug**
Using any of the _Copy_ functions in Safari doesn't seem to copy the item to the clipboard -whether it's `Copy value`, `Copy raw JSON`.

Checking the console I see

```
undefined is not an object (evaluating 'r.navigator.clipboard.writeText') seq-ui2-1615287814558.min.js:46
```

**To Reproduce**
In Safari the steps to reproduce the behavior are:
1. Go to the events list
2. Click on Export
3. Click `Copy raw JSON`
4. See error in console

**Expected behavior**
It should copy the value to the clipboard

**Environment (please complete the following information):**
 - OS: `macOS Big Sur`
 - Browser: `Safari Version 14.0.3 (16610.4.3.1.7)`
 - Seq Version: `2021.1`
 - Using Docker? `No`

**Comment by nblumhardt** [comment]
Thanks for the report, Tim, looks like we must have broken this. We'll dig in 👍

**Comment by nblumhardt** [comment]
Hi Tim,

We've just realized that this is an HTTP/HTTPS issue; it appears that the copy-text API will only work for Safari if the page is served over HTTPS (or possibly on `localhost`).

Testing this on Safari 14.11/Big Sur works for us, over HTTPS.

How does this line up with your observations?

**Comment by timgaunt** [comment]
Ah. That makes sense. Back to enabling ssl then. We got a little stuck on that last time. What are the best docs for this? We'll need to run http and https while we update all config I guess?


--
Tim Gaunt
Managing Director | The Site Doctor | Reg'd in England & Wales: 6502026
M: 07715 110 656 | T: 0121 31 45 374
www.thesitedoctor.co.uk | @thesitedoc

On 8 Jun 2021, at 06:46, Nicholas Blumhardt ***@***.***> wrote:

﻿

Hi Tim,

We've just realized that this is an HTTP/HTTPS issue; it appears that the copy-text API will only work for Safari if the page is served over HTTPS (or possibly on localhost).

Testing this on Safari 14.11/Big Sur works for us, over HTTPS.

How does this line up with your observations?

**Comment by nblumhardt** [comment]
Hi Tim; https://docs.datalust.co/docs/ssl will be the best place to start, but after installing the SSL cert in your _Local Machine/Personal_ certificate store, it should just come down to:

```
seq bind-ssl --thumbprint="THUMBPRINT HERE"
seq config set -k api.listenUris -v https://YOURSERVER,http://YOURSERVER
seq service restart
```

(Plus any needed Windows Firewall config.)

Please drop us a line via `support@` if you run into any issues 👍

**Comment by timgaunt** [comment]
Thanks Nick,

That seems to work and copy is working 👍

It’s probably worth noting that it works as long as I don’t try and run it on a custom port. Running on 443 we get a certificate error -is that because it’s a self signed certificate?

[cid:417F759A-1020-4ABB-B2A2-099F8CC3FAE8]

This is what I ran
seq bind-ssl --thumbprint="..." --hostname=somedomain.com<http://somedomain.com/>
seq config -k api.listenUris -v http://somedomain.com:5341,https://somedomain.com
seq service restart

–
Tim Gaunt
Managing Director | The Site Doctor | Reg'd in England & Wales: 6502026
M: 07715 110 656 | T: 0121 31 45 374
www.thesitedoctor.co.uk<http://www.thesitedoctor.co.uk/> | @thesitedoc

On 9 Jun 2021, at 02:52, Nicholas Blumhardt ***@***.******@***.***>> wrote:



Hi Tim; https://docs.datalust.co/docs/ssl will be the best place to start, but after installing the SSL cert in your Local Machine/Personal certificate store, it should just come down to:

seq bind-ssl --thumbprint="THUMBPRINT HERE"
seq config set -k api.listenUris -v https://YOURSERVER,http://YOURSERVER<https://yourserver,http//YOURSERVER>
seq service restart


(Plus any needed Windows Firewall config.)

Please drop us a line via support@ if you run into any issues 👍

**Comment by nblumhardt** [comment]
Hi Tim,

I can't see the screenshot (if that should have come through?) but I'd assume yes - unless you add the self-signed cert to the "Trusted Root Certificates" store on your workstation, you'll get a certificate error.

To use a custom port, you'd need to also specify the `--port` argument to the `bind-ssl` command, in case that helps?

**Comment by timgaunt** [comment]
Ok thanks, I’ll look at issuing a proper cert in that case I think.

Can you supply multiple ports in that parameter or does it only support one?


–
Tim Gaunt
Managing Director | The Site Doctor | Reg'd in England & Wales: 6502026
M: 07715 110 656 | T: 0121 31 45 374
www.thesitedoctor.co.uk<http://www.thesitedoctor.co.uk> | @thesitedoc

On 9 Jun 2021, at 04:59, Nicholas Blumhardt ***@***.******@***.***>> wrote:



Hi Tim,

I can't see the screenshot (if that should have come through?) but I'd assume yes - unless you add the self-signed cert to the "Trusted Root Certificates" store on your workstation, you'll get a certificate error.

To use a custom port, you'd need to also specify the --port argument to the bind-ssl command, in case that helps?

**Comment by nblumhardt** [comment]
:+1:

Only one port - but the command can be run multiple times, with a different port specified each time.
