### ISSUE TITLE
Previous/Next month arrows missing in calendar

### ISSUE THREAD

**Issue by timgaunt** [datalust/seq-tickets#1163]
**Describe the bug**
A minor issue but I keep meaning to mention it but the arrows appear to have gone from the calendar -I'm in Safari but its the same on Chrome as well

**To Reproduce**
In Safari the steps to reproduce the behavior are:
1. Go to the events list
2. Click either of the date pickers

![image](https://user-images.githubusercontent.com/254564/110897827-11f88f00-82f6-11eb-921b-d520b5f4f002.png)

**Expected behavior**
The arrows should show

**Environment (please complete the following information):**
 - OS: `macOS Big Sur`
 - Browser: `Safari Version 14.0.3 (16610.4.3.1.7)`
 - Seq Version: `2021.1`
 - Using Docker? `No`

**Comment by nblumhardt** [comment]
Looks like Seq's content-security-policy is blocking this - the control uses `data:` urls, which are not allowed in the frontend anymore. Thanks Tim!

**Comment by nblumhardt** [comment]
Fixed: 

![image](https://user-images.githubusercontent.com/342712/111103803-fbbf2d00-859a-11eb-9473-f3486c7234d9.png)
