### ISSUE TITLE
Signal expression editor is incorrectly grouping signals

### ISSUE THREAD

**Issue by burnbay** [datalust/seq-tickets#1177]
I've always combined signals in apps to send notifications (email, message etc.). In the latest release (2021.2.5495) there seems to be a problem. I've created signals with the new DatePart function so that I can filter events at specific time intervals. I'm trying to combine an Error signal with a "Working hours" signal, but all "Error" events are sent to the app.

Seems like there's an issue adding signals in the app instance. 
Before adding a new signal (working as expected):
![image](https://user-images.githubusercontent.com/2721929/112585195-a59f8480-8df9-11eb-8f94-9ae70ffcfe05.png)

After adding a new signal (Not working - missing "in"):
![image](https://user-images.githubusercontent.com/2721929/112585885-fe235180-8dfa-11eb-9442-bfdcfaba5e38.png)

**Comment by nblumhardt** [comment]
Thanks for getting in touch. The signals will be shown together like that (and combined differently) if they're in the same "group".

If you look at the three signals in the signal editor, do they show the group as "automatic", like the example below?

![image](https://user-images.githubusercontent.com/342712/112586603-d3131f00-8e47-11eb-8775-a595fa36f7aa.png)

**Comment by burnbay** [comment]
I’ve specified «@Level» for the Errors signal, Automatic for the «SSB Datalast», «Baseline 3.0» for Baseline... and «CAR» for the CAR... signal.

**Comment by nblumhardt** [comment]
Thanks - I've just reproduced this, it looks as though the signal expression editor is grouping signals without checking that they are in the same group.

We'll aim to get a patch out for this quickly, since it's such a disruptive bug; in the meantime, you can temporarily remove the groupings from those signals/set them back to "Automatic", while you configure the app.

Thanks again for the report!

**Comment by nblumhardt** [comment]
![expr-edit-fix](https://user-images.githubusercontent.com/342712/112910145-20d4a380-9136-11eb-8eb0-36d9115772a5.gif)

Fixed; I shouldn't be trusted to write code in dynamically-typed languages :-) ... a nice reminder of why we're using TypeScript for our newer UI components.

New patch will be out within 24 hrs. Thanks for reporting this!
