### ISSUE TITLE
Timestamps are off by one month when using yyyy-mm-dd date format

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#1185]
When using the new "Prefer yyyy-mm-dd date formatting" option, all timestamps in the Events-Views are off by one month.

![grafik](https://user-images.githubusercontent.com/10319545/113601148-40d9fa80-9641-11eb-8169-cd8db3286396.png)

![grafik](https://user-images.githubusercontent.com/10319545/113601204-53543400-9641-11eb-8330-af91a2816ae2.png)

I suspect that this is a bug, because it seems to be visible on the screenshot here too: https://github.com/datalust/seq-tickets/issues/1128 (The ticket was resolved 20 days ago in March, but the screenshot shows dates in February.

**Expected behavior**
The month should be identical, regardless of the "yyyy-mm-dd" formatting option.

**Environment:**
 - OS: Windows Server Core 2019
 - Browser: Firefox 87.0
 - Seq Version: 2021.2.5595
 - Using Docker? No

**Comment by nblumhardt** [comment]
Thanks Sebastian! I can't believe I didn't spot this - the old `Date.getMonth()`-returns-zero-based-indexes footgun. We're looking at when we might ship a tiny patch to fix this up.

**Comment by nblumhardt** [comment]
The fix for this is out now 👍
