### ISSUE TITLE
SEQ Base URL param in Teams app not working

### ISSUE THREAD

**Issue by TheDaemonBarber** [datalust/seq-tickets#1188]
**Describe the bug**
The SEQ Base URL configured in an instance of Seq.App.Teams package does not get used from generated alerts.
However, when manually sending an existing alert to the app, it works

**To Reproduce**
1. Have the Teams app installed
2. add a new alert, configure the app and specify the SEQ Base URL to the URL of the instance
3. add the app to a dashboard alert

**Expected behavior**
The links in the teams message should direct to the URL provided
we actually get the ip address of the instance

**Environment (please complete the following information):**
 - OS: Windows Server 2016
 - Chrome
 - Seq Version 2020.4.5119
 - Using Docker? No

**Comment by nblumhardt** [comment]
Hi @TheDaemonBarber - thanks for the heads-up.

The base URL is now generally configured through Seq's `api.canonicalUri` setting - it sounds like the Teams app may need an update, we'll check it out 👍 

On the Seq server, you can set this with:

```
seq config set -k api.canonicalUri -v https://your-seq
seq service restart
```

Hope this helps,
Nick
