### ISSUE TITLE
Dedicated `/health` endpoint

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1200]
At present, `/api` is used as Seq's "health check" endpoint, but this suffers a few drawbacks:

 * It produces more content than necessary
 * It doesn't directly yield health information
 * In multi-node configurations, it will always be served by the "leader" node, and so won't reflect the health status of the node handling the request

Following the defacto standard set by AWS, ASP.NET Core and others, we'll add `/health` and this will explicitly serve health information for the node handling the request.

At present we expect `/health` will return either 200 or 503, and will always respond (at a minimum) with a JSON body with a `status` property.

(H/T @andymac4182 for the nudge!)

**Comment by andymac4182** [comment]
Great to see this implemented :)
