### ISSUE TITLE
PostgreSQL metastore support

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1210]
Seq can currently store metadata (users, signals, etc.) in Microsoft SQL Server. This is used primarily in Azure Container Instances, where the available SMB-based storage does not work well with Seq's embedded metadata store.

Using an external database for metadata is a core part of the plan for multi-node support, including high availability and zero-downtime upgrades. As part of this work, we want to enable PostgreSQL as a metastore option, too.

**Comment by nblumhardt** [comment]
Alrighty! Here's how it looks....

You'll need to create a PostgreSQL database ahead of time.

Setting up a new Seq instance to use PostgreSQL for metadata storage is as simple as:

```
seq secret set -k metastore.postgres.connectionString -v <connection string here>
```

If you have an existing instance and want to migrate, it's:

```
seq metastore to-postgres --connection-string="<connection string here>"
```

**Comment by andymac4182** [comment]
This is great to see!
