### ISSUE TITLE
VMM page caching pushes Seq memory cache to zero on Docker/Linux

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1214]
On some Docker instances, the OS virtual memory manager will aggressively keep mapped pages from Seq's archive store in-memory, causing the more conservative cache manager in Seq to drop cached events. This over time causes the VMM to cache more pages, leading to Seq eventually emptying its memory cache.

In 2021.3 we're going to try to avoid this failure mode by advising `MADV_DONTNEED` more eagerly on memory maps after use.

**Comment by nblumhardt** [comment]
Done; will be monitoring to see how this performs once we get the preview container published.

**Comment by KodrAus** [comment]
Another change we've made in 2021.3 is to set a .NET GC hard limit in Docker containers to a high value (~95%) if one hasn't been set explicitly to give Seq a chance to manage its own cache. This should help prevent OOMs on startup or under pressure.
