### ISSUE TITLE
Allow tags to be specified for dashboard alerts

### ISSUE THREAD

**Issue by MattMofDoom** [datalust/seq-tickets#1221]
This is an idea springing from my pull request at https://github.com/datalust/seq-app-opsgenie/pull/1

I added a feature to allow tags to be dynamically added to OpsGenie alerts, based on watching for a configured property. This immediately benefits https://github.com/MattMofDoom/Seq.App.EventTimeout which we're using extensively. It will allow tags from that app's events to be passed through to OpsGenie. 

Tags are very useful in the context of OpsGenie, for driving policy and even downstream integrations. Hence passing through tags is also of value. If dashboard alerts supported tags, these could then be passed through to OpsGenie Alerting, or any other app that implemented it. 

This would reduce the number of OpsGenie instances needed when you have a lot of dashboard-driven alerting, since it could pass the dashboard alert-configured tags through to a single app instance to direct the OpsGenie alert to where it needs to go.

A follow-on thought would be around the other properties added in the pull request:

- the ability to set a Priority at the dashboard alert, which could then also be passed through to OpsGenie or other alerting apps. 
- Responders could also be optionally configured for the same type of passthrough.
- This wouldn't take much to include in the enhancements to OpsGenie Alerting, since I implemented specifying a static priority and responders; it could similarly take a property that will contain the priority and/or responders.

The idea is to allow for further flexibility for the dashboard. Obviously when OpsGenie Alerting is listening to signals to fire alerts, this will need multiple instances of the app - but an enhancement to dashboards would make a single 'dashboard alerts' instance viable.

**Comment by nblumhardt** [comment]
Thanks for the suggestions! We're working in this area at the moment - we'll give this some thought 👍

**Comment by MattMofDoom** [comment]
@nblumhardt Just a note that Seq.App.Atlassian.Jira now supports dynamic properties like we added for OpsGenie 😊

**Comment by nblumhardt** [comment]
That's awesome, @MattMofDoom :-)

On the native alerting side, we've implemented this (preview still yet to drop); each alert gets `Name = Value` tags applied, and these are passed along through notifications as properties on the notification event:

![image](https://user-images.githubusercontent.com/342712/128285678-3f2ab542-2849-4644-8377-060fe956c326.png)

They're not dynamic/programmable, but there's a chance we'll attempt it at a later date.

**Comment by MattMofDoom** [comment]
@nblumhardt  That's fantastic, I think it'll work really well!

 I think not being dynamic is okay, because generally the destination app will do the mapping, eg. OpsGenie, Jira, etc. 

Would love the keypair input type to show up in Seq Apps at some point, although I appreciate that likely needs some thought. For now, the Key=Value comma separated list seems to work well enough 😊

**Comment by nblumhardt** [comment]
Thanks for the feedback. Since this ticket's done and will make it into the next preview, time to close, here :-)
