### ISSUE TITLE
Support for Apple Silicon/ARM64

### ISSUE THREAD

**Issue by rangitoto72** [datalust/seq-tickets#1224]
About a month ago SEQ stopped working in Docker

You start SEQ in Docker, it starts then exits and try's to restart after a few seconds.

Logs show bellow error.

docker logs --tail 50 --follow 
Error: Failed to create CoreCLR, HRESULT: 0x8007FF06
Error: Failed to create CoreCLR, HRESULT: 0x8007FF06
Error: Failed to create CoreCLR, HRESULT: 0x8007FF06
Error: Failed to create CoreCLR, HRESULT: 0x8007FF06

However when googling this error, alot of results refer to dot net run time.
However this was working fine a month ago and now it's not
.
So i removed the container and image.

Then i ran through the creation process again (Documented bellow)
Same issue

**To Reproduce**

1.  Open Terminal
2. docker pull datalust/seq 
3.

I have tried both the following: 

docker run --platform=linux/amd64  --name seq -d --restart unless-stopped -e ACCEPT_EULA=Y -p 5341:80 datalust/seq:latest

or 

docker run --name seq -e ACCEPT_EULA=Y -p 5341:80 datalust/seq:latest

**Expected behavior**
Should create an image of SEQ

**Environment**
 - OS: MAC OS M1
 - Seq  Latest  Image
 - DIGEST:sha256:6af94094a27bcb17f96942d7d7fba97ce84965b50c5c68a24eb0b5c8ff583078
 - Using Docker? Yes
 - Docker Version v20.10.6

Any help would be appreciated.

**Comment by KodrAus** [comment]
Hi @rangitoto72 👋 

I see this specific hresult too when attempting to run our x86-based Docker container on an arm-based host like M1. As far as I know that’s a CoreCLR issue rather than a Seq issue. They use QEMU to run containers on different architectures, but it seems like it might be tricky for CoreCLR to detect.

Have you had the container image working on your M1-based MacBook previously?

**Comment by rangitoto72** [comment]
Thanks for the reply Ashley, 
Yeah I had it running fine about 1-2 months ago prior to latest OSX update.
I cant quite recollect if this was working since changing to the new version of Docker for M1 support.

In my docker environment I have the following containers deployed and working.

MS-Sql
Maria Db
Raneto

Thanks.

**Comment by chan4lk** [comment]
Same issue here.

**Comment by nblumhardt** [comment]
Hi all 👋 - thanks for the feedback on this. We've made quite a bit of progress on native support for Apple Silicon and think this will be the smoothest route to having Seq run nicely on this platform.

We're expecting to RTM this around the time of .NET 6 (November 2021) but will update the thread here as soon as we have a preview image available.

**Comment by cjpvillaruel** [comment]
I had the same problem. It was working before but when I upgraded from docker preview to the latest docker, it keeps on restarting and showing the error from above.

**Comment by mbohovic** [comment]
Hi,
please is there any progress in this matter? I need to have this resolved as soon as possible.

**Comment by nblumhardt** [comment]
Hi @mbohovic - we're hoping to have a preview image out there before too long. We've made it as far as getting Seq loaded up on ARM now, but have other work in the pipeline ahead of assembling the preview container, unfortunately.

**Comment by KodrAus** [comment]
I should have cross-posted from [the discussion thread](https://github.com/datalust/seq-tickets/discussions/1189#discussioncomment-1298784), but we do have a very early preview release of an ARM build you can grab:

```
docker pull datalust/seq:2021.3.6410-pre
```

I might close this one in favor of the discussion for now so anybody who wants to keep up can watch it.

**Comment by rab170** [comment]
Hey @KodrAus - it would be really really incredibly helpful if you could answer one small question about this .NET error code... 

Did switching to the .NET 6 release candidate solve this issue with the dotnet/CoreCLR, or did you also have to build additional logic around that? 

I receive the **exact** same error (HRESULT and all) while building a debian based image on M1 silicon... would very nice to know if switching to .NET 6 would solve the problem :) 

Thanks in advance if you manage to get back to me :) (no worries if not!)

**Comment by nblumhardt** [comment]
@rab170 Hi! It was the .NET 6 RC, I don't think we made any other changes (although the `dotnet` publishing command-line args and MSBuild properties did change a bit between 5 and 6.) HTH!
