### ISSUE TITLE
Free disk space checking can take a long time on some filesystems

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#1232]
On some cloud filesystems, the free space checking can take a really long time if it needs to enumerate all files to calculate the space remaining. This might also have the unintended effect of burning IOPS that are needed for ingestion and querying.

We already issue a warning if the space check takes a long time (>1 second), but if it takes a really long time (>1 minute) then we should probably avoid it altogether. The check could also be disabled through config to avoid ever running it by setting the `storage.disableFreeDiskSpaceChecking` to `true`.

We definitely wouldn't recommend disabling the free space check if you don't absolutely need to. You'd probably still want your cloud environment of choice to surface free space metrics for you somewhere.

**Comment by nblumhardt** [comment]
Note, in containerized environments, setting `SEQ_STORAGE_DISABLEFREEDISKSPACECHECKING = true` will have this effect.
