### ISSUE TITLE
Copy settings

### ISSUE THREAD

**Issue by zraffaele** [datalust/seq-tickets#1233]
It would be very interesting to have the possibility to export all the Signals, Queries, Dashboards configuration, then copy it to other installations or other instances.
Is it possible to include it as a milestone in an upcoming release?

**Comment by andymac4182** [comment]
@zraffaele This is all included in the backups. It also includes the applications and configuration. Could you use that or is there something that won't work with using the backup?

**Comment by nblumhardt** [comment]
We've just implemented `seqcli template export`, which copies signals/dashboards/queries etc. to a set of JSON-like `.template` files, and `seqcli template import` to apply them to another server:

https://github.com/datalust/seqcli/pull/197

Some preview binaries are available from CI (linked in the PR); would be great to hear how you go, if you're able to give it a try! 😎

**Comment by nblumhardt** [comment]
(Final build is coming alongside the 2021.3 release.)

**Comment by nblumhardt** [comment]
Closing as `seqcli template` is the planned implementation of this - let me know if you're able to try it out, @zraffaele 👍

**Comment by zraffaele** [comment]
Of course. 
Thanks
