### ISSUE TITLE
ARM64 docker image

### ISSUE THREAD

**Issue by JokerQyou** [datalust/seq-tickets#1246]
This is somewhat related to #1224 but not really the same thing. Docker allows an image tag to support multiple architectures by specifically building for that platform. You can see by this field on the tag listing page.

![image](https://user-images.githubusercontent.com/1465267/122663281-d3fbe880-d1cb-11eb-9b7e-e12e952761e2.png)

Now, here is a random image that supports ARM v5 architecture:

![image](https://user-images.githubusercontent.com/1465267/122663310-fa218880-d1cb-11eb-86a2-7767cba4034e.png)

If a user is on an ARM64 machine, and he tries to pull `datalust/seq`, it would succeed (because by default `docker pull` does not check image architecture). However this pulled image would not be able to start, because AMD64 and ARM64 have different binary formats.

**Comment by nblumhardt** [comment]
Thanks @JokerQyou - we'll be addressing this as part of #1224, so I've made slight change to the title of that issue. Thanks again!
