### ISSUE TITLE
 Custom dashboard time ranges, e.g. a specific range of days at some time in the past

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1255]
From #565 / #1111. Currently our most-requested dashboarding enhancement. We'll prioritize this post-2021.3.

**Comment by alexb5dh** [comment]
Just to clarify - as 2021.4 was released, should we expect this anytime soon?

**Comment by nblumhardt** [comment]
Thanks for the nudge, @alexb5dh; we've been discussing this lately - it won't make it for 2022.1, unfortunately, but it's not off the radar.

**Comment by nblumhardt** [comment]
We're working on this now for Seq 2023.4. Better late than never! :-)

**Comment by nblumhardt** [comment]
Check out the new preview to see this in action :-)
