### ISSUE TITLE
Nuget package persistently reverts to old version

### ISSUE THREAD

**Issue by MattMofDoom** [datalust/seq-tickets#1270]
**Describe the bug**
This might be a Nuget issue or an issue with my Seq instance - not sure. When I attempt to update or install Seq.App.EventTimeout, it persistently installs v1.4.8. The current version is v1.5.1 and shows correctly on Nuget. I have delisted all other versions, including v1.4.8. 

If I manually specify 1.5.1, it will install without a problem, but an update will revert to 1.4.8.

**To Reproduce**
Attempt to install or update Seq.App.EventTimeout. Version installed is v1.4.8.

**Expected behavior**
Seq.App.EventTimeout v1.5.1 is installed.

**Environment (please complete the following information):**
 - OS: Windows 2016
 - Browser: Edge Chromium
 - Seq Version:  2021.2
 - Using Docker? No

**Additional context**
Package info has only been incremented in version number. Initial build was v1.4.9, but then attempted changing to v1.5.0. A subsequent update raised this to v1.5.1. No matter what I do, an update will revert to v1.4.8. If I attempt a new install, v1.4.8 will be installed (I didn't actually know I could run multiple versions at the same time, but I now have a lot of insight in how apps will operate for multiple 'installs' and side by side versions).

I can't see anything wrong on the Nuget side and all queries I perform show v1.5.1. 1The only place this behaviour shows up is in Seq.

I would remove the existing install and attempt a fresh install, but there are a large number of instances of Seq.App.EventTimeout configured that I would then have to manually configure again.

**Comment by MattMofDoom** [comment]
Sample of issue below. I have just attempted an install of Seq.App.EventTimeout while 1.5.1 is installed, and it has installed 1.4.8.

Expected behaviour (based on testing) is that I would have two installs of Seq.App.EventTimeout 1.5.1, running from the same binaries on disk.

![image](https://user-images.githubusercontent.com/30714560/127764216-db29f2b9-a520-4e51-a89f-e58f7c2a71fd.png)

**Comment by MattMofDoom** [comment]
I was able to reproduce the issue by installing a local individual copy of Seq and installing the app. 

Given that only 1.5.1 is listed on Nuget, this is really perplexing!

**Comment by KodrAus** [comment]
Hi @MattMofDoom! :wave:

On Windows we still default to targeting NuGet's V2 API. For some reason the highest version number the V2 API reports for `Seq.App.EventTimeout` from its `FindPackagesById()` endpoint is `1.4.8`. I'm not 100% sure why that is yet, I'll do some digging.

It will resolve correctly to `1.5.1` through the V3 API, which you can use by updating your feed's URI to:

```
https://api.nuget.org/v3/index.json
```

<img width="912" alt="Capture" src="https://user-images.githubusercontent.com/6721458/127787194-2bf0f5ea-c2e3-4c9f-a46c-7915606cf27d.PNG">

**Comment by KodrAus** [comment]
Ah also... I've fixed that little display bug where the app's description flows into the info text 🙂

**Comment by nblumhardt** [comment]
We'll automatically update v2 NuGet.org feeds to the v3 endpoint in 2021.3.

**Comment by MattMofDoom** [comment]
Thanks @KodrAus  ... that's helpful to address an individual problem at least! And thanks @nblumhardt 😊

I've been bashing my head against how to get the feed to use 1.5.x, I even manually uploaded 1.5.2 this morning, in case it was an Appveyor issue. Other packages being uploaded via Appveyor are perfectly happy to update in Seq though, so it seemed like a long shot (didn't pay off either).

**Comment by MattMofDoom** [comment]
I've sent a "Contact Support" on Nuget reflecting that the v2 API is returning the old version, and referencing this ticket.

**Comment by MattMofDoom** [comment]
I've put up a PSA after grabbing some screenshots on the issue at https://mattmofdoom.com/psa-update-your-seq-nuget-api-feed-to-v3/

Appreciate this isn't strictly a Seq issue, rather an issue with the v2 Nuget API, but worth noting so that people can update if they have an issue like this before 2021.3 is out.

**Comment by nblumhardt** [comment]
Thanks for dropping by, @joelverhagen. We use a custom and very minimal NuGet client (we needed a v2 client on Linux some time ago, which AFAIK isn't offered out of the box), so it's possible we have a bug lurking somewhere around paged results - I'll take a look now 👍

**Comment by nblumhardt** [comment]
You're right, thanks @joelverhagen. New fix incoming!

Before:

```
[12:07:55 INF] NuGet v2 "GET" "https://www.nuget.org/api/v2/FindPackagesById()?id='Seq.App.EventTimeout'"
[12:07:57 INF] NuGet v2 "GET" "https://www.nuget.org/api/v2/Packages(Id='Seq.App.EventTimeout',Version='1.4.8')"
[12:07:58 INF] NuGet v2 "GET" "https://www.nuget.org/api/v2/package/Seq.App.EventTimeout/1.4.8"
```

After:

```
[12:09:23 INF] NuGet v2 "GET" "https://www.nuget.org/api/v2/FindPackagesById()?id='Seq.App.EventTimeout'"
[12:09:25 INF] NuGet v2 "GET" "https://www.nuget.org/api/v2/FindPackagesById()?id='Seq.App.EventTimeout'&$skip=100"
[12:09:26 INF] NuGet v2 "GET" "https://www.nuget.org/api/v2/Packages(Id='Seq.App.EventTimeout',Version='1.5.2')"
```

We were thrown off when we originally investigated this because we thought we'd fallen foul of the OData query deprecation/removal. I've also make a quick update so that we set our `User-Agent`, hopefully that will make it easier for the NuGet team to keep track of the features we rely on.

We'll continue with the plan to migrate existing installs to v3 by default, too.

Thanks again!

**Comment by MattMofDoom** [comment]
Nice work guys, thanks 😁
