### ISSUE TITLE
Seq time issue on docker

### ISSUE THREAD

**Issue by omidkrad** [datalust/seq-tickets#1275]
When I use Seq with docker some times I notice the log time is so off from the even time:

```
03 Aug 2021 09:53:11.309	Time is 08/03/2021 09:53:09
03 Aug 2021 02:35:39.013	Time is 08/03/2021 09:42:27
```

Notice above that log time is 02:35 when event time is 09:42.

**To Reproduce**
1. Run seq with docker:
  `docker run -d --name seq --volume seq-data:/data/ -p 80:80 -p 5341:5341 --env ACCEPT_EULA=Y datalust/seq:latest`
2. Log an event `seqcli log -m "Time is $(date)"`
3. Set the computer to sleep, and come back after few hours.
4. Log the even again `seqcli log -m "Time is $(date)"`

**Expected behavior**
Log time should be the same as (or very close to) the even time.

**Environment:**
 - OS: Windows 10 (20H2)
 - Seq Docker image versions:
     datalust/seqcli         latest    227e4d1469fa
     datalust/seq            latest    a1c7a96e2371
 - Docker: version 20.10.7, build f0df350

**Additional context**
Running Docker with WSL2 on Windows 10 VM

I noticed even restarting the container won't fix it. Things that may fix the issue are removing the container and volume then restarting it. Restarting the docker service (daemon) may also fix it.

**Comment by KodrAus** [comment]
Hi @omidkrad :wave:

Hmm, that's quite odd. Could that possibly be due to this issue in WSL2? https://github.com/microsoft/WSL/issues/5324

It seems like only very recent `5.1` versions of the WSL2 kernel will keep their clocks synced after waking from sleep.

**Comment by omidkrad** [comment]
Hi @KodrAus, it's very possible that's the issue. Thanks for digging it up. I close this for now since it doesn't seem to be Seq issue.
