### ISSUE TITLE
Searching by irregular property name from structured data viewer doesn't work properly

### ISSUE THREAD

**Issue by klinki** [datalust/seq-tickets#1297]
**Describe the bug**
Filtering events based on some property with irregular name (in my case it is  `ADDITIONAL_DATA[]`) doesn't work properly.

**To Reproduce**
1. Find some log event with property with irregular name (in this case `ADDITIONAL_DATA[]`)
2. Click Find on that property
3. Search expression will change to `ADDITIONAL_DATA[]`
4. Nothing will be found, not even the original event

**Expected behavior**
For properties with irregular names, array syntax should be used.
So instead of applying `Params.ADDITIONAL_DATA[]` as filter, it should use `Params['ADDITIONAL_DATA[]']` syntax.

**Screenshots**
Example of event
![properties-seq](https://user-images.githubusercontent.com/1476175/129171257-5a2d4a22-3207-4ffb-aa03-5e1a756ce4a9.JPG)

Filtering by property with regular name (Params.Email) works fine:
![properties-find-seq](https://user-images.githubusercontent.com/1476175/129170636-ee522c3f-1873-42cf-ad89-a9d7a3ce1182.JPG)
![properties-find-email](https://user-images.githubusercontent.com/1476175/129170683-06a1d605-a177-469e-9675-8204b5a9be1d.JPG)

Filtering by property with spaces in name uses the array syntax by default:
![properties-find-spaces-in-name](https://user-images.githubusercontent.com/1476175/129170709-9beb53ee-43fa-458a-b551-e1db7126f631.JPG)

But filtering by property with `[]` in name doesn't use the array syntax and it doesn't find anything.
![properties-find-special-chars-in-name](https://user-images.githubusercontent.com/1476175/129170725-1da6eafe-4217-4dda-b250-f69d1056b53f.JPG)

**Environment (please complete the following information):**
 - Seq Version [Seq 2021.2.6288]
 - Using Docker? Yes

**Comment by nblumhardt** [comment]
Nice catch - thank you, David, we'll patch this up in 2021.3 👍

**Comment by nblumhardt** [comment]
Oops!

```diff
  isIdentifier(name: string) {
-    return /^[_A-z][_A-z0-9]*$/.test(name);
+    return /^[_a-zA-Z][_a-zA-Z0-9]*$/.test(name);
  }
```
