### ISSUE TITLE
--storage parameter with trailing \ prevents Seq from starting as a service

### ISSUE THREAD

**Issue by HenningNT** [datalust/seq-tickets#1324]
**Describe the bug**
When specifying--storage parameter with trailing \ Seq does not start up when run as as a service.

**To Reproduce**
1. Install Seq service: seq service install --storage="PATH\WITH\TRAILING\"
2. Start seq: seq service start
3. See error

**Expected behavior**
I was expecting the service to accept the storage path, even with a trailing \

**Log entry**
{"@t":"2021-09-17T06:57:34.0516806Z","@mt":"Failed to load configuration from {ConfigFilePath}","@l":"Fatal","@x":"System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'D:\\Seq-data\"'\r\n   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)\r\n   at System.IO.Directory.CreateDirectory(String path)\r\n   at Seq.Server.Cli.Shared.SeqConfigInstaller.CreateDefaultConfig(StoragePathFeature storagePath, ListenUrisFeature listenUris, MemoryThresholdsFeature memoryThresholds)\r\n   at Seq.Server.Cli.RunCommand.LoadOrCreateConfig()\r\n   at Seq.Server.Cli.RunCommand.RunAsync(TextWriter cout)","ConfigFilePath":"D:\\Seq-data\"\\Seq.json"}

**Environment (please complete the following information):**
 - OS:Windows server 2019 Standard
 - Browser:  N/A
 - Seq Version 2021.2
 - Using Docker? No

**Comment by nblumhardt** [comment]
Hi Henning! Thanks for the report.

What's happened here is that the trailing backslash has been interpreted as the escape character, and so the following double-quote has ended up being interpreted as a part of the folder name itself, e.g.

```
D:\Seq-data"
```

Not sure at what level we should try to fix this, if at all - I suspect that this could be shell behavior; we'll take a look 👍
