### ISSUE TITLE
Seq randomly stops being able to use plugins and stops sending us alerts to Microsoft Teams as a result

### ISSUE THREAD

**Issue by xantari** [datalust/seq-tickets#1368]
**Describe the bug**

We receive millions of events every day to our Seq server. Over time it seems to stop sending us alerts of issues.

What we see when this occurs is various plugins stop working and complain of random .DLL's being missing.

For instance:

![image](https://user-images.githubusercontent.com/6610039/139955187-1eb14590-de3d-4b3f-b3cb-a8f4e1ce59ee.png)

However the moment we restart the Seq windows service everything is fine again.

But it will stop working after an unknown number of days.

**To Reproduce**
1. Let Seq Server run for a very long time and receive massive amounts of data.

**Expected behavior**

Shouldn't have to reboot Seq server every day to ensure alerting integrity.

**Screenshots**
See above.

**Environment (please complete the following information):**
 - OS: Windows Server 2016 Data Center Edition
 - Browser: Chrome (Latest)
 - Seq Version 2021.2.5647
 - Using Docker? No

**Additional context**
N/A

**Comment by xantari** [comment]
I did notice on thing. We discovered this issue today, and i'm not sure how long we've been not getting error alerts as we don't get them all the time. But on 10/15 we couldn't connect to our domain controller for a bit of time and the servers time drifted until the domain controller came back online. Do you think the time drift could cause this behavior?

``` 
The time service detected a time difference of greater than 5000 milliseconds for 900 seconds. The time difference might be caused by synchronization with low-accuracy time sources or by suboptimal network conditions. The time service is no longer synchronized and cannot provide the time to other clients or update the system clock. When a valid time stamp is received from a time service provider, the time service will correct itself.
```

**Comment by nblumhardt** [comment]
Hi @xantari - thanks for dropping by, sorry about the hassles!

This sounds like #1242 , fixed in 2021.3 - does that help?

**Comment by xantari** [comment]
Oh that might be the issue. I’ll close this issue for now and get the upgrade scheduled. Will re-open if it happens again after the upgrade.

**Comment by nblumhardt** [comment]
Thanks 👍
