### ISSUE TITLE
make Signal Highlighting  turn off when in touch devices

### ISSUE THREAD

**Issue by daveteu** [datalust/seq-tickets#1375]
When viewing Events (on touch device, e.g. iPad), when you tap on the signal, the highlighting turns on. However, when you want to turn off the signal, the highlighting remains until you tap elsewhere on the screen.

Recommendation - disable hover on touch devices, and only allow highlighting (background color change) when active.

**Comment by nblumhardt** [comment]
Thanks for the note, we'll take a look 👍

**Comment by nblumhardt** [comment]
Coming in 2021.4
