### ISSUE TITLE
Upgrade from 2020.2 to latest (2021.3.x) has the service fail to start

### ISSUE THREAD

**Issue by IanYates** [datalust/seq-tickets#1378]
**Describe the bug**
Update a server from 2020.2 to new release 2021.3.6660  (have also tried .6681)

Installation goes smoothly.  Service config tool tries to start service.  Throws error indicating service could not start.

**To Reproduce**
Install 2020.2.  Use Seq

Upgrade to 2021.3.x.  Installation fails to start the service

(although this environment has Seq upgraded from probably the 5.x days....)

**Expected behavior**
Service works after upgrade

**Screenshots**
See context / fix below

**Environment (please complete the following information):**
 - OS: Windows Server 2012 R2
 - Browser: Edgium
 - Seq Version 2020.2 -> 2021.3
 - Using Docker? No

**Additional context**
The fix is not too difficult.
An uninstallation of Seq via Control Panel (albeit I haven't ever done a server restart) does not remove the Windows service entry in the registry.

The Seq service registry entry is
![image](https://user-images.githubusercontent.com/1314477/141882132-5016f2cd-676b-4423-9e56-7eea5b76442f.png)

The `ImagePath` has the value `"C:\Program Files\Seq\seq.exe" run --storage="C:\ProgramData\Seq" --listen="http://localhost:5341" --ram-target="15"`

If I *remove* the `--ram-target="15"` from the command line then Seq runs normally.

This installation of Seq was probably upgraded from 5.x where maybe this switch was added, and it has just stayed as a command line switch on the service registration since then.

Could `2021.3.x` be patched to at least not crash on the presence of this command line option?  (even if it's just ignored)

Thanks!

**Comment by nblumhardt** [comment]
Sorry about that, Ian! The `--ram-target=` switch might even be a relic of the 3.x era - could the install have survived on this machine that long?! :-)

We dropped support for it in 2021.3, but didn't think to add a hook on upgrade to rewrite the service entry command-line. `seq service stop; seq service uninstall; seq service install; seq service start` will be enough to fix it, though you've already done that by removing the switch.

We might be better off accepting but silently ignoring the setting. We'll take a look and let you know what plan we come up with. Thanks for the detailed report, much appreciated.

**Comment by IanYates** [comment]
:)  It's an old server - a good 6 years or so I'd say.  Due for migration in the next two weeks actually.
