### ISSUE TITLE
Styles.css failed to load

### ISSUE THREAD

**Issue by zahedshareef** [datalust/seq-tickets#1387]
Seq dashboard takes too long to load (about 3-4 mins). We're using docker to host Seq.

**Screenshots**
![msedge_2021-11-26_10-43-37](https://user-images.githubusercontent.com/1624394/143625749-6333506c-ae1e-418c-802a-9743780aa36b.png)

**Environment (please complete the following information):**
 - OS: Linux 64 Bits
 - Browser: Edge
 - Seq Version: 2021.3.6681
 - Using Docker: Yes

**Comment by nblumhardt** [comment]
Hi Zahed, thanks for getting in touch! Looks like something is going on server-side; if you're able to collect the container logs and/or a report from Settings > Diagnostics > Download a full diagnostic report, and send those to our support email address (found in the Seq "Support" menu) we should be able to spot some clues.

Best regards,
Nick

**Comment by nblumhardt** [comment]
Closing as it's been a couple of weeks since our last email on this; if you need any further help with it, please let us know.
