### ISSUE TITLE
Put Add API Key button at the top of the screen

### ISSUE THREAD

**Issue by krajek** [datalust/seq-tickets#1389]
Little request. As the number of services grows, there are so many API keys, that we have to scroll to the end of the page to find Add API Key button.
![image](https://user-images.githubusercontent.com/3998666/143865341-ee19776f-36eb-4cf1-8395-d7265b1332ec.png)
My suggestion is to just put it at the top, so it is always visible.

**Comment by nblumhardt** [comment]
Thanks for the suggestion! We made this change on the _Data > Ingestion_ page, in case that's more convenient to use while we figure out a plan for _Settings > API keys_.

**Comment by krajek** [comment]
Thanks, I did not notice, this will work just fine.
