### ISSUE TITLE
How to run the UI/dashboard?

### ISSUE THREAD

**Issue by Oleg26Dev** [datalust/seq-tickets#1402]
I have Windows 10, I run the docker:
>docker run --name seq -d --restart unless-stopped -e ACCEPT_EULA=Y -p 5341:80 datalust/seq:latest

(There is : https://hub.docker.com/r/datalust/seq)

Now I try to run the UI 
htp://localhost:5341

But  receive
"This page is not working"

What do I wrong? How to run the UI?

**Comment by Oleg26Dev** [comment]
The solution: my powershell changed uppercase characters and this parameter was changed too
-e ACCEPT_EULA=Y -> -e _=

The docker started without messages but no UI. When I started correctly it works OK.

**Comment by nblumhardt** [comment]
Thanks for the follow-up, glad you were able to get it working 👍
