### ISSUE TITLE
Edit as JSON overflow screen

### ISSUE THREAD

**Issue by BeChaRem** [datalust/seq-tickets#1414]
**Describe the bug**
The popup to edit a Dashboard overflow the page making any changes impossible.

**To Reproduce**
1. Go to Dashboards
2. Click on the dropdown menu
3. Click on Edit as JSON
4. JSON editor overflow the screen hiding ways to, scroll, save or discard.

**Expected behavior**
An editor with basic functionality to modify the json content.

**Screenshots**
![image](https://user-images.githubusercontent.com/60513607/146580867-b6d04967-97f3-4516-bf91-2e470fb1eeb1.png)

![image](https://user-images.githubusercontent.com/60513607/146580170-dcb85579-8d6a-485b-aee1-133745701482.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Chrome & Edge
 - Seq Version 2021.3.6651
 - Using Docker? No

**Additional context**

**Comment by nblumhardt** [comment]
Thanks for the heads-up! 👍

**Comment by Rycardas** [comment]
To work around this:

1. Go to Dashboards
2. Click on the dropdown menu
3. Click on Edit as JSON
4. F12 to open debug mode.
5. Ctrl+Shift+C to select element.
6. Click anywhere in JSON edit field.
7. Find "CodeMirror-sizer" class in < div > and change "element.style" variables.
8. Uncheck: "min-height" and add new value "height: 80vh" (80 percent of vertical height).
9. You should be able to see action buttons.
![seqdash2](https://user-images.githubusercontent.com/55191252/148210969-4c5ff341-1bc5-4558-a4c4-9f11375cfe62.png)

**Comment by liammclennan** [comment]
@Rycardas thanks for the workaround. You can probably set this up as a 'Style override' on the Settings -> Instance page.
