### ISSUE TITLE
Storage view should/could clear signals when navigating to a day in the Events view

### ISSUE THREAD

**Issue by taspeotis** [datalust/seq-tickets#1420]
Sorry for the obtuse title, hopefully what I am proposing is clear from this example:

I've been using `Space by Event Type` regularly to find events that are taking up the most space on disk so I can add retention policies for them.

My modus operandi has been to the Storage view to find storage heavy days. Clicking on a day takes me back to the Events view for further analysis. Then I click `Space by Event Type` to see which event takes up the most space.

The Events view has my default signals which have (for the past few days) obfuscated just which events are actually taking up the most storage.

Seq hasn't misrepresented anything to me: the signals are my default signals and clearly shown as enabled in the UI, but for the purpose of being taken to the Events view from the Storage view, I think all signals should be turned off so you see all events that are stored on disk.

Adding a toast when this happens (e.g. *Navigating from Storage view turns off signals, click `Default` when you are done*) would make it clear what has happened and how to resume normal use of Seq.

Thanks in advance. And again Seq hasn't done anything wrong here so feel free to close this proposal as user error :)

**Comment by nblumhardt** [comment]
Thanks for spotting this, @taspeotis! We'll change the behavior here 👍
