### ISSUE TITLE
Customizable Content Security Policy: iframes and embedding

### ISSUE THREAD

**Issue by Jm-Fox** [datalust/seq-tickets#1448]
This is an Enhancement suggestion.

Seq (2021.4) currently returns the following header:
`content-security-policy: default-src 'self'; frame-src 'self'; connect-src 'self' ws:; img-src 'self' https: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline'`

This prevents embedding iframes.

It would be handy to be able to whitelist embedding iframes from select domains. This could be done in the system configuration, or somewhere else.

The reason I ask is because I was brainstorming how to put together a certain troubleshooting page, and I thought it'd be handy to have Seq logs side-by-side with the controls for troubleshooting (use of which may change the Seq url with filter query strings).

**Comment by nblumhardt** [comment]
Hi Joseph,

Thanks for the suggestion. This is what the Seq `api.frameAllowFrom` setting previously addressed, but as [`ALLOW FROM` has been deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options), it would make sense for us to replace this setting with the corresponding `frame-ancestors` CSP directive 👍

**Comment by Jm-Fox** [comment]
Thanks for the prompt reply letting me know how this can be configured in the current version of Seq.

I finally got around to testing `api.frameAllowFrom` (Seq version 2021.4.6986), and I get errors in the Chrome (98.0.4758.102) log which aren't due to deprecation.

For the following configuration command:
> `seq config set -k api.frameAllowFrom -v "localhost *.example.com *.example.local"`

I get the console error:
```
Invalid 'X-Frame-Options' header encountered when loading 'https://dev-seq.example.local/': 'ALLOW-FROM localhost *.example.com *.example.local is not a recognized directive. The header will be ignored.
```

When I try adding quotes:
> `seq config set -k api.frameAllowFrom -v "'localhost' '*.example.com' '*.example.local'"`

I get the console errors:
```
The source list for the Content Security Policy directive 'frame-src' contains an invalid source: ''localhost''. It will be ignored.
The source list for the Content Security Policy directive 'frame-src' contains an invalid source: ''*.example.com''. It will be ignored.
The source list for the Content Security Policy directive 'frame-src' contains an invalid source: ''*.example.local''. It will be ignored.
```

It seems the issue is `api.frameAllowFrom` is returned in two different headers: `X-Frame-Options` and `Content-Security-Policy`, however Chrome has different expected value formats for these two headers. For all I know what Chrome allows in these header values has changed since this was first implemented.

I've not tested with other browsers as other browsers are not important to me for my present use case.

As could be guessed, I did not actually use hosts `example.com` and `example.local`; at present my employer prefers to be relatively anonymous on public forums.

---

These errors cause Chrome to disregard all frame security policies, which is actually sufficient for my use case. Because our Seq instances are not exposed to the internet and lie behind authentication, losing some security policy protection is an acceptable risk. I'm fine using this as-is, but I wanted to make sure you're aware of the behavior observed above.

**Comment by nblumhardt** [comment]
Thanks for all of the info, Joseph. I think the current implementation of the setting in Seq only supports a single URI value, e.g. "https://example.com", and won't work correctly with multiple hosts or wildcards. Definitely high time we updated this 👍

**Comment by liammclennan** [comment]
See https://docs.datalust.co/v2022.1/docs/json-config

This will be a new config key 'frameAncestors' that corresponds to the CSP frame-ancestors directive. So the example above would become:

```
seq config set -k api.frameAncestors -v localhost,*.example.com,*.example.local
```

and that could create a CSP header like:

```
Content-Security-Policy: default-src 'self'; frame-src 'none'; frame-ancestors localhost *.example.com *.example.local; connect-src 'self' ws:; img-src 'self' https: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline'
```
