### ISSUE TITLE
Failed with status code InternalServerError: An error occurred writing to event storage

### ISSUE THREAD

**Issue by realivanjx** [datalust/seq-tickets#1476]
**Describe the bug**
I got `Failed with status code InternalServerError: An error occurred writing to event storage.` with `sqelf`.  Restarting `sqelf` does not help at all. `seq` just wont accept any logs from the `sqelf` nor from my `serilog` in c# until i restarted the container. This happens after several hours (10-15 hours) running `seq`. However im still able to access the web gui just fine it is just that `seq` wont ingest log from anywhere.

**To Reproduce**
1. Just leave it running for several hours.

**Expected behavior**
`seq` keeps ingesting logs forever.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 (Raspberry Pi 4)
 - Seq Version: 2021.4
 - Using Docker? Yes

**Additional context**
Im running `seq` and `sqelf` with limited memory of 150 MB with 1 GB swap each.

Some of the logs from `seq`:
```
[09:34:39 INF] The policy ran but took no action; elapsed 274.8986 ms
[09:34:39 INF] Removing events before "2022-02-07T09:30:00.0000000Z" matching "`signal-129`" under policy "retentionpolicy-131" (deleting from "2022-02-06T21:55:00.0000000Z")
[09:34:39 INF] The policy ran but took no action; elapsed 0.1354 ms
[09:34:39 INF] Retention processing and compaction took 812.1665 ms; allocating 599187.8335 ms for indexing
[09:34:39 INF] Beginning indexing
[09:34:39 INF] Wrote 0 index sets in 29 ms
[09:34:39 INF] Indexing took 29 ms; total iteration time was 841.7907 ms
[09:34:42 INF] 52 more generation 2 garbage collection(s) occurred
[09:35:42 INF] 50 more generation 2 garbage collection(s) occurred
[09:36:42 INF] 47 more generation 2 garbage collection(s) occurred
[09:37:42 INF] 43 more generation 2 garbage collection(s) occurred
```

**Comment by nblumhardt** [comment]
Hi! Thanks for getting in touch.

Those GC rates suggest that you're ingesting or retaining more than the tiny instance can handle (150 MB is not a lot of RAM for Seq, even with some swap, unfortunately).

Storage speed is also likely to be a problem on tiny machines, as is storage device and filesystem behavior, though it's hard to gauge whether this is having an impact. There should be some more diagnostic info in `/data/Logs`, which you can forward to us via support@ if you need some help interpreting it.

In all, though, my best guess given the amount of GC going on is that you'll need to allocate the container quite a bit more RAM. YMMV :-)

Hope this helps!

Nick

**Comment by nblumhardt** [comment]
Hi @realivanjx - if you need any further help please don't hesitate to ping some diagnostics (either the log data mentioned above, or _Settings > Diagnostics > Download a full diagnostic report_) through to our support team. I'll close this assuming you were able to work around the issue by assigning the container some more resources.

Best regards,
Nick

**Comment by realivanjx** [comment]
i have increased the ram limit to 200mb and it works quite good for a few days now without a problem. i have also changed from sdcard to ssd for my raspberry pi. most of the time it only consumes around 120-130mb of memory so i thought setting it to 150mb wont be a problem. too bad some swap cant help it. i also have changed the sqelf container to the ones from the nuget apps.

**Comment by nblumhardt** [comment]
That's great - thanks for the follow-up.
