### ISSUE TITLE
Is it Possible Use Seq as a MessageQueue/PubSub/Stream

### ISSUE THREAD

**Issue by dengyakui** [datalust/seq-tickets#1481]
There are some cool features when treat Seq as a MQ,  for example, 
-  Cross platform + Windows friendly, do not require linux deloy, easy setup for developer
-  Built in dashboard and manage system
-  High Performance, RUST engine + dotnet runtime,   real time viewing the incoming messge logs
-  support backup storage and retention policy settings
-  Built in  Support Cluster mode, no 3rd dependency like zookeeper

I have some crazy idea,  since Seq provides SDK to write custom code to listening logs, Can We improve this feature?
- when i writes logging,  add a [Topic] attribute to the msg
- when i listening log, i can spcify the Topic to filter
- when my consumer app get the message, do some business logic, could [Ack] the msg to Seq by ID.

**Comment by nblumhardt** [comment]
Thanks again for raising this @dengyakui. We'll close as it's not a feature we plan to progress at this point, but if you would like to discuss it more, please don't hesitate to open a thread over in `/discussions` - happy to dig in! 👍
