### ISSUE TITLE
Seq Retention Policy not working

### ISSUE THREAD

**Issue by mpp-olano** [datalust/seq-tickets#1494]
Seq Instance runs in a Docker container on an Azure VM. Disk space is fast running out as app logs volume has increased. However, I reduced the retention policy from 30 days to 18 days but this didn't free up disk space. Also, I noticed the server still keeps 30 days Logs in the Logs folder after the update.
![image](https://user-images.githubusercontent.com/87758886/155194629-6162b96f-b800-4316-9c75-f3a65b0532f1.png)
![image](https://user-images.githubusercontent.com/87758886/155194746-cb423695-1c7f-42c9-b97e-b82d19f62f50.png)

**Comment by liammclennan** [comment]
Hi @mpp-olano , 

The retention policy is unable to run because there is not enough free space on the disk to write the temporary files that are required by some delete operations.

Are you able to manually reclaim some disk space or expand the DR server's disk?

**Comment by nblumhardt** [comment]
Hi again - just checking in on this one, were you able to free some disk space and return the server to healthy operation? Let us know if there's anything more we can do to help.

**Comment by nblumhardt** [comment]
Hi @mpp-olano - we'll close this assuming you were able to resolve the issue; if you need any further help, please don't hesitate to contact us here or via `support@datalust.co`. Thanks!

**Comment by mpp-olano** [comment]
Hi Nicholas,

Thank you for your mail.

Sorry for the late response. Yes, you can close the ticket.

Regards,

From: Nicholas Blumhardt ***@***.***>
Sent: 24 March 2022 03:32
To: datalust/seq-tickets ***@***.***>
Cc: Olan Odunlami ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [datalust/seq-tickets] Seq Retention Policy not working (Issue #1494)


Hi @mpp-olano<https://github.com/mpp-olano> - we'll close this assuming you were able to resolve the issue; if you need any further help, please don't hesitate to contact us here or via ***@***.******@***.***>. Thanks!
