### ISSUE TITLE
Instructions for connecting Slack app to a web hook are unclear

### ISSUE THREAD

**Issue by mortenn** [datalust/seq-tickets#1513]
As the web hooks feature of slack is deprecated, are there any plans on building a Seq app for slack?

**Comment by liammclennan** [comment]
Hi @mortenn,

There is a Seq app for Slack. 

https://docs.datalust.co/docs/slack-notifications

https://blog.datalust.co/sending-alerts-to-slack/

**Comment by mortenn** [comment]
Hi @liammclennan 

Yes, I am well aware of that and I use it, but when I set up an incoming web hook "app" in slack, there is a notice stating it is deprecated by slack, and may be removed in the future, recommending one uses a slack app instead.
I could not find any slack app for seq in slacks registry, hence me raising this issue.

**Comment by liammclennan** [comment]
Seq uses the '[incoming webhooks](https://slack.com/intl/en-au/help/articles/115005265063-Incoming-webhooks-for-Slack)' feature of Slack Apps which does not appear to be deprecated. 

Slack's ['Legacy incoming webhooks'](https://api.slack.com/legacy/custom-integrations/messaging/webhooks) has a warning that 'they will be deprecated and possibly removed in the future', but we do not use this feature.

**Comment by mortenn** [comment]
As the configuration UI for the seq app says "Add the Incoming WebHooks app to your Slack to get this URL." 
![image](https://user-images.githubusercontent.com/640095/157857303-96e5f6ff-fc38-4106-8f40-c5e0ab015c78.png)

When I searched for "incoming webhooks", the only app I found in slacks directory was the legacy incoming webhooks app, so that is what I used. Updating the hint text below the webhook url field might be desirable?

**Comment by liammclennan** [comment]
Thanks Morten,
We'll have a look and see if we can find something clearer.
