### ISSUE TITLE
Infinite scrolling works on Chrome but not Firefox

### ISSUE THREAD

**Issue by SeanKilleen** [datalust/seq-tickets#1514]
**Describe the bug**

When viewing enough log results that infinite scrolling is enabled, I am unable to scroll in Firefox using a mouse wheel or laptop touchpad. Chrome appears to be unaffected and behaves as expected.

This bug has existed for a while but figured I'd write it up after encountering it on the most recent release. Has existed for me over multiple versions of both Chrome and Firefox, but I'll capture all the current versions here for reference.

**To Reproduce**

OS: Windows (both 10 and 11) -- not sure if OS affects the behavior

* run a containerized Seq, `datalust/seq:2021.4.7192`
  * By the way, I absolutely ❤️ that seq can be run in a container.
* Log enough messages in Seq to enable scrolling
* Open seq in latest Chrome, e.g. `99.0.4844.51`
* Attempt to scroll. Works as expected
* Open seq in latest Firefox, e.g. `98.0`
* Attempt to scroll. Scrollbar appears to catch or not allow infinite scrolling.

ℹ️ Note that if I grab the scrollbar with the mouse, I can drag it in Firefox. It's just doesn't work without clicking and dragging the scrollbar explicitly. 

**Expected behavior**

I expect infinite scroll to work across major browsers.

**Screenshots**

Animated screencap of behavior:

![Screencap of behavior](https://user-images.githubusercontent.com/2148318/158030320-70c4147f-4f3b-4ca3-a1ce-0eda9e189394.gif)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chome 99.0.4844.51, Firefox 98.0
 - Seq Version: 2021.4.7192
 - Using Docker? Yes

**Comment by nblumhardt** [comment]
Thanks Sean, we'll take a look!

**Comment by liammclennan** [comment]
Hi Sean,

Thanks for the report. It looks like the browser starts to scroll but keeps bouncing back up.

I have tested in Firefox 97 and 98 on Linux and Windows 10 and so far not been able to reproduce the bug.

Can you please have a look in the browser developer tolls and see if it is reporting any errors?

Also, are you able to scroll using the up/down arrows or page up / page down?

**Comment by SeanKilleen** [comment]
> Can you please have a look in the browser developer tools and see if it is reporting any errors?

I looked before submitting -- only some warnings related to cookies, nothing relevant.

> Also, are you able to scroll using the up/down arrows or page up / page down?

If I click a specific log message, then yes I can navigate with the arrows and page up/down.

The issue seems to be scoped to just when a query is run or a page is loaded.

One thing I noticed on both Chrome & Firefox -- after a search is run or a page is loaded and results are displayed, if I try to scroll even the tiniest bit, the "Play" icon turns to a "Stop" icon, as if seq is completing some sort of operation. It only happens during the first attempt at a scroll and not afterwards. 

> ![2022-03-18_seq-scrolling-firefox](https://user-images.githubusercontent.com/2148318/158990848-b4ded31b-b961-4455-a076-49908141d9c5.gif)

In Chrome, this appears to correspond with infinite scroll being "loaded" or ready, and in Firefox it seems that operation may not complete.

**Comment by liammclennan** [comment]
Hi Sean,
We still haven't had any luck reproducing this. We thought it might be related to touch screens, or unusual resolutions, but neither of those helped get a reproduction. 

If you have a server that shows the problem, but does not have any sensitive data, could you please send a HAR file to support?

**Comment by SeanKilleen** [comment]
@liammclennan wow, that is truly odd. I have this problem on my machine even when entirely blowing away the seq container and pulling the latest version again, even across versions. (No specific data, no volumes saved, etc.) Even more interesting, I believe can recreate on both my desktop (an older win10 machine) and my laptop (a newer XPS 15). I believe I can recreate it whether using a mouse on the desktop, the mouse connected to a laptop, or the trackpad of the laptop. (The laptop itself is not a touchscreen). The reason I reported it is because it seems fairly reproducible to me. Seems like we've got an interesting one on our hands. :)

Perhaps a video walkthrough or quick meeting would be helpful?

**Comment by SeanKilleen** [comment]
@liammclennan also, apologies, I missed your request for a HAR file. Happy to do it when I get the chance. I'll recreate seq in the container, run my console app to get a few lines in, and then will get the HAR generated.

One other thing I'll try now that I know this may be a "me problem" 😆 -- I'll ensure that I disable all extensions etc. in case something is interfering there.

**Comment by SeanKilleen** [comment]
Well well well....after some more extensive troubleshooting on my end, this appears to be an issue with a browser extension doing something it shouldn't in Firefox. I restarted with add-ons disabled and it works as expected. I'm in the process of narrowing down the culprit and then I'll post more information here as an FYI. Sorry for not doing that specific troubleshooting earlier.

**Comment by SeanKilleen** [comment]
I found it! The issue in my case was the `Logitech SetPoint` extension, which (ironically) touts "Smooth scrolling for Logitech mice" 😆 . 

Again, thanks for the effort put into supporting this and sorry that I hadn't thought to disable extensions first.

**Comment by nblumhardt** [comment]
That's good to know - thanks Sean!
