### ISSUE TITLE
Seq crashes at random after upgrading to 2021.4.7192

### ISSUE THREAD

**Issue by kopetersen** [datalust/seq-tickets#1520]
We upgraded Seq march the 15th. Upgrade went well, but Seq has crashed 4 times since then. 

We get these in the event log each time:
`Application: seq.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFCAB4C2B5C`

`Faulting application name: seq.exe, version: 2021.4.7192.0, time stamp: 0x61954b73
Faulting module name: coreclr.dll, version: 6.0.121.56705, time stamp: 0x619543a3
Exception code: 0xc0000005
Fault offset: 0x00000000000c2b5c
Faulting process id: 0x24f8
Faulting application start time: 0x01d83834179d0905
Faulting application path: C:\Program Files\Seq\seq.exe
Faulting module path: C:\Program Files\Seq\coreclr.dll
Report Id: 501821d1-b5ec-49bf-a307-6626f53e31c1
Faulting package full name: 
Faulting package-relative application ID: `

I looked in the Seq log to see if there was a pattern.
Here is the logs where I included the last line before the crash and the line where Seq starts again.
I can send full logs if needed.

`{"@t":"2022-03-17T10:48:45.6097911Z","@mt":"Memory is overutilized, so cooling down segment {Segment} ({HotCount} events)","Segment":"2022-03-17T04:00:00.0000000Z","HotCount":17729025,"SourceContext":"Flare.Cache.SegmentCache"}
{"@t":"2022-03-17T10:51:11.1805348Z","@mt":"Seq {SeqVersion} running on OS {OSCaption}","SeqVersion":"2021.4.7192","OSCaption":"Microsoft Windows Server 2019 Standard","SourceContext":"Seq.Server.Features.Diagnostics.EnvironmentInformationWriter"}
`

`{"@t":"2022-03-18T08:31:11.9701341Z","@mt":"HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms","@r":["0.3877"],"RequestMethod":"GET","RequestPath":"/api/settings/setting-checkforupdates","StatusCode":403,"Elapsed":0.3877,"SourceContext":"Seq.Server.Web.Middleware.RequestCompletionMiddleware","RequestId":"800322e7-000a-f400-b63f-84710c7967bb"}
{"@t":"2022-03-18T08:33:00.7455470Z","@mt":"Seq {SeqVersion} running on OS {OSCaption}","SeqVersion":"2021.4.7192","OSCaption":"Microsoft Windows Server 2019 Standard","SourceContext":"Seq.Server.Features.Diagnostics.EnvironmentInformationWriter"}
`

`{"@t":"2022-03-21T03:18:14.2177898Z","@mt":"HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms","@r":["0.4204"],"RequestMethod":"GET","RequestPath":"/api/settings/setting-checkforupdates","StatusCode":403,"Elapsed":0.4204,"SourceContext":"Seq.Server.Web.Middleware.RequestCompletionMiddleware","RequestId":"80052c2c-0006-f800-b63f-84710c7967bb"}
{"@t":"2022-03-21T03:20:58.6811763Z","@mt":"Seq {SeqVersion} running on OS {OSCaption}","SeqVersion":"2021.4.7192","OSCaption":"Microsoft Windows Server 2019 Standard","SourceContext":"Seq.Server.Features.Diagnostics.EnvironmentInformationWriter"}
`

`{"@t":"2022-03-21T13:54:48.1426792Z","@mt":"Removing events before {DeletingUntilUtc:u} matching {RemovedSignalExpression} under policy {RetentionPolicyId} (deleting from {DeletingFrom:u})","@r":["2022-03-14 13:50:00Z","2022-03-14 13:40:00Z"],"DeletingUntilUtc":"2022-03-14T13:50:00.0000000Z","RemovedSignalExpression":"signal-3589","RetentionPolicyId":"retentionpolicy-3591","DeletingFrom":"2022-03-14T13:40:00.0000000Z","SourceContext":"Seq.Server.Features.Retention.RetentionPolicyApplier"}
{"@t":"2022-03-21T14:07:24.2611732Z","@mt":"Seq {SeqVersion} running on OS {OSCaption}","SeqVersion":"2021.4.7192","OSCaption":"Microsoft Windows Server 2019 Standard","SourceContext":"Seq.Server.Features.Diagnostics.EnvironmentInformationWriter"}
`

**SeqVersion: 2021.4.7192
OS Version: Microsoft Windows Server 2019 Standard (1809)**

**Comment by nblumhardt** [comment]
Thanks for getting in touch, @kopetersen, sorry to hear you're encountering some difficulties.

We haven't seen this issue previously - we may need some additional memory diagnostics, but to get us up to speed on how the instance is going, the best starting point would be the diagnostic report from _Settings > Diagnostics > Download a full diagnostic report_. If you can shoot that through to `support@datalust.co`, we'll dig in and figure out some next-steps.

Best regards,
Nick

**Comment by kopetersen** [comment]
Ok, thanks

I have sent a mail with diagnostics data.

**Comment by nblumhardt** [comment]
Thanks for that, @kopetersen. Do you happen to recall which version you upgraded from? I.e. was it another 2021.4 version, or an earlier release?

Best regards,
Nick

**Comment by nblumhardt** [comment]
One other thought (may be better for the email thread than here), are you running any antivirus software on the server in question? If so, does excluding Seq.exe and its storage folders alleviate the issue? Thanks!

**Comment by kopetersen** [comment]
I´m not 100% on this, think it was this version before: Seq-2021.2.5647. That´s the file I found in the Recycle Bin.

When I upgraded I excluded the Stream folder as recommended in your documentation.
It´s just the default Windows Defender in Server 2019.

I will try to exclude the seq.exe too.

**Comment by kopetersen** [comment]
Fixed by updating Seq to latest version

**Comment by nblumhardt** [comment]
Fantastic news, thanks @kopetersen :+1:
