### ISSUE TITLE
Signals in retention displayed incorrectly

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#1532]
**Describe the bug**
On the retention tab in the settings, the `in` keyword is pushed to the right instead of inbetween the signals

**Expected behavior**
Display similiar to this
![image](https://user-images.githubusercontent.com/7110884/160601239-67e28fbd-22fb-4663-9092-068ba981ba5c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/7110884/160601020-174c29f3-358e-4cdf-8b94-b6490a6d0c07.png)

**Environment (please complete the following information):**
 - OS: Windows Server 2019
 - Browser: Edge 99.0.1150.46
 - Seq Version: 2022.1
 - Using Docker? No

**Comment by KodrAus** [comment]
Thanks for the report @Suchiman! That certainly doesn't look right...

**Comment by nblumhardt** [comment]
Fixed in the upcoming patch 👍
