### ISSUE TITLE
Aborting query results in spurious error

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#1534]
**Describe the bug**
If you abort a running query that did not yield any results thus far, seq will say that events could not be loaded because the server couldn't be contacted

**To Reproduce**
1. Enter a query that will not yield results like `1 == 0`
2. While seq reports the scan progress, click on the Stop button.
3. See error

**Expected behavior**
Seq displays how many events until when were scanned and that no events matched
![image](https://user-images.githubusercontent.com/7110884/160627571-e6da56c9-3b76-44dd-95b2-9a3bcc86fe40.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/7110884/160627210-ef4fd6fc-6744-4a15-8a85-d8f6c82beba2.png)

Environment (please complete the following information):

OS: Windows Server 2019
Browser: Edge 99.0.1150.46
Seq Version: 2022.1
Using Docker? No

**Comment by nblumhardt** [comment]
Thanks :+1:
