### ISSUE TITLE
Edit and Continue for Queries

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#1535]
When searching through historical data i sometimes select too much data and would like to refine my search criteria to exclude more events but if you had to wait 10 minutes for the archieve search already, starting over is a waste of time and aborting, changing the `To` to where you left off and resume discards existing results and is more effort than necessary.

I believe it would be easily implementable in frontend code only to allow editing the query text and then have a button to "apply the changes" to the running query which simply changes the `signal` / `filter` query parameter supplied to the API while keeping the same `afterId` argument.  The current request could either be arborted and immediately reissued or only start applying the changed filter on the next request.

Optically, the previous and new query texts could be displayed inline with the results as a horizontal divider to make it clear that you've changed something.

A stretch goal would be to drop events from display that no longer match the filter without rerunning the query, but i believe this is probably too difficult to accomplish.

**Comment by nblumhardt** [comment]
Thanks for the suggestion! Your "stretch goal" sounds like it overlaps with "search within results", which we've also given some thought to. We'll loop back to this and discuss :+1:

**Comment by nblumhardt** [comment]
Hi again, thanks for raising this. We're not anticipating being able to move this one forward in the near future. Thanks for getting it onto our radar, though, we'll definitely keep it in mind.
