### ISSUE TITLE
Dashboard: Edit as JSON, buttons not available

### ISSUE THREAD

**Issue by HenningTorsteinsenBouvet** [datalust/seq-tickets#1540]
**Describe the bug**
The JSON dashboard editor does not have scrollbar, and the vertical size of the editor is adjusted to the length of the JSON. 
This causes the editor to extend above and below the visible screen area, making it impossible to get to the "Done" or "Cancel" buttons.

In addition, keyboard navigation is not implemented (Esc to close?) so the only option is to reload the page.

**To Reproduce**
1. Go to a dashboards
2. Click on 'Edit as JSON'
3. Despair

**Expected behavior**
Scrollbar to scroll long JSON.
Press Escape key to close JSON editor

**Environment**
 - OS: Windows Version 10.0.19042.1586
 - Browser: Chrome and Edge
 - Seq Version 2021.3
 - Using Docker? No

**Additional context**

**Comment by liammclennan** [comment]
Hi @HenningTorsteinsenBouvet ,

Thanks for the report. This is a bug that has been fixed. Upgrading to the latest version of Seq should fix it for you.

**Comment by HenningTorsteinsenBouvet** [comment]
Oh, sorry about that!
