### ISSUE TITLE
Confusing behaviour of time filtering text box when UTC time is selected in preferences

### ISSUE THREAD

**Issue by frabul** [datalust/seq-tickets#1551]
**Describe the bug**
I have selected "Show timestamps in Coordinated Universal Time (UTC) " in personale preferences.
In events window:
1) whenever i write something or select a day in the time filters text boxes then the time selected seems to be considered local and gets automatcally converted to UTC as soon as the text box loose focus or enter is pressed 
2) when the query is executed the time currently seeen in text box is *again* considered local and converted to UTC
 

**To Reproduce**
1. Select "Show timestamps in Coordinated Universal Time (UTC) " in personale preferences
2. Go to events
3. Write query "select count(*) from stream  group by time(1d)"
4. Select current day in the text box "FIRST"
5. Press enter multiple times
6. Observe how the time is changed every time enter is pressed
7. Observe how the start time of each group is different then the time in the text box

**Expected behavior**
The time entered trough the UI should be considered already UTC

**Screenshots**
![immagine](https://user-images.githubusercontent.com/180771/163132813-09b41ac1-1c81-4659-8ecb-e9790cab6719.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser Firefox
 - Seq Version 2022.1
 - Using Docker? Yes 

**Additional context**

**Comment by liammclennan** [comment]
Hi @frabul ,
Thanks for the report. That does not look right at all.
