### ISSUE TITLE
Support multi-tenant storage of metastore in SQL Server

### ISSUE THREAD

**Issue by HakanL** [datalust/seq-tickets#1580]
I'm looking into hosting multiple independent SEQ instances and it would've been neat to have the metastore in Azure SQL, however I don't want a SQL server/instance per tenant (SEQ instance). Instead I'd like them all to store the metadata in a single Azure SQL Database, but with some identifier related to the name of the SEQ instance.

**Comment by nblumhardt** [comment]
Thanks for the note, Hakan. This should already be supported via the `--schema` argument accepted by `metastore to-mssql`, and in the `metastore.msSql.schema`/`SEQ_METASTORE_MSSQL_SCHEMA` environment variable. Does this help?

**Comment by HakanL** [comment]
Thanks Nicholas, I'll try that, I didn't see that when I looked through the docs, it just said that even with SQL it needed exclusive access to the database.

**Comment by nblumhardt** [comment]
Thanks for the note about the docs - I'll update them 👍

**Comment by nblumhardt** [comment]
Docs updated now.
