### ISSUE TITLE
Public ECR Docker Image

### ISSUE THREAD

**Issue by andymac4182** [datalust/seq-tickets#1581]
Hi,

It would be great if the latest images are started to be posted to https://gallery.ecr.aws/datalust/seq as well as docker hub which will reduce start times and remove any issues with the image being references from AWS.

**Comment by nblumhardt** [comment]
The 2021.1 patch we're about to publish will sim-ship to ECR :-)

**Comment by andymac4182** [comment]
Thanks :D
