### ISSUE TITLE
Automatic change of culture for log output?

### ISSUE THREAD

**Issue by ahorn42** [datalust/seq-tickets#1592]
Hi, 

I discovered culture formatting issue while logging numeric data.

In my C# code I have a command like the following:

```csharp
_log.Verbose($"{ Point.X.ToString(CultureInfo.InvariantCulture) } { Point.Y.ToString(CultureInfo.InvariantCulture) }");
```
`Point.X` and `Point.Y` are of the type `double`.

If I check the raw JSON export I see the data as assumed:

```
12.3 4.56
```

but in the events area of the seq web interface I see:

```
12,3 4,56
```

The region of my PC is configured for Germany (we use a comma as decimal separator as default), but as I actively convert the data to string before handing it over to seq (with the `ToString` function) I would assume, that seq should handle it as string and print it as it is (with a dot as separator, due to the `CultureInfo.InvariantCulture` parameter) and not parse it as double and put it out again with a different localized culture formatter.

For logging I use [Serilog](https://github.com/serilog/serilog). It is configured as following:

```csharp
Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Verbose()
                .Enrich.FromLogContext()
                .Enrich.WithThreadId()
                .Enrich.WithProperty("RootAssemblyName", executingAssemblyName.Name)
                .Enrich.WithProperty("RootAssemblyVersion", executingAssemblyName.Version)
                .WriteTo.File(logPath, outputTemplate: FileFormat, rollingInterval: RollingInterval.Day)
                .WriteTo.Debug(outputTemplate: DebugFormat)
                .WriteTo.Seq("http://127.0.0.1:5341")
                .CreateLogger();
```

In my opinion this is more a bug as a feature ;-)

I also see a little chance that a part of this issue originates form Serilog (might be that they do the conversion back to double), but anyway I think normal and raw output should not differ in the culture formatting of numbers.

best regards!

**Comment by liammclennan** [comment]
Hi @ahorn42 ,

Thanks for the report. 

When you say "raw output" do you mean the log file at `logPath` configured with `.WriteTo.File`?

Also, can you please provide a screenshot of the Seq UI showing where that formatting appears? Please obscure any sensitive data and send the image to `support@datalust.co`. 

Please also verify that the event you see in Seq is generated by the `_log.Verbose` call above. Perhaps try modifying it to something like:

```
_log.Verbose($"{ Point.X.ToString(CultureInfo.InvariantCulture) } { Point.Y.ToString(CultureInfo.InvariantCulture) } ^");
```

and check that you get `12,3 4,56 ^` in the Seq UI.

**Comment by ahorn42** [comment]
With "raw output" I meant the JSON I get, from the export menu of an entry:
![image](https://user-images.githubusercontent.com/5106205/175232607-f4d27893-0c71-4a86-b1eb-394c43d4f84d.png)

But as I tested your suggestion I found the issue - seems like there was a second place, were the coordinates were logged also, which misses the `ToString` part. Now it works as expected - sorry so much for false alarm.
