### ISSUE TITLE
Update `Microsoft.Data.SqlClient` to enable Azure Federated Identity (depends on v5.0.0 GA)

### ISSUE THREAD

**Issue by pinkfloydx33** [datalust/seq-tickets#1598]
The current Seq implementation supports connecting to SQL server for the metastore database. As mentioned in [this post](https://docs.datalust.co/discuss/613762a0ddd039015f96d83d) it currently supports managed identity authentication to Azure SQL inheritenly thanks to the employed version of `Microsoft.Data.SqlClient`.

Unfortunately the current version of Ms.D.SqlClient does not support the new Azure Federated Identity. For those of us running Seq in Kubernetes, we currently obtain managed identity authentication via a mechanism called pod-identity. This addon is in permanent, deprecated preview and is being replaced by federated authentication via the more general-purpose Azure Workload Identity. 

Support for this type of  authentication requires updates to the various azure clients, etc. In the case of SQL, this means an eventual update to the Microsoft.Data.SqlClient package. The necessary support is now available in the recently released version 5.0.0-preview3

I am not requesting that Seq upgrade to the preview version as I realize that would be unreasonable. I am merely filing this issue to track the eventual update to 5.0.0, the planned release date of which I am unsure. 

Seq will be our final blocker for moving off the deprecated pod-identity product. I am hopeful that you will take this under consideration once 5.0.0 goes GA.

**Comment by nblumhardt** [comment]
Appreciate the heads-up, we'll aim to update as soon as possible 👍

**Comment by pinkfloydx33** [comment]
According to their roadmap, they had planned to GA in May 2022. I posted a discussion in their repo to see if there's a new estimate as to when it will GA.

For reference, it turns out this only _technically_ depends on `Azure.Identity` 1.5.0+. I had assumed it was something in SqlClient but it's actually coming from the Identity package. The new 5.0 version of SqlClient is referencing Identity 1.6.0 out of the box, rather than the 1.3.0 you're distributing.

**Comment by pinkfloydx33** [comment]
5.0 was released Friday August 5th

**Comment by nblumhardt** [comment]
Thanks @pinkfloydx33 :+1:

**Comment by nblumhardt** [comment]
2023.1 now includes 5.0.1; preview builds should start to appear in the next few hours.
