### ISSUE TITLE
Seq crashes on a query

### ISSUE THREAD

**Issue by BryanKipp** [datalust/seq-tickets#1614]
Hello!

Thank you for making a wonderful tool.

My Seq instance on Azure VM (2 vcpus, 8 GiB memory) crashes when I'm trying to execute the following query:

`select distinct(InstallId) from stream where @Message like '%revoked%'`

The date interval is 30 days. If I set a 3 days interval, everything works as expected.

I'm attaching the Diagnostics log to the issue. (redacted)

After the crash, the Seq server is not restarted automatically, so I have to start it manually:
![image](https://user-images.githubusercontent.com/5780816/179588445-db5401ea-3f25-45da-a102-25d79adbe3fe.png)

Here is what I see in the Event Log:
![image](https://user-images.githubusercontent.com/5780816/179590790-c956c98c-32a0-480b-9c1e-e1909fef700e.png)

Any ideas? Please let me know if I need to provide any additional information.

**Comment by nblumhardt** [comment]
Thanks for the report, Bryan, we'd love to get to the bottom of this. Unfortunately the fault information in the event log leads us to a very general part of the codebase and doesn't reveal the issue. To get more detail we'll need a Windows crash dump.

If you're able to collect one for us, the process is to first ensure the following registry key (folder, in Regedit) exists:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps
```

Once the key is present, and Seq crashes, Windows will write a dump file to:

```
%LOCALAPPDATA%\CrashDumps
```

Please send this to us privately via `support@datalust.co` (crash dumps can contain fragments of application memory at the time of the crash, so it's not advisable to post it here).

Thanks again! These are - thankfully - as rare as hens' teeth, and having the chance to track down a reproducible crash like this is really valuable to us.

Best regards,
Nick

**Comment by BryanKipp** [comment]
Hi Nick,

Thank you for the quick response.
I've reproduced the crash the same way I described above and sent a full dump to `support@datalust.co` , the subject line is "Crash dump - issue #1614".
Please let me know if I need to provide any details.

**Comment by nblumhardt** [comment]
Thank you, Bryan - downloading now! :+1:

**Comment by nblumhardt** [comment]
Closing as we've resolved this one; thanks Bryan!
