### ISSUE TITLE
Ingestion & Arrival graph not working

### ISSUE THREAD

**Issue by EC2E-Gaulupeau** [datalust/seq-tickets#1617]
**Describe the bug**
The graphs of the ingestion are not updating, they are stuck on Monday 12PM (we are Tuesday 4PM in France)

**To Reproduce**
Click on "Data" and then "Ingestion"

**Expected behavior**
The graphs working as intended, there is data ingested for more than 5 hours now

**Screenshots**
![image](https://user-images.githubusercontent.com/109609657/179779693-a1fe542c-74e6-4712-b85f-e7fa8c81398f.png)

**Environment (please complete the following information):**
 - OS: Client on Windows 10 up to date
 - Browser : Chrome 103.0.5060.114 
 - Seq 2022.1.7929
 - Using Docker? YES
 - Accessed using NGINX PROXY MANAGER in proxy for the web app

**Additional context**
It was working on another instance, one week ago, I've setup this one yesterday.

**Comment by nblumhardt** [comment]
Thank you for the report.

Are any error messages shown in Chrome's developer tools console (Ctrl + Shift + i) when browsing the ingestion screen?

Another possibility might be clock drift on your Seq server; you can check this by running:

```sql
select ToIsoString(now())
```

in the Seq events screen.

Alternatively, if none of the above yield any clues, you can check the diagnostic report at Settings > Diagnostics > Download a full diagnostic report for relevant errors. Feel free to send this, or extracts from it, to `support@datalust.co` if you need help interpreting its contents.

Best regards,
Nick

**Comment by EC2E-Gaulupeau** [comment]
Hi,
Thank for your response ;) 
I don't see any error on the dev tools, only when i go to the page "event" i got the following errors 
![image](https://user-images.githubusercontent.com/109609657/179918454-90532a63-c833-42d8-bb0b-5c562b57d8a1.png)
The select output the expected date in UTC format.
The main graph is still frozen to the same date even 1 day later.
Strangely the "Health CheckInput" graph seems to update fine as show below.
![image](https://user-images.githubusercontent.com/109609657/179918942-c4146b0f-5f90-4071-8577-6fb1409c83bb.png)

Do you need the diagnostic report ? I've checked it and nothing seems odd.
Should i restart the docker container ?
Best regards

**Comment by nblumhardt** [comment]
Thank you for the follow-up; we'll dig in deeper and see what we can figure out.

In the meantime, restarting the container might be worth a try - it'd be interesting to hear if this resolves it 👍

**Comment by EC2E-Gaulupeau** [comment]
Hi, I've restarted it, will check in the next hour if the problem is resolved

**Comment by EC2E-Gaulupeau** [comment]
Hi, 
It's working now, maybe once the container is created it should be restarted to be fine.
![image](https://user-images.githubusercontent.com/109609657/179930136-524e8d31-cea5-4a5a-9fc9-ee59e8b66c7e.png)
Thank you ;)
👍

**Comment by nblumhardt** [comment]
That's great - thanks @EC2E-Gaulupeau. Internally, those counters have some logic built in to deal with clock changes that could have temporarily suppressed them - I'll keep an eye out for any future occurrences of this, though!
