### ISSUE TITLE
Setting SEQ_FIRSTRUN_ADMINPASSWORDHASH does not work for me

### ISSUE THREAD

**Issue by hesperanca** [datalust/seq-tickets#1623]
**Describe the bug**
I cannot make the setting "SEQ_FIRSTRUN_ADMINPASSWORDHASH" work for me.  I generated the password by issuing the command:

`echo 'Password123' | docker run --rm -i  datalust/seq:latest config hash`
(as per the instructions here: https://blog.datalust.co/setting-an-initial-password-when-deploying-seq-to-docker/)

but everytime I try to login using the password ( 'Password123' in the example above ) I get a "could not login error".  Everything works fine if I do not set a password.

I think there is a problem with the code that generates the hash because every time I run the command I get a different hash value.

I'm running on a windows 11 machine with docker desktop installed.

**To Reproduce**
1. Using the latest Docker image of seq

2. Generate the password hash by issuing the command:
`echo 'Password123' | docker run --rm -i datalust/seq:latest config hash config hash`

3. Generate the password a second time by issuing the same command above

**Expected behavior**
I would expect the same hash value returned by both commands given that the password is the same

**Screenshots**
![image](https://user-images.githubusercontent.com/29897247/180852881-f0413a11-d28d-4c0c-b25a-3ef565047644.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Seq Version: Using the latest Docker image release 
 - Using Docker? Yes

**Comment by nblumhardt** [comment]
Hi @hesperanca, thanks for getting in touch, and for the detailed report.

The value returned by `config hash` differs each time because the hash is salted, so this won't be the cause of the problem.

The `SEQ_FIRSTRUN_*` settings are only applied when Seq initializes a brand new data store, e.g., when the mounted `/data` volume is completely empty. Could that be the problem here?

Best regards,
Nick

**Comment by hesperanca** [comment]
Hi Nick,

Thanks for your reply. The different values make sense now (because of the random salt).

We just deployed SEQ for the first time to our Azure environment to test it. We have not yet attached any storage to it, we are just working with the default that comes with the image. The plan is to use Azure files. 

Could this be the reason for the issue?

Regards,
Hugo

**Comment by nblumhardt** [comment]
Hi Hugo, thanks for your reply.

Yes, I think so - unless storage is mounted, you'll end up with a fresh container each time you run it, so the container you're logging into won't be carrying the data that `SEQ_FIRSTRUN_...` intialized 👍 

Best regards,
Nick

**Comment by nblumhardt** [comment]
Hi Hugo,

I'll close this ticket as stale, but if you need any further help please just let me know.

Best regards,
Nick
