### ISSUE TITLE
Dashboard chart rendering broken on iPhone

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1627]
When dashboards are rendered on iPhone browsers (reported for Chrome, tested with Safari on iPhone 13), no traces/bars/points are shown on charts.

**Comment by liammclennan** [comment]
Could not reproduce on iOS 12 Chrome and Safari

**Comment by nblumhardt** [comment]
Either via WebKit or our frontend updates, this is no longer an issue in 2023.1 so I'll leave it in the milestone but close here.
