### ISSUE TITLE
Support Lumberjack input in Seq

### ISSUE THREAD

**Issue by LordMike** [datalust/seq-tickets#1629]
I couldnt' find an issue on it, so I'll consider this a tracking issue for lumberjack support in seq :)

I've recently begun using Seq as a server to see how it was, because Nicholas keeps blabbering about it - and I'm happy so far. I was looking at ingesting some file-based logs, but couldn't find a good guide on Seqs pages on it, so I'm looking at using filebeat, but none of filebeats outputs align with Seqs inputs (gelf, syslog). Filebeat does support "logstash" output, which is codeword for the [Lumberjack protocol](https://github.com/elastic/logstash-forwarder/blob/master/PROTOCOL.md).

I think if Seq supported more inputs (which I can only assume is the end goal), it'll have a wider reach and thus grow - I imagine Lumberjack can be instrumental here - as Lumberjack allows for using Filebeat, which in turn opens up a whole world of inputs.

If I were to prototype this - can I simply copy the gelf input and read lumberjack, and see what happens?

References:
* NLog has a [lumberjack writer](https://github.com/kaa/nlog.targets.lumberjack/tree/master/NLog.Targets.Lumberjack), which can give an indication of reading complexity

**Comment by liammclennan** [comment]
Hi @LordMike ,

Seq apps can be used to provide new ingestion options, so yes, you can copy gelf input and convert it to read the lumberjack protocol. 

Another option for ingesting plain text logs is to use `seqcli ingest` with the `--extract` option. https://github.com/datalust/seqcli#ingest

**Comment by LordMike** [comment]
So, I checked up a few things, and found that Lumberjack is undocumented.. V1 exists, but has apparently changed a lot to what it is now, which isn't documented.. So it probably has a long ways to go.

For anyone looking, I would start with the RabbitMQ input, and not the Gelf input. The gelf input is a native binary (rust).

**Comment by liammclennan** [comment]
What's the issue with native binaries?

**Comment by nblumhardt** [comment]
FWIW, it appears likely that FileBeat will support OTLP sometime in the near-to-mid term: https://github.com/elastic/beats/issues/32549#issuecomment-1664156059.

Closing this one as not planned, but thanks for raising it, and do reach out if you (or anyone following along) decide to take a shot at it.
