### ISSUE TITLE
Upload log files through Dashboard

### ISSUE THREAD

**Issue by tobias-tengler** [datalust/seq-tickets#1653]
Hi, I'm loving Seq, but there is one feature that would make my life a lot easier:

We send out our application to customers, but these applications run in an environment that's not connected to the outside world. So I can't send logs to some remote source for ingestion and I also can't easily host a Seq instance in that network I could connect to.
So we are using file based logging and if an error occurs the customer sends us the log files. I know this is not an optimal scenario, but there's nothing I can change about these requirements.

So on the daily I get sent some log files and I use Seq on my machine to nicely visualize these logs. Currently we are using the CLI to ingest these log files and it works fine, but it's also a bit clunky.

A really cool option would be something like an upload button in the UI, where I can just select or drag these log files into and they are automatically ingested. I imagine this to be a low-complexity change on your side, but it would make my experience using the product so much better.

I imagine it also makes it easier for folks to try out the product in general: "Have some existing log file? Just drag it onto the dashboard and view your logs." Makes it really easy to try out without having to configure a bunch of things!

**Comment by nblumhardt** [comment]
Thanks for the suggestion! We've considered this in the past and essentially agree, it's something we'd love to do at some point. We'll give it some more thought and keep you posted here. :+1:

**Comment by nblumhardt** [comment]
We're still interested in enabling this but don't plan to work on it in the near future, so we'll close this in the interests of focus. Thanks for the suggestion nonetheless!
