### ISSUE TITLE
Ingestion page hangs with a large number of API keys

### ISSUE THREAD

**Issue by liammclennan** [datalust/seq-tickets#1668]
**Describe the bug**
Given hundreds or thousands of API keys, the ingestion pages hangs.

**Expected behavior**
The ingestion page should not hang. Accomplishing this will probably involve reducing the detail shown for instances with many API keys. 

**Additional context**
This occurs because Seq plots ~ 300 points in the sparkline for each API key.

**Comment by morgul77** [comment]
I would like to add that the UI hangs/lags on other pages as well after visiting the ingestion page because all data are still fetched in the background even though the user has navigated away from the page

**Comment by liammclennan** [comment]
Thanks @morgul77, how many API keys does your Seq server have?

**Comment by morgul77** [comment]
We have currently 1448

**Comment by nblumhardt** [comment]
This is fixed in 2023.4
