### ISSUE TITLE
Seq UI not responding

### ISSUE THREAD

**Issue by ldubrois** [datalust/seq-tickets#1670]
**Describe the bug**
Once a day, our Seq instance is no longer responding on the website. We have to restart the K8S pod to make the UI available.

The browser sends the requests but no response from the server.

However, while the UI is not available, the logs are still ingested and stored correctly. When Seq is restarted we can see all the logs with no gaps.

**To Reproduce**
Don't know 

**Expected behavior**
The website should be available.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux, AKS environment
 - Browser: Firefox
 - Seq Version: 2022.1
 - Using Docker? Yes

**Additional context**

**Comment by nblumhardt** [comment]
Hi Luc, thanks for reaching out!

Thinking of a few more things that will help us narrow this down - could you please let us know:

 * Is the outage at the same time every day? (e.g. always at 13:00 or some other time?)
 * Do the outages also occur on weekends/when nobody is using Seq?
 * How long have you left the pod for before restarting? (e.g. minutes/hours/days?)
 * What kind of storage do you have attached to the pod (e.g. Azure Managed Disk)?
 * Are you using the same port for logging and ingestion, or do you use a separate ingestion port?

If you can send that info, along with a diagnostic report from Settings > Diagnostics, and a screenshot of your Data > Storage screen to support@datalust.co we will dig in and figure out what's going on.

Thanks!

**Comment by nblumhardt** [comment]
Hi Luc; I'll close this one as stale for now, but if you're still experiencing the issue please let me know. Thanks!
