### ISSUE TITLE
Time span string parsing handled inconsistently by `TotalMilliseconds()`

### ISSUE THREAD

**Issue by taspeotis** [datalust/seq-tickets#1673]
On my local machine (Seq 2022.1 on Windows 11) I can use `TotalMilliseconds` to convert a `TimeSpan` to milliseconds:

![image](https://user-images.githubusercontent.com/1189399/196863989-d05e3330-5503-42b3-a1f7-bb3e56e2095a.png)

Running the same query against our Seq server in production (2022.1, deployed in our Kubernetes cluster using Seq's helm chart) `TotalMilliseconds` cannot convert them:

![image](https://user-images.githubusercontent.com/1189399/196864209-b65496e4-bb0c-478a-bcf2-c5db23e4e3f2.png)

I hope this can be resolved easily! Thank you in advance.

**Comment by taspeotis** [comment]
`TotalMilliseconds(TimeSpan(Duration))` does indeed work perfectly, as you suggest:

![image](https://user-images.githubusercontent.com/1189399/197077384-e7d8f150-4bd5-42d4-be33-60d479e53f2d.png)

My interpretation of what you have written is:

1. It's a regression and `TotalMilliseconds(x)` will work again in a later version of Seq
2. Regardless, `TotalMilliseconds(TimeSpan(x))` works around it in 2022.1
3. Prefer to use numbers with `TotalMilliseconds` rather than a string representation of a `TimeSpan`

On the latter, [the documentation](https://docs.datalust.co/docs/scalar-functions#totalmillisecondstimespan) seems to give equal footing to numbers or strings being fed into `TotalMilliseconds`.

At any rate, the `TotalMilliseconds(TimeSpan(...))` expression is enough for me, thank you.

**Comment by nblumhardt** [comment]
I think your summary matches the conclusions we reached 👍

**Comment by nblumhardt** [comment]
Fixed in Seq 2023.1. Thanks Todd!
