### ISSUE TITLE
Error when grouping by nullable properties for Alerts

### ISSUE THREAD

**Issue by pegasy** [datalust/seq-tickets#1677]
Hi when grouping by a property that is null or sometimes null the Alerts page just says

![image](https://user-images.githubusercontent.com/3257270/198025229-ca3fc5fc-c6d0-41d7-848d-92627827ff39.png)

This is how the alert is defined
![image](https://user-images.githubusercontent.com/3257270/198021836-492ecedc-7245-439e-b753-2730516acfdb.png)

Tested on 2021.3 and 2022.1 and its the same on both

**Comment by nblumhardt** [comment]
Thanks for reporting this @pegasy - definitely a bug here 👍 

As a workaround, you can use something like `coalesce(property_that_does_not_exist, '<null>')` to use a placeholder string value for those missing groups.

We'll get this fixed, thanks again.
