### ISSUE TITLE
Ingestion endpoint for OpenTelemetry Logs

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1679]
The [OpenTelemetry Logs specification](https://opentelemetry.io/docs/reference/specification/logs/) promises to better integrate logs with the metric and trace data collected from OTel-instrumented applications and diverse log sources.

The OTel log format and protocol (though still marked "experimental") is expected to map closely to Seq's HTTP ingestion infrastructure and should be reasonably straightforward to support alongside the existing HTTP, GELF, Syslog, and queue inputs.

We'll tackle OpenTelemetry log ingestion in 2023 because:

 * OTel presents a fantastic opportunity to ease ingestion of rich structured log data into Seq from a variety of systems that might not have first class logging library integration today
 * Support for OTel log ingestion will also help integrate Seq into environments where the deployed log collector or routing infrastructure supports the OTel protocol and format

Ingestion of traces and metrics won't be in scope for this work, but are a future direction we'll need to consider alongside the initial implementation for logs.

**Comment by andymac4182** [comment]
Keen to see how you go with this! 

My personal request would be for the following order
* OTel Logs
* OTel Metrics
* OTel Traces

Metrics would be amazing to integrate with the dashboarding that already exists and hopefully not too complex to expand the current feature set.

**Comment by nblumhardt** [comment]
Logs ingestion is coming together, but there are currently no stable client implementations so nothing can be nailed down just yet of course :-)

![image](https://user-images.githubusercontent.com/342712/232669809-c152810f-5455-4b1f-ac7c-527b367c6717.png)

This is using `OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs` and:

```csharp
builder.Services.AddOpenTelemetry().ConfigureResource(res =>
{
    res.AddService(DiagnosticsConfig.ServiceName);
});

builder.Services.AddLogging(logging => logging.AddOpenTelemetry(otlp =>
    {
        otlp.IncludeScopes = true;
        otlp.IncludeFormattedMessage = true;
        otlp.AddOtlpExporter(exporter =>
        {
            exporter.Endpoint = new Uri("https://localhost:45341/v1/logs");
            exporter.Protocol = OtlpExportProtocol.Grpc;
        });
    }
));
```

**Comment by nblumhardt** [comment]
A new preview that includes this feature is out now. I'm just writing up some quick instructions that will find their way to the Seq blog soon 🎉 

Things have moved along a bit since my last update above; the first thing you'll notice is that dotted OTLP properties like `service.name` and various resource attributes appear directly in the properties list, rather than nested as sub-objects:

![aspnetcore-otlp](https://github.com/datalust/seq-tickets/assets/342712/11d4eb80-4b9f-44c5-b799-45999cc8c8bb)

This makes it much quicker and more pleasant to spot one and filter/chart/exclude it, but the approach called for quite a bit more supporting infrastructure -

 * Resource attributes now live in the `@Resource` namespace, so that their names don't clash with properties attached directly to the log record, and
 * Along with resource attributes, dotted property names now get some inlay/tooltip assistance showing the correct syntax to use when interacting with them in queries (you can see this going on with `dotnet.ilogger.category`, which is a regular property with a dotted name).

Trace and span ids also moved up from the log event payload to a special `Trace` drop-down menu, and some dedicated `@TraceId` and `@SpanId` properties in the query language. Building blocks that should support many interesting use cases in the future.

On the whole I think we're on track to a great low-friction back-end for OTLP logs 😎 

The new preview does require jumping through some hoops to host gRPC services on Windows. Blog post will cover those, but for the GA I think we'll very likely add `http/protobuf` support. Would be great to get any feedback you might have in that area.

**Comment by nblumhardt** [comment]
We've just added a new preview with plain HTTP/protobuf support, which means you can use OTLP ingestion with any existing Seq API endpoint: https://blog.datalust.co/adding-http-protobuf-support-to-opentelemetry-log-ingestion/

All seems to be coming together really nicely - please drop us a line if you can share your experiences with it, good or bad! :-)

**Comment by nschmitz4** [comment]
We are using Seq + Serilog and I recently started to experiment with OpenTelemetry, so this is very timely. The documentation was easy to follow and the process was smooth; adding this to a project was easy!

I do have a question, though, and I apologize if it has already been addressed elsewhere. Are there any plans to introduce support for trace visualization? It would be great to have the ability to visualize the traces/spans themselves and/or see trace/span attributes.

**Comment by nblumhardt** [comment]
Hi @nschmitz4 - thanks for reaching out! Yes, we're definitely on the path to providing higher-level support for both traces and metrics, however in the upcoming release (2023.2) Seq will support logs only. Hope this answers your question, but let me know if you need more info.

**Comment by nblumhardt** [comment]
We're prioritizing iteration and feedback over going too much deeper in 2023.2; the current `datalust/seq:preview` container and preview MSI at https://datalust.co/download cover the functionality we're expecting to ship in the first drop :-) (🎉)

Feel free to chime back in here or open new tickets/discussions with issues or suggestions. Closing as "done" for 2023.2.

**Comment by nschmitz4** [comment]
That does answer my question. Thank you, and thank you for all the work into this product!
