### ISSUE TITLE
copy raw json not working in edge browser

### ISSUE THREAD

**Issue by digitalsigi** [datalust/seq-tickets#1684]
**Describe the bug**

I want to copy raw json from events , not the whole log entry but just for a certain object. But the json does not get copied to clicpboard. 

**To Reproduce**
1. Open Events in seq
2. Click on an entry with some object data
3. Hoover to the front of the opening brace
4. click on the circle 
5. click on copy raw json
6. Paste local editor -> nothing happens 

**Expected behavior**
The json representation is copied to clipboard and can be pasted into some local editor

**Screenshots**
![image](https://user-images.githubusercontent.com/5047081/201057812-1572a0fa-9267-47e7-8816-cccfcb30ba12.png)
Paste is gray and inactive
![image](https://user-images.githubusercontent.com/5047081/201059064-579db714-0d1d-4bfe-b556-99928389aa74.png)

**Environment (please complete the following information):**
 - OS: Windows 10 21h1 Build 19043.2006
 - Browser: Edge
 - Seq Version: 2022.1.7929
 - Using Docker? Yes 

**Additional context**
Download raw json of whole log entry works

**Comment by liammclennan** [comment]
Hi @digitalsigi ,

Thanks for the bug report. I have not been able to reproduce it yet. Do you mind trying with the developer tools open to see if there is an error message?

**Comment by nblumhardt** [comment]
Another thing to check - are you serving Seq over HTTPS? Some browsers disable copy/paste for pages served over HTTP. HTH!

**Comment by digitalsigi** [comment]
@nblumhardt Oh yeah, that's probably the reason. Because seq has no public IP on the server I have to go through ssh tunnel. Thx for pointing me there,

**Comment by digitalsigi** [comment]
Unfortunately, does not seem to be the problem. When highlightning any text, I can copy&paste. However, devtools shows some errors, see screen shot:
![image](https://user-images.githubusercontent.com/5047081/201375667-0d6b856b-88f1-4223-ab2d-6b0edc0997a0.png)

As noted before, I access seq via ssh and port forward. I am not aware of any component blocking the map file.
Any suggestions?

**Comment by digitalsigi** [comment]
I inspected seq docker container seq seqsvr/wwwroot/ and found the file simply does not exist.  But found the explaination for the errors here: https://stackoverflow.com/a/71876238/1889267

Have to either find a way to use https or have no copy paste.

**Comment by nblumhardt** [comment]
Thanks for closing the loop @digitalsigi. Looks like we should fail more gracefully when the clipboard is unavailable :-) thanks for posting all of the details.

Best regards,
Nick
