### ISSUE TITLE
Dashboard y-axis isn't scaling to max value

### ISSUE THREAD

**Issue by sergiojrdotnet** [datalust/seq-tickets#1700]
![image](https://user-images.githubusercontent.com/72770006/205120179-b430461c-9269-4c62-8acc-bbb8ce2c749c.png)

**Comment by nblumhardt** [comment]
Thanks for the heads-up! It would be good to know the Seq version, browser and OS you're using, and anything you can share about the query and chart configuration - we haven't seen this previously so we don't have a lot of ideas what might be triggering it.

**Comment by sergiojrdotnet** [comment]
The company is running version 2021.4.7192 on Windows Server 2016 Standard (v10.0.14393 Build 14393).

![image](https://user-images.githubusercontent.com/72770006/205278526-9ddfb21f-db4d-4986-b120-aa674c100d38.png)

![image](https://user-images.githubusercontent.com/72770006/205278551-fdc547f1-6706-4024-baa0-c609d1d3e63d.png)

![image](https://user-images.githubusercontent.com/72770006/205278571-c785c943-bba6-48de-b17c-c7bb0401e8be.png)

Today, the max value is lower, and it still suppressing line top values.

![image](https://user-images.githubusercontent.com/72770006/205278805-61861ff2-8668-4336-9b0c-bb02bdfd11b5.png)

**Comment by nblumhardt** [comment]
Thanks for your reply. Knowing which browser you're using would also help shed some light on it, however I think the first step should be to upgrade to the latest supported Seq version, which will include updates to dependencies such as those used for charting, and may address the issue.

**Comment by sergiojrdotnet** [comment]
I'm using Microsoft Edge but also found the same issue on another browsers like Chrome, Firefox and Opera.
The company plans to do the version upgrade, but we'll have to wait until next sprint.
Thanks for helping @nblumhardt

**Comment by sergiojrdotnet** [comment]
Hello @nblumhardt, we've upgraded to 2022.1.7929 version this week and the visual error still persists

**Comment by nblumhardt** [comment]
Very strange! Thanks for looping back to us.

Just to double-check, have you refreshed the Seq application in the browser since upgrading, e.g. via F5?

**Comment by sergiojrdotnet** [comment]
Yep, see video evidence

https://user-images.githubusercontent.com/72770006/209320690-73dcea5d-4e70-4e5c-b7c6-10e944984cc3.mp4

**Comment by nblumhardt** [comment]
Thank you Sergio. We'll figure out how to track this down 👍

**Comment by nblumhardt** [comment]
Quick update - we've so far been unable to repro, however we've taken the library that drives these charts through a major version upgrade so we're optimistic that 2023.1 will sort out the bug. If not, we'll take another shot at this for the next update.

**Comment by sergiojrdotnet** [comment]
It's working fine now

![image](https://github.com/datalust/seq-tickets/assets/72770006/5ad8faa2-1e85-4b08-b81c-6769195e9fee)
