### ISSUE TITLE
Retention policies for event properties

### ISSUE THREAD

**Issue by taspeotis** [datalust/seq-tickets#1702]
Could you please consider allowing retention policies to target individual properties on events?

We have an event that logs a HTTP request and response body (among other things), and while [it violates some of your guidelines](https://docs.datalust.co/docs/extend-cache-coverage) (Log smaller events, Avoid serializing large objects into events) it's just convenient to have the body there sometimes.

HTTP calls are numerous, and their bodies are kind of large, so we have a retention policy set up to purge these events after a while.

What I'd like to be able to do is drop the `RequestBody` and `ResponseBody` properties on an event after 3mo, so we can retain the URI, status code, duration etc. without the disk usage.

Managing retention policies with signals works well for us (notwithstanding this request), but signals match events, so there would need to be some sort of syntax for evaluating property names and values in retention policies:

```sql
@PropertyName IN [ 'RequestBody', 'ResponseBody' ]
```

or

```sql
Length(@PropertyValue) > 8192
```

Note this is in no way necessary or urgent. For now we're emulating this by having a retention policy to delete large events: `Length(@Document) > 65536`.

**Comment by nblumhardt** [comment]
Thanks for the note, Todd - we'll give this one some thought 👍 

Another approach you might use is to log the request bodies using a second correlated event (same `RequestId`) that carries the body only, and set the shorter retention policy for these.

Hope this helps,
Nick

**Comment by nblumhardt** [comment]
Thanks again for raising this. We've decided not to attempt this in the immediate future, though it's still interesting for us to keep in mind. Thanks again!
