### ISSUE TITLE
Remove parentheses - ( and ) - from the URL

### ISSUE THREAD

**Issue by xwipeoutx** [datalust/seq-tickets#1752]
I was making an Azure Dashboard with some links to useful signal combinations, and the URL I copied for it was this:

```
https://seq.synth.earth/#/events?signal=(signal-m33301~signal-m33302),signal-167
```

Unfortunately, the parantheses messed up markdown - I could escape it easily enough with `%28` and `%29` manually, but would be nice to have it easily copy/pastable to markdown.

**Comment by xwipeoutx** [comment]
Cheers - just realised I missed some context - the tile I'm using in Azure Dashboards is just MarkDown, so issue is probably broader for that use case.

**Comment by nblumhardt** [comment]
Thanks for raising this. We've decided it's not something we're likely to address in the near future, so we'll close this for now, but thanks again!
