### ISSUE TITLE
Password Requirements 2023.1

### ISSUE THREAD

**Issue by CodeMan99** [datalust/seq-tickets#1758]
Using the datalust/seq docker image, with a volume for `/data`.

While upgrading I found that the password requirements changed. Namely that the UI forces a password minimum length of 8. This cause a problem for me since my password was only 4 characters long.

### Previous Version

```
$ docker run --rm 94535a0516c9 version
2022.1.7929
```

### New Version

```
$ docker run --rm datalust/seq version
2023.1.8829
```

### Resolution

First I had to stop the server, then reset the password like this:

```
$ docker run --rm -i -v seq-dev-volume:/data datalust/seq auth reset --username admin --password-stdin <<< "newpassword"
```

Then, restart the server and login again with the forced reset (UI).

### Request

Please document this breaking change here: https://docs.datalust.co/docs/whats-new

**Comment by nblumhardt** [comment]
Thanks for the heads-up; I suspect there's actually a bug, here, Seq shouldn't apply minimum requirements when upgrading password hash strength, we'll take a look and either make a note or publish a patch 👍

**Comment by nblumhardt** [comment]
New patch being published now.
