### ISSUE TITLE
Provide a mechanism to limit Seq memory usage on Windows

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1762]
Seq will attempt to use as much memory and CPU as possible to maximize the performance of ingestion, indexing, and queries.

We currently recommend dedicated hosts for production use (either through containers, VMs, or physical infrastructure), but in cases where it's desirable or convenient to run Seq alongside other applications, a mechanism to limit/control resource usage would make Seq a better citizen.

**Comment by nblumhardt** [comment]
The configuration point for this will be:

```
seq config set -k process.workingSetLimitBytes -v 1000000000
seq service restart
```

**Comment by nblumhardt** [comment]
Note that for existing installs this will likely require either reconfiguring the default service account, or running as `LocalSystem`. More details on that to follow.

**Comment by nblumhardt** [comment]
To apply this to an existing install that's running as `LocalSystem`, simply upgrade and set the `process.workingSetLimitBytes` configuration field mentioned above.

If your install is running as `SeqDefaultInstance`, first note the install location and listen URIs:

```
seq service list
seq config get -k api.listenUris
```

Then stop and uninstall the service:

```
seq service stop
seq service uninstall
```

Next, either:

 * Update Seq to the latest version, or
 * If you're already running the latest version, run Seq Service Administration from the Start menu.

Seq Service Administration (the post-install setup wizard) will configure service account permissions to allow memory limiting.

Make sure to use the same storage path and listen URIs as observed in the first step.

Finally, you can set the `process.workingSetLimitBytes` setting as mentioned up above.

**Comment by korggy** [comment]
Is there an environment variable I can use to manage this setting for container-based instances?

**Comment by liammclennan** [comment]
@korggy `SEQ_PROCESS_WORKINGSETLIMITBYTES`
