### ISSUE TITLE
Applying `process.workingSetLimitBytes` breaks plug-in app startup

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1766]
#1762 introduced `process.workingSetLimitBytes` as a way to better share host resources on machines where Seq is not the only important application process.

Unfortunately this causes a regression: once memory hits the working set limit, plug-in apps are unable to be launched, and exceptions are recorded in the internal diagnostic log, resembling:

> System.ComponentModel.Win32Exception (1450): An error occurred trying to start process 'C:\\Windows\\TEMP\\Seq\\Client\\12345678901234567890\\seqcli.exe'
 with working directory 'C:\\ProgramData\\Seq\\Packages\\nugetfeed-1\\Seq.App.EmailPlus\\4.0.0-dev-00218\\lib\\net6.0'. Insufficient system resources exist to complete the requested service.

**Comment by TTT178** [comment]
We are currently facing the same issue. `process.workingSetLimitBytes` leads to us not being able to launch any plug-in apps. Restarting seq and trying to launch the apps, while the RAM-limit hasn't been reached doesn't work either.

**Comment by nblumhardt** [comment]
Thanks for letting us know, @TTT178 👍 

We've had some trouble reproducing this, but think we have a handle on the likely cause. If anyone's able to try build 8902 from `https://datalust.co/download/begin?version=2023.1.8902` and confirm whether this addresses it for you, it would be a great help towards closing this one.

**Comment by TTT178** [comment]
The build has fixed the issue for us for now! Thanks for the quick fix!

**Comment by nblumhardt** [comment]
Excellent, thanks!
