### ISSUE TITLE
Seq UI becomes unresponsive when server CPU utilization is high

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1767]
We've received a number of reports that the Seq UI/API is sluggish while other activity consumes high levels of CPU, after upgrading to 2023.1.

While a handful of scheduling and memory allocation issues have been fixed in 2023.1.8899 which may alleviate some high-CPU problems, we believe that concurrent query load is the major remaining cause.

The team is currently working on a patch to make query execution less aggressive/yield more time to incoming UI/API and ingestion requests, which we'll release as soon as we're able to verify its effectiveness.

If you believe your instance may be impacted, please let us know via `support@`, and follow this ticket for updates. Thanks!

**Comment by Sebbl22** [comment]
I believe we are affected, since we had high CPU loads since updating. Seq UI would not respond when that happens

**Comment by TTT178** [comment]
We are also affected by this issue. We had limited our RAM-usage via 'workingSetLimitBytes' already but now our CPU tends to spike from time to time. This leads to the machine barely being able to shut down the seq-service and the UI not responding anymore

**Comment by burnbay** [comment]
Hi!

Looks like we’re affected. The service runs fine for a moment, but eventually cosumes 99% CPU

**Comment by nblumhardt** [comment]
Thanks everyone for chiming in! 👍 Sorry about the disruption; we set out to get better utilization but might have been just a _bit_ too successful.

If anyone's able to send diagnostics to support@datalust.co we'd benefit from some data to work with. We're confident we'll be able to iron this out fairly quickly, but we're keen to do so with minimal impact on overall perf, so we're treading carefully.

**Comment by burnbay** [comment]
Unfortunately I'm not allowed to share any data, but I do see an interesting pattern (maybe you already know):
1. If I use "Tail" on events without any signal selected, the CPU runs around 2-4%
2. If I use "Tail" on events **with** a signal selected, the CPU goes to 98-100%

**Comment by nblumhardt** [comment]
Definitely interesting! Thanks @burnbay 👍

**Comment by nblumhardt** [comment]
Hi again, I hope you've all had a great week. It's Friday afternoon here, so thought I'd post a quick update on where we are with this.

We've been doing some work on how queries are scheduled, and have a patch build in testing. **CPU usage may still be high** - the problem we're addressing is poor responsiveness, not high CPU usage itself. When Seq is working well, it will still aim to saturate the majority of CPUs with work if possible, in order to serve queries faster.

The current build of the patch is not listed on `/downloads` or tagged `:latest`, but it is available if anyone has an opportunity to try it out over the next couple of days. (We'd love to hear any feedback from you if you do! 🙏)

You can get it by:

 * pulling `datalust/seq:2023.1.8926` from Docker Hub, or
 * downloading the MSI at `https://datalust.co/download/begin?version=2023.1.8926`.

Thanks again for your help and patience while we shake out the last few issues in the new architecture. I'll drop back in here early next week with another update. 👋

**Comment by TTT178** [comment]
Hey!
I've installed the update and it ran fine for around 2 hours. Now it has returned to around 95% to 100% CPU load. Unfortunately I am unable to control or see, what the other users are currently doing.

While it was running fine, CPU load was at around 40% (still almost double from before the update)

**Comment by liammclennan** [comment]
Hi @TTT178, 

As Nick noted above Seq is designed to answer queries as fast as possible by fully utilizing available resources. Any large query will reliably cause 95-100% CPU load. While they are running you will be able to see these queries listed on the _Settings > Diagnostics_ page.

**Comment by liammclennan** [comment]
@burnbay one reason why 'tail' + signal causes work is because Seq searches all the way back through time to find a page of results for the signal. 

One practical way to speed it up, if you are only interested in recent events, is to set a value in the 'FIRST' datepicker (say 10 minutes ago). That way Seq will only search back to that timestamp, instead of search all the way back to the start of the log.

**Comment by nblumhardt** [comment]
We've found some improvements still on the table for tailing, so the next patch should reduce the resource requirements for Tail substantially by default.

**Comment by nblumhardt** [comment]
👋 Hi again. We're publishing a new patch, `2023.1.8948`, which we believe will address the responsiveness issues being reported here.

The new build uses thread prioritization to keep CPU utilization high, while freeing up more capacity for the API, and therefore keeping the UI responsive under load.

This build also includes significant improvements to the "tail" function -

 * the UI now limits requests to a narrower time range, does not make requests when the Seq browser tab is hidden/off-screen, and avoids an unnecessary request when cancelling tailing,
 * the server limits "tail" requests to a single concurrent thread once the initial event set has been loaded, and
 * some UI glitchiness has been fixed (#1770 and other small improvements).

I'll leave this ticket open until we've received further feedback from everyone.

**If you update to 2023.1.8948 and still observe responsiveness issues,** please feel free to comment here, but we'd also appreciate it if you can contact us via `support@datalust.co` so that we can properly investigate your case and ensure you're up and running smoothly as soon as possible.

The new version is at https://datalust.co/download and tagged `:latest` on Docker Hub. Thanks!

**Comment by nblumhardt** [comment]
Progress update! We were still unhappy with ingestion performance in some areas with 2023.1.8948, so we made some deeper changes. The new version 2023.1.8991 cuts CPU requirements for running apps by several times, and we expect it will perform at least as well as 2022.1 for all ingestion-related tasks.

Closing this now, but very eager to hear how you go with 2023.1.8991, so please comment here if you see an improvement there, or notice any further issues.

Thanks all for your patience and help with this one.

**Comment by SeriousM** [comment]
I can confirm that the upgrade from version 2023.1.8899 (worst performance) to version 2023.1.8948 (ok again performance) helped a lot.
Today we updated to version 2023.1.8991 and I hope the performance stays good.
Thanks for the effort!

**Comment by burnbay** [comment]
I can also confirm that 2023.1.8991 works great. CPU usage is low overall and the UI is responsive. 

Thanks a lot for the quick fix!

**Comment by TTT178** [comment]
2023.1.8991 has worked great so far.
Thanks for the fix!
