### ISSUE TITLE
Stop search after requestId was found

### ISSUE THREAD

**Issue by SeriousM** [datalust/seq-tickets#1774]
We use Seq for all dotnet loggings. All webservice requests or azure function calls have an identifier that creates a correlation to other log entries.

Because the request or function invocation has a time window where the logs with this correlation can appear, we could limit this search timeframe to save some search resources and makes the everyday search easier.

![image](https://user-images.githubusercontent.com/462013/221522218-65635d27-f9a9-4632-8a0e-a95a2d751e19.png)

Could we get a feature where I can define a set of properties that is searched for (eg. `RequestId` from asp.net, `AzureFunctions_InvocationId` from azure functions) and a time-offset (eg. 1h) to limit/stop the search?

**Comment by nblumhardt** [comment]
Thanks for the suggestion! Makes sense 👍 

Looking at this from another angle, we have some improvements to Seq's date picker planned for this year. If the datepicker made it easy to switch between "Last 15 minutes", "Last hour", "Last day", "Last week" etc., would this problem be (partially?) alleviated for you?

Thanks again!

**Comment by SeriousM** [comment]
> "Last 15 minutes", "Last hour", "Last day", "Last week" etc.

that sounds like grafanas datepicker? 
![image](https://user-images.githubusercontent.com/462013/221534858-159be204-9b80-4266-b6ca-1978e283a60d.png)

this would indeed help, maybe this can be set as systemwide default setting for every user.
and if the end was reached, offer a "search the next 6/12/24h in the past".

**Comment by nblumhardt** [comment]
Thanks for the reply! Yes, along those lines - it's become a fairly common pattern for datepickers since the original Seq one was written 👍

**Comment by andymac4182** [comment]
That would be great @nblumhardt !! ;)

**Comment by nblumhardt** [comment]
2023.4 defaults the limit to the last day:

![image](https://github.com/datalust/seq-tickets/assets/342712/ae3103d0-7ef4-47f2-9845-fe1d2a0715a0)

This works in conjunction with the new date pickers on Events/Dashboards.

Preview is out now, and the final build shouldn't be more than a couple of weeks away. We'd love to hear how it goes!
