### ISSUE TITLE
Configure License on deployment via Helm Chart

### ISSUE THREAD

**Issue by iainsproat** [datalust/seq-tickets#1777]
## Problem statement

I would like to deploy seq server to Kubernetes in a fully-declarative manner, configuring all parameters via code.
I believe I am currently unable to configure the license in a declarative manner, and instead have to navigate the web UI to input the license into seq server.

## Potential Solution

1. I add the license as a Kubernetes secret
1. I configure the seq Helm Chart, providing details of the secret name and key at which the license can be found.
1. The seq Helm Chart does the following:
    1. adds the secret name to the `secrets` parameter of the Service Account, allowing the seq deployment access to that secret.
    1. mounts the secret to the seq container [as a volume](https://stackoverflow.com/questions/51365355/kubernetes-secrets-volumes-vs-environment-variables).
    1. seq reads the secret from the volume path

**Comment by nblumhardt** [comment]
Hi @iainsproat! Thanks for including all the details 👍 

The `license apply` command supported by the `datalust/seqcli` container will do rougly what you're after:

```
seqcli license apply [<args>]

Apply a license to the Seq server

Example:
  seqcli license apply --certificate="license.txt"

Arguments:
  -c, --certificate=VALUE    Certificate file; the file must be UTF-8 text
      --certificate-stdin    Read the license certificate from `STDIN`
      --automatically-refresh
                             If the license is for a subscription,
                               periodically check `datalust.co` and
                               automatically refresh the certificate when the
                               subscription is changed or renewed
  -s, --server=VALUE         The URL of the Seq server; by default the `
                               connection.serverUrl` config value will be used
  -a, --apikey=VALUE         The API key to use when connecting to the server;
                               by default the `connection.apiKey` config
                               value will be used
      --profile=VALUE        A connection profile to use; by default the `
                               connection.serverUrl` and `connection.apiKey`
                               config values will be used
      --verbose              Print verbose output to `STDERR`
```

Piping the certificate from STDIN is probably the easiest way to go.

It's possible to run the command in an [init script](https://docs.datalust.co/docs/init-scripts), in which case `seqcli` is on the path and won't need to be run via its container distribution.

Let me know if this helps!
Nick

**Comment by nblumhardt** [comment]
Closing under the assumption that this is working for you, but please let us know if not :-)
