### ISSUE TITLE
Data > Storage page should show last 30 days by default instead of all-time

### ISSUE THREAD

**Issue by CrossBound** [datalust/seq-tickets#1781]
### The Problem

Currently when you open the data > storage page in the Seq app, it will default to showing "all time" data. If you have a busy instance and years of data, this takes a long time to load and display. This is frustrating to wait for when all you want is possibly to see a more recent set of data. 

### Proposed Solution

By default it would be nice if it would load a much more manageable data set, like last 30 days, or even last 7 days and let the customer intentionally choose the "all-time" if they really want to see that far back.

**Comment by nblumhardt** [comment]
Agreed, thanks :+1:
