### ISSUE TITLE
Signal expression textbox clear button does not work in Safari

### ISSUE THREAD

**Issue by liammclennan** [datalust/seq-tickets#1788]
**To Reproduce**
1. Type an expression in the filter bar
2. Add the expression to a signal
3. Click the clear button in the signal expression textbox

**Expected behavior**
The textbox is cleared

**Screenshots**
![image](https://user-images.githubusercontent.com/271514/223618478-1eb798f0-22cd-4299-8912-66db2aba83c8.png)

**Environment (please complete the following information):**
 - Safari
 - Seq 2023.1

**Comment by nblumhardt** [comment]
We had some trouble reproducing this just now, we'll push it to 2023.3 and investigate once the current release is out.
