### ISSUE TITLE
Can't test an alert query using Boolean aggregations (t.toFixed is not a function)

### ISSUE THREAD

**Issue by todthomson** [datalust/seq-tickets#1799]
**Describe the bug**

Attempting to add an Alert, using a query that works correctly in the default Seq query window, triggers the following browser JavaScript issue (shown in the Seq UI Alerts page):
```
Couldn't test the alert query
t.toFixed is not a function
```

**To Reproduce**

We have the query to reproduce here internally here at Datalust / Seq.

**Expected behavior**

We expect the "test" function to successfully test the query the same as running it in the default query window.

**Screenshots**

We have screenshots internally here at Datalust / Seq.

**Environment (please complete the following information):**
 - **Browser:** Microsoft Edge Version 111.0.1661.43 (Official build) (64-bit)
 - **Seq Version:** 2022.1.7929

**Additional context**

This looks to be a JavaScript bug in the Seq UI/UX.

**Comment by nblumhardt** [comment]
The issue is caused by the alert query using a non-numeric aggregation, e.g. `any(X)` rather than a numeric aggregation like `count()`, `min()`, etc.

**Comment by todthomson** [comment]
Updated to include the browser and Seq version.

**Comment by todthomson** [comment]
Simplest query I could write to reproduce this bug:
```
select Substring(@Message, 0, 10) as MessageShort from stream
where @Message like '%a%'
limit 10
