### ISSUE TITLE
Seq UI default filter-box silently goes into overtype mode when INSERT key is pressed, which is confusing

### ISSUE THREAD

**Issue by todthomson** [datalust/seq-tickets#1803]
**Describe the bug**

Seq UI default filter-box silently goes into overtype mode when INSERT key is pressed, which is confusing.

**To Reproduce**

https://user-images.githubusercontent.com/515811/227435178-b3f60a88-5a77-4a8b-a0d7-b3f248b21083.mp4

And I clicked the INSERT key before (over)typing `abc`.

**Expected behavior**

The UI/UX should show the user clearly if/when they are in overtype mode.

**Environment**
 - _Browser:_ Chrome Version 111.0.5563.111 (Official Build) (64-bit)
 - _Seq Version:_ 2023.1.9133

**Comment by todthomson** [comment]
This is probably the simplest fix: https://codemirror.net/5/doc/manual.html#toggleOverwrite

**Comment by nblumhardt** [comment]
Fixed in 2023.4; the search box no longer toggles overwrite on <INS>. Thanks!
