### ISSUE TITLE
Error exporting query results to CSV

### ISSUE THREAD

**Issue by liammclennan** [datalust/seq-tickets#1810]
**Describe the bug**

The combination of: a query ('select ...'), export to CSV and load on the server causes exports to fail. Appears in the diagnostics log as `"@x":"System.ObjectDisposedException: IFeatureCollection has been disposed.\r\nObject name: 'Collection'`.

No workaround, other than smaller queries and less server load.

**Comment by karlfcnsw** [comment]
I am seeing the same thing on our server, attempt to export to CSV and receive the same error.

`{"@t":"2023-04-10T23:29:54.0262463Z","@mt":"Uncaught exception from worker {WorkDescription} ({WorkId})","@l":"Error","@x":"System.ObjectDisposedException: IFeatureCollection has been disposed.\r\nObject name: 'Collection'.\r\n   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed()\r\n   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Items()\r\n   at Seq.Server.Web.SeqAspNetCoreController.get_CurrentPrincipal()\r\n   at Seq.Server.Web.Api.DataController.<>c__DisplayClass10_0.<Query>g__Calculate|0(IComponentContext ctx, CancellationToken cancel)\r\n   at Seq.Server.Web.Api.DeferredRequestsController.<>c__DisplayClass5_0.<GetDeferred>b__0(CancellationToken cancel)\r\n   at Seq.Engine.Workers.WorkerPool.<>c__DisplayClass6_0.<Run>b__0(CancellationToken ct)\r\n   at Seq.Engine.Workers.WorkerPool.<>c__DisplayClass7_0`1.<Run>g__DoWork|0()","WorkDescription":"Compute deferred result","WorkId":"d5187888-81a1-4627-9f3b-0144cb7b125d","SourceContext":"Seq.Engine.Workers.WorkerPool","Princ`

**Comment by liammclennan** [comment]
@karlfcnsw that's the one. 

A fix has been merged and will be in the next Seq release.
