### ISSUE TITLE
Seq should include `<meta name="robots" content="noindex, nofollow" />` in its `index.html`

### ISSUE THREAD

**Issue by todthomson** [datalust/seq-tickets#1811]
**Describe the bug**
We should default Seq to telling search engines (e.g. Google) not to index people's public Seq instances.

```
<meta name="robots" content="noindex, nofollow" />
```

**Comment by nblumhardt** [comment]
This shipped in 2021.3: https://github.com/datalust/seq-tickets/issues/1342
