### ISSUE TITLE
Docker Tag Seq:Latest is older than Seq:2023.1

### ISSUE THREAD

**Issue by chkoella** [datalust/seq-tickets#1816]
**Describe the bug**
When I pull Seq:latest I receive the image for 2023.1.9133. On Dockerhub I see last pushed 23 days ago on the latest tag.
My Seq Installation tells me, there's a new Version 2023.1.9162. It seems that the Tag 2023 and 2023.1 point to this release because Last pushed 16 days ago.

**To Reproduce**
Go to https://hub.docker.com/r/datalust/seq/tags

**Expected behavior**
I expect the latest tag to return the latest image.

**Screenshots**
![image](https://user-images.githubusercontent.com/1381228/231458714-57ac1e18-9c90-4fa5-a63e-fa36240935ee.png)

**Environment (please complete the following information):**
 - OS: any
 - Browser any
 - Seq Version 2023.1.9133
 - Using Docker? Yes 

**Additional context**

**Comment by KodrAus** [comment]
Hi @chkoella :wave:

Thanks for pointing this out! Sometimes we hold off on promoting a particular release to the `latest` tag immediately, but we should get them back in line now.

**Comment by KodrAus** [comment]
<img width="934" alt="Screenshot 2023-04-13 084832" src="https://user-images.githubusercontent.com/6721458/231602907-5e0c025d-96fc-40b5-b893-fc8e9cc44e2f.png">

Done! Thanks again @chkoella
