### ISSUE TITLE
Read-only users cannot change preferences or their password

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1817]
This seems to still occur with `Seq 2023.1.9162`

![image](https://user-images.githubusercontent.com/1201644/231408410-d39d4389-7bc4-4a23-8a89-d911fd3db40a.png)

This is a login with the `User (read-only)` role

_Originally posted by @CumpsD in https://github.com/datalust/seq-tickets/issues/739#issuecomment-1504918271_

**Comment by nblumhardt** [comment]
We originally decided "read-only" would mean _strictly_ read-only, i.e., disallow access to any write endpoints. This isn't a great choice for how read-only accounts are used in the majority of cases. It's unexpected by customers, so I'll mark this as a bug.

This ticket proposes to allow read-only accounts to update their own user preferences and password (if username/password authentication is in use).

I've also marked this as a breaking change, because there's a faint possibility that customers today are relying on the current behavior for some unforeseen use cases.

**Comment by nblumhardt** [comment]
![image](https://github.com/datalust/seq-tickets/assets/342712/06c4feb4-66c1-43a6-be87-cbf08dd24385)

As of 2023.2, read-only users will be able to change their own:

 * Account trivia (display name and email)
 * Password
 * Theme
 * Display preferences
 * Query timeout

**Comment by liammclennan** [comment]
@CumpsD That is correct. 2023.2 has not been released.

**Comment by CumpsD** [comment]
> @CumpsD That is correct. 2023.2 has not been released.

When is the release planned?

**Comment by nblumhardt** [comment]
Aiming for next Tuesday (6th June), but still a few loose ends to tie up so may need a little extra time depending on how it all comes together :-)

**Comment by CumpsD** [comment]
Thanks!
