### ISSUE TITLE
Data --> Ingestion page very slow with many API keys

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#1877]
When having many API keys, the Data --> Ingestion view becomes unresponsive.

1. Create 700 API keys
2. Go to Data --> Ingestion in Firefox
3. Firefox uses a unusual high amount of CPU and the page becomes unresponsive. Sometimes the page would not even open.

**Expected behavior**
The page should be responsive with any amount of API keys. 

**Screenshots**
Resizing the page in Firefox has a noticeable delay. Firefox is already resized, but the content is not:
![grafik](https://github.com/datalust/seq-tickets/assets/10319545/bdd7be49-7180-44b8-a990-cba81d9fcb96)

![grafik](https://github.com/datalust/seq-tickets/assets/10319545/6905a780-db4a-4498-b6da-9be3fd3b19e2)

**Environment (please complete the following information):**
 - OS: Windows 10 22H2 64-bit
 - Browser: Firefox 114.0.2 64-bit, Edge 114.0.1823.51 64-bit, Chrome not tested
 - Seq Version: Seq 2023.1.8991
 - Using Docker? No

**Additional context**
I am guessing, that the issue is related to the large amount of diagrams (1 per API key) on the Data --> Ingestion page, because they load in very slow.

**Comment by KodrAus** [comment]
Thanks for the report @Sebbl22. This is definitely something we should fix :+1:

**Comment by nblumhardt** [comment]
The upcoming 2023.3 build improves this significantly, by batching network requests, dropping the resolution of per-API key ingestion sparklines, and not showing sparklines when more than 200 keys are present (filtering the table below 200 entries will cause sparklines to show).

In a future release we might improve on this further by paginating the list.

The new build will be available next week, it'll be good to hear how it goes.
