### ISSUE TITLE
Add "Add API Key" button to the top of the page

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#1899]
Consider having a large amount of Api keys (100+) under Settings --> API KEYS
Creating a new Api key requires scrolling down to the bottom of the page and clicking the "add api key" button.

I find myself sometimes wondering, where the button to create a new key is located, since I am not doing this very often.

I would suggest, that an additional button with the exact same functionality is added at the top of the API KEY page.

**Comment by KodrAus** [comment]
Thanks for the suggestion @Sebbl22 :+1: That's pretty standard practice to duplicate controls on tabular data at the top and bottom of the tables.

**Comment by liammclennan** [comment]
Hi @Sebbl22 

Thank you for the suggestion. This change has been merged and will be in the next release.
