### ISSUE TITLE
Sorting by permissions on API Key page does not work

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#1900]
**Describe the bug**
The permission column on the api key settings page is a sortable column. However, sorting the column does not result in a sorted list.

**To Reproduce**
1. Go to Settings --> API KEYS
2. Click on the "PERMISSION" column, so that it gets sorted.
3. The order of the displayed api keys is changed, but it is not sorted by permission.
![grafik](https://github.com/datalust/seq-tickets/assets/10319545/7f0dc641-7f77-4e27-b12d-7ac812292698)
The graphic shows the "PERMISSIONS" column with the arrow as sorting indicator. However, the table of api keys is not sorted.

**Expected behavior**
I would expect the table of api keys to be sorted alphabetically by permission
OR
remove the sorting functionality for permissions completely, since sorting by permissions does not seem to be very useful. The usual scenario would be to filter the list of api keys by permission, which can be done via the search bar.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Seq 2023.1.8991
 - Using Docker?  No

**Comment by KodrAus** [comment]
Thanks for the report @Sebbl22, that does look rather strange 🤔
