### ISSUE TITLE
Few UI improvments

### ISSUE THREAD

**Issue by DanAvni** [datalust/seq-tickets#1917]
Sometimes I want to change multiple things in a query: From Date, To Date, Take values from an event into the query. Every change I make refreshes the UI so here are a few improvement suggestions:
1. Add a pause button to disable the auto-refresh after filter or dates change
2. When clicking the checkmark next to a property of an event I can run the Find command and that sets the query to "<PropertyName>=<Value>", If I want to add another property to the query I have to copy the existing query first and then do Find again and then return the query I copied. Please add the ability to add multiple properties to the query (one at a time but do not clear the existing query)

**Comment by liammclennan** [comment]
Hi @DanAvni 

Thank you for the suggestions. 

For 1. how is this different to disabling the tail?

For 2. would you imagine the two clauses would be joined by a logical AND? 

Just copying the name of the property or its value might also be useful.

**Comment by nblumhardt** [comment]
Thanks for raising these. We'll keep them on our radar but we're not actively planning work in this area in the immediate future so will close for now.
