### ISSUE TITLE
Cursor randomly moves to the end of the text in the search box

### ISSUE THREAD

**Issue by honestegg** [datalust/seq-tickets#1924]
**Describe the bug**
Cursor randomly moves to the end of the text in the search box

**To Reproduce**
1. Add query to search box
2. Move cursor somewhere in the middle of the text
3. Type until the cursor automatically moves to the end of the text

**Expected behavior**
Cursor doesn't move randomly to the end of the line

**Screenshots**
https://github.com/datalust/seq-tickets/assets/1371145/decb9239-b2fe-4214-ab36-c11395f3a626

**Environment:**
 - OS: Windows 11
 - Browser Chrome 115.0.5790.171
 - Seq Version 2023.3.9691
 - Using Docker? No

**Comment by KodrAus** [comment]
Thanks for the report @honestegg! This is actually fixed in the upcoming 2023.4 preview, which also fixes an issue of ending up in overwrite mode by hitting the `insert` key.

**Comment by nblumhardt** [comment]
The preview release including this change has now been published: https://twitter.com/datalust_seq/status/1694842321299513796
