### ISSUE TITLE
Event "Search FROM timestamp" and "Search TO timestamp" don't seem to work

### ISSUE THREAD

**Issue by honestegg** [datalust/seq-tickets#1930]
**Describe the bug**
The Event "Search FROM timestamp" and "Search TO timestamp" don't seem to work. Selecting those from the dropdown doesn't seem to do anything and pressing the "Go" button just seems to "spin" on searching.

**To Reproduce**
1. Expand an event log
2. Click on the Event dropdown
3. Select  "Search FROM timestamp" or  "Search TO timestamp"
4. Nothing happens
5. Click the "Go" button
6. Searching message just "spins"

**Expected behavior**
Update the date selector to Custom and set the Start or End datetime to the datetime of the selected log entry/event

**Environment:**
 - OS: Windows 11
 - Browser Chrome 116.0.5845.97
 - Seq Version 2023.4.9959-pre
 - Using Docker? Yes

**Comment by nblumhardt** [comment]
Thanks for reporting this! It looks like a regression in the new preview; we'll patch it up in the next preview build, which should be out in day or so.

**Comment by honestegg** [comment]
Great, thanks!
