### ISSUE TITLE
New update won't remember time scale settings for dashboards

### ISSUE THREAD

**Issue by mhegreberg** [datalust/seq-tickets#1945]
**Describe the bug**
Dashboard will reset timescale to last day/15m each time I login to use the app. before I was able to set it to 30d/1day and it would stay that way. I have to change it every time now.

**To Reproduce**
1. change the timescale settings in a dashboard
2. log out
3. log back in
4. the timescale settings are not preserved

**Expected behavior**
I'd like them to keep the previous settings, like the prior version.

**Screenshots**
![image](https://github.com/datalust/seq-tickets/assets/11844475/6700e723-8177-4c25-a6c4-064f59d2b9e2)
![image](https://github.com/datalust/seq-tickets/assets/11844475/e98222b5-fcc0-492e-a865-8792cd815e4e)

**Environment (please complete the following information):**
 - running on kubernetes, installed with helm chart. 
 - 2023.4.10067

**Comment by liammclennan** [comment]
Hi @mhegreberg 

Thank you for the report. This is a change we made intentionally, to help avoid accidentally running big queries and to make the dashboards align with the URL - however we can see how it might be undesirable. We will re-examine this one and update this ticket. 

In the meantime, you might find it useful to bookmark your dashboard and return that way. The url has `range` and `group` parameters which can have any time values, not just those that are selectable in the UI.

**Comment by mhegreberg** [comment]
I'll try bookmarks in the mean time.

I can see how for larger datasets, starting at 30 days or a year could cause performance issues. perhaps each dashboard can have a default timescale?

thanks for the swift reply!

**Comment by mhegreberg** [comment]
I've been messing with the bookmark option, and I think it works for my use case just fine. it's actually more convenient, because I can jump straight to a dashboard if I'm checking something.

thanks for all your help.

**Comment by nblumhardt** [comment]
Just a quick note, we'll have a patch out with this fix shortly.
