### ISSUE TITLE
Seq runs unstably with process.workingSetLimitBytes above host memory on Windows

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#1953]
If you specify a `process.workingSetLimitBytes` value higher than the total host memory on Windows Seq will happily start, but will destabilize if it attempts to use that memory.

As of 2023.4, there isn't really a need to set a working set limit anymore, because Seq doesn't hold on to mapped files longer than it takes to read them, so the steady-state working set should be low.

**Comment by nblumhardt** [comment]
Because this setting is for an advanced/tuning use case, I think we should leave this as "by design". Setting a too-low value here will also cause Seq to fail or run unstably.
