### ISSUE TITLE
Additional range selector options

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1954]
We've had a couple of requests for additional options in the new date range selector; we'll collect them in this ticket.

 * `From now`
 * `Last 2h`

**Comment by liammclennan** [comment]
What if there was a system setting that was a comma separated list of the durations in the range selector?

**Comment by aarondandy** [comment]
I use "Now" all the time. I noticed the change in my local docker instance and am waiting on this before updating our real Seq instance. It's really important to me to set up a "from now" query as I do a deployment. It helps me see very quickly when the shit has hit the fan and what my users were eating.

![image](https://github.com/datalust/seq-tickets/assets/404933/1c617f70-2026-4b8b-a6d6-1ea240707a7a)
I miss you little buddy 😢

**Comment by nblumhardt** [comment]
![270857793-8f3e37ef-a67c-43af-99f2-cd269fbe8e7e](https://github.com/datalust/seq-tickets/assets/342712/12cdaebc-9662-4b0d-944e-617f689f1944)

"From now" making a comeback..

**Comment by nblumhardt** [comment]
Custom ranges:

![image](https://github.com/datalust/seq-tickets/assets/342712/b0bb38d1-90e5-4897-9d10-ff56caa4172a)

![image](https://github.com/datalust/seq-tickets/assets/342712/787df025-1c5f-409a-a5f6-12fad4f2e8a0)

![image](https://github.com/datalust/seq-tickets/assets/342712/e2708712-e96e-4f9e-9f6e-0a48d6c22008)
