### ISSUE TITLE
Add support for editing an API key attached properties

### ISSUE THREAD

**Issue by DanAvni** [datalust/seq-tickets#1955]
When cloning an API key I need to change one of the attached properties. Please add support for editing it

**Comment by KodrAus** [comment]
Thanks for the suggestion @DanAvni :+1: It would definitely be handy to be able to change the value of an attached property without having to retype the whole lot

**Comment by nblumhardt** [comment]
We're keen to enable this but expect it would be included in a more general update to the API keys screens. Still on our radar. Thanks again for the suggestion!
