### ISSUE TITLE
Apps screen may be slow when there are many app instances active

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#1967]
On systems with 200+ app instances, the _Settings > Apps_ screen may load very slowly or not at all. The problem seems to be at the `/api/appinstances` endpoint.

**Comment by nblumhardt** [comment]
We haven't yet managed to reproduce this; I'll pull it from the `-patch5` milestone while we gather some more information, and schedule a new patch when possible.

**Comment by nblumhardt** [comment]
Closing until we have a reproduction.
