### ISSUE TITLE
Improve the contrast on the search textbox selection in dark mode

### ISSUE THREAD

**Issue by timgaunt** [datalust/seq-tickets#1973]
Running `2023.4.10219` we're finding the contrast on the selected (`1234` in the below example) and unselected text in the search box a little close. Could you make it stand out a touch more please :) 

<img width="231" alt="image" src="https://github.com/datalust/seq-tickets/assets/254564/5302525a-5276-4d0d-853f-0834d831b7d8">

**Comment by nblumhardt** [comment]
Thanks for the report, Tim. I think this is a styling bug, we'll take a closer look.

**Comment by nblumhardt** [comment]
We have a fix coming for this, targeting 2024.1; in the meantime you can work around it by adding the following to _Settings > Instance_:

```css
.cm-line::selection {
  background: #ccc !important;
}
```

Let me know if this doesn't do the trick for you. Thanks again for letting us know about this, Tim :+1:
