### ISSUE TITLE
Fewer clicks to access custom date range selection

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1975]
From a customer:

> I thought it worth feeding back about the date picker which has added an extra click which is a bit of a pain. Most of the time the team use Seq to triage an issue that’s happened in the past -and by the time it’s reported it’s rarely in the past hour or two. 
 
> Would it be possible to add a calendar button next to the down arrow to save it being “Down Arrow>Custom>Date selection”?
 
<img width="264" alt="image001" src="https://github.com/datalust/seq-tickets/assets/342712/1e4ca6a0-fee7-40e0-882e-1e54b826386a">

**Comment by timgaunt** [comment]
We've had a little more time to play with this and we've found that it's pretty impeding on quick triaging the logs -especially when you're narrowing down date windows you have to keep clicking `Custom...` and then modifying the dates. Having a button we can click to go straight to the date pickers would be good -or when a specific window is selected it could jump straight to the date pickers.

Happy to show the team how we're working with it.

**Comment by nblumhardt** [comment]
Thanks, @timgaunt  - I think I have a clear picture of the workflow you're talking about, we'll reconsider how we approach this and let you know what we come up with 👍

**Comment by xt0rted** [comment]
This is still a huge pain point for me and the main reason I'll push back on updating our production instances.

Having to open the dropdown, select custom, pick dates, remember to hit apply, all while hoping I don't try to select the input text and accidentally release the mouse outside of the popup (that causes it to insta-hide), for every single date change is super annoying.

Aside from the `now` option I pretty much work exclusively with custom ranges and would absolutely love the ability to keep the start/end inputs permanently visible again.

**Comment by nblumhardt** [comment]
We think we have a workable solution for this; it won't go as far as promoting the from/to boxes back to the top level, unfortunately, but in custom date selection mode, the drop-down should be able to open the custom range picker directly, without stepping through "Custom".

This will require adding a "Reset" button to the custom range dialog, alongside "Apply" and "Cancel" (exact layout/names TBC).

We'll need to spend some time with the result to make sure we're not regressing anything else unexpectedly, so I've marked this for 2024.2 rather than the next 2024.1 patch. Thanks for all the feedback!

**Comment by nblumhardt** [comment]
![312260648-6fd82739-4143-4569-bdee-886bb37fd7e9](https://github.com/datalust/seq-tickets/assets/342712/372c2c58-26d0-462c-9a8e-a4ec6eb28640)
