### ISSUE TITLE
API Key Attached Properties with Computed Values

### ISSUE THREAD

**Issue by williamb1024** [datalust/seq-tickets#1978]
I have a specific need to attach the IP address of the sender to events arriving with a specific API key. Providing a set of predefined values that could be used within attached properties, where one of the values is the HTTP request's source IP address, would allow me to resolve this issue without changing the source of the logs.

A couple of values come to mind that might be useful:

source ip address
server time

I would imagine the attached property syntax might be similar to:

SourceIp = @sourceIp
ServerArrived = @serverTime

Possibly allowing references to incoming properties may provide some benefit. For example, if the API key is configured to use the server's time rather than the client's time, an attached property might be able to reference the incoming time property and place it into a new property before it is replaced with the server's timestamp.

**Comment by nblumhardt** [comment]
Thanks, William. We've considered some features along these lines in the past, we'll revisit it and let you know what we come up with.

**Comment by nblumhardt** [comment]
Thanks again for raising this. While we agree it's a useful feature in some scenarios, we don't plan to move forward with it due to time constraints and implementation concerns. Thanks again!
