### ISSUE TITLE
"Tail" on the dashboard view resets its state every few seconds

### ISSUE THREAD

**Issue by taspeotis** [datalust/seq-tickets#1979]
**Describe the bug**

If you're on the dashboard with tail (default?) and change it in some way, say double click on a series to focus on it, a few seconds later all the series will come back when the chart is refreshed.

**To Reproduce**

View a chart with multiple series, double click on one series, wait.

**Expected behavior**

Either tail is disabled while I look at the data or it refreshes but remembers which series I have enabled/disabled.

**Screenshots**

![image](https://github.com/datalust/seq-tickets/assets/1189399/73b5fe5b-5703-4af2-a925-99ea22792162)

Wait a few seconds

![image](https://github.com/datalust/seq-tickets/assets/1189399/f3a6482c-63e6-49e5-b023-2783a164ba7e)

**Environment (please complete the following information):**

Seq 2023.4.10219

**Comment by nblumhardt** [comment]
Thanks, Todd, we'll sort this out 👍
