### ISSUE TITLE
OIDC: Send client_id or id_token_hint in logout URI

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#1982]
The [OIDC spec](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) recommends applications send the original token as `id_token_hint` to the provider's logout endpoint. Optionally, you could also/instead send the client id as `client_id`. Some providers require one of these values to log users out successfully.

Seq should send either `id_token_hint` or `client_id` during logout to support these providers.

**Comment by nblumhardt** [comment]
(Note that this is currently an issue when using Keycloak, which treats these as required, although we believe they're actually optional.)
