### ISSUE TITLE
Json columns exported as Seq.Engine.Structured.SchematicProperties when exporting to CSV

### ISSUE THREAD

**Issue by timgaunt** [datalust/seq-tickets#1983]
**Describe the bug**
When exporting to CSV from the event stream it exports json properties as `Seq.Engine.Structured.SchematicProperties` however if you do it from a table query then it will export the JSON object in CSV

**To Reproduce**
1. Export a set of events from the event stream as CSV which have JSON properties
2. See error

**Expected behavior**
The JSON object should be the CSV's cell value as it is if you do a Table export

**Screenshots**
![image](https://github.com/datalust/seq-tickets/assets/254564/b400991d-4eff-4cf6-ba8e-fc273c678018)

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Seq Version 2023.4.10219
 - Using Docker? No

**Comment by KodrAus** [comment]
Thanks for the report @timgaunt! We'll look into this.
