### ISSUE TITLE
Distributed tracing support

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1986]
Seq 2024.1 will include ingestion and visualization of hierarchical traces. This is being integrated directly into the Events screen, so that the trace associated with an event can be quickly visualized, and then the spans and other detailed information within the trace then used to further filter and navigate through span and log data:

![image](https://github.com/datalust/seq-tickets/assets/342712/abb9bdcf-c8f7-452e-a1b3-c34a2e4c86fc)

In scope for the initial implementation we have:

 * Trace ingestion via OTLP (`http/protobuf` and `grpc` protocol flavors)
 * Trace ingestion via newline-delimited JSON over HTTP (extending the CLEF schema that Seq currently accepts)
 * Visualization in the Events screen
   - Span hierarchy, timings, and other details
   - Coloring by service
 * Filtering/navigation from traces
   - Find events in a trace
   - Find events in a specific span
 * Indexing of trace ids

See also the earlier discussions in #844 and #1105.

**Comment by nblumhardt** [comment]
:wave: It's high time we sent an update! Previews of Seq 2024.1 have been quietly rolling along for a few weeks now as tracing support becomes more usable:

![image](https://github.com/datalust/seq-tickets/assets/342712/d748968e-884f-443a-abc0-cd709a271c71)

It's going well! :sunglasses: 

First, the major goal that's led to so much careful work on this is to _enhance and complement_ the rest of Seq's functionality, instead of just tacking on a "traces" screen and settling for demoware ;-). The trace viewer that's built into the Events screen helps put all diagnostic data - logs and spans - in context. You can keep a trace open while navigating around within its spans and to related events, or you can quickly show traces for a list of interesting events.

Second, trace id indexing is amazing. On a 1 TB stream our current benchmark pulls back traces by id in 5 to 6 milliseconds. This also means that log queries within a trace and its spans are similarly accelerated. Using segmented hash indexes, we've managed to keep the on-disk cost of trace indexing to around 1%.

We still have some work to do, filling in some small gaps, optimizing, and polishing up user interactions. Oh, and choosing some nicer span colors :laughing:. We'll post a detailed write-up on how to get started on our blog soon, but if you're keen to try things out as they are, you can grab the current preview build and point OTLP/gRPC data to any ingestion port, or OTLP/HTTP to `/ingest/otlp/v1/traces`. Feel free to ask for help here, or reach out (`nblumhardt@` our domain) if you'd like to join our community Slack, where we've been posting more regular updates.

**Comment by Sebazzz** [comment]
I tried this out and didn't get anything when attempting to show a trace. I figured out that Seq apparently does a query like this: 

```sql
select coalesce(@Resource.service.name, Application, 'unknown_service') as serviceName, @Message as message, @Level as level, @TraceId as traceId, @SpanId as spanId, @ParentId as parentId, TotalMilliseconds(@Elapsed) as elapsedMs, ToIsoString(@Start) as start, ToIsoString(@Timestamp) as timestamp, @Start as startTick, @Timestamp as timestampTick from stream where Has(@Start) and Has(@SpanId) and @TraceId = '7ee34c2ed89c0826c2155cab0dac985f'
```

Since my log events don't have a `@Start`, nothing was shown (and without anything to go on, the functionality looked broken).

**Comment by Sebazzz** [comment]
One addition, I recalled that I already passed `@st` and `@ps` (Span start, Parent span) to Seq via a custom Serilog IFormatter, and in the old Seq these properties (as they weren't recognized) showed up like `Properties['@st']` - the old log entries in the new Seq version don't show these properties anymore, but Seq is not able to show the tracing either (probably because it didn't migrate them to have `@st` recognized as `@Start`).

For new log events the tracing does show up.

**Comment by liammclennan** [comment]
Thanks for trying the preview @Sebazzz. 

OTEL log events won't show as traces, because they don't carry timing information (`@Start`). 

Seq considers events that have `@Start` and `@SpanId` to be spans that can be included in the trace visualization.

**Comment by nblumhardt** [comment]
This is done! We're marking the latest `:preview` (2024.1.10933-pre) as a release candidate and will have some more details on the blog and in the docs shortly.
