### ISSUE TITLE
Property value visualizers

### ISSUE THREAD

**Issue by arri-cc** [datalust/seq-tickets#199]
Quite often we use seq to troubleshoot unexpected errors encountered by consumers of our web services.  While we log the request objects to event properties `{@MyRequest}`, currently is difficult to get the object out of seq in its original form, if for instance I want replay the request in another environment.  

I understand the purpose of the structure for exposing an entire event, but it would be nice to be able to export just a single property value without the type tags and as a bonus have the option to camel case it.

**Comment by nblumhardt** [comment]
@arri-cc I like this idea but I don't think we're going to tackle it in the next release, so I'd say I'll move this to https://seq.uservoice.com ... Before I do, is this still something you'd benefit from? Have you looked at what you can get from the API here? Cheers!

**Comment by arri-cc** [comment]
@nblumhardt yes.  What if you had a set of property visualizers similar to visual studio that could display property values that supported text, XML, HTML, and json?  Then you could support stripping sew properties prior to display.  Also it'd be awesome to have a full screen mode like the script editor in octopus.

**Comment by nblumhardt** [comment]
As much as we hope this can be done in the near future, it's more likely to come in as part of a UI overhaul than be addressed as a standalone ticket. We're closing this to keep the tracker healthy, but it's not forgotten :-) - thanks!
