### ISSUE TITLE
Could not update API key A title must be supplied for the API key

### ISSUE THREAD

**Issue by bruce588** [datalust/seq-tickets#2002]
**Describe the bug**
API Key can be added, but an error message will appear when it is modified.

**To Reproduce**
1. Go to '/settings/api-keys'
2. Click 'Save Changes'
3. See error

**Expected behavior**
It should be able to be stored properly.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Seq Version [2023.4.10219]
 - Using Docker?  No

**Comment by nblumhardt** [comment]
Thanks for the heads-up, @bruce588.

This doesn't seem to repro for me (same version, using Chrome on Windows) - I can perform those steps successfully.

Wondering if a password manager or something similar might be involved? 🤔

**Comment by bruce588** [comment]
The one I installed on windows 11 runs fine, but the one I installed on windows server doesn't save, and I can still add api keys, but I can't modify them.

[error1](https://drive.google.com/file/d/19Oe43IxSa4gunk1eu4N3sjYw9htLwJ8b/view?usp=drive_link)
[error2](https://drive.google.com/file/d/1dGrofmxb-vxP2SSf8pukjXekP-NbWn3R/view?usp=drive_link)
[error3](https://drive.google.com/file/d/1dzpNGUsKnCLntbT4TcylCpngHHxQAnbV/view?usp=drive_link)

**Comment by bruce588** [comment]
DIAGNOSTICS has error message :

Diagnostic reporter Seq.Server.Features.Diagnostics.ProcessorReporter failed.
System.Management.ManagementException: Not found
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.PropertyData.RefreshPropertyInfo()
   at System.Management.PropertyData..ctor(ManagementBaseObject parent, String propName)
   at System.Management.PropertyDataCollection.get_Item(String propertyName)
   at System.Management.ManagementBaseObject.GetPropertyValue(String propertyName)
   at System.Management.ManagementBaseObject.get_Item(String propertyName)
   at Seq.Server.Features.Diagnostics.Wmi.Processor.get_IsNumberOfEnabledCoreNull()
   at Seq.Server.Features.Diagnostics.ProcessorReporter.Report(DiagnosticReport report)
   at Seq.Server.Features.Diagnostics.Reporting.DiagnosticReportCollector.CollectDiagnosticReport(TextWriter output)

**Comment by nblumhardt** [comment]
Thanks for the additional info!

The "ProcessorReporter" error in the diagnostic report is unrelated; some older Windows versions don't expose processor information through WMI in the way we use for reporting, so we ignore these.

Just going on "the server could not be contacted" in those error messages - is there any network infrastructure between your browser and the Seq instance?

Typical culprits for this kind of thing might be:

 * A local internet proxy on your client/development machine
 * Some form of corporate firewall/security infrastructure
 * A load balancer or reverse proxy in front of Seq on the server side

Any clues there?

Best regards,
Nick

**Comment by bruce588** [comment]
Thank you for your prompt response. I suspect that the issue may originate from our company's firewall/security infrastructure, or the load balancer/reverse proxy on the server side as you pointed out.
What should I do next?

**Comment by nblumhardt** [comment]
Thanks for your reply, @bruce588.

The requests from Seq should be fairly normal HTTP `POST`s, so the group managing your server/network infrastructure should have some tools/processes at hand to trace one of these and figure out where it is being blocked.

Without direct knowledge of the infrastructure it's hard to narrow it down further than than from here, but if anything turns up that we can help with, please let me know.

**Comment by bruce588** [comment]
Does Seq Server have a log that can help me identify the cause?

**Comment by nblumhardt** [comment]
Seq uses HTTP.sys on Windows by default, so the `httperr*.log` files mentioned in https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/aspnet/site-behavior-performance/error-logging-http-apis may have some information on what's happening to the requests before they reach Seq, if they're getting that far.

Otherwise, if the requests aren't getting to Seq then using a tool like Wireshark or other generic network monitoring might be your best bet, but this really comes down to the environment and infrastructure involved. HTH!

**Comment by bruce588** [comment]
I didn't find anything in HTTP.sys, I think it's not sent, but I have some doubts, why I can add new API Key, and get error when I modify it, is the mechanism different between add and modify?
		Is there a different mechanism between adding and modifying?

**Comment by nblumhardt** [comment]
Hi! Adding is an HTTP `POST` while updating is a `PUT` - they're otherwise completely identical calls, though.

**Comment by nblumhardt** [comment]
Hi @bruce588; hoping you had some luck with this! Just tidying up the tracker and this one seems stale now, I'll close it as I don't think there's anything we can action at our end, but please let us know if you need any further info from us.
