### ISSUE TITLE
Feat: Add/Move "ADD API KEY" button to top of page

### ISSUE THREAD

**Issue by ruant** [datalust/seq-tickets#2010]
I have a lot of keys, and currently not using the SEQ-API to handle them the creation of these.
So scrolling/ctrl+end to the end of the page is tedious every time I have to add a new API key.

Would be a nice UX to either move the button above the API key list,
or add another one to the top and keep the bottom one.

**Comment by liammclennan** [comment]
Hi @ruant 

Are you on the latest version? I feel like we may have done this already.

**Comment by ruant** [comment]
@liammclennan Your completely correct.
My bad for not checking what version we were on before raising this 🙏
