### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by raul-mk** [datalust/seq-tickets#2012]
I get Forbidden Error when I brows localhost:5341 also when I execute "seqcli log -m test" command,  I get Failed with status code Forbidden: null , Failed with status code Forbidden (Forbidden).
port 5341 is open.
I decide to update seq, after update to new version, I get {"Error":"Not found."} when I brows http://localhost:5341/ and when I execute "seqcli log -m test" command,  I get Failed with status code Forbidden: null , Failed with status code Forbidden (Forbidden).
port 5341 is open.

**Comment by liammclennan** [comment]
Hi @raul-mk 

Seq can be configured to have ports that serve the application and ports that are limited to ingesting events.

You are trying to access the application through a port that is restricted to ingestion. 

If you look in the server logs (/data/Logs or Settings > Diagnostics > Diagnostic Report) you will see an error message to that effect.

**Comment by nblumhardt** [comment]
Hi @raul-mk, hopefully you've figured out what's going on; if not, please feel free to jump in with some more details (how you're running Seq, operating system, etc.) and we'll aim to suggest some more things to check.
