### ISSUE TITLE
Histogram button under search-input is disabled when loading page with &tail in the URL

### ISSUE THREAD

**Issue by Sune1337** [datalust/seq-tickets#2026]
**Describe the bug**
When SEQ is loaded with "&tail" in the URL, the "Histogram" button under the search-input is disabled.

**To Reproduce**
1. Go to 'http://seq.xxxxxx.yy' (your SEQ instance)
2. Click on 'Tail' button
3. Reload the page in webbrowser. (ie F5)
4. Notice that you cannot click "Histogram" button under search-input now.

**Expected behavior**
Can click "Histogram" button to see a graph of number of messages under search-input.

**Environment (please complete the following information):**
 - OS: Server: Windows Server 2019 1908 (17763.4377).
OS: Client: Windows 10 21H2 (19044.3570)
 - Browser Edge 119.0.2151.58
 - Seq Version 2023.4.10219
 - Using Docker? No

**Additional context**
Noticed this bug after upgrading SEQ from 2023.1 to 2023.4

**Comment by liammclennan** [comment]
Hi @Sune1337 

This is the expected behavior. Reloading the histogram while tailing would increase the load upon the server. We will reconsider if this is ideal.

**Comment by Sune1337** [comment]
Previously i do believe the histogram-button showed the current logs at the time the button was clicked; just not updating the histogram automatically as new logs arrived to Seq. To me this felt ok; however not being able to click the Histogram-button at all feels like it doesn't work.

Maybe it's just a matter of perception and what i was used to.

Thanks for your reply.

**Comment by Sune1337** [comment]
I would like to suggest to show a tooltip of the histogram button when it is disabled:
- Will not show histogram due to All time being selected
- Will not show histogram due to tailing

**Comment by KodrAus** [comment]
Thanks for the suggestion @Sune1337. It is a bit confusing when and why the histogram will disable, so in our upcoming 2024.1 release we've changed the behavior. The histogram button will never be disabled, but opening the histogram when you have an unbounded date range or tailing will show a help message in the histogram area similar to your suggested help text.
