### ISSUE TITLE
Dashboard chart query Group-by-time and Limit properties not editable

### ISSUE THREAD

**Issue by ode2code95** [datalust/seq-tickets#2030]
**Describe the bug**
When creating a new chart, the Group-by-time and Limit properties are not editable from the Query view.

**To Reproduce**
1. Go to 'Dashboards'
2. Click on your dashboard.
3. Create a new Chart
4. Open the 'Query' tab
5. Set `where` to `@Timestamp >= Now() - 15d`, `group by` to `time(1d)`, and `limit` to some value other than `10,000`.

**Expected behavior**
The Time and Limit fields in the SQL query are updated.

**Screenshots**

![image](https://github.com/datalust/seq-tickets/assets/23080282/afc152f4-048f-42ca-a3fd-043cb2c4c2be)

**Environment (please complete the following information):**
 - OS: **Windows 11**
 - Browser: **Brave**
 - Seq Version: **Seq 2023.1.9162**
 - Using Docker? **No**

**Additional context**
This bug is also reproduceable when trying to save a custom query with group-by intervals and limits different from the defaults to a chart. These parts of the query are not preserved when the chart is created.

**Comment by liammclennan** [comment]
Hi @ode2code95 

Thank you for the report.

The dashboard time range and grouping is set by the dashboards UI (top right), so it is not possible to specify a grouping in the query. Similarly, a limit would cause part of the visualization to be missing, without the user being aware.

**Comment by ode2code95** [comment]
Oh I see, so it was user error. 🤦 

Would you consider updating the "Query" tab inputs to disallow editing the fields that won't be used anyway?

**Comment by ode2code95** [comment]
Good point. For now, I'd say your explanation suffices for a resolution. This user will need to read the documentation more carefully next time.
