### ISSUE TITLE
AAD Approval Required for Seq in ACI with AAD integration

### ISSUE THREAD

**Issue by amitjaura** [datalust/seq-tickets#2033]
### Discussed in https://github.com/datalust/seq-tickets/discussions/2029

<div type='discussions-op-text'>

<sup>Originally posted by **amitjaura** November 28, 2023</sup>
Hi,

Our Seq instance is hosted in ACI and linked to AAD. Recently we have seen new users trying to log into Seq is presented with below option. It used to be simple onboarding. Has something changed recently?

<img width="217" alt="image" src="https://github.com/datalust/seq-tickets/assets/25460755/17437f4b-7636-43bd-a857-adc09eed7a1b">
</div>

**Comment by liammclennan** [comment]
Hi @amitjaura ,

This looks like an AAD configuration issue. Have you tried your Azure support?

**Comment by amitjaura** [comment]
Thanks @liammclennan. Just checked that AAD Admin settings are changed recently causing this issue. 
Do we know list of claims that Seq requires so I can reach out to our AAD Admin?

<img width="865" alt="image" src="https://github.com/datalust/seq-tickets/assets/25460755/d7c0fb2e-df20-4ce4-9836-36b343d8421e">

**Comment by nblumhardt** [comment]
Hi Amit; Seq requests "openid", "profile", "email", and "offline_access". Hope this helps!
