### ISSUE TITLE
Seq starts then immediately stops on Windows Server 2019

### ISSUE THREAD

**Issue by fschlaef** [datalust/seq-tickets#2037]
**Describe the bug**
After a fresh install of 2023.4.10219, no error messages, the Seq server is unavailable (ERR_CONNECTION_RESET)
The Seq service is stopped.

Event log shows a `Service started successfully`. event immediately followed with another event `Service stopped successfully`.

Note that both events starts with 

> The description for Event ID 0 from source Seq cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.

I attempted reboots, reinstalls but it always ends up like this.

**Environment (please complete the following information):**
 - OS: Windows Server 2019
 - Browser: Chrome
 - Seq Version 2023.4.10219
 - Using Docker? No

**Additional context**
I'm using Seq on another Windows Server 2019 machine with no issue.

**Comment by KodrAus** [comment]
Hi @fschlaef 👋 

Would it be possible to grab the contents of your `C:\ProgramData\Seq\Logs` directory? That could shed some light on what’s going on here.

**Comment by nblumhardt** [comment]
Hi again! I'll close this as stale, assuming you've found a way around the issue - please let us know either here or via `support@` if you need more help with this.
