### ISSUE TITLE
Be less strict when parsing custom date ranges

### ISSUE THREAD

**Issue by ticosido** [datalust/seq-tickets#2045]
If I want to display log entries for a custom date range, I can enter a start date and an end date.  On my system these are displayed like this: 

![image](https://github.com/datalust/seq-tickets/assets/73162624/c1aee540-54f1-43ce-b953-c7c4b37ae31b)

If I want to change the values, I have to enter them in precisely this format.  If I enter something in a different format (e.g. dd/mm/yyyy), an error message is displayed, telling me that the date format is invalid.. For example:

![image](https://github.com/datalust/seq-tickets/assets/73162624/a703f36c-f57d-4082-8770-66543f71f5d7)

Could this be changed so it's less strict about the date format?

**Comment by liammclennan** [comment]
Hi @ticosido,

This dialog does support a lot of different date formats, just not that one. For the same number of characters you can do `2023-12-13` and it will work. Also, you can click on the month and year and choose a date that way.

**Comment by GWeidmann** [comment]
I don't like that this is valid ...

![image](https://github.com/datalust/seq-tickets/assets/97590580/78e7660a-a6cd-4cfa-aa75-bfe48dbb3518)

... but these are not

![image](https://github.com/datalust/seq-tickets/assets/97590580/5630d1c4-a93f-49a4-b7ba-d88cdf77288d)
![image](https://github.com/datalust/seq-tickets/assets/97590580/b575f5a2-322b-49b6-b853-5705bd39e875)

It would be great to just be able to enter the numbers and to get the time, e.g. Grindstone does this great

![image](https://github.com/datalust/seq-tickets/assets/97590580/6085cf99-99a8-4cb9-965d-17e79a4af2c2)
![image](https://github.com/datalust/seq-tickets/assets/97590580/291983e8-1a3c-476c-ab35-d89d3310cc81)
![image](https://github.com/datalust/seq-tickets/assets/97590580/7c757c6c-2ab2-4ef2-8c49-802b862e6ed7)
![image](https://github.com/datalust/seq-tickets/assets/97590580/b3ccb096-475d-44df-86f7-fc17e66889b9)

**Comment by liammclennan** [comment]
@ticosido @GWeidmann a date parsing improvement has been merged and will be in 2024.1.
