### ISSUE TITLE
Signal indexes not effective in `2024.1.10871-pre`

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#2046]
The recent `2024.1.10871-pre` preview, with all of its focus on tracing, let through a regression in how signal indexes are selected. This means that searches using signals are not as fast as expected.

The underlying problem comes from the migration to a new index container format for trace indexing; we'll potentially need to spend some more time on this before RTM, but will release a new patch shortly that mitigates the issue for early adopters/explorers of the 2024 preview releases.

**Comment by KodrAus** [comment]
This is fixed in the latest 2024.1.10873-pre release.
