### ISSUE TITLE
UI Improvement suggestion for dropdown list option

### ISSUE THREAD

**Issue by dengyakui** [datalust/seq-tickets#2051]
Seq has a dropdown list for user to select time ranges. 
But the defatult time ranges only has 8 different options for user.
 But some times, I often need to use a custom range to filter log, like 2d/3d/4d,  but the dropdonw list was not editable, so I had to change the value from the brower addressbar, but after I hit enter, the logs got not refresh immediatiely, I can't know whether change has take effect. So  I have to  re-click the "Go" button or "Tail" button again to ensure the the log got refreshed
 
 If Seq enable users to set their own options  or make the dropdrop list control editable, it would be a huge improvement.
 
![image](https://github.com/datalust/seq-tickets/assets/3945919/43ffed77-8bf3-40e7-bb60-f635b32a489c)

**Comment by liammclennan** [comment]
Hi @dengyakui 

The list of time ranges is editable in settings.

**Comment by dengyakui** [comment]
Hi, @liammclennan 
I got it. It seems i can only save 1 option, it works for me. Thanks! 
![image](https://github.com/datalust/seq-tickets/assets/3945919/1e18921b-5b4a-4f0e-8c61-025c565a46cf)

**Comment by liammclennan** [comment]
Hi @dengyakui 

I made a mistake. The option is in `preferences`

![image](https://github.com/datalust/seq-tickets/assets/271514/ca0d029f-5ff6-4062-804b-0c9dcac95558)

**Comment by dengyakui** [comment]
Hi, @liammclennan : 
Thanks , resolved.
![image](https://github.com/datalust/seq-tickets/assets/3945919/8301fb5f-3cc5-47a1-bddd-26d3178b563a)
