### ISSUE TITLE
Show Signal Group in Drop-Down Lists

### ISSUE THREAD

**Issue by c0shea** [datalust/seq-tickets#2071]
I have a list of signals that are automatically grouped that have the same name but filter on different properties. For example, my list of signals in the main Events view look something like this:

- Api Users
  - Fulfillment
  - Integration
- Application
  - Fulfillment
  - Integration
- Environment
  - Dev
  - Prod

This is great for the Events view and keeps everything nicely organized, but I run into issues when trying to build alerts or app instances (like emails). Those two functions allow you to select one or more signals, but the problem is the drop-down list provided doesn't give you any indication of the grouping that the signal is part of. That makes the list have a bunch of seemingly duplicate entries, but it's impossible to know which entry will filter by the Api User property as opposed to the Application property if both list entries are named Integration.

![image](https://github.com/datalust/seq-tickets/assets/17714002/c135a8e4-d2fe-4722-b16a-005f7339f065)

A simple solution might be to change the option names to include the group name first:
- `Api Users > Integration`
- `Application > Integration`
- `Integration` (ungrouped)

**Comment by KodrAus** [comment]
That is a bit of a nasty papercut and would be great to fix up. Thanks for pointing this out @c0shea :+1:

**Comment by nblumhardt** [comment]
![image](https://github.com/datalust/seq-tickets/assets/342712/59806434-f060-48a3-9f21-65b773307805)
