### ISSUE TITLE
Login Page Not Available (403 FORBIDDEN), When Setting Initial Credentials On Docker 

### ISSUE THREAD

**Issue by sangeethnandakumar** [datalust/seq-tickets#2073]
## Run Seq on Docker with an initial username & password
I ran

```bash
docker run -d -p 5341:5341 -v /docker_volumes/seq:/data --name seq -e ACCEPT_EULA=Y -e SEQ_FIRSTRUN_ADMINUSERNAME=***** -e SEQ_FIRSTRUN_ADMINPASSWORDHASH=$(echo '******' | docker run --rm -i datalust/seq config hash) datalust/seq
```

> You can see i set a initial username using `SEQ_FIRSTRUN_ADMINUSERNAME` and initial password using `SEQ_FIRSTRUN_ADMINPASSWORDHASH`

Now my container started. The problem is not even the login page is working, It's authentication blocked. 

## How can I log in?

1. Docker Process
![image](https://github.com/datalust/seq-tickets/assets/24974154/7972bb7e-78b7-4fe2-b7ff-ba7de8d05ce3)

2. Seq Log
![image](https://github.com/datalust/seq-tickets/assets/24974154/d8ddf879-dad6-4759-9a32-360df6e0f887)

3. A simple CURL request to login page
![image](https://github.com/datalust/seq-tickets/assets/24974154/7335f1af-152d-4a9f-84f4-144e87288dad)

4. Reverse Proxied output on the browser
![image](https://github.com/datalust/seq-tickets/assets/24974154/728c7e19-3cb1-48d3-a3ef-4436eadf7a92)

**Comment by sangeethnandakumar** [comment]
Ok, I was able to make it work when I forward
> 5341->80

instead of 

> 5341->5341

Does that mean the UI lives only on 80 and 443? If that's the case I assume 5341 is Seq API.
It would be better if this is more clear. Closing this ticket

**Comment by liammclennan** [comment]
Hi @sangeethnandakumar 

Looks like you found your solution. [Getting Started with Docker](https://docs.datalust.co/docs/getting-started-with-docker) says:

```
-p 80:80 map the host's localhost:80 to Seq UI and API (port 80)
-p 5341:5341 map the host's localhost:5341 to Seq's special ingestion-only port (port 5341). [We recommend exposing the ingestion-only port separately.](https://docs.datalust.co/docs/urls#ingestion-port)
```

**Comment by sangeethnandakumar** [comment]
Got it @liammclennan. Much appreciated ..!
