### ISSUE TITLE
Symbol "Delete matching events" not visible anymore if input is to long

### ISSUE THREAD

**Issue by hpetriffer** [datalust/seq-tickets#2079]
If you haven an long input without newlines, than the button "Delete matching events" is not visible anymore.

Here after  a long input
![image](https://github.com/datalust/seq-tickets/assets/20905638/b9f0c897-7a2b-4c24-a045-fcaed4b33021)

and this is the screenshot after a few lines more 
![image](https://github.com/datalust/seq-tickets/assets/20905638/f8dc61f0-2ec9-4f22-8a04-a866a70e7196)

We use 2024.1.10981 and Chrome 121.0.6167.140 as browser

**Comment by liammclennan** [comment]
Hi @hpetriffer 

Thanks for the report.
