### ISSUE TITLE
Seq.exe crash: The process was terminated due to an unhandled exception - exception code c0000005

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#2093]
Reported by @jorgenfries in https://github.com/datalust/seq-tickets/discussions/2092; now being investigated.

**Comment by DanAvni** [comment]
Started having the same issue also. I am downgrading to 2023.4 for now as that was the previous version that did work

**Comment by nblumhardt** [comment]
Thanks for the added data point, @DanAvni; we're digging into this one, if you need any help downgrading in the meantime please let us know.

**Comment by nblumhardt** [comment]
This is fixed in 2024.1.11028, which we've just published. Thanks again for your help tracking this one down!
