### ISSUE TITLE
 Root level properties of complex objects will be shown as seperate data fields

### ISSUE THREAD

**Issue by kechf** [datalust/seq-tickets#2094]
**Describe the bug**
After seq 2024.1 update, sometimes the root level properties of complex objects will be shown as seperate data fields in the seq events, instead of a whole json object. 

**To Reproduce**
This issue occurrs after the seq upgrade from version 2023.x to 2024.1
We doesn't changed anything in the code. We use always the serilog framework in connection with  @ destructuring operator to log complex objects as json.

**Expected behavior**
We expect, that complex objects in connection with the destructuring operator in serilog will be shown as json data field in the log events.

**Screenshots**
![Seq_issue](https://github.com/datalust/seq-tickets/assets/23336242/83c2f5e7-3991-407a-ac53-58d81bf24bbd)

**Environment (please complete the following information):**
 - OS: Microsoft Windows Server 2016 (64-bit)
 - Chrome
 - Seq Version 2024.1
 - Using Docker? No (only clients, that create logs, use docker)

**Comment by nblumhardt** [comment]
Hi! Thanks for reaching out. You can switch this back to the old layout in user preferences, by deselecting "Flatten event properties view" - some more details and a screenshot in #2091. Does this help?

**Comment by ryanbuening** [comment]
We ran into this too and thought it was strange. It's a little confusing that "Flatten" was made to be the default. Especially when upgrading from 2023.x to 2024.x. 

Also of note, when Flatten is selected, it doesn't appear to affect all nested properties as shown below. I'm not sure if that is expected or not.

![image](https://github.com/datalust/seq-tickets/assets/812974/ef345732-6b64-4d24-b5d2-03e8aaffe2b7)

**Comment by liammclennan** [comment]
For future reference https://blog.datalust.co/nested-event-properties/

**Comment by jdlegan** [comment]
Is there  a way to turn this off at the server level? This caused is quite a bit of troubleshooting as a company which has been using Seq and Serilog for almost seven years. Very undesirable impact and now that we know the root cause, which is great, I do not want every new user to have to turn it off as the second step to all of the Seq instances they log into.

**Comment by liammclennan** [comment]
Hi @jdlegan, it is possible to disable flattening for all users using the api endpoint: `PUT api/users/{id}`. https://docs.datalust.co/docs/server-http-api#apiusers

**Comment by jdlegan** [comment]
@liammclennan is that for all our existing users or will this set the default setting for new users who are added via Azure AAD SSO integration?

**Comment by liammclennan** [comment]
@jdlegan `PUT api/users/{id}` is the endpoint to update an existing user.

**Comment by liammclennan** [comment]
@ryanbuening the flattening stops when it reaches an array, because there is no nice way to flatten an array.
