### ISSUE TITLE
Error in Seq v2024.1.11001

### ISSUE THREAD

**Issue by stevekirks** [datalust/seq-tickets#2095]
Hi

After upgrading from Seq v2023.4.10219 to v2024.1.11001, this Seq.App.Replication v4.0.0-dev-00006 package doesn't run, with the following error thrown:

> System.MissingMethodException: Method not found: 'Serilog.LoggerConfiguration Serilog.SeqLoggerConfigurationExtensions.Seq(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, Int32, System.Nullable`1<System.TimeSpan>, System.String, System.String, System.Nullable`1<Int64>, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, System.Net.Http.HttpMessageHandler, System.Nullable`1<Int64>, Int32)'.
>    at Seq.App.Replication.Replicator.OnAttached()
>    at Seq.Apps.SeqApp.Attach(IAppHost host)
>    at SeqCli.Apps.Hosting.AppContainer..ctor(ILogger logger, String packageBinaryPath, App app, Host host, String seqAppTypeName) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 62
>    at SeqCli.Apps.Hosting.AppHost.Run(String packageBinaryPath, IReadOnlyDictionary`2 appSettings, String storagePath, String seqBaseUri, String appInstanceId, String appInstanceTitle, String seqInstanceName, String mainAppTypeName) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppHost.cs:line 57

Let me know if any more info needed, thanks.

**Comment by nblumhardt** [comment]
Unfortunately this still reproduces with the new build; we'll need to push the replication app further forward:

![image](https://github.com/datalust/seq-tickets/assets/342712/190d1908-2226-4c27-b4de-bffd305b8fe5)

**Comment by nblumhardt** [comment]
Hi @stevekirks; [`5.0.0-dev-00015`](https://www.nuget.org/packages/Seq.App.Replication/5.0.0-dev-00015) now resolves this. Thanks for your patience; if you run into any more difficulties please just let us know.
