### ISSUE TITLE
Seq Uninstaller doesn't remove items from %path%

### ISSUE THREAD

**Issue by PaulFarry** [datalust/seq-tickets#2101]
**Describe the bug**
When I installed the 2024.1.11001 version of the Windows Installer version of the application, and I then uninstalled it, it leaves the Environment Variables behind on the uninstall.

**To Reproduce**
1. Run the installer
2. Check the Environment variable Path 
  2.1. 
![image](https://github.com/datalust/seq-tickets/assets/81415/1ded1bd8-8918-4c2b-b4fb-1faf243fa7a9)

3. Uninstall the application
4. 
![image](https://github.com/datalust/seq-tickets/assets/81415/ef802e91-90fa-4ad2-8819-3109bd6021ee)

5. The Variables are left behind

![image](https://github.com/datalust/seq-tickets/assets/81415/61b7a246-009b-4d95-bb59-c000c7eab8b9)

**Expected behavior**
The Path variables would be removed upon completion of uninstallation.

**Screenshots**
Added in the Steps to give context

**Environment (please complete the following information):**
 - OS: Windows
 - Browser N/A
 - Seq Version 2024.1.11001 
 - Using Docker? No

**Comment by nblumhardt** [comment]
Thanks, we'll take a look :+1:

**Comment by PaulFarry** [comment]
FYI: I also just checked a 4.2 uninstall and it leaves the path values behind as well.
