### ISSUE TITLE
Queries on @Id don't reduce search space

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#2114]
In Seq versions before 2023.1, a query like `@Id = 'event-ec852a6c24f908dcb4580a0a00000000'` would be able to quickly find an event with the matching id because it encodes its timestamp. The 2023.1 query engine rewrite lost this optimization, making `@Id` queries much slower than they need to be.

**Comment by tuyndv** [comment]
Hi @nblumhardt 
Could you please let me know when version 2024.2 will be available?
Thanks

**Comment by nblumhardt** [comment]
Hi @tuyndv; we don't have a precise date set on this one yet, but expect that it will be within the next 2-4 weeks. Hope this helps!
