### ISSUE TITLE
Allow the UI's service name expression to be customized

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#2121]
Currently, the UI uses `coalesce(service.name, Application)` when titling services in the trace view and related controls. Some existing installs will use other names for these properties, making some configurability desirable.

See: https://github.com/serilog-tracing/serilog-tracing/issues/67#issuecomment-1989279996

**Comment by nblumhardt** [comment]
![image](https://github.com/datalust/seq-tickets/assets/342712/29c070d8-efe1-4ab2-a3e3-95d1287c3783)

**Comment by Suchiman** [comment]
Thanks Nick! That's looking great
