### ISSUE TITLE
The new auto-complete only works for the first property in query

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#2139]
### Discussed in https://github.com/datalust/seq-tickets/discussions/2138

<div type='discussions-op-text'>

<sup>Originally posted by **CrossBound** March 28, 2024</sup>
I like the new auto-complete introduced in 2023.4, but not sure if it's just me or not but when I search the auto-complete only works for the first property I work with. If I try to do a compound search filter (combining filters with "AND" or "OR") auto-complete doesn't work for secondary filter clauses</div>

**Comment by KodrAus** [comment]
Filters like `Elapsed > 500 and SourceContext = '..'` will autocomplete `Elapsed`, but not `SourceContext`.

SQL queries like `select count(*) from stream where Elapsed > 500 and SourceContext = '..'` will autocomplete both `Elapsed` and `SourceContext`.

**Comment by nblumhardt** [comment]
Fixed, patch due within a week or so :+1:
