### ISSUE TITLE
Support wildcard certificates under Kestrel on Windows

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#2142]
> Hi  - I've just done a fresh install of SEQ on a Windows server, and I've setup the listening URL as https://seq.example.corp. I have a *.example.corp wildcard cert in the local machine / personal store. When I start the SEQ service, it stops straight away, and in the error logs show this:
>
> System.InvalidOperationException: The requested certificate seq.example.corp could not be found in LocalMachine/My with AllowInvalid setting: True.\r\n   at Microsoft.AspNetCore.Server.Kestrel.Https.CertificateLoader.LoadFromStoreCert(String subject, String storeName, StoreLocation storeLocation, Boolean allowInvalid)\r\n  
>
> Is there a way to tell it to use the wildcard rather than trying to match the certificate name? I would prefer not to have to issue a specific cert just for this.  I tried using the seq-bindssl command, but it saying that it's not supported under Kestrel. Do I have to change to http.sys as per https://docs.datalust.co/docs/ssl? 
>
> `C:\Users\pa009999>seq bind-ssl --thumbprint="<my wildcard cert thumbnail>"`
>
> Could not bind the certificate: The current value of the `api.webServer` setting is `Kestrel`. Kestrel loads certificates automatically from the `Local Computer/Personal` certificate store, and cannot be configured using the `bind-ssl` command.

_Originally posted by @tspencer-all in https://github.com/datalust/seq-tickets/discussions/2140_

**Comment by parvic1** [comment]
was this ever fixed?

**Comment by nblumhardt** [comment]
Hi @parvic1; the intended fix shipped in a 2024.2 maintenance patch, but I'm not sure whether any subsequent issues were found with it. Are you running into trouble with wildcard certs?

**Comment by parvic1** [comment]
Yes we are. The certificate is indeed under LocalComputer\Personal\Certificates

Here is the log from Seq: (changed the domain name for privacy)

***@***.******@***.***":"A certificate with subject {Hostname} was not found; trying wildcard match {WildcardHostname}","Hostname":"bbgapp-logs.ourdomain.org","WildcardHostname":"*.ourdomain.org","SourceContext":"Seq.Server.Web.Host.WebHostBuilderExtensions"}
***@***.******@***.***":"Application startup ***@***.******@***.***":"Autofac.Core.DependencyResolutionException: An exception was thrown while activating Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.\r\n ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Connections.IConnectionListenerFactory], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Connections.IMultiplexedConnectionListenerFactory], Microsoft.AspNetCore.Server.Kestrel.Core.IHttpsConfigurationService, Microsoft.Extensions.Logging.ILoggerFactory, Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelMetrics)' on type 'KestrelServerImpl'.\r\n ---> System.InvalidOperationException: The requested certificate *.ourdomain.org could not be found in LocalMachine/My with AllowInvalid setting: True.\r\n   at Microsoft.AspNetCore.Server.Kestrel.Https.CertificateLoader.LoadFromStoreCert(String subject, String storeName, StoreLocation storeLocation, Boolean allowInvalid)\r\n   at Seq.Server.Web.Host.WebHostBuilderExtensions.LoadCertificate(Uri apiListenUri)\r\n   at Seq.Server.Web.Host.WebHostBuilderExtensions.<>c__DisplayClass0_1.<UsePlatformHost>b__6(ListenOptions listenOptions)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(EndPoint endPoint, Action`1 configure)\r\n   at Seq.Server.Web.Host.WebHostBuilderExtensions.<>c__DisplayClass0_0.<UsePlatformHost>b__3(KestrelServerOptions options)\r\n   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)\r\n   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource, KestrelMetrics metrics)\r\n   at lambda_method185(Closure, Object[])\r\n   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()\r\n   --- End of inner exception stack trace ---\r\n   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Extensions.DependencyInjection.KeyedServiceMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   --- End of inner exception stack trace ---\r\n   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()\r\n   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)\r\n   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)\r\n   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)\r\n   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)\r\n   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest& request)\r\n   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)\r\n   at Autofac.Core.Container.ResolveComponent(ResolveRequest& request)\r\n   at Autofac.Core.Container.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)\r\n   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)\r\n   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)\r\n   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)\r\n   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)\r\n   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)\r\n   at Microsoft.AspNetCore.Hosting.WebHost.EnsureServer()\r\n   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()","EventId":{"Id":6},"SourceContext":"Microsoft.AspNetCore.Hosting.Diagnostics"}
***@***.******@***.***":"Error running the server ***@***.******@***.***":"Autofac.Core.DependencyResolutionException: An exception was thrown while activating Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.\r\n ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Connections.IConnectionListenerFactory], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Connections.IMultiplexedConnectionListenerFactory], Microsoft.AspNetCore.Server.Kestrel.Core.IHttpsConfigurationService, Microsoft.Extensions.Logging.ILoggerFactory, Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelMetrics)' on type 'KestrelServerImpl'.\r\n ---> System.InvalidOperationException: The requested certificate *.ourdomain.org could not be found in LocalMachine/My with AllowInvalid setting: True.\r\n   at Microsoft.AspNetCore.Server.Kestrel.Https.CertificateLoader.LoadFromStoreCert(String subject, String storeName, StoreLocation storeLocation, Boolean allowInvalid)\r\n   at Seq.Server.Web.Host.WebHostBuilderExtensions.LoadCertificate(Uri apiListenUri)\r\n   at Seq.Server.Web.Host.WebHostBuilderExtensions.<>c__DisplayClass0_1.<UsePlatformHost>b__6(ListenOptions listenOptions)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(EndPoint endPoint, Action`1 configure)\r\n   at Seq.Server.Web.Host.WebHostBuilderExtensions.<>c__DisplayClass0_0.<UsePlatformHost>b__3(KestrelServerOptions options)\r\n   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)\r\n   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource, KestrelMetrics metrics)\r\n   at lambda_method185(Closure, Object[])\r\n   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()\r\n   --- End of inner exception stack trace ---\r\n   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Extensions.DependencyInjection.KeyedServiceMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   --- End of inner exception stack trace ---\r\n   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()\r\n   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)\r\n   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)\r\n   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)\r\n   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)\r\n   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest& request)\r\n   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)\r\n   at Autofac.Core.Container.ResolveComponent(ResolveRequest& request)\r\n   at Autofac.Core.Container.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)\r\n   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)\r\n   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)\r\n   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)\r\n   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)\r\n   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)\r\n   at Microsoft.AspNetCore.Hosting.WebHost.EnsureServer()\r\n   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()\r\n   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)\r\n   at Microsoft.AspNetCore.Hosting.WebHost.Start()\r\n   at ***@***.******@***.***%22:%22The>
***@***.******@***.******@***.******@***.***%22:%22The> Seq server could not be ***@***.******@***.***":"Autofac.Core.DependencyResolutionException: An exception was thrown while activating Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.\r\n ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Connections.IConnectionListenerFactory], System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.Connections.IMultiplexedConnectionListenerFactory], Microsoft.AspNetCore.Server.Kestrel.Core.IHttpsConfigurationService, Microsoft.Extensions.Logging.ILoggerFactory, Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelMetrics)' on type 'KestrelServerImpl'.\r\n ---> System.InvalidOperationException: The requested certificate *.ourdomain.org could not be found in LocalMachine/My with AllowInvalid setting: True.\r\n   at Microsoft.AspNetCore.Server.Kestrel.Https.CertificateLoader.LoadFromStoreCert(String subject, String storeName, StoreLocation storeLocation, Boolean allowInvalid)\r\n   at Seq.Server.Web.Host.WebHostBuilderExtensions.LoadCertificate(Uri apiListenUri)\r\n   at Seq.Server.Web.Host.WebHostBuilderExtensions.<>c__DisplayClass0_1.<UsePlatformHost>b__6(ListenOptions listenOptions)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(EndPoint endPoint, Action`1 configure)\r\n   at Seq.Server.Web.Host.WebHostBuilderExtensions.<>c__DisplayClass0_0.<UsePlatformHost>b__3(KestrelServerOptions options)\r\n   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)\r\n   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource, KestrelMetrics metrics)\r\n   at lambda_method185(Closure, Object[])\r\n   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()\r\n   --- End of inner exception stack trace ---\r\n   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()\r\n   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Extensions.DependencyInjection.KeyedServiceMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   --- End of inner exception stack trace ---\r\n   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()\r\n   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)\r\n   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)\r\n   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)\r\n   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)\r\n   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)\r\n   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)\r\n   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)\r\n   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest& request)\r\n   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)\r\n   at Autofac.Core.Container.ResolveComponent(ResolveRequest& request)\r\n   at Autofac.Core.Container.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)\r\n   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)\r\n   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)\r\n   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)\r\n   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)\r\n   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)\r\n   at Microsoft.AspNetCore.Hosting.WebHost.EnsureServer()\r\n   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()\r\n   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)\r\n   at Microsoft.AspNetCore.Hosting.WebHost.Start()\r\n   at Seq.ServiceProcess.ServerService.Start()\r\n   at Seq.ServiceProcess.SeqWindowsService.<>c__DisplayClass2_0.<.ctor>b__0()"}

**Comment by nblumhardt** [comment]
Thanks for your reply; just giving the code a quick scan to see what's expected - ts the certificate's `CN` exactly `*.yourdomain.tld`?

**Comment by parvic1** [comment]
Sorry... did not understand your question. The certificate is a wildcard cert as *.domain.org

**Comment by parvic1** [comment]
Does the default account created by Seq installation require specific permissions to read the cert stores?
