### ISSUE TITLE
Dashboard: Tail is Disabled After Drilldown in a Chart

### ISSUE THREAD

**Issue by IsThatUniqueEnough** [datalust/seq-tickets#2157]
**Current behaviour**
When coming back from a drilldown in a chart with activated tail, tail is deactivated,

**To Reproduce**
1. Go to a dashboard with charts
2. Activate tail
3. Double click on a data point in the chart
4. Hit browser back button to return to the dashboard. Tail is now inactive.

**Expected behavior**
The state of "tail" should be the same as before the drilldown. 

**Use case**
When a diagram shows an unusual peak I double click the data point to investigate what happened. When returning to the dashboard I expect the dashboard to be in the state I left it: "alive" (with active tailing)

**Environment (please complete the following information):**
 - OS: Server: Linux, Browser: Windows
 - Browser: Firefox, Chrome, Edge
 - Seq 2024.2.11240
 - Using Docker? Yes

**Additional context**
This worked as expected before the "Refresh every [interval]" option was replaced by the "tail" buttons.

**Comment by nblumhardt** [comment]
Thanks for raising this, we'll take a look.

**Comment by nblumhardt** [comment]
The state of Events and Dashboards are both now remembered when navigating back from another screen. Thanks again for the nudge!
