### ISSUE TITLE
documentation issue: init-scripts

### ISSUE THREAD

**Issue by asitha99x** [datalust/seq-tickets#2172]
this is not a super serious issue but it will save time.

**Describe the bug**
https://docs.datalust.co/docs/init-scripts

```
#!/bin/bash
seqsvr restore --from-latest
```

the missing` -y` flag on the init script sample cause this script to fail ( waiting for user input) , since its already mounted in to the container it will keep on failing the container restart. 

in our case only way out was this loop was the stop the deployment and mount the disk some other container and clean the code.

*** suggestion** 
may be a script which get fails once should be moved, like the solution you have for the complected scripts 

{old-name}.done
{old-name}.failed

**Comment by nblumhardt** [comment]
Thanks for the report and the suggestion. I've fixed the docs, I'll close but we'll keep the suggestion in mind.
