### ISSUE TITLE
Optimize @MessageTemplate search with @EventType index

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#2181]
If someone searches for
```sql
@MessageTemplate = 'Hello {Name}'
```
that could be trivially optimized to
```sql
@EventType = ToEventType('Hello {Name}')
```
which then performs a lot faster due to the new indexing capabilities.

**Comment by nblumhardt** [comment]
Thanks for the suggestion! Unfortunately, `@EventType` isn't strictly determined by `@MessageTemplate` - data sources can specify event types explicitly (though most rely on the default hash of the message template).

We're just about to ship 2024.3, which will allow an index to be created on `@MessageTemplate` if you wish. The UI only allows regular properties to be indexed, but running:

```
seqcli expressionindex create -e "@MessageTemplate"
```

will have the effect you want (with a similar storage cost to the `@EventType` index). Let me know if it sounds like this will help.

Best regards,
Nick

**Comment by Suchiman** [comment]
> data sources can specify event types explicitly

TIL

> with a similar storage cost to the `@EventType` index

I guess in that case i'll live with having to remember to use the second trick :)
My main usecase here has been figuring out if a log message i'm seeing in code has ever happened, so it's not a frequent thing to do but it hugely benefits from the index, being able to confirm in a few seconds that this message never happened in the past year (or only did a handful of times).

Thanks for the quick response as always Nick!
