### ISSUE TITLE
Wrong Colors in Storage overview

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#2187]
**Describe the bug**
If you hover over the graph the colors in the legend are wrong. The graph uses purple for indexes and pink for queued but the legend visualizes black for indexes and purple for queued.

**Screenshots**
![image](https://github.com/datalust/seq-tickets/assets/7110884/da079436-10ae-4cee-8e81-3bd92295c99c)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Seq Version: 2024.3.11500-pre
 - Using Docker? No

**Comment by KodrAus** [comment]
Ah thanks for the report @Suchiman :bow: We'll get that fixed up.
