### ISSUE TITLE
Dashboard: Resetting date range sets "by" to "1ms"

### ISSUE THREAD

**Issue by IsThatUniqueEnough** [datalust/seq-tickets#2202]
**Description**
When hitting "RESET" in the custom date range dialog of a dashboard "by" is set to "1ms".

**To Reproduce**
1. Dashboard is set to "Last 1d" by "15m" (or any custom range)
2. Click on 'Last 1d'
3. Click on "Custom..."
4. Click on "RESET"
5. Setting is now "Last 1d" by "1ms"

**Expected behavior**
Reset the values to reasonable defaults instead of setting "by" to "1ms". (I'm not sure how the defaults for the date range and "by" are calculated but usually my dashboards default to "1d" by "15m" and "by" is set to an interval that makes sense for the currently selected date range).

**Environment**
- OS: Server: Linux, Browser: Windows
- Browser: Firefox, Chrome, Edge
- Seq 2024.3.11547
- Using Docker? Yes

**Comment by nblumhardt** [comment]
Thanks, looks like we broke this when we modified custom date selection in 2024.3, we'll patch it up :+1:
