### ISSUE TITLE
Please accept a unified OTLP endpoint for logs, traces, metrics

### ISSUE THREAD

**Issue by alrz** [datalust/seq-tickets#2206]
There's a extension method to export OTLP for [logs, traces and metrics](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Builder/OpenTelemetryBuilderOtlpExporterExtensions.cs):
```cs
      builder.Services.AddOpenTelemetry()
            .UseOtlpExporter(OtlpExportProtocol.Grpc, new Uri("http://endpoint"))
            .ConfigureResource(...)
            .WithMetrics(...)
            .WithTracing(...);
```
But as of now seq require a distinct endpoint for logs and traces (and probably metrics in the future). This complicates the setup since each endpoint must be configured separately. It would be nice to support a unified endpoint so that the above code would be sufficient to cover all three.

**Comment by liammclennan** [comment]
Hi @alrz ,

Seq follows the OTEL standard. When using gRPC (as in your example) logs and traces use the same endpoint. When using HTTP/protobuf then endpoints are `/ingest/otlp/v1/logs` and `/ingest/otlp/v1/traces`.

**Comment by nblumhardt** [comment]
2026.1 will add metrics support to the OTLP and JSON ingestion endpoints. https://github.com/datalust/seq-tickets/issues/2491 is tracking.
