### ISSUE TITLE
Cannot read properties of undefined (reading 'ElapsedMilliseconds')

### ISSUE THREAD

**Issue by c0shea** [datalust/seq-tickets#2229]
**Describe the bug**
Seq returns the error "Cannot read properties of undefined (reading 'ElapsedMilliseconds')" for a long-running query.

**To Reproduce**
1. Run a long-running query, such as `select RequestBody from stream limit 100000000000` over a 3 day span. It's expected to return 40,000 or so rows of JSON payloads.
2. After a minute or so, it returns the error message

**Expected behavior**
A clearer message that my user timeout period has elapsed. My profile is set to 2,000 seconds and that wasn't respected as the error returned in less than two minutes instead of 33 minutes.

**Screenshots**
![image](https://github.com/user-attachments/assets/37e9c89a-49a7-4520-b56e-8a4b5492b6e5)
![image](https://github.com/user-attachments/assets/b3564f2c-4058-473a-b7ed-08791fd8eda1)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Seq Version: 2024.3.11510
 - Using Docker? No

**Comment by liammclennan** [comment]
Hi @c0shea 

When you get this error is there a stack trace (or any more detail) in the browser's developer console?

**Comment by c0shea** [comment]
Yes, it writes this to the console:

```
TypeError: Cannot read properties of undefined (reading 'ElapsedMilliseconds')
    at api.data.inSignal.then.cancelLastRequest (main-LSJBemFd.js:18:196948)
    at angular-DvxoCOxF.js:141:454
    at m.$digest (angular-DvxoCOxF.js:153:67)
    at m.$apply (angular-DvxoCOxF.js:156:484)
    at k (angular-DvxoCOxF.js:107:445)
    at v (angular-DvxoCOxF.js:113:40)
    at y.onload (angular-DvxoCOxF.js:113:464) 'Possibly unhandled rejection: {}'
```

![image](https://github.com/user-attachments/assets/f76e877c-5949-4618-b0b9-78832abb56e8)

The main-LSJBemFd.js file pointed to this line:

![image](https://github.com/user-attachments/assets/a928c8ba-6506-4084-a9c0-18618fb681d5)

**Comment by liammclennan** [comment]
That's brilliant. Thank you. We'll get this fixed.

**Comment by liammclennan** [comment]
this is fixed for the next release. Thanks for the report @c0shea !
