### ISSUE TITLE
Seq upgrade installer blew away service configuration

### ISSUE THREAD

**Issue by c0shea** [datalust/seq-tickets#2245]
**Describe the bug**
I ran the installer to upgrade to the latest version 2024.3.12021. The install itself worked fine. I left the box checked to run the service configuration tool and closed the install wizard. A new UI opened for service administration and it didn't remember any of my previous settings. It defaulted to the ProgramData directory to store data, even though my current install kept the data on the D drive. It also reset the URL to localhost:5341 and I had to re-enter our HTTPS URL.

**To Reproduce**
1. Run the installer to upgrade from 2024.3.11914 to 2024.3.12021.

**Expected behavior**
If the installer was going to uninstall and reinstall the Seq Windows Service, it should have kept my existing configuration to respect the data directory and URL.

**Screenshots**
This is the new dialog that didn't respect my existing config.
![image](https://github.com/user-attachments/assets/54ea7cc4-2b2d-4d52-8cb8-0e2ca02ec4ce)

**Environment (please complete the following information):**
 - OS: Windows Server 2022 Datacenter
 - Browser Edge
 - Seq Version 2024.3.12021

**Comment by nblumhardt** [comment]
Thanks for the report @c0shea; we've seen one other instance of this, I think I've figured out what's going on, we'll get this sorted out :+1:

**Comment by nblumhardt** [comment]
We'll release a patch fixing this in the next week or so. Unfortunately, the bug is in the installer's _remove_ logic, so going from any of the existing versions to the fixed version will still be fragile and require the storage location/listen URI to be re-entered.
