### ISSUE TITLE
Request: Query history 

### ISSUE THREAD

**Issue by SeanKilleen** [datalust/seq-tickets#2246]
Writing this up really quickly before I forget. Might even learn that this capability exists already in a way that just hasn't been intuitive for me yet.

Repro steps:

* Execute a bunch of different queries in Seq
* Reopen the web browser
* Try to go back to one of those queries

Desired Behavior: I can hit the up arrow or CTRL + Up (or similar) while in the query box and get back to prior queries I'd executed.

Current Behavior: No way I can find to see my prior queries (am I just missing it)?

**Comment by nblumhardt** [comment]
Hi Sean! Currently you'll find this in the "History" tool window; it's collapsed by default but it'll be shown as a tab over on the right of the screen:

![image](https://github.com/user-attachments/assets/219dc6cc-fa65-4436-b1d1-e347cdeb1450)

**Comment by SeanKilleen** [comment]
Thank you so much! I figured I had to be missing it somewhere, but I truly could not find it for the life of me.
