### ISSUE TITLE
Show alerts from all users

### ISSUE THREAD

**Issue by liammclennan** [datalust/seq-tickets#2248]
Users with the 'Project' permission should be able to see alerts from all users, to enable noisy alerts to be disabled. Other users' alerts should be available by enabling a 'Include alerts from all users' option. 

Alerts created by other users, and not shared or protected, can be disabled but not edited in any other way. 

Alerts are re-enabled when the owner edits and saves them. 

This replaces the _Settings > Notifications_ functionality.

**Comment by nblumhardt** [comment]
This is complete.
