### ISSUE TITLE
Login fails when password contains double quote

### ISSUE THREAD

**Issue by simon-chester** [datalust/seq-tickets#2253]
Attempt to sign-in to Seq as a user that has at least 1 double-quote (") in their password. Sign fails even though credentials have been entered correctly.

(If you look at the request payload to /api/users/login, you'll see that the double-quote character is unexpectedly prepended by a backslash.)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 127
 - Seq Version 2024.3.12250
 - Using Docker? No

My love for Seq is undiminished 😂

**Comment by KodrAus** [comment]
Thanks for the report @simon-chester!

**Comment by KodrAus** [comment]
Hi @simon-chester :wave: We weren't able to reproduce this ourselves; the `\"` escaping is what you'd expect to see inside a JSON string, and is unescaped server-side. Are you trying to sign in via the built-in username/password scheme or via OIDC/EntraID?

Feel free to drop us a line at our `support@datalust.co` address with any more details if you'd like.

**Comment by simon-chester** [comment]
Hi @KodrAus, Thanks for looking at this.

Yes, that makes perfect sense about the JSON escaping (sorry, it was the end of a long day when I opened this issue last night 🥱).

I was using the built-in username/password. Here's a video: https://www.youtube.com/watch?v=OrrwhaAbfYw

**Comment by simon-chester** [comment]
..... Just as a quick sanity-check... Here's another of me then removing the double-quote, and the login then succeeding: https://youtu.be/pm8_eNcDtu4

**Comment by liammclennan** [comment]
Hi Simon,

The problem is likely to be that your shell is messing with the quotes. You can use the [`--password-stdin`](https://docs.datalust.co/docs/server-command-line#auth-reset) option, or set your password in Seq.

It is also possible to escape the quotes in command line arguments, but the [rules are complicated](https://stackoverflow.com/questions/7760545/escape-double-quotes-in-parameter) and different for every shell.

**Comment by simon-chester** [comment]
Hi @liammclennan, Thank you - that makes perfect sense. Thanks for your help.
