### ISSUE TITLE
Fail to start seq  by GC error

### ISSUE THREAD

**Issue by git1453** [datalust/seq-tickets#2263]
**Describe the bug**
fail to start seq

**To Reproduce**
1. docker run --name seq -d --restart unless-stopped -e ACCEPT_EULA=Y -p 5341:80 datalust/seq:latest 

**Expected behavior**
docker logs seq  
GC: Failed to initialize GCToOSInterface
GC initialization failed with error 0x80004005
Failed to create CoreCLR, HRESULT: 0x80004005

**Screenshots**
![image](https://github.com/user-attachments/assets/40896e6b-2025-45cb-8f86-b4b2adab9677)

**Environment (please complete the following information):**
 - OS: [e.g. Linux,]![image](https://github.com/user-attachments/assets/dd8f6bae-845e-4ac9-b38d-7506a8e6da4b)
 - Browser [Firefox,]
 - Seq Version [datalust/seq:latest  arm64 eaf463954067] 
 - Using Docker? Yes  
 - Docker Version 19.0.3

**Additional context**

**Comment by liammclennan** [comment]
Hi @git1453 

What hardware are you running this on?

and, it looks like a .NET runtime error so it would be good to establish if you can run containers with .NET code. See https://hub.docker.com/r/microsoft/dotnet-samples/ and consider running `docker run --rm mcr.microsoft.com/dotnet/samples` to verify that .NET containers work for you.

**Comment by git1453** [comment]
I running `docker run --rm mcr.microsoft.com/dotnet/samples` ,and the same problem. in the server i had run the  asp.net core 6.0 web program, it work well. it should be containers problem.

**Comment by nblumhardt** [comment]
Thanks for the follow-up :+1:
