### ISSUE TITLE
Custom color for columns on Events tab

### ISSUE THREAD

**Issue by MrVitaly** [datalust/seq-tickets#2269]
It would be beneficial to introduce the ability to specify custom color for each specified column on the Events tab.

The current design automatically assigns light colors to specified columns, which may not offer enough contrast or differentiation, leading to reduced readability and usability.

This feature would enable users to improve visual distinction between columns, especially when working with a large number of columns.

**Comment by KodrAus** [comment]
Thanks for the suggestion @MrVitaly :+1: We do have work to do to improve the contrast of parts of the UI across the board.

You could specify your own colours using an instance theme. Columns have CSS classes like `tag-1`, `tag-2`, `tag-3`, etc.

**Comment by MrVitaly** [comment]
@KodrAus, @nblumhardt, thank you for the recommendation to use CSS styles, but the main idea of my suggestion is to allow the specification of colors for columns based on **property names**, rather than relying on the order of the columns.

By assigning colors to specific property names, users will be able to consistently highlight the same columns across all signals, regardless of their order or position within a particular signal. This approach eliminates the need to manage the column sequence manually and via CSS theming which would improve the user experience by making the interface more intuitive and adaptable to individual preferences.

**Comment by KodrAus** [comment]
Assigning colours per column expression or column value could be something to explore for sure, like we do for service names in traces :+1:

**Comment by nblumhardt** [comment]
Hi again; just revisiting this in triage - the custom CSS approach can work give the `title` attribute that's applied to columns:

```css
.event-columns .property-name[title="Origin"] {
  color: red !important;
}
```

![image](https://github.com/user-attachments/assets/2fc809ff-0e9f-4a0d-a242-e7819bb1c44c)

We'd like to be able to improve this in a future design, but for now, the workaround should be usable in many cases. As we're not expecting to revisit this within the next few versions we'll close for now.

Thanks again for the feedback!

**Comment by MrVitaly** [comment]
@KodrAus, @nblumhardt, is it possible to use the current custom CSS approach, taking into account the user's theme, to set up different colors for Dark and Light themes?

**Comment by KodrAus** [comment]
@MrVitaly not with Seq's current theming system, which is based on Sass mixins, but we've been porting to CSS variables for the next release which should make it easier to customize colours.
