### ISSUE TITLE
Improvements around frontend errors & documentation regarding WAF rules

### ISSUE THREAD

**Issue by codymullins** [datalust/seq-tickets#2301]
This issue tiptoes the line between bug, enhancement, and general information.

It appears Cloudflare will block some functionality based on rules detecting SQL in the querystring -- this is used in the `Show Trace` functionality. 

Some thoughts:

1. Add a section to the documentation (we're deploying with Azure + Cloudflare) that notes this could be blocked by WAF rules.
2. Perhaps a `POST` in this case, with the data in the body, would get around it? I'm not totally sure.
3. Although it was obvious as soon as I opened the network tab, I initially thought the error was during ingestion. No errors were in the logs - perhaps a way to track front-end errors here and surface them so they're apparent would be nice.

![image](https://github.com/user-attachments/assets/c4d29c99-442b-4921-97a1-deb52d68ff55)

### Additionally, the below error message was unhelpful.

How do I check the index is up to date? No idea. I spent too much time thinking this was an ingestion issue or some corrupted state.

Now, it makes sense. Seq couldn't find the trace. Some message improvements here -- "here's instructions on how to check the index", or "the request was blocked by your firewall/adblocker/yada yada"

![image](https://github.com/user-attachments/assets/72f83724-b4dc-4701-b77c-770c44e4eb95)

**Comment by nblumhardt** [comment]
Thanks for the heads-up, Cody; we'll have to give this one some thought 👍

**Comment by codymullins** [comment]
Thanks - not expecting any quick resolution - we have a workaround for the ruleset for now. Hope the feedback helps.

**Comment by nblumhardt** [comment]
We've changed the message to:

```
If trace loading regularly times out, this
may indicate an indexing problem, or network infrastructure may be
blocking these requests.
```

Thanks, Cody!
