### ISSUE TITLE
LLM Observability with OpenTelemetry

### ISSUE THREAD

**Issue by patcher9** [datalust/seq-tickets#2341]
Hi Team,

I’m one of the maintainers of [OpenLIT](https://github.com/openlit/openlit), an open-source AI Engineering platform that offers in-depth monitoring for LLM applications and AI agents. We seamlessly integrate with over 50 GenAI tools, providing users with robust OpenTelemetry tracing and metrics right out of the box. Our platform was even spotlighted as the go-to tool in [Opentelemetry's blog post](https://opentelemetry.io/blog/2024/llm-observability/). Plus, observability solutions like [Grafana](https://grafana.com/docs/grafana-cloud/monitor-applications/ai-observability/instrument/), [New Relic](https://docs.newrelic.com/docs/opentelemetry/get-started/openlit-llm-observability/openlit-llm-observability-intro/), and [Middleware.io](https://docs.middleware.io/llm-observability/openlit/python) have used our tools to build LLM observability features.

I’d love to explore a collaboration with Seq to bring these features to life. Let us know if you are interested and we can set aside some time to chat about potential ideas and next steps.

**Comment by KodrAus** [comment]
Hi @patcher9 👋 We don’t have anything planned in this space at this time. Seq supports OTLP ingestion, so any diagnostics produced in that format will be compatible with it.

If OpenTelemetry adopts conventions or a data model specifically for LLMs then it’s something we could consider more targeted support for in the product in the future.
