### ISSUE TITLE
Include originating host in messages

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-tickets#298]
It would be convenient to **store the IP Address or host name** of incoming messages as part of the event stored in Seq (i.e. the IP address of the http client that connected to the Seq server).

This would allow proper filtering by originating server without needing to explicitly enrich events in every client.

This would allow for some cool additional features could be : 
- map all these IP addresses/hostnames to environments or additional semantic properties
- ignoring messages from a host that is no longer relevant (when not relying on application keys)

**Comment by nblumhardt** [comment]
API keys partially cover this already (you can choose to associate properties with each API key). Adding the option to automatically apply IP address/hostname would definitely be a worthwhile improvement. Thanks!

**Comment by dunkymole** [comment]
Plus one for the source IP. Would be a great help in the world of immutable infrastructure/cloud deployments.

**Comment by clockwisemusic** [comment]
I get around this by making everyone in our team use a library for logging that automatically adds hostname as a property to each log... but this feature would be handy too.

**Comment by nblumhardt** [comment]
We agree this would be useful, but the cost/benefit hasn't lined up for the last few releases and so we'll close this ticket for now. Hopefully, custom inputs will provide a way to implement this in the future. Thanks all!
