### ISSUE TITLE
Indented view of structured property values

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#421]
Small structured values like `{"Username": "nblumhardt", "Name", "Nick"}` are better displayed inline when present as event properties. Beyond a line or two however, inline formatting becomes difficult to visually parse.

When a property value spans more than a line (or so) of JSON, indented display would be more appropriate.

Via @dsplaisted / https://twitter.com/dsplaisted/status/730200809615425536

**Comment by dsplaisted** [comment]
In addition to indenting the display, it would be nice to be able to separately expand or collapse each node in the property tree.  Otherwise expanding the event is still going to give me an overload of data.  Perhaps when collapsed it could display the first few properties, and/or the count of subproperties.

**Comment by nblumhardt** [comment]
:+1: 

![expandcollapse](https://cloud.githubusercontent.com/assets/342712/15209196/20a7b28a-1873-11e6-8e30-d1c6b52d4ac6.gif)

:-)

This is already done for the second level of data onwards; yours is just a particularly nasty one here because of the large, flat property list.

**Comment by rsuter** [comment]
I also would like to see some hierarchical display of JSON data (not inline). I use Serilog.Exceptions to log the exception details and to read the details I have to download and format the JSON with Notepad++. In Seq this looks like this one: 

![image](https://cloud.githubusercontent.com/assets/2603405/20455952/982d6b48-ae68-11e6-8671-bda5aa5fe888.png)

It would be cool to have somethink like this: 

![image](https://cloud.githubusercontent.com/assets/2603405/20455957/b20d0f32-ae68-11e6-83cb-3e4c4141c249.png)

**Comment by nblumhardt** [comment]
We've made the tough decision to close this. We do definitely want to make an improvement here, but it hinges on a UI refresh that we're not yet ready to schedule, and so this is cluttering up the issue tracker. Not forgotten, though! Thanks all for the input :-)

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/59007004-f9795c00-8867-11e9-96d5-75529ea3c1d9.png)

Taking another look; attempting a basic implementation of this in the next patch.

**Comment by nblumhardt** [comment]
![Expander](https://user-images.githubusercontent.com/342712/59008611-5bd55b00-886e-11e9-9aca-eb26fb4086a3.gif)

**Comment by mraming** [comment]
Nick,
Awsome - I think this is a good approach that addresses the need effectively.

**Comment by nblumhardt** [comment]
Thanks @mraming 👍

**Comment by nblumhardt** [comment]
This has shipped in 5.1.3118

**Comment by mraming** [comment]
@nblumhardt : Brilliant - simple and effective. Works as expected and addresses the issue completely. Well done :-)

**Comment by taspeotis** [comment]
This seems like a good place to support quickly including/excluding events based on structured properties. It's always bugged me I can't quickly filter to a `Client.ClientId` from the ✔️❌ buttons but I can quickly filter a literal `ClientId` property. I'm being penalised for structured logging!

![image](https://user-images.githubusercontent.com/1189399/59407440-8e460180-8df4-11e9-9abf-c592361ea856.png)

The result being the corresponding `Client.ClientId = 1` or `Client.DatabaseGuid = ...`.

If I'm the last Seq user in the world who hasn't discovered how to do this in a current version of Seq ... please send me the memo :)

**Comment by nblumhardt** [comment]
Hey @taspeotis :-) ... we've been talking about this; there are a few small twists around how we handle array elements (`[?]` or `[n]`) and also a concern that the interface will get a bit crazy when a lot of fields are present, but nothing insurmountable.

Showing tick/cross only on hover would be natural for desktop use, but it translates poorly to mobile/touch, so we'll put some more thought into that.
