### ISSUE TITLE
Open in new window

### ISSUE THREAD

**Issue by hayian** [datalust/seq-tickets#431]
When looking through a list we'll often want to dive deeper into a httprequestid to see specifics on that request, so we'll usually open a new window, and then copy and paste the requestid into the search box to look further into that.  It'd be nice to be able to click on the parameter, then right click on find and open in new tab, or at least something that achieves the same without losing the list you're currently looking through.

**Comment by andymac4182** [comment]
It would be great if middle click worked on the current menu options. I use that on websites all the time and forget that Seq doesn't work nicely with it.

**Comment by nblumhardt** [comment]
Thanks for the feedback, will take a look at this one :+1:
