### ISSUE TITLE
Ability to select timezone in GUI

### ISSUE THREAD

**Issue by dunkymole** [datalust/seq-tickets#432]
We have an international team on different timezones. Furthermore we store datetimes in the DB as UTC. It would be great to be able to switch the timezone of the timestamp labels on the fly.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, sounds like a good idea.

**Comment by nblumhardt** [comment]
#399 adds UTC as an option, which may help a little here.

**Comment by nblumhardt** [comment]
Now that UTC as well as local timezones are supported, we suspect we're covering the majority of scenarios here.

**Comment by HakanL** [comment]
I know this is several years old. To display the UTC timestamp is good, but I'm also working on international teams where users may report an issue happening at X hour at their local time. It would be super nice to be able to select what timezone all datetimes should be displayed in (User's browser, UTC, any given time zone), and it should be both for the display of events, and the date/time range.

**Comment by nblumhardt** [comment]
While it's unlikely to make it into a near-future version, it's good to have your feedback @HakanL - still a chance we'll consider this down the track 👍

**Comment by HakanL** [comment]
@nblumhardt Is there a separate request/issue open somewhere that can be used to track the feature request to be able to select time zone for the display? I run into this issue weekly, users in a different timezone from myself report issue happening at X hour, their time, and I have to manually re-calculate the offset to find the events in seq. More often they will send me a log file from their PC client, with local timestamps, and I need to correlate to data in SEQ, so the timezone offset calculation has to be done many times over. If I could just select what timezone to display in SEQ then it would make it so much easier to do this task.

**Comment by nblumhardt** [comment]
Hi @HakanL. There's no tracking ticket for this one currently - TBH I'm not sure whether it'll make it sufficiently high on the backlog, given it's not a huge number of clicks to switch desktop time zones on most client OSes. Does that work for you as a workaround?

**Comment by HakanL** [comment]
Ok, hmm, everything else I do is on the local timezone, it's just when troubleshooting for this client who is in Europe that it would make things a lot more efficient if I could choose the timezone in SEQ since their servers and clients are all in that timezone. Could we at least have a backlog entry for it, maybe one day? :)

**Comment by nblumhardt** [comment]
Thanks for your reply @HakanL.

Another option might be to use a browser extension for the time zone change: https://chromewebstore.google.com/detail/change-timezone-for-googl/cejckpjfigehbeecbbfhangbknpidcnh

We tend to limit our issue list to things we're actively pursuing, but we welcome +1s/comments on closed issues like this one and we do review possible improvements periodically.

Opening a fresh ticket for it will likely only cause it to be closed in the next round of triage, but having the discussion here is still useful for tracking.

**Comment by HakanL** [comment]
Thanks for the extension @nblumhardt, that is a pretty good workaround. Ok, fair enough, I won't open another issue ;)
