### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#440]
Over time, teams using Seq often work on multiple applications and components. These are often worked on by different groups of people and evolve at different rates.

_Projects_ will allow a set of signals, events (via an attached property) and API keys to be collected together.

This will also provide a simpler interface to filter-based security by allowing users to be granted permission to projects instead of via the raw filter.

**Comment by nblumhardt** [comment]
Status update: we want to make the completed work like saved SQL queries and a vastly improved filter editor that are already completed in 3.3 available to everyone sooner, so, we're splitting this feature out into a new 3.4 milestone and will continue work on it there. I'll post some more details on how Projects will function once the 3.3 release ships.

**Comment by ShaneCourtrille** [comment]
Any update on this?

**Comment by nblumhardt** [comment]
Hi @ShaneCourtrille, thanks for getting in touch.

This ticket has stalled a little as there are still some unresolved implementation questions.

Just to add some data here - is there a particular dimension (signals, users, api keys, etc.) that this is particularly applicable to in your installation?

Thanks!

**Comment by lonevvolf** [comment]
@nblumhardt sorry to hear that the feature has stalled.  We are also very interested in this feature, as we work with Seq across multiple teams.  I submitted some basic feedback related to the feature here:
https://seq.uservoice.com/forums/268188-general/suggestions/16301389-allow-more-granular-permissions

I would also be happy to give you some thoughts on how the feature can be useful, if I can get an idea as to what types of questions are unresolved?  The basic concept for us revolves around the idea of having separate teams, working on separate projects, deployed to different environments (QAT, Prod, etc.) all using the same Seq installation.  We would basically like to see a full partitioning of the interface for each Team.  This would mean separate user team membership management, separate admins per Team, separate lists of API keys per Project, and an automatically filtered events view based on Team membership of the current user.

For reference, we use exactly this type of structure in Octopus, and it seems to work very well.  Please feel free to let me know if you would like any more feedback on the feature - I am very chatty and opinionated.  :smile:

**Comment by tsimbalar** [comment]
@lonevvolf in order to really split everything (UI, users etc), isn't it easier to just set up several named instances (or even different servers) ? In our case, we have one server for all the "development-ish" kinds of environment (QA / "labs" etc) , and one "production-ish" server with several named instances (staging / prod) ... that does work pretty well, even though that means consuming a license per instance (and also that the app config files are aware of the seq instance to use depending on the environment)...

**Comment by lonevvolf** [comment]
In fact, we are doing exactly this, mostly for performance reasons. There's a few problems here though:
1. As you mention, licensing cost. Not a neglible factor
2. Configuration is more complex, but this is not a problem for us
3. It doesn't solve the main problem, which is partitioning of the UI/data for teams. Unless you set up 1 server per team, which is simply silly and would be an exorbitant cost

**Comment by tsimbalar** [comment]
@lonevvolf "1 server per team" : yes that's what I was implying ... indeed, that is the ultimate level of isolation, but probably overkill  (and overprice) :P

Just for "inspiration", to steal the good ideas (but not the bad ones :P), there are 2 products that I know of that have this kind of concept : 
- **Team Foundation Server** has *Team Projects* (stored in a *Team Project Collection* ... you can have several *Team Project Collections*. *Projects* from different collections are very isolated from each other)
- **RabbitMQ** has *virtual hosts* : i.e. "logical" segmentation / container for queues , and while the users are defined globally, their permissions are attributed per *virtual hosts* (but admin roles can have permissions that span several *virtual hosts*) . RabbitMQ comes with one *virtual* host by default (named `/`).

My experience with those products tells me : 
- I liked the "url"/"hierarchy"-like naming convention from RabbitMQ that says `/` is the default , and other virtual hosts have names like `/foo` or `/baz/qux` . This introduces a natural hierarchy, and translates rather well to the *uris* exposed by the "Rest-ish" APIs
- In RabbitMQ Management UI, exposing the list of *virtual hosts* so you can change "scope" at any time is quite convenient to efficiently switch from a global view to more "project-specific" views
- in TFS, permissions have a notion of scope , and I found it confusing (some permissions are project collection-level, others are project-level, other are repo-level etc)
- permission inheritance from one level to a lower level is a bit confusing and probably overkill most of the time

**Comment by nblumhardt** [comment]
Thanks for all the input. The discussion of named instances pretty much hits the nail on the head - on many levels, they're already a better "projects" feature than my first cut design of this. In particular, instances make projects independent of each other in the event store, so for example, queries and retention policies within the context of an instance only need to deal with the events belonging to that instance.

It's probably worth adding - the Seq licensing is per _machine_, so it's possible to create many instances (`/`, `/dev`, `/test`, `/test/staging`) on a single server using the one Seq license.

Of course, separating projects into distinct instances means that queries can't span more than one project, which makes it harder for people with cross-cutting roles to work across many projects at once. Managing multiple instances is also currently harder than managing a single Seq instance.

The feature here is still a worthwhile one for us to pursue, sorry about the lack of clarity around the timeline. I don't think we'll hold up the 3.4 release for it, but I'll try to get a bit more transparency around progress into this thread.

**Comment by tsimbalar** [comment]
> It's probably worth adding - the Seq licensing is per machine, so it's possible to create many instances (/, /dev, /test, /test/staging) on a single server using the one Seq license.

Oh ! I had totally missed that !

**Comment by lonevvolf** [comment]
@nblumhardt Thanks for the great feedback.  I hope that this feature doesn't get left behind as you move forward.  One of the main purposes of our using Seq is to make dealing with our growing infrastructure easier, and as you can imagine, adding new instances flies in the face of that.  I really hope this feature gets a good implementation!

**Comment by clockwisemusic** [comment]
I would love this feature too.

**Comment by nblumhardt** [comment]
We're investigating this _yet again_ in the final Seq 5 release planning. Our current thinking is that there are really still two features here:

 1. A way to organize large numbers of items in heavily-used servers, and
 1. A security/permissions boundary that maps to team/role structures

The solution to (2) looks to us a lot like today's "instances", but there are obviously opportunities to improve the UX and administration of them. We're still not sure when/how to land this, and will probably push this out, yet again, to a future release.

For (1), we've put together a proposal to introduce [Labels](https://github.com/datalust/seq-tickets/pull/717) as an organizing concept, particularly for dashboards and the signal bar. This is the chunk we expect to land in Seq 5.

It's submitted to this repository as a PR: thoughts/comments/corrections/suggestions would be wonderful, if anyone following this thread has a chance to check it out. Thanks!

**Comment by nblumhardt** [comment]
Hi again, folks-

We've thought long and hard about this ticket, and decided that for the immediate future, instances will remain the best abstraction for isolating groups of users in Seq. 

We think that shifting the discussion away from "projects", and towards how we can better isolate, manage, and synchronize multiple Seq instances, will yield the best results.

Many of our misgivings about the approach laid out in this ticket stem from the idea of basing permissions on attached event properties. Though we do support this in a basic way with user view filters, doesn't seem like the best long-term model for strong security (event contents are intended and designed to be user-controlled). The overheads of any other per-event permissions model seem unappealing to make a permanent bet on.

Diagnostic analysis also usually draws on data from multiple "projects"; permissions are more often organization-unit-boundary-based; this maps better to the features of "instances", since, for example, errors from many "projects" will often find their way to a single team/department Slack channel. We want to make sure any permissions boundaries in Seq still allow for bigger-picture scenarios.

The next steps forward from here are to identify how we can make instance management better - we've already got a lot of ideas that will feed into our next round of release planning post-Seq 5.

Thanks for all the input!
