### ISSUE TITLE
Quick "Create query" functionality in place of "Move to signal" when editing

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-tickets#528]
When writing a SQL query in the filter field, the "double arrow" is always greayed out. How am I supposed to add a SQL query in the "saved queries", under the list of signals ? 

![image](https://cloud.githubusercontent.com/assets/160544/21882177/954c9816-d8a9-11e6-828c-ccedaa05032c.png)

*As of Seq v3.4.18 in Firefox v50.1.0*

**Comment by nblumhardt** [comment]
Thanks for the post. Not as intuitive as I would like, but clicking the `(+)` icon next to `QUERIES` will do this (just click Add on the dialog).

We should change this so that the >> button becomes a "save" button or similar when an SQL query is active.

**Comment by nblumhardt** [comment]
The new `(+)` "add query" button improves the UX a little, here. While we'll keep this one in mind, we think it's unlikely to make the cut for the next few releases and so we'll close it for now. Thanks @tsimbalar !
