### ISSUE TITLE
OpenID Connect Authentication Support

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#552]
Via: http://docs.getseq.net/v3/discuss/58f41da514ce490f0015618c

**Comment by nblumhardt** [comment]
Removing this from the v5 milestone due to time constraints, but this is still high on our list.

**Comment by nblumhardt** [comment]
We have a working implementation now of OpenID Connect, to preview in our next update 🎉 

We've been testing against Auth0; it would be great if those following this ticket can let us know the providers they're currently using, so that we can aim to widen our testing a bit 🙏 

Cheers! :-)

**Comment by amaechler** [comment]
That's great news! We use Auth0 as well :) our main identity provider Auth0 is connecting to is Azure AD.

**Comment by nblumhardt** [comment]
Thanks @amaechler :+1:

**Comment by 0x15e** [comment]
Awesome! We're using Okta over here. https://developer.okta.com/docs/reference/api/oidc/

**Comment by nblumhardt** [comment]
Thanks @0x15e 👍

**Comment by DominikPf** [comment]
We ware using IdentityServer4. If Auth0 works IdentityServer should also work 👍 
Thanks for this @nblumhardt i can't wait to move to oidc signin :)

**Comment by nblumhardt** [comment]
Thanks @DominikPf and everyone who chimed in 👍 

We've just pushed build 2020.1.4018-pre to https://datalust.co/download and `datalust/seq:preview` on Docker Hub, with this feature included 🎉 

Some basic documentation, showing setup with Auth0 (should be transferrable to other providers) is here:

https://docs.datalust.co/v2020.1/docs/openid-connect

I'm going to close this feature tracking issue so that it doesn't become a long and rambling thread, but, feedback inline here is still very welcome, and if you have questions/suggestions/bug reports, please feel free to open new issues here also.

We're really going all-out to make 2020.1 an awesome release, so nitpicking/bikeshedding is also much appreciated 😄
