### ISSUE TITLE
Make minimizing signals more obvious in UI

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-tickets#585]
**Seq version 4.0.58**

We have about 30 people using one of our production Seq instances right now and I've had 5 of those people ask about minimizing the Signals section on the right.

I've let them know they can click the light blue bar (fortunately no colour blind people have asked yet :P) to the left of the Signals pane to minimize it but it's clearly not obvious enough to users that they can minimize the pane like that.

I'd suggest adding an icon or some other indicator that the pane can be minimized so it's more obvious to new users.

**Comment by nblumhardt** [comment]
Thanks for the feedback and suggestion, Laurence 👍

**Comment by laurencee** [comment]
This would apply to the dashboard page as well for the pane on the left ;)

**Comment by nblumhardt** [comment]
Thanks again for raising this. For now, we're going to close the ticket, although we've taken the feedback on board. Thanks @laurencee !
