### ISSUE TITLE
Charts temporarily render using default style after not being the active tab/window for a while

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-tickets#595]
**Seq version 4.0.58**

Repro:

1. Configure a Seq dashboard to have a non-default style (e.g. red bar graph)
2. Leave a Seq dashboard running in a tab/window that is not currently the active window.
3. Switch back to the Seq dashboard tab after leaving it for a while (not long required, for me it happens within a few minutes)

**Expected**
Dashboard appears as normal and starts to refresh

**Actual**
Dashboard reverts to default style settings until the next refresh, see the following screenshot:

![image](https://user-images.githubusercontent.com/3850553/27937679-2e0d442e-62fc-11e7-8f15-8c9f81920b1a.png)

**Comment by nblumhardt** [comment]
Thanks for writing this up. I should have noted this earlier, I've seen it on my machine, though only very, very rarely. Will see what I can find :+1:

**Comment by nblumhardt** [comment]
Think we have this one fixed 👍
