### ISSUE TITLE
Deploy to Docker/Linux

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#598]
**Edit (2018-02-13):** We're well on our way towards this goal. In addition to Docker/Linux support, we're aiming to support local (e.g. for development) use on macOS.

**Comment by gertjvr** [comment]
If you need any alpha testers let me know. 😉

**Comment by michaelsogos** [comment]
There is a prediction of stable release for a docker image?

**Comment by nblumhardt** [comment]
Hi @michaelsogos, thanks for the note. No, this one's going to be very much a "ready when it's ready" release. We'll try to narrow down dates as we proceed. Right now it looks to be within the next twelve months, but there are still some unknowns to iron out.

**Comment by gjonespf** [comment]
Hey @nblumhardt - can I ask if you're concentrating on a Windows or Linux based docker container first?  I'd think a Windows based one may be simpler to get running, though a Linux one would certainly reach a larger audience.  Definitely keen to see a Linux image longer term.

**Comment by nblumhardt** [comment]
@gjonespf thanks for the note, Gavin. Does https://github.com/serilog/serilog-docker/blob/master/seq/Dockerfile help at all? Cheers!

**Comment by gjonespf** [comment]
@nblumhardt looks awesome, I'd not seen it.  Will have to give it a go.

**Comment by mmisztal1980** [comment]
@nblumhardt I wanted to follow up on this, has there been any progress?

**Comment by nblumhardt** [comment]
Hi @mmisztal1980,

Yes, there's been some incremental progress via #608 - we've completed and will be shipping a new app hosting component in 4.2 that replaces our reliance on .NET `AppDomain`s and can run cross-platform. The aim is to have the rest of 4.2 complete in a few more weeks.

After that, 5.0 will focus on the Docker/Linux story, with cross-plat being a main pillar of the release.

HTH,
Nick

**Comment by mmisztal1980** [comment]
awesome, fingers crossed :)

**Comment by KodrAus** [comment]
We've made some great progress porting Seq to .NET Core! There's still a lot of fundamental work to do. Expect some more details in the coming weeks.

Here's how Seq currently looks on my local OSX environment:

![seq-osx-1](https://user-images.githubusercontent.com/6721458/36132726-8944f410-10c4-11e8-9c24-84f59f4b3362.png)
<img width="1082" alt="seq-osx-2" src="https://user-images.githubusercontent.com/6721458/36132729-959b56dc-10c4-11e8-96e6-5b8b4eb51c2f.png">

**Comment by nblumhardt** [comment]
Aaand... its matching cousin over on Ubuntu 17.10:

![screenshot from 2018-02-13 15-08-50](https://user-images.githubusercontent.com/342712/36134337-e8451aac-10cf-11e8-8ddc-294061fd9905.png)

**Comment by gertjvr** [comment]
Now you just teasing us. Super excited to get my hands on this.

**Comment by mmisztal1980** [comment]
Awesome, can’t wait

**Comment by nblumhardt** [comment]
Hey all! It's an early preview, but you can now give this a try :-)

https://blog.getseq.net/docker-developer-preview-1/

Would love to have your feedback/experience reports - any and all suggestions welcome. Cheers!

**Comment by nblumhardt** [comment]
Since datalust/seq is now on Docker hub, we'll track progress through find-grained tickets from now through to release.
