### ISSUE TITLE
Occasional "LMDB extent is read-only" errors in log

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#599]
Occasionally I'm observing the following error in the ingestion log while writing to the new LMDB-based storage.

```
Flare.FlareException: The LMDB extent 2017-07-12T00:00:00.0000000Z is temporarily read-only.
```

This will correlate either with retention processing or with compaction. As long as the client re-tries this shouldn't have serious impact, but we'll need to mitigate server-side rather than rely on the client, of course.

**Comment by andymac4182** [comment]
Is this something that should stop use in production?

**Comment by nblumhardt** [comment]
Thanks for the note. Using the Serilog sink, it should be fine - the cases I've collected of it all succeeded on a retry. It could be problematic for senders that don't retry on failure.

Though - I've dug a bit deeper and now think the problem is just a lock acquisition timeout that's too short to cover a slow write/sync. If that theory holds up, the patch will be quick and low-risk (literally just a timeout change), so should be on the downloads page early in the week. I'll update this ticket as soon as I've got some more info.

**Comment by nblumhardt** [comment]
4.1.16 is up now, with an expanded write timeout. I had thought 5 seconds to acquire the write lock on an extent was over-generous, but it appears at least on my slow, HDD-backed Azure Classic VM, once in a while some more time is needed. Extended to **15 whole seconds** - a digital eternity - in the .16 build.

**Comment by nblumhardt** [comment]
This has been reported in 4.1.17 also - more investigation required.

**Comment by nblumhardt** [comment]
We're rolling up further storage engine work into 5.0, alongside x-plat work. Unfortunately for this one I think it means recommending against high-volume use of LMDB in the 4.x series.

**Comment by nblumhardt** [comment]
The native storage implementation introduced with #694 will replace both ESENT and LMDB, rendering this issue obsolete.
