### ISSUE TITLE
Make auto-refresh start quicker when going back into history

### ISSUE THREAD

**Issue by janpieterz** [datalust/seq-tickets#605]
When there are not a lot of (recent) events, clicking auto-refresh takes a long time because it 'forces' itself to fill a whole page before auto-refreshing.

I run quite often into this quite often when developing or testing something, as most often I look for very specific events and/or new events, where the auto-refresh takes a long time to get started.

I'd propose that auto-refresh, as it's so focused on the new and incoming things, works with loading say the previous 24 hour first, then auto-refreshes anything new.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, I'll take a look at this.

**Comment by nblumhardt** [comment]
This and #643 may be related

**Comment by nblumhardt** [comment]
Thanks again for this suggestion. We're considering it as an improvement we could make in our next major UI refresh, but won't be able to address it standalone, and so we'll close this ticket for now.
