### ISSUE TITLE
Suggestion: Push changes to query to browser history

### ISSUE THREAD

**Issue by janpieterz** [datalust/seq-tickets#614]
Any changes to a filter are pushed to the url (and copy-pastable) but not to the browser's history.

This makes it difficult when tracing paths to sometimes do a couple of steps back.

**Comment by nblumhardt** [comment]
Thanks Jan-Pieter. I've revisited this several times but still agree there's room to improve on the way it works currently.

Originally, Seq did push everything to history, but then clicking back-back-back would kick off several (sometimes many) queries in quick succession, causing a slowdown. The drop-down "recent queries" attached to the search box was implemented as a better-performing alternative.

However, it'd be nice (and equally efficient) if clicking "back" just changed the filter box text, without implicitly kicking off the refresh process. It's a little trick to get right, but I'm keen to explore this further.

**Comment by janpieterz** [comment]
I have to admit I never used the 'recent queries' dropdown! Though the back-navigation-filling of the search box would indeed be nicer, this certainly makes it a lot less necessary, thanks!

**Comment by nblumhardt** [comment]
We're reviewing issues and think that, while we'll improve this down the track, the "recent queries" support makes it unlikely we'll do it through the back button. We're considering richer "diagnostic session" tracking and will definitely be thinking about this in that context.

**Comment by nblumhardt** [comment]
We've done a lot of foundational work in the Seq 2023.4 UI, and can happily report that this is now implemented 🎉

All changes to the date range, search/query, tailing, and selected signals are now pushed onto history and can be reactivated using the back button.

While "back" and "forward" will change the selected signals and content of the filter box, it's necessary to press the "go" (green triangle) button to actually run the search/query after navigation (this prevents wasted resources when pressing "back" a few times in succession).

A new preview with this functionality is available now; we're expecting to ship a final build in the next week or two.
