### ISSUE TITLE
Charts time-scale are not aligned when labels have different names

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-tickets#617]
When put "on top of each other", the charts' timescales are not exactly the same, meaning that a given time is not aligned with the same time in the charts below it.

This is a bit annoying when trying to see correlations between different metrics ... 

![image](https://user-images.githubusercontent.com/160544/30803300-6368fe2a-a1e9-11e7-9de0-b9831ee7c3d7.png)

**Comment by nblumhardt** [comment]
Thanks for the note, yes, this is one I'd like to sort out 👍

**Comment by tsimbalar** [comment]
I just noticed on https://monitor.gitlab.net/dashboard/db/fleet-overview?refresh=5m&orgId=1 that "on hover" on a chart, the current "time point" is also highlighted on the other charts of the dashboard ... 

I thought that was a nice solution to the problem of correlating multiple charts ... plus it also works for charts that are positioned side-by-side...

**Comment by nblumhardt** [comment]
@tsimbalar thanks for the suggestion, sounds like it'd be a good avenue for us to explore.

**Comment by nblumhardt** [comment]
Done via legend suppression; originally duplicated by #730 

![image](https://user-images.githubusercontent.com/342712/46984467-cd6a6880-d128-11e8-8e1d-751dcafa1ff1.png)
