### ISSUE TITLE
Rowset-valued charts on dashboard

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#628]
I.e. show a tabular result computed over the whole dashboard range.

From #565

**Comment by nblumhardt** [comment]
We've decided to drop this out of 4.2 for now, and reconsider in the 5.0 milestone. The level of effort looks like it will be higher than we initially expected.

**Comment by nblumhardt** [comment]
Triaged - still interested in this, but doesn't appear to make the cut for a near-future release.

**Comment by andymac4182** [comment]
I have a few cases where this would be super helpful. Happy to provide the use cases if that might help.

**Comment by nblumhardt** [comment]
Any and all info appreciated, @andymac4182 - still something we'd love to squeeze in at some point :+1:

**Comment by nblumhardt** [comment]
I will leave this open on the dashboarding enhancements #565 ticket.

**Comment by nblumhardt** [comment]
Reopening; scheduled for 5.1

**Comment by nblumhardt** [comment]
Coming in the next preview 🎉
