### ISSUE TITLE
Pie charts on dashboard

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#629]
Also computed over the whole range.

From #565

**Comment by KodrAus** [comment]
Pie charts are now supported on dashboards as another way to visualise your event stream.

<img width="1251" alt="pies" src="https://user-images.githubusercontent.com/6721458/33865100-e4abbab0-df3b-11e7-8822-b2f85496265f.PNG">

# Creating a pie chart

Pie charts can be created manually on a dashboard like other charts, and need to have a single `group by` clause in the query:

![create-pie](https://user-images.githubusercontent.com/6721458/33865097-df33da72-df3b-11e7-95c1-49c28cdecfbf.gif)

More details to come as we continue integrate pie charts into the events screen!

**Comment by nblumhardt** [comment]
4.2.305-pre is up with some work-in-progress to try out 🎉 

@KodrAus guessing its on your list, but thought I might as well leave a note 😄; just noticed that the top margin of the pie is a bit tight for the labels at small sizes:

![image](https://user-images.githubusercontent.com/342712/33869851-d5e02d7a-df56-11e7-8d9a-53169072f6f9.png)
