### ISSUE TITLE
Show alert thresholds on dashboard charts

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#630]
If an alert has a simple `x > 5` or `y < 10` condition, show this on the dashboard if displayed at the appropriate time resolution.

From #565

**Comment by KodrAus** [comment]
# Visualising alert thresholds

Time-series charts will now show a shaded region representing the threshold for an alert so long as:

- The range for the dashboard is the same as the alert window (so an alert like _count > 50 in 1 hour_ will be visible if the dashboard range is set to _by hour_.)
- The alert condition follows a simple `{label} {operator} {threshold}` format, where `operator` is one of `<`, `>`, `<=`, `>=`
- The alert threshold isn't too much larger than the max value on the chart. This is just to prevent squashing charts if a very high alert value is specified, like _count > 1000_ when _count_ is normally around 10

# Adding and viewing an alert on a chart

![alert-thresholds](https://user-images.githubusercontent.com/6721458/34188862-43ec2c00-e584-11e7-88e4-ea02e3db28f4.gif)

**Comment by nblumhardt** [comment]
👏
