### ISSUE TITLE
Syslog input

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#632]
Related to #598, deployment in *nix environments would be smoother with support for syslog out-of-the-box.

(https://github.com/tetious/SyslogProxy has been available in Windows environments for some time thanks to @tetious.)

**Comment by nblumhardt** [comment]
We should seriously consider GELF in this context, too: https://github.com/datalust/seq-tickets/issues/688

**Comment by nblumhardt** [comment]
We're just putting the finishing touches on the GELF input and will soon loop back around to this.

Because of the amount of variation in syslog implementations, we're curious to know what rsyslog log sources people are using - any scenario info to share? Thanks all!

**Comment by nblumhardt** [comment]
It's looking like we'll ship #794 in lieu of implementing this directly - the two codebases already out there (GELF/Rust and RabbitMQ/C#) would form a good starting point for anyone wanting to push syslog support further in the short term.

**Comment by DNF-SaS** [comment]
Any chance that the GELF-input-plugin will be able to eat syslog too? (actually, it only says "GELF processing failed")

**Comment by nblumhardt** [comment]
Hi @DNF-SaS - no, not at this point (they're somewhat different formats), though it's quite possible we'll use the https://github.com/datalust/sqelf codebase as a starting point for Syslog ingestion. Thanks for the nudge on this!

**Comment by CrossBound** [comment]
I'm also needing the syslog input. Do you think this will be implemented soon? I really don't want to have to write it, but if it's still going to be a while yet I may need to try my hand at writing it myself. 

P.S. Thanks for a great product. We just purchased a team license and I'm loving what Seq gives us so far. I'm excited about the new health check feature and will hopefully be implementing that soon.

**Comment by nblumhardt** [comment]
Thanks for the feedback @CrossBound. We're planning our next milestone currently, and this one's high on the list.

All - do you have any examples of the syslog messages you'd like to ingest? Unlike GELF, these tend to come as plain text, so extracting structured data from them is trickier. The more scenarios we can examine, the better, if it's possible to send some suggestions our way :-) - Thanks!

**Comment by pcoombe** [comment]
this has just come back on my radar.
my plan will be to send rabbitmq logs into seq
https://www.rabbitmq.com/logging.html#logging-to-syslog

**Comment by thomas-frantz** [comment]
This would be quite useful for me as well. My use-case would be logging (among other things) syslog messages from security appliances (specifically, Meraki security appliances.)

**Comment by nblumhardt** [comment]
@DNF-SaS @CrossBound @pcoombe @thomas-frantz - Hi all!

We've started working on a native syslog input for Seq; if anyone's still interested in this, we have a few questions:

 * Which protocol versions are most important to you - RFC 5424, 5425 (TLS), 3164?
 * Which transports - TCP or UDP?
 * Do you have any sample packets/syslog messages (without identifying data) that you can share?

Thanks in advance :-)

**Comment by CrossBound** [comment]
I'm definitely still interested. Because of the sensitive nature of these logs I'm not sure I can share but let me see if I can find some that I can post.

Thanks

**Comment by CrossBound** [comment]
I'll also find the answer to your other questions in regard to our scenario

**Comment by nblumhardt** [comment]
Thanks, David!

**Comment by DNF-SaS** [comment]
> * Which protocol versions are most important to you - RFC 5424, 5425 (TLS), 3164?
> 
> * Which transports - TCP or UDP?
> 
> * Do you have any sample packets/syslog messages (without identifying data) that you can share?

I think it's important to support the most basic constellation (RFC 5424 UDP) first.

**Comment by nblumhardt** [comment]
Thanks @DNF-SaS! _Seq.Input.Syslog_ (now on NuGet) and `datalust/squiflog` (Docker Hub) support RFC 5424/UDP, would be great to hear if those work for you.

**Comment by pcoombe** [comment]
Looks good with RabbitMQ
![image](https://user-images.githubusercontent.com/15317948/78310280-276b2200-7599-11ea-97e5-8063383f5b25.png)

**Comment by DNF-SaS** [comment]
> 
> 
> Thanks @DNF-SaS! _Seq.Input.Syslog_ (now on NuGet) and `datalust/squiflog` (Docker Hub) support RFC 5424/UDP, would be great to hear if those work for you.

Looks fine so far. :-)
Is it possible to filter syslog messages using a signal? (maybe add a property "Syslog-Sender" with the IP-Address of the host who sent the message)

**Comment by jhf** [comment]
We are using HAProxy, that can log directly to syslog, but has a custom compact http message format.
The ideal situation would be to support decoding those messages directly, but that's quite possibly beyond the scope of a simple syslog parser. 
The format is documented here https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#8.2.3
For Greylog there is for instance plugin/extension https://marketplace.graylog.org/addons/555e70b7-dcd3-403d-bca5-6fa50bfef3cc that opens a custom port that parses those messages.
Another, and maybe better option, would be to use the standard port and allow custom filtering based on app name, such that one could match `haproxy` with the `haproxy-standard-http-log` and then haproxy could use UDP (to avoid stalling when logging) to report directly to Seq, and one could immediately graph the data, with nice labels, and an efficient(compact) transport from HAproxy to Seq.

-- 
 Jørgen Hermanrud Fjeld
 jorgen@veridit.no

**Comment by larenelg** [comment]
> Looks fine so far. :-)
> Is it possible to filter syslog messages using a signal? (maybe add a property "Syslog-Sender" with the IP-Address of the host who sent the message)

Hi @DNF-SaS thanks for your question, :)

If your Syslog format is RFC 5424, `hostname` is one of the properties you can currently filter on. For example, if your system sends a log like:

```
<165>1 2003-08-24T05:14:15.000003-07:00 192.0.2.1 myproc 8710 - - %% It's time to make the do-nuts.\n
```

You can search in Seq with `hostname = '192.0.2.1'`, and [create a signal](https://docs.datalust.co/docs/signals) from that.

![a screenshot demonstrating the example described above](https://user-images.githubusercontent.com/7476736/78527345-f2243580-781f-11ea-8dcc-4039c7b4c9c1.png)

I hope that helps?

**Comment by larenelg** [comment]
> Another, and maybe better option, would be to use the standard port and allow custom filtering based on app name, such that one could match `haproxy` with the `haproxy-standard-http-log` and then haproxy could use UDP (to avoid stalling when logging) to report directly to Seq, and one could immediately graph the data, with nice labels, and an efficient(compact) transport from HAproxy to Seq.

Hi @jhf, thanks for the feedback! HAProxy `httplog` is an interesting format. We're deep in feature development for our next big release, so sadly won't have time in the very near future to look at supporting `http` format and other widely used formats, but [I've created a ticket on the _Seq.Input.Syslog_ GitHub repo](https://github.com/datalust/squiflog/issues/24) to keep track of your suggestion, and in case anyone in the community might have time to get to it before we do 😄 

On a side note - I've tried parsing one of the examples from https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#8.2.3 using `Seq.Input.Syslog` (pictured) it does not seem to follow Syslog RFC 5424 format (I assumed the httplog might be the in the `message` component of a syslog) - may I ask if the example representative of what you receive from HAProxy? Many thanks!
![image](https://user-images.githubusercontent.com/7476736/78529223-809ab600-7824-11ea-81fa-0335ec5c7eee.png)

**Comment by larenelg** [comment]
[Seq.Input.Syslog](https://www.nuget.org/packages/Seq.Input.Syslog/) is now available! You can find out how to install it by checking out the [readme](https://github.com/datalust/squiflog/blob/dev/README.md).

If there are any further issues, feedback, or suggestions, we'd be more than happy to hear them at https://github.com/datalust/squiflog/issues

Happy logging 😁

**Comment by jhf** [comment]
> On a side note - I've tried parsing one of the examples from https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#8.2.3 using `Seq.Input.Syslog` (pictured) it does not seem to follow Syslog RFC 5424 format (I assumed the httplog might be the in the `message` component of a syslog) - may I ask if the example representative of what you receive from HAProxy? Many thanks!

It turns out that HAProxy uses the RFC3164 syslog message format by default, but it can just be changed to `rfc5424` with a simple configuration change.

Relevant excerpt from `/etc/haproxy/haproxy.conf`:
```
global
        log /dev/log format rfc5424 local0
```
