### ISSUE TITLE
Add `DATEPART` to expression language

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#639]
Would allow for queries like "only events on weekdays".

Via: https://twitter.com/firstdrafthell/status/940465106021965824

**Comment by chessels** [comment]
What about other date parts, like _year_, _month_, _week_, etc?

**Comment by nblumhardt** [comment]
Thanks for the suggestion @chessels, yes, these seem reasonable to consider under this ticket :+1:

**Comment by skovsende** [comment]
Any progress on this?

**Comment by nblumhardt** [comment]
Still on the radar, but no progress yet - thanks for the nudge @skovsende :+1:

**Comment by CrossBound** [comment]
I am looking for a way to say something simple like '@Timestamp >= Today()' which would give me any events occurring at or after 00:00 UTC today. Is there a way to do this currently or is this ticket the solution to that as well? I know there is a Now() function and I could do Now() - 24h but I'm looking for more of a "today" functionality than a rolling 24 hours.

**Comment by nblumhardt** [comment]
Hi @CrossBound - I think this should work, though it's a little hacky:

```sql
@Timestamp > Now() - TimeOfDay(Now(), -7)
```

where `-7` is your time zone offset, in hours. Let me know if this helps!

**Comment by CrossBound** [comment]
Is there currently any functions that return the current timezone offset? If not that makes these type of queries difficult because you have to change them every time we go through daylight savings time change.

**Comment by nblumhardt** [comment]
Unfortunately, no - I think the major stumbling block is that the offset depends on the client, not the server. We might be able to do something like `OffsetOf('PST')` 🤔
