### ISSUE TITLE
Enable easy copy of property values from Seq web page

### ISSUE THREAD

**Issue by jimmcslim** [datalust/seq-tickets#644]
I occasionally find myself copying a stack trace from the StackTrace child property of an ExceptionDetail property of an event. This is a little tedious, dragging the whole stack trace and then copying to clipboard.

It would be good if there was a right-click context menu on property names in events that enabled copy to clipboard via clipboard.js or some similar non-Flash clipboard functionality.

**Comment by nblumhardt** [comment]
We're looking into this again - we may tackle it in the future but for now we think it's unlikely to make the cut for the next few releases and so we'll declutter the issue tracker and close it. Thanks @jimmcslim !
