### ISSUE TITLE
Allow filtering on a global level 

### ISSUE THREAD

**Issue by janpieterz** [datalust/seq-tickets#651]
Instead of inbound filtering per API key I sometimes have the 'need' to have a global filter.
For example we run into some issues with local file logging not having debug logging for Microsoft.X or NServiceBus.X but don't want this clogging our Seq instance with a lot of 'useless' logs.

Easy to create a signal for too of course, but for instances where support employees also use it, it can become a bit annoying to explain (plus, I forget it myself a lot too).

It'd be great if, besides having API key filters, it could have a top level filter.

This would be easier to maintain from Seq than to have to change all services to do start including them. In case we have issues we'd like to get more in depth logs for it's an easy thing to change and get them right away.

**Comment by andymac4182** [comment]
If you are using Serilog you could probably look at using a Sublogger (https://github.com/serilog/serilog/wiki/Configuration-Basics#sub-loggers) that goes to Seq that includes a level switch to prevent the logs arriving in Seq but leave the file logger at the main part to get all logs. 

Would that accomplish what you are looking for?

**Comment by janpieterz** [comment]
Partially. I played around with that but got mixed results, somehow other debug logging also being filtered out. Relevant Serilog config I used, that didn't work for us:
```c#
.WriteTo.Logger(
                    lc =>
                        lc
                            .Filter.ByExcluding(@event =>
                                @event.Level < LogEventLevel.Warning &&
                                Matching.FromSource("NServiceBus").Invoke(@event))
                            .Filter.ByExcluding(@event =>
                                @event.Level < LogEventLevel.Warning &&
                                Matching.FromSource("Microsoft").Invoke(@event))
                            .Filter.ByExcluding(@event =>
                                @event.Level < LogEventLevel.Warning &&
                                Matching.FromSource("System").Invoke(@event))
                            .WriteTo.Seq(seqEndpoint, LogEventLevel.Debug, apiKey: seqKey, compact: true)
                )
```
It'd still be preferable to have a main Seq filter though, as it's much easier when things break to switch a filter off in Seq than to redeploy all services, just because we'd like to start capturing debug logging.

**Comment by andymac4182** [comment]
@janpieterz I was thinking of using DynamicLog level https://github.com/serilog/serilog-sinks-seq#dynamic-log-level-control

That would give you dynamic for all logs except for the 3 sources that have their level set statically. Is this what you are looking for?

```
var levelSwitch = new LoggingLevelSwitch(LogEventLevel.Verbose);
```

```
.MinimumLevel.Override("NServiceBus", LogEventLevel.Warning)
.MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
.MinimumLevel.Override("System", LogEventLevel.Warning)
.MinimumLevel.ControlledBy(levelSwitch)
.WriteTo.Seq(seqEndpoint, LogEventLevel.Debug, apiKey: seqKey, compact: true, controlLevelSwitch: levelSwitch)
```

**Comment by janpieterz** [comment]
Not totally, I never switch the level. Good to know about it though, might look for more verbose logging statements and switch them from Seq :)

It's exactly those minimum level override's I'd like to cancel though, but also for example certain request paths. We have a heartbeat path I now filter out per API key (all the same). This generally stays off except when doing big deployments or something goes wrong, much like the minimum level overrides.

**Comment by andymac4182** [comment]
Ahh right. Yeah our company has internally talked about how it would be great if you could have multiple logging level switches from Seq that controlled those minimum levels. Even 2 would probably be enough. A global one and auxiliary one for those other overrides.

**Comment by tsimbalar** [comment]
There would probably be a way to accomplish that using `LoggingFilterSwitch` as well I believe (see the last paragraphs in https://nblumhardt.com/2017/10/logging-filter-switch/ )

**Comment by nblumhardt** [comment]
Thanks for all of the suggestions; this one might take a while to digest - I think I have a grasp of what's needed here, but need to give it some more thought 👍

**Comment by nblumhardt** [comment]
We've just run through this and decided that while it's an interesting scenario, it's not likely to be broad enough to make the cut for 5.x and so we'll close it for now. Additional comments/thoughts/discussion most welcome, though - and thanks again for all the input!
