### ISSUE TITLE
Specify time ranges for alerts

### ISSUE THREAD

**Issue by skovsende** [datalust/seq-tickets#654]
I would like to be able a time range for an alert so I can control that my alert doesn't trigger during the weekend when we run maintenance jobs. It should be possible to specify a time range, or series of time ranges throughout the day, and possibly a time range in a week. Not exactly sure how a nice UI would look like for this though.

**Comment by nblumhardt** [comment]
Thanks for the suggestion :+1:

**Comment by laeaton2001** [comment]
I'd like to see this feature as well.

**Comment by burnbay** [comment]
Would be a very nice feature. I've made a SMS Seq App that has similar functionality:
![image](https://user-images.githubusercontent.com/2721929/36499526-d2048b24-1741-11e8-846e-98ff0e1e125e.png)
On the screenshot, the property "Delivery time" indicates that SMS messages should not be delivered after the time specified. I guess a similar UI could be made for alerts, but with a little bit more advanced functionality (choose days, time slot etc.)

**Comment by nblumhardt** [comment]
Nice app, @burnbay!

Is the timed delivery implemented in the app itself, or by the external SMS gateway?

**Comment by burnbay** [comment]
@nblumhardt Lucky for me it's in the SMS gateway

**Comment by nblumhardt** [comment]
We've been discussing this and think that while it's a great feature, it's unlikely we'll address it in 5.x.

We did come up with a possible workaround based on #639 - in this model, the alert's "condition" might look like:

```sql
# Don't alert on Sundays
count > 5 and DayOfWeek(Now(), 10) <> 0
```

Thoughts/pros/cons?

**Comment by laeaton2001** [comment]
That would work fine for my purpose, as mentioned in the other ticket an implementation of C# datepart would be preferred (at least by me) to allow for more flexible filtering than just the day of the week.

**Comment by skovsende** [comment]
That should be fine for now.

**Comment by nblumhardt** [comment]
Great, thank you for the feedback 👍

**Comment by Scotty79** [comment]
DayOfWeek implementation would be a huge win for our company. We need to be able to monitor when our systems which only run on certain days of the week and at certain times do not start as they should. Hopefully this feature is still in the backlog?

**Comment by nblumhardt** [comment]
Thanks for the feedback, all - we're going to roll this into #639

**Comment by nblumhardt** [comment]
This will ship in 2021.2 :tada: - just added a few notes here: https://github.com/datalust/seq-tickets/discussions/1108#discussioncomment-486418

```sql
# Don't alert on Sundays
count > 5 and datepart(now(), 'weekday', offsetin('Australia/Brisbane', now())) <> 0
```
