### ISSUE TITLE
4.2.476 download blocked - Virus Detected

### ISSUE THREAD

**Issue by gregpakes** [datalust/seq-tickets#655]
I'm assuming this is a false positive, but when i download 4.2.476 in Chrome, I get the following error:

> Failed - Virus detected

![image](https://user-images.githubusercontent.com/102243/35247246-cc084b4c-001d-11e8-88b5-bc17bc0ccfc7.png)

I am using Sophos, but I don't think it is sophos detecting this.  When I load Sophos it doesn't seem to have any knowledge of the blocked file.

**Comment by nblumhardt** [comment]
Thanks for the heads-up, @gregpakes. My guess is that this will somehow be shelling out to Sophos, since we have a large number of customers downloading via Chrome (and use it a lot ourselves).

The MSI is signed, so Windows should detect any tampering on the wire/after the fact.

Is there any way to run Sophos manually on the file and get some output? It would be interesting to know what it thinks the problem is.

Thanks again!

**Comment by gregpakes** [comment]
Hi - I have done this.  I downloaded the MSI in a VM, then copied it to another VM with Sophos installed.  I then scanned the file with Sophos and it detected nothing.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Would you be able to post through the Chrome version you're running?

**Comment by gregpakes** [comment]
Sure - It's an Azure VM, so not sure if that changes anything.

Chrome version is 63.0.3239.132

![image](https://user-images.githubusercontent.com/102243/35248023-abb7e188-0020-11e8-99ad-597c5ef54894.png)

**Comment by gregpakes** [comment]
Further tests:

Another Azure VM (**without sophos installed**): No issue
A non-Azure VM (with Sophos installed): No issue

Pretty unhelpful to be honest!

**Comment by nblumhardt** [comment]
Hmmm, odd! Thanks for the follow-up. Could  be a connectivity problem, e.g. the first VM being unable to call out to check the revocation status of our publisher (code signing) certificate? (Just trying to brainstorm some possibilities.. :-))

**Comment by gregpakes** [comment]
That VM is still exhibiting the issue.  Nevermind.  

I suggest we leave this here so if others have the issue they can find it.

Happy to close the issue.

**Comment by nblumhardt** [comment]
Thanks; it'd be interesting to hear whether it continues, or if you find any clues as to why it's happening - but seems reasonable to close based on the information we currently have.
