### ISSUE TITLE
Underscores are duplicated when adding a query to the dashboard

### ISSUE THREAD

**Issue by nvivo** [datalust/seq-tickets#658]
When adding a search to the dashboard using the button, underscores are duplicated causing the chart to be empty:

![image](https://user-images.githubusercontent.com/202449/35883289-e4688f98-0b6d-11e8-90e8-ef27e2132061.png)

This is generated as:
```
@Message like '%foo__bar%' or @Exception like '%foo__bar%'
```

Using seq 4.2.476

**Comment by nblumhardt** [comment]
Thanks for the bug report, Natan - the `__` doubling is correct (to escape the `_` which would otherwise be interpreted as a wildcard in a `like` expression), but it doesn't seem like the escaping is being processed correctly.
