### ISSUE TITLE
"Open in new tab" support for chart points

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-tickets#659]
Heya,

I have found myself quite a number of times attempting (unconciously) to middle mouse click bars/points on charts so I could open multiple different sets of log entries at the same time. This seems like it would be generally useful enhancement to the charts.

Thoughts?

**Comment by nblumhardt** [comment]
:+1: definitely - Ctrl-Click/middle-click support throughout the UI is something we'd like to improve.

**Comment by nblumhardt** [comment]
We'll consider this in #431 - thanks!
