### ISSUE TITLE
Problem with groups

### ISSUE THREAD

**Issue by martinbu** [datalust/seq-tickets#662]
Manually defined signal groups are not created.

To reproduce the Problem:
Save a Signal (TestSignal) and specify the group name manually with the name 'TestGroup'.

**Expected:**
None
TestGroup
    -- TestSignal

**But the  result is:**
None
TestSignal

But, if a signal group is created automatically it works. Also all signals with a manually defined group name which is equal to the automatically created group name are grouped afterwards.

It would also be great if a signal could be added to multiple groups.

I have version 4.2.605 installed.

**Comment by nblumhardt** [comment]
Hi Martin, thanks for the report.

Signals are only shown in groups when there are two or more signals in the group - if the signal is the only member of the group, the group heading won't display.

Could that be the cause here? Thanks!

**Comment by martinbu** [comment]
Hi Nicholas,

your are completely right.  Thanks for this information! It would be great if you could add this hint to the documentation.

Thank you very much.
