### ISSUE TITLE
Content-Type header fails CORS preflight after upgrade to 4.2.605

### ISSUE THREAD

**Issue by Wedvich** [datalust/seq-tickets#664]
After upgrading to 4.2.605, we seem to have issues with the `content-type` header. All requests to the ingestion endpoint now fail the CORS preflight when the `content-type` header is included with the request. I checked the response headers for the preflight and they DO include `access-control-allow-headers: content-type`, so I'm not sure where this all breaks down. The only change we made before it broke was to upgrade though, and it worked on 4.1.17, so I have nothing else to correlate it to.

We used the `content-type` header to specify that our log events are in the compact format. Removing the header and using the `clef` query parameter instead has it working again, so it's not a critical issue, but it's worth investigating.

**Comment by nblumhardt** [comment]
Thanks for the report and diagnosis, Martin. Looks like a bug 👍 - we'll turn around a fix for this first thing on Monday.
