### ISSUE TITLE
Allow descriptions for alerts

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-tickets#670]
Heya,

This is specific to sending alerts via email or other notification mechanisms.
Since alerts aren't necessarily always being sent to just developers it would be good to be able to provide an english description for what the alert means.

An example of this for us was an alert is configured to go off if no events are detected in a period of time, the alert will come through as `Alert condition count = 0 detected on XXX` but what would be better is if the alert said `No events detected for X, confirm system is running` or something along those lines.

**Comment by nblumhardt** [comment]
Thanks, great suggestion 👍

**Comment by KodrAus** [comment]
Thanks again for the suggestion @laurencee!

In Seq 5 we've added a title field to alerts that's available for apps to render in their notifications:

<img width="932" alt="alert title" src="https://user-images.githubusercontent.com/6721458/44890769-39327680-ad1f-11e8-9a95-30ef0020a4ae.png">

If the title doesn't have a value then we'll generate one that just includes the condition and measurement window.
