### ISSUE TITLE
Installation\upgrade issue with SEQ 4.2.822 - missing patched library

### ISSUE THREAD

**Issue by centur** [datalust/seq-tickets#674]
Hi, I think I found an installation problem. Recently we upgraded our old license for another year.
After that I installed 4.2.822 on top of our installation of 3.4.xsomething. 
That old installation was patched for recently discovered issue (was in private email from SEQ to all license holders). So when new version was installed on top of old-patched version - SEQ can't start out of the box, reporting error with missing reference of that patched library (umm you know which one :) ). I've applied the patch for old version again and then SEQ instance started without any problems. 

Seems that new installer is missing that library somehow.

**Comment by tsimbalar** [comment]
With the issue #636 re-running the installer seemed to fix issues with missing Dlls ... Does that help ?

**Comment by nblumhardt** [comment]
Thanks for the report, @centur. Yes, this is the same kind of issue as #636 - the file version of the hotfix DLL is problematic; re-running the installer will resolve this (thanks @tsimbalar).

I don't think this is one we can go back in time to fix, so I'll close this here, but it should be a good resource for anyone who hits this issue in the future.

**Comment by centur** [comment]
@tsimbalar I fixed it by re-running security patch that was sent in email recently.
@nblumhardt nws, was not sure whether some found reports are relevant (and didn't looked them through in details. Might be easier if datalust will send an info email and let other users know that there is a such pitfall if one is upgrading. 
Strange, though, it can't be fixed in installer itself - why can't it overwrite library with newest bundled version all the time ?

**Comment by nblumhardt** [comment]
Thanks for the follow-up @centur. MSI is unfortunately a bit painful on this - we set the file version of the patch high so that it would not be inadvertently "repaired" back to the original version, but as a consequence upgrades need the extra step. We missed this at the time the patch went out.

It could be worked around in another MSI, but the risk of introducing new problems makes it unappealing to do so right now, as we don't expect it will have a wide impact, and the workaround is straightforward. Sorry about the confusion and thanks again for reaching out.

**Comment by centur** [comment]
Update to this issues - we just discovered that although SEQ was running after that patching - ingestion didn't happened - it was producing these errors in logs:
```
System.InvalidCastException: Unable to cast object of type 'Nancy.IO.RequestStream' to type 'Nancy.Hosting.Self.RawRequestStream'.
  at Seq.Server.Web.Api.RawEventsModule.get_RawInputStream()
  at Seq.Server.Web.Api.RawEventsModule.TryParseRawFormatBody(ApiKey apiKey, StorageEventCreationData[]& events, String& errorMessage)
```

So my solution with patching it via emailed patch, *does not work* properly. Uninstall and reinstall helped the problem. Sorry if the other comment here misguided you.
Lesson learned: if something starts and shows you an UI, doesn't mean it works correctly :\

**Comment by nblumhardt** [comment]
Going to have a shot at working around this by pushing the file version yet further ahead :-)
