### ISSUE TITLE
Support for Kubernetes Ingress

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#676]
When requests are routed to a Seq container through a [Kubernetes Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/), the request URL may not bear any relation to the original URL requested from the browser/originating client.

For example, the user might send a request to `/prod/api/events/raw` while Seq receives a request routed to `/api/events/raw`.

To properly handle this scenario, the Seq container needs to accept a "canonical base URL" that it should use:

 * In the paths to assets that are linked from index.html
 * In generated URLs, i.e. for notifications
 * As a reply URL for Azure AD

and possibly other places.

**Comment by gertjvr** [comment]
[https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/annotations.md#rewrite](kubernetes ingress has the ability to do a rewrite) but as mention the generated links in html and other request has to respect a base path being set.

System like [kibana](https://www.elastic.co/guide/en/kibana/current/settings.html) does it using configuration setting.
> server.basePath:
    Enables you to specify a path to mount Kibana at if you are running behind a proxy. This only affects the URLs generated by Kibana, your proxy is expected to remove the basePath value before forwarding requests to Kibana. This setting cannot end in a slash (/). 

aspnet core allows you to update it using middleware [UsePathBase](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.usepathbaseextensions.usepathbase?view=aspnetcore-2.0)
> var host = new WebHostBuilder()
                    .UsePathBase("/prod")
                    .UseStartup<Startup>()
                    .Build();

**Comment by nblumhardt** [comment]
The image now accepts an `-e BASE_URI` environment variable to support this.
