### ISSUE TITLE
Transfer time range from event to date/time picker

### ISSUE THREAD

**Issue by HakanL** [datalust/seq-tickets#683]
A lot of times I've found an error in SEQ and then I want everything around it. I can do the "Id-dropdown" with adjacent, but it doesn't set the picker, it replaces the search criteria based on the event id. What I really want is the date/time picker to select around the time (let's say +/- 5 min) so I can then go in and do additional queries in that time range, etc.

**Comment by nblumhardt** [comment]
This has been implemented in Seq 5- we accidentally created a duplicate #696
