### ISSUE TITLE
Consider monospace/fixed width font for tags

### ISSUE THREAD

**Issue by laurencee** [datalust/seq-tickets#685]
Heya,

We are using tags for things like machine names, app names etc and for our machines we tend to use a standard naming format that keeps the length of machine names pretty consistent.

Unfortunately when these tags are displayed in Seq they don't line up because of the variable-width font and there's something uncomfortable about that to me.

Thoughts and opinions welcome.

**Comment by nblumhardt** [comment]
Thanks, Laurence 👍 - will try this out when we have a chance, and see how it looks.

In the meantime, you can add the following to your Seq theme (_Settings_ > _Theme_) to do it:

```
.tagged-properties .property-name {
  font-family: monospace;
}
```

**Comment by nblumhardt** [comment]
Done

![image](https://user-images.githubusercontent.com/342712/48032486-86a9e480-e1a3-11e8-8fac-6030e611bdbb.png)
