### ISSUE TITLE
Collecting docker logs

### ISSUE THREAD

**Issue by dazinator** [datalust/seq-tickets#688]
When running docker containers, you can "listen" or collect to their log output via the `docker logs` command: https://docs.docker.com/engine/reference/commandline/logs/#parent-command

I am not sure how faesible this is, but it would be nice if there was some way to collect this output and get it into seq.

I haven't investigated very rigorously, but it looks like their might be a way to control the format of log output from docker: https://docs.docker.com/config/containers/logging/log_tags/
and if you wanted to go all out, I can see docker has the concept of log drivers, and a few that log to cloud providers for example: https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers

**Comment by nblumhardt** [comment]
Hi Darrell!

We're building the `seqcli ingest` command with this kind of usage in mind:

https://github.com/datalust/seqcli#examples

Still early days, but would be keen to hear whether its' useful.

We're also keen to get a docker log driver together at some point, thanks for the note 👍

**Comment by nblumhardt** [comment]
Hi Darrell, any thoughts on this? Cheers!

**Comment by dazinator** [comment]
Nope sorry! I will eventually get around to experimenting with `ingest` and docker to see what I can work out. It's low priority for me at the moment however! If you hear about anyone achieving anything on this front please let me know :-)

**Comment by dazinator** [comment]
I think this looks like the way forward: https://github.com/jwulf/Gandelf

**Comment by nblumhardt** [comment]
We're closing this and considering GELF and Syslog support as the long-term answer to this 👍  thanks!
