### ISSUE TITLE
Applied properties under API key are not working

### ISSUE THREAD

**Issue by HakanL** [datalust/seq-tickets#691]
I'm testing Seq 5.0.949-pre and I have API keys that have applied properties that set the environment and service name. These aren't working any more, the applied properties aren't set, but I'm still ingesting messages.

**Comment by HakanL** [comment]
Hmm, now I'm a little confused, it may be that the data comes in under the "None" API key, that's where I see the rate counter. There's been no other change than upgrade to 5.0, and it's a free version.

**Comment by HakanL** [comment]
Yea I confirmed with the ingestion log, all messages come in as invalid api key now. But the key is matching.

**Comment by nblumhardt** [comment]
Thanks for the heads-up, Hakan - sounds like a bug, we'll take a look :+1:

**Comment by nblumhardt** [comment]
Looking into this, it seems to be a bug in the 4.2->5.0 API key upgrade (we've changed how these are stored and matched); investigating further.

**Comment by nblumhardt** [comment]
Found the issue; fix coming in the next 5.x preview. Thanks @HakanL!
