### ISSUE TITLE
Branching/tabbed diagnostic sessions

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#697]
Via Tyson Williams at: https://docs.getseq.net/v4.2/discuss/5b0d64ec3b30dc0003c862ac

It's often desirable, when debugging an issue, to go off and explore a hunch, then return to an earlier point. For example, if the events screen has a particular web request pinpointed, then exploring along various axes linked to the web request - the initiator of the request, services called by it, data mentioned within it - can turn up new information, but at each point it's necessary to come back to the request.

We've had tickets like #431 raised for better "middle click"/"open in new window" support that suggests using browser tabs would be one answer to this. Unfortunately, as called out in the linked post, new tabs don't inherit state in un-saved signals, for example, excluded events.

Raising this ticket here to consider, post-5.0, baking some kind of branching/tabbed session support directly into the events screen.

**Comment by bender2k14** [comment]
Thanks @nblumhardt for creating this GitHub issue :)

**Comment by nblumhardt** [comment]
Closing in favour of #431 for now - where there are browser features to use, we should support these ahead of custom UI.

**Comment by bender2k14** [comment]
A nice feature in Google Chrome is that when the browser closes unexpectedly, upon reopening the browser, the user is prompted to restore all previously opened tabs, and (of course) responding positively to this prompt does indeed restore these tabs.

However, it is possible for the search results on the events page of SEQ to depend on unsaved state (i.e. on parts of the query not expressed in the URL), such as excluded events.

SEQ would be making better use of this feature, without any change to its existing UI, if it simply represented the full state of the events page (be it saved or unsaved) in the URL.

**Comment by nblumhardt** [comment]
Thanks for the suggestion. I started off down this path in the very early days, but IE has a URL length limit of ~2000 chars, which put that idea to rest back then. Things may have improved since, but Seq does still support IE11. One for us to look into :-)

**Comment by bender2k14** [comment]
It seems ok to me if SEQ stored this unsaved state in the URL up until some limit (that either depends on the browser or is just a constant) and resumed its current behavior where it leaves the URL unchanged (possibly with a warning displayed to the user).  I don't expect that I would ever run into this limitation.
