### ISSUE TITLE
Seq in Docker shows wrong free space

### ISSUE THREAD

**Issue by qadmium** [datalust/seq-tickets#700]
When storage directory not in root fs, but mounted

E.g Seq launched with --storage=/ephemeral option, and some external drive is mounted to /ephemeral.
Looks like Seq is taking into account only free space on /

**Comment by nblumhardt** [comment]
Thanks for the note! We'll take a look at this :+1:

**Comment by nblumhardt** [comment]
Fixed in the upcoming 5.x preview. Thanks @qadmium !
