### ISSUE TITLE
SIGILL/exit when attempting to ingest any events

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#703]
On some Docker hosts (currently observed only on some Linux hosts), the Seq container exits when trying to ingest any event data. The process exits without producing any output at the console.

When GDB is attached, a SIGILL signal is trapped, and this appears to be related to a release-mode assertion in the storage engine.

We're currently collecting reports and attempting to narrow this down to a specific configuration.

**Comment by palmtech** [comment]
I'm getting something similiar, exit code 132, nothing logged. Could it be some CPU specific extensions being expected?

	Number of cores		8 (max 8)
	Number of threads	16 (max 16)
	Name			Intel Xeon E5 2450L
	Codename		Sandy Bridge-EN
	Specification		Intel(R) Xeon(R) CPU E5-2450L 0 @ 1.80GHz
	Package (platform ID)	Socket 1356 LGA (0x3)
	CPUID			6.D.7
	Extended CPUID		6.2D
	Core Stepping		C2
	Technology		32 nm
	TDP Limit		70.0 Watts
	Tjmax			83.0 °C
	Core Speed		1189.0 MHz
	Multiplier x Bus Speed	12.0 x 99.1 MHz
	Base frequency (cores)	99.1 MHz
	Base frequency (ext.)	99.1 MHz
	Rated Bus speed		3963.3 MHz
	Stock frequency		1800 MHz
	Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, AES, AVX
	Microcode Revision	0x710
	L1 Data cache		8 x 32 KBytes, 8-way set associative, 64-byte line size
	L1 Instruction cache	8 x 32 KBytes, 8-way set associative, 64-byte line size
	L2 cache		8 x 256 KBytes, 8-way set associative, 64-byte line size
	L3 cache		20 MBytes, 20-way set associative, 64-byte line size
	Max CPUID level		0000000Dh
	Max CPUID ext. level	80000008h
	Cache descriptor	Level 1, D, 32 KB, 2 thread(s)
	Cache descriptor	Level 1, I, 32 KB, 2 thread(s)
	Cache descriptor	Level 2, U, 256 KB, 2 thread(s)
	Cache descriptor	Level 3, U, 20 MB, 32 thread(s)
	FID/VID Control		yes


	IBRS			not supported
	IBPB			not supported
	STIBP			not supported
	RDCL_NO			no
	IBRS_ALL		not supported
	Turbo Mode		supported, enabled
	Max non-turbo ratio	18x
	Max turbo ratio		23x
	Max efficiency ratio	12x
	Max Power		110 Watts
	Min Power		40 Watts
	O/C bins		none
	Ratio 1 core		23x
	Ratio 2 cores		23x
	Ratio 3 cores		22x
	Ratio 4 cores		22x
	Ratio 5 cores		21x
	Ratio 6 cores		21x
	Ratio 7 cores		20x
	Ratio 8 cores		20x

	Temperature 0		49 degC (120 degF) (Package)
	Temperature 1		46 degC (114 degF) (Core #0)
	Temperature 2		41 degC (105 degF) (Core #1)
	Temperature 3		43 degC (109 degF) (Core #2)
	Temperature 4		42 degC (107 degF) (Core #3)
	Temperature 5		45 degC (113 degF) (Core #4)
	Temperature 6		43 degC (109 degF) (Core #5)
	Temperature 7		48 degC (118 degF) (Core #6)
	Temperature 8		46 degC (114 degF) (Core #7)
	Voltage 0		0.84 Volts (VID)
	Power 00		20.17 W (Package)
	Power 01		6.99 W (IA Cores)
	Power 02		13.18 W (Uncore)
	Clock Speed 0		1188.98 MHz (Core #0)
	Clock Speed 1		1188.98 MHz (Core #1)
	Clock Speed 2		1188.98 MHz (Core #2)
	Clock Speed 3		1188.98 MHz (Core #3)
	Clock Speed 4		1188.98 MHz (Core #4)
	Clock Speed 5		1188.98 MHz (Core #5)
	Clock Speed 6		1188.98 MHz (Core #6)
	Clock Speed 7		1188.98 MHz (Core #7)
	Core 0 max ratio	23.0 (effective 18.0)
	Core 1 max ratio	23.0 (effective 18.0)
	Core 2 max ratio	23.0 (effective 18.0)
	Core 3 max ratio	23.0 (effective 18.0)
	Core 4 max ratio	23.0 (effective 18.0)
	Core 5 max ratio	23.0 (effective 18.0)
	Core 6 max ratio	23.0 (effective 18.0)
	Core 7 max ratio	23.0 (effective 18.0)

**Comment by nblumhardt** [comment]
Thanks for the added info @palmtech  - we're investigating this one 👍

**Comment by nblumhardt** [comment]
5.0.1915-pre is now available, with what we hope is the fix for this one. If you're able to try it out and confirm, feedback would be appreciated. Thanks!

**Comment by nblumhardt** [comment]
Confirmed fixed on at least one problem machine 🎉

**Comment by palmtech** [comment]
Yep, working here. Thanks! 👍
