### ISSUE TITLE
AzureAD authentication broken in 5.0 previews

### ISSUE THREAD

**Issue by patros** [datalust/seq-tickets#713]
The reply url is now set correctly. But now we are getting this error message...
Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

I'll email in the seq log.

**Comment by nblumhardt** [comment]
Thank you, we'll take a look 👍

**Comment by nblumhardt** [comment]
Just a heads-up, we're considering enabling Azure AD support in Docker via OpenId rather than the ADAL (Azure AD-specific) integration that we're currently using on Windows. Any caveats that we're not aware of would be great to hear :-)

**Comment by andymac4182** [comment]
If it supports Identity Server that will be a great win for us :)

**Comment by patros** [comment]
No gotchas that I'm aware of @nblumhardt. We've been using OpenId with Azure AD and Okta no problems. Let me know as soon as I can test it out.

**Comment by nblumhardt** [comment]
(Updated the issue title to reflect that we've hit this on Windows, too)

**Comment by nblumhardt** [comment]
We've addressed this one directly and think we'll continue with the same AAD integration setup in v5; it's likely we'll push back general OpenId Connect integration to a future release.

**Comment by patros** [comment]
When you do end up getting to this @nblumhardt it would be great if user settings could be migrated from AAD to OIDC based on email address. We'll be using AAD for the foreseeable future but it would be really good to be able to migrate away from a vendor specific IDP.
