### ISSUE TITLE
Seq show-key doesn't find Seq.json in docker image

### ISSUE THREAD

**Issue by patros** [datalust/seq-tickets#714]
I'd say this is expected behaviour, and just a backlog item to update wording/documentation before release.

The backup settings interface says `The key must be retrieved in cleartext using the seq.exe show-key command.`

I tried running `/bin/seq-server/Seq show-key` but it just looks for `./Seq/Seq.json`. You need to run `/bin/seq-server/Seq show-key --storage=/data`.

It would be great if the interface could display the required command.

**Comment by nblumhardt** [comment]
Thanks 👍

**Comment by nblumhardt** [comment]
I think this one should be achievable using:

```
docker run \
  -e ACCEPT_EULA=Y \
  -v /path/to/seq/data:/data \
  datalust/seq \
  show-key
```

Our documentation for using Docker is still pretty rudimentary, but we're starting to assemble some so I've added a note here: https://docs.getseq.net/v5.0/docs/running-server-commands

Thanks again for raising this!
