### ISSUE TITLE
Light/Dark theme selection

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#728]
We've had a lot of requests for a dark theme over the years, we're finally going to ship one with Seq 5 :-)

**Comment by KodrAus** [comment]
The latest Seq 5 previews now have support for multiple themes! The existing theme has been re-purposed as a light theme and tweaked to keep things consistent with the new dark theme. There's more browser compatibility work to do in upcoming previews but the themes are stable enough to start using. We hope you enjoy them as much as we do :)

Light theme:

![screen shot 2018-10-15 at 09 30 47](https://user-images.githubusercontent.com/6721458/46923591-18b74500-d05d-11e8-9d5a-a5b0cbc5efee.png)

Dark theme:

![screen shot 2018-10-15 at 09 30 27](https://user-images.githubusercontent.com/6721458/46923590-181eae80-d05d-11e8-8745-75d7a250f32f.png)

You can set your personal theme in your user preferences. Theme selection is user-specific:

![screen shot 2018-10-15 at 09 31 04](https://user-images.githubusercontent.com/6721458/46923592-18b74500-d05d-11e8-8a1e-9867cba402a7.png)

**Comment by nblumhardt** [comment]
Much credit due to @KodrAus's artiCSStry :-) .. 🎉 🎉 🎉

**Comment by MPieter** [comment]
Would be nice if you also have an option to use the system settings. Then the theme will switch automatically together with the OS.

**Comment by larenelg** [comment]
@MPieter luckily, we just implemented this! Please take a look at https://github.com/datalust/seq-tickets/issues/996

Thanks for the feedback, my thinking was making it automatic as well! I've added an extra issue to further enhance it to use system settings and switch automatically. #1030

**Comment by MPieter** [comment]
@larenelg great thanks! Looking forward to the future updates :)
