### ISSUE TITLE
Mobile Dashboard App

### ISSUE THREAD

**Issue by IanElsinga** [datalust/seq-tickets#729]
It would be wonderful to have an Android/iOS app that would display already-configured dashboards.   Is there a third party app that works with Seq already and if not may I suggest this as part of the roadmap? 

Thanks, enjoying Seq.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, Ian. We'd love to do this - it's not on our list for Seq 5.0, but we'll keep an eye out for where it might fit in the future.

**Comment by nblumhardt** [comment]
We've reviewed this and think we'd likely address it only as part of a broader UI update. Closing this ticket for now to keep the tracker manageable. Thanks @IanElsinga !

**Comment by ramonsmits** [comment]
It doesn't really need an app but a more responsive UI would help.

Related to:

- #1961
