### ISSUE TITLE
Option to suppress chart legends

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#730]
On many charts, the legend is redundant and just causes clutter/misalignment with other charts on the veritical axis. E.g the time ranges do not line up in the example below:

![image](https://user-images.githubusercontent.com/342712/46924007-633bc000-d063-11e8-954e-c6faac092281.png)

From https://github.com/datalust/seq-tickets/issues/565

**Comment by tsimbalar** [comment]
This also fixes https://github.com/datalust/seq-tickets/issues/617 I guess 🎉

**Comment by nblumhardt** [comment]
Ah, I knew there was an original ticket somewhere! Marking this one 'duplicate' 👍  - thanks @tsimbalar
