### ISSUE TITLE
seq named instance not starting automatically after reboot

### ISSUE THREAD

**Issue by softlion** [datalust/seq-tickets#732]
After windows updates reboots the server automatically, only the default seq instance is restarted. The named instances are not restarted automatically.

Is this a bug ?

**Comment by nblumhardt** [comment]
Hi - thanks for the heads-up. Are they set to start-up automatically? (I.e. in the Windows Services configuration?) I'm not sure whether there's anything that the service needs to do in order for it to be restarted by Windows Update, I'll take a quick look around 👍

**Comment by softlion** [comment]
There is only one seq service and it starts correctly. But it starts only the default instance.

**Comment by nblumhardt** [comment]
Ah, thanks - to get the other instances to start up automatically, you need to `install` them, e.g.:

```
seq install -n OtherInstance
```

Depending on how they've been running to date, you may need to pass a `--storage` path to them.

Each instance will end up being run in its own Windows service.

Hope this helps, and if not, can you please send some more information (here or two support) about the paths/URLs/other config for the instances?

Cheers,
Nick

**Comment by softlion** [comment]
The scenario seems unsupported (buggy). It seems it tries to create a new windows service with the same name.

```
An exception occurred during the Install phase.
System.ComponentModel.Win32Exception: The specified service already exists
   at System.ServiceProcess.ServiceInstaller.Install(IDictionary stateSaver)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at System.Configuration.Install.AssemblyInstaller.Install(IDictionary savedState)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
```

**Comment by nblumhardt** [comment]
Thanks for the follow-up; can you please post:

 * The Seq version
 * The command-line used, and
 * The output from `seq list`?

Many thanks

**Comment by nblumhardt** [comment]
Hi @softlion - did you make any progress on this one? Thanks!

**Comment by softlion** [comment]
It works fine but you need to add the swich to select the instance, to the command to add the windows service. This is badly documented.
