### ISSUE TITLE
ChangeService2 messages after Windows  install

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-tickets#733]
not really an issue, but I was kind of intrigued by the messages logged in the window after installing the latest preview of Seq v5 ... mostly the 2 occurrences of `ChangeServiceConfig2`

```
Installing service...
Creating a new configuration file in C:\ProgramData\Seq\Seq.json...
[SC] CreateService SUCCESS
Setting service restart policy...
[SC] ChangeServiceConfig2 SUCCESS
Setting service description...
[SC] ChangeServiceConfig2 SUCCESS
Service installed successfully.
Starting Seq...
Waiting up to 15 seconds for the service to start (currently: Stopped)...
Started.
```

![image](https://user-images.githubusercontent.com/160544/46972005-cbb78b00-d0bd-11e8-8b28-197689d37419.png)

as of *Seq 5.0.2119-pre*

**Comment by nblumhardt** [comment]
Thanks for the heads-up. These are expected - we now shell out to `sc.exe` to do service configuration (under .NET Core). When we invoke it to change the restart policy, e.g.:

```
Setting service restart policy...
[SC] ChangeServiceConfig2 SUCCESS
```

then we collect its output in case there's any useful diagnostic information. We probably should suppress this unless there's a failure, but for now it's harmless (though the formatting is a bit odd).

**Comment by tsimbalar** [comment]
Thanks for the explanation. 
That's totally not an issue, so feel free to close it if you like.
