### ISSUE TITLE
Server can be slow to start after migrating 4.x -> 5.0

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#735]
The migration "Embed permalinked events in permalink documents" moves events from the primary event store into permalink documents themselves.

Under some condition, perhaps when a large number of permalinks are present, it appears this can take upward of 2 minutes, causing server start-up to be delayed.

**Comment by dgSean** [comment]
I'm in the middle of a 4.2->5.0 migration right now, with only 16 permalinks in the db, and it's taking 5-10 minutes per link easily. It has been about an hour and a half since I completed the installation and the service started for the first time.

I've tried prioritizing the seq process in hopes to speed it up, but this has been an unexpectedly painful upgrade. 

There definitely seems like there is something really wrong here.

**Comment by nblumhardt** [comment]
@dgSean thanks for the heads-up, and sorry to hear about the trouble :-/ ... That's much slower than we'd anticipate. Has the process completed? Letting it finish is still probably the best course of action, but if you do need to stop the upgrade please mail us at support@ and we'll help make sure things go smoothly. (cont'd..)

**Comment by nblumhardt** [comment]
In the hope that we can narrow down the cause; brain dump format, answers to any of these appreciated but please feel free to ignore:

 - Is CPU or I/O pegged?
 - Is it possible to grab a process dump?
 - How much data is in your Extents folder?
 - How many permalinks is the process reporting as broken? (Out of how many, total?)
 - Have you previously recovered disk space by deleting extents directly from disk?
 - Is storage generally slow on the machine?
 - Have you noticed any past errors about storage corruption?
 - Which OS is Seq running on?
 - Anything else you can think of that might make this sever behave differently, or that might make your storage setup unusual?

Many thanks!

**Comment by nblumhardt** [comment]
Hi again- quick update, we think we have a possible cause for this (a bug in the way the migration constructs queries), we're running a build through CI now, and if it passes automated testing I'll post a link to the new installer here in advance of publishing it to the downloads page.

**Comment by dgSean** [comment]
Thanks for the follow up.

The migration did complete; the entire process was about 2 and a half hours. All seems well outside of CORS not seeming to work anymore (I haven't done any investigation into this yet). We're using Seq mostly for monitoring/debugging purposes so the unavailability wasn't too big an issue; just wanted to raise some awareness. 

In case the info is still useful:

I don't think there is anything too special about the setup, 
it's a win server 2016 VM w/ 4gb and 2,8ghz, Seq is the only thing on it, but what else is running on that hardware is outside my purview.

The data looks to be around 8.5GB at the moment.

CPU was constantly between 50-80% utilization, changing the process prioritization didn't seem to have any effect.

there were 16 permalinks none were broken.

There were no direct edits to the file structure, but I did however migrate this data from another system to this one. That process seemed to go as expected, and have not seen any warning/errors regarding corruption.

I have found historically that the API often abandons queries that are pulling data more than a couple days (taking too long error).  Presumably anything pushed out of memory, which I suppose imply some storage performance as a likely issue. This was actually the main thing I was hoping would be resolved by the upgrade.

**Comment by nblumhardt** [comment]
Hi @dgSean - appreciate the additional details. Glad it came through in the end.

We think we have the bug in our sights here, just going through the process of building and testing a new install; slow storage would exacerbate it, but we're 99% sure the problem is with the migration itself.

Hopefully perf will be much improved after the upgrade; it does take some time for data to build up in the new engine (historical data won't be moved out of ESENT in this version), so we'll cross our fingers.

If the CORS issue turns out to be related to the new build, please shoot us a support@ email or raise a ticket here, we'll jump straight on it. Thanks!

**Comment by nblumhardt** [comment]
We're burn-in testing 5.0.2296 and will publish it to the website later today if it keeps performing as expected.

If you've hit this issue and want to jump ahead, the MSI is now at: http://getseq.net/download/begin?version=5.0.2296
