### ISSUE TITLE
Docker/Azure Active Directory login intermittently fails with ERR_ZERO_SIZE_OBJECT

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#743]
_We suspect this might be a problem with the ACI infrastructure rather than Seq, as the issue isn't reproducible elsewhere, but posting this here in case anyone else encounters/has encountered it._

A customer running Seq on Docker/Azure Container Instances has reported that after logging in using Azure Active Directory, the redirect back to `/aad` on Seq fails with error:

```
Internal Error: Missing Template ERR_ZERO_SIZE_OBJECT
```

The error appears to originate with a Squid 3.5 proxy/caching server running somewhere on the Azure network. Old versions of Squid (< 3.2.2?) were known to incorrectly produce this error in some circumstances, and one possible cause was not providing `Content-Length: 0` with a zero-length response. However, the Squid version reported is a later one, and Seq does send the `Content-Length` header correctly when responding on the `/aad` reply URL.

No error is recorded in Seq's internal log, and Seq continues to respond normally on other API endpoints as far as we can tell.

**Comment by weznagwama** [comment]
Unfortunately, we've ran into this issue and found it to be completely non-reproducible, in a consistent fashion (as you said).

Steps to (finger in the air) reproduce:
- Deploy SEQ to an ACI instance -> datalust/seq:latest
- Ensure persistent storage is mapped to a storage account
- Configure OAUTH2 auth. provider (Azure AD for example)
- Wait an unspecified amount of time
- Attempting to login will redirect back to SEQ instance with the 'login code', but display error messsage `Internal Error: Missing Template ERR_ZERO_SIZE_OBJECT`

Will post back here with more info if/when it occurs.

**Comment by tsimbalar** [comment]
Just a minor comment : in the docs (https://docs.getseq.net/v5.0/docs/upgrading-from-seq-42), the link to this issue 745 actually points to issue 735 in GitHub. Probably just a typo :)

**Comment by nblumhardt** [comment]
Removing this from the current dev milestone while we investigate further; so far no reports from other AAD/ACI users, so we'll do a bit more work to narrow this down.

**Comment by nblumhardt** [comment]
Closing as we don't know of any active installs still encountering this; please let us know if you're affected by it.
