### ISSUE TITLE
HTML title of browser window/tab to show which seq instance the tab refers to

### ISSUE THREAD

**Issue by dkerwood** [datalust/seq-tickets#744]
Enhancement. Please customize browser tab title to reflect the URL of the seq instance being accessed - showing only "Seq" in all the instances makes it inefficient to navigate to the required browser tab.  Title should show name of URL being accessed.

![image](https://user-images.githubusercontent.com/14816250/48180067-b60c4d00-e36d-11e8-8bab-96803dc2d816.png)

**Comment by dkerwood** [comment]
Thanks, Nick!
I don't seem to be able to set this when logged on as a "user", I can only change the instance title when logged in as admin.  Could the theme be available to users, not just admin?

**Comment by nblumhardt** [comment]
Hi again; I'll close this for now as we don't plan to change the feature at this point, but thanks for the feedback and please let us know if the current system causes problems for you that we haven't identified. Thanks!
