### ISSUE TITLE
Feature Request: Duplicate Alert

### ISSUE THREAD

**Issue by whoiskevinrich** [datalust/seq-tickets#746]
Would it be possible to add a "Duplicate Alert" button in the Dashboards\Alerts Area?

Use case:
In an application, I frequently want an alert to trigger with only slight differences in the configuration, based on similar criteria.

Example:
If I'm monitoring a monitor receives 5 exceptions in an hour, I may want to send a message to a general group as a warning. If the monitor receives 100 exceptions, I may want to send the message as an error to an elevated group.

Background:
I use Seq.App.Slack to manage alerts for my company. Each alert I setup includes a setting for criteria, severity, suppression, window, channel, slack app name, message, and icon, but often I only need to change 2-3 settings after the initial alert setup.

**Comment by nblumhardt** [comment]
I've added this to #565. Thanks @whoiskevinrich !
