### ISSUE TITLE
Re-generate/clone an API key

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#747]
Now that API key tokens (in 5.0) are irretrievable once created, re-generating a key (with a new token) will sometimes be necessary. This is currently laborious because of the need to configure attached properties and levels. We should provide a quick "clone" or "regenerate" feature to API keys in order to address this.

**Comment by KodrAus** [comment]
API keys can now be cloned when editing. This will retain their applied properties and filters, make them shared and regenerate the key:

![switch-to-clone-1](https://user-images.githubusercontent.com/6721458/48685342-8c6ee380-ec01-11e8-8787-7eb47c2b9b27.png)

![switch-to-clone-2](https://user-images.githubusercontent.com/6721458/48685343-8c6ee380-ec01-11e8-814c-21cb52043bf7.png)

**Comment by AndrewSav** [comment]
@KodrAus which version number is this available in please?

**Comment by KodrAus** [comment]
Hi @AndrewSav :wave:

This will be available in the next patch we push out. I'll give this ticket a ping once that's ready!

**Comment by KodrAus** [comment]
Alrighty, support for cloning API keys is available as of the `5.0.2360` build.
