### ISSUE TITLE
Suggestion: allow to enrich events during display

### ISSUE THREAD

**Issue by MaxShoshin** [datalust/seq-tickets#751]
It will be very usefull for us if we can create some enrichers for events on UI side.

For example: we have a lot of services, each of them reports its own `InstanceId`. During startup services write diagnostics information like host name, configuration, listen address and so on. 

When we explore event log we always can retrieve such information by filtering by Event Type and `InstanceId` field. But it will be very useful if we can retrieve such information right on the event (may be in additional panel, but without additional filterring).

I.e. we have some kind of correlationIds and we would like to enhance all events with the same correlationId by additional context information on the fly. Such information can be calculated somehow but not stored in the event itself (we can have a huge amount of such information and sore them within each event is not a good idea). 

What do you think about it? 

Thank you!

**Comment by nblumhardt** [comment]
Hi Max, thank you for the suggestion, it's very interesting food for thought.

We're heads-down on post-release work this week so I'll have to loop back around to this when I have a spare minute to think through it :-) - Thanks again!

**Comment by nblumhardt** [comment]
Thanks again for this. It's a very interesting use case, but doesn't currently line up with our plans for the next few releases and so we'll close the ticket for now.
