### ISSUE TITLE
Feature Request: Double-click to isolate signals within groups

### ISSUE THREAD

**Issue by nskerl** [datalust/seq-tickets#753]
Within a Signal Group with a large number of Signals, it is sometimes a chore to _unselect_ a bunch of Signals to focus on one. It would be nice to mirror the double-click function from the dashboard here in Signal groups.

**Comment by nblumhardt** [comment]
This is an interesting suggestion but we're inclined to think discoverability would be a challenge, so we're deferring it for now. We'll keep it in mind, though! Thanks again @nskerl 👍
