### ISSUE TITLE
NullReferenceException when ingesting events from Python/seqlog

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#756]
Via: https://docs.getseq.net/v5.0/discuss/5bf300725faec3000e561fa6

**Comment by nblumhardt** [comment]
This is due to a bug in handling of requests with no `Content-Type` HTTP header. Fixed in the next patch build.

**Comment by tintoy** [comment]
Thanks! Also fixed in Seqlog v0.3.13.
