### ISSUE TITLE
No documentation on how docker base image updates are handled

### ISSUE THREAD

**Issue by patros** [datalust/seq-tickets#757]
Hi,

I couldn't find any details on how updates, especially security, are being managed for the docker image.

Thanks

**Comment by nblumhardt** [comment]
Hi Patrick; at present, we're just rolling ahead the `latest` and `5` tags with each incremental release. Is there another image you'd point to as having an optimal update scheme, that we could consider as a model?

Cheers,
Nick

**Comment by patros** [comment]
Hi @nblumhardt. I'm assuming you're using the official Ubuntu 16.04 base image. So for example it was updated earlier today. It would be great if that triggered a new Seq image build to take advantage of the updates they have included in the new base image.

I haven't had to really worry about it myself. I've just scheduled a weekly rebuild for any container images I have. Although it makes more sense to only do that when the base image has actually changed. Especially if you end up with multiple Seq container image versions that are actually the same.

I'll do a bit of poking around because I'd like to incorporate it into our Seq release process anyway.

**Comment by patros** [comment]
Actually, looking at the release history on that base image it doesn't look like it is updated often enough. Do you have an `apt-get upgrade` as part of your build process? Maybe it should just be a weekly rebuild?

**Comment by nblumhardt** [comment]
Thanks for the follow-up, Patrick. By a weekly "rebuild" do you mean `docker build --no-cache`? We've just been over the options, and think adding this to our regular build (combined with shipping regular maintenance releases on our part) is the best option currently. Thoughts?

**Comment by patros** [comment]
Not really, although I guess it should be part of the maintenance release build.

In my docker files I have `RUN apt-get update -q` and `RUN apt-get upgrade -q` to apply all source distribution package updates. You can also add a `RUN rm -rf /var/lib/apt/lists/*` at the end to do a bit of cleanup of things that don't need to be shipped.

**Comment by patros** [comment]
I haven't had the problem of publicly versioning and releasing an image though. There could be a better way, but none I can think of.

**Comment by nblumhardt** [comment]
Thanks for the follow-up; we're doing something along the lines of the "rm" to clean things up already 👍 

The Docker best practices posted at https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run recommend against `apt-get upgrade`:

> Avoid RUN apt-get upgrade and dist-upgrade, as many of the “essential” packages from the parent images cannot upgrade inside an unprivileged container. If a package contained in the parent image is out-of-date, contact its maintainers.

Unsure here whether the advice given is going to be always-applicable in our use case, so I guess we'll dig deeper into this :-) Thanks!

**Comment by patros** [comment]
Hmm... I should have really RTFM. For my own paranoia I might just script a check to see if there are any security updates available. Thanks @nblumhardt
