### ISSUE TITLE
Inaccurate memory sampling in Docker causes containers to swap and/or OOM

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#764]
In a very small (1 GB) container I've just observed a substantial discrepancy between Seq's detected system memory utilization and actual utilization, resulting in a container restart. We'll need to investigate the cause of this.

**Comment by nblumhardt** [comment]
Okay, we have a handle on this! It's too late in the week to push a new build, but we'll roll this into a new patch Monday or Tuesday.

**Comment by andymac4182** [comment]
Will it be possible to set a non % based target? We have some machines it would be great to set a MB based target.

**Comment by nblumhardt** [comment]
As in per-process MB limit, or for system utilization, @andymac4182?

In the context of this PR, we'll make pretty limited changes just to correct the algorithm we're using, but we're coming back around to spending some time on caching behaviour soon, so good to understand the scenario 👍

**Comment by andymac4182** [comment]
As a seq process MB limit. Will have a chat offline about the reasons 😄
