### ISSUE TITLE
Feature Request: See configured alerts using App Instance

### ISSUE THREAD

**Issue by whoiskevinrich** [datalust/seq-tickets#765]
There have been many times our group has wanted to migrate from one alert technology to another. For example, changing from Slack to Pager Duty. We have a number of alerts set up, and I'm always hesitant to delete an app instance, because I don't want to have alerts fired into a void.

I would like to see the ability to find all alerts that fire to an app instance from the Settings -> Apps -> App Instance screen.

**Comment by nblumhardt** [comment]
Hi Kevin - thanks for the suggestion; this something of an obvious feature, it'd be great if we could expose this information one way or another 👍 

We'll give this some thought, thanks again!

**Comment by nblumhardt** [comment]
Thanks again for raising this, Kevin - we think it will be addressed by #679 and will track it there.
