### ISSUE TITLE
Feature Request: Custom Gravatar Url

### ISSUE THREAD

**Issue by DominikPf** [datalust/seq-tickets#767]
It would be nice to have an option to configure a custom "Gravatar-Url".
(e.g. in Gitea https://docs.gitea.io/en-us/config-cheat-sheet/, Topic "Picture" GRAVATAR_SOURCE)

**Comment by nblumhardt** [comment]
Thanks for the suggestion! We'll take a look 👍

**Comment by nblumhardt** [comment]
Thanks again for the suggestion, Dominik. We don't think this will make its way into the next few releases, so we're closing this ticket to keep the issue tracker focused.
