### ISSUE TITLE
Support default signals in workspaces

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#770]
When opening a workspace there might be a particular combination of signals that are sensible defaults to have selected by default when opening that workspace.

**Comment by Suchiman** [comment]
Yes! Also when switching workspaces, this should select the default signals of that workspace, instead of bringing your current signal selection into the other workspace.

**Comment by smudge202** [comment]
Somewhat related request, when you have many signals there seems to be some kind of logic that determines which are shown and which need to be searched for in the sidebar. Could that logic look at "most used" or even "most recently used"? Whilst I don't know what the logic is, the few signals I use the most I _always_ have to search for.

**Comment by nblumhardt** [comment]
Hi @smudge202 - it sounds like you may need to save the current workspace once you've searched for and selected a signal. In 5.1 (IIRC) we made this automatic, so if you haven't already upgraded, after doing so it _should_ "just work". Let me know if it sounds like I'm off-track. Thanks!

**Comment by smudge202** [comment]
Ah, I'll make sure I'm on latest and give that a try. Thanks!

**Comment by fredrik-lundin** [comment]
Any progress, or status on if/when this will be implemented?

**Comment by nblumhardt** [comment]
Thanks for the nudge, @fredrik-lundin - I'll pull it into our 6.0 feature milestone and we'll take another look - we're keen to include it if we can do so without any major caveats.

**Comment by nblumhardt** [comment]
Okay! We're there 👍 

Workspace details have moved under _Settings_ (shared workspaces) and user preferences (the more common case):

![image](https://user-images.githubusercontent.com/342712/101552912-6e01fd80-39ff-11eb-9008-974a93a169ef.png)

Switching into a workspace activates the default signals associated with the workspace:

![default-signals](https://user-images.githubusercontent.com/342712/101553308-1adc7a80-3a00-11eb-880a-6f89c76f71e1.gif)

User-level/global default signals are gone; in their place, you can now choose a default workspace under user preferences:

![image](https://user-images.githubusercontent.com/342712/101553462-65f68d80-3a00-11eb-84a1-e33e3ec234d6.png)

Thoughts/feedback welcome; we'll have a preview out later this week, if all goes to plan.

**Comment by nblumhardt** [comment]
2020.5.5137-pre is now at https://datalust.co/download/ and on Docker Hub, in case anyone's keen to try this one out :-)
