### ISSUE TITLE
Missing Documentation: v5 Dashboard Features

### ISSUE THREAD

**Issue by whoiskevinrich** [datalust/seq-tickets#771]
I could find no documentation on the following features which appear new in v5:

* Protected Dashboards:

![image](https://user-images.githubusercontent.com/2496620/49536359-275ef300-f87b-11e8-904b-d1b3b532f82a.png)

* Remove from Workspace:

![image](https://user-images.githubusercontent.com/2496620/49536406-43629480-f87b-11e8-8fe0-f6350668a62d.png)

Existing Documentation: 

The [existing documentation](https://docs.getseq.net/docs/dashboards#section-dashboard-tools) does not include the above Dashboard Features.

![image](https://user-images.githubusercontent.com/2496620/49536473-73aa3300-f87b-11e8-9ac0-321709a751e6.png)

**Comment by KodrAus** [comment]
We've now got [some documentation](https://docs.datalust.co/docs/dashboards#section-dashboard-tools) for the new tools we introduced in 5.0.

Similar sections have been introduced for signals and queries, which have similar sharing and workspace tools.
