### ISSUE TITLE
Index out of bounds error when installing nuget package with 4-part version numbers

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#772]
When attempting to install an app named like `Seq.App.Something.1.2.3.4`, an exception is rasied for an index out of range:

```
startindex cannot be larger than length of string
```

We should be producing a more helpful error message here.

**Comment by nblumhardt** [comment]
There are various related issues involving four-part version numbers; see also: https://docs.getseq.net/v5.0/discuss/5c18b652ab3f28000d8f5ba0

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/51156646-3f894f80-18c8-11e9-93a7-c63591199641.png)

👍
