### ISSUE TITLE
Are the inputs for the `EventType` hash configurable?

### ISSUE THREAD

**Issue by redoz** [datalust/seq-tickets#773]
So the question is if the `EventType` can be based off other things than the message template as our logging facilities already provide unique event identifiers. Nicer still if we could provide a human readable `EventType`, or a mapping of some sort so we're not looking at hashes in the UI.

**Comment by nblumhardt** [comment]
Hi Patrik; if you're using a custom logging client to send events to Seq, you can specify an event type explicitly in the payload at ingestion time by setting the `"@i"` field in the JSON document: https://github.com/serilog/serilog-formatting-compact#format-details

(Note for Seq this needs to be either a regular number or hex-encoded unsigned 32-bit integer.)

If the event reaches Seq without an event type specified, it's computed based on the message template only.

Does this help?

**Comment by redoz** [comment]
Yeah, that lets us avoid accidental collisions based on message template alone. So the follow-up question is if each event has a canonical 32-bit representation, would it be possible to map those values into something human readable for the UI? It's not super important, but as we're using pre-defined events we have proper/unique names for them.

**Comment by nblumhardt** [comment]
Hi Patrik; sorry this ticket got buried over the holiday period! :-0

There isn't an option for this at present; I can imagine it being possible someday via UI extensibility, but I don't think it fits any feature plans currently on the roadmap.

Would using an enrichment approach (tagging each event with a human-readable property derived from the event type) be preferable? Or possibly switching from u32 to string event ids?

**Comment by redoz** [comment]
No worries, things were pretty quiet here too.

Anyway, providing the "@i" solved the immediate issue of ensuring the event ids are unique even though the message template might not be.  The ability to get something more friendly to look at than a 32bit hex would be nice of course, but it's hardly critical.  I believe we already tag each event with the source and id, so the data is already in the recorded event, perhaps the solution is just to provide a custom format string for the display value? Moving to string event ids would also solve it, but that sounds like a significant change, and I'm not sure that's warranted, this is just a "nice to have" after all.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Will close this for the time being, but keep the whole configurable-event-id mechanism in mind :+1:
