### ISSUE TITLE
Occasional long response latencies for various API actions

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#778]
Seq 5.0 uses a different write queueing strategy from 4.x, which, in some environments, causes starvation of other HTTP API requests. This surfaces in particular when background I/O (indexing, retention processing) consumes IOPS and holds up writers.

The impact of this is apparent unresponsiveness in the Seq web UI/slow responses.

Allocating additional IOPS to affected servers should mitigate the issue (we're in the process of confirming this), but in 5.1 we are planning several changes to handle this scenario more efficiently.

**Comment by andymac4182** [comment]
This would explain some weird behaviours when our machine is under crazy load.

**Comment by nblumhardt** [comment]
We've done some work to more aggressively kill queued write requests if performance drops, but, we think the root cause of the issues that we've seen in the wild are more frequently due to large numbers of "Keep-Alive" connections being kept around when clients use a new connection for every event/batch of events. We're addressing this by substantially shortening the idle-connection timeout.

We're dropping a bunch of this into 5.1 and expect we'll have a preview build by the end of this week, for anyone who can put it to the test :-)

**Comment by nblumhardt** [comment]
Just a quick heads-up, [5.1.2669-pre](https://getseq.net/download) is a good build to try, if you think you might be impacted by this. Feedback appreciated :-)

**Comment by RickFrankel** [comment]
Hi Nicholas,  We are running xxx and appear to be still hitting this issue multiple times a day.  We have also found that when it happens we cannot stop the SEQ windows service and it requires a force kill on the process to stop the service and for it to start again and then become responsive.  Happy to provide any logs/details that might help you.

Cheers

**Comment by nblumhardt** [comment]
Hi @RickFrankel thanks for jumping in. If you're able to send the full diagnostic report from _Settings > Diagnostics_, bottom of page, to support@getseq.net, we'll take a look.

The original instance of this problem was purely network-related, i.e. CPU and other metrics remained normal - it'd be great to hear whether that's also the case for you. Thanks!

**Comment by RickFrankel** [comment]
Done.. Send to you now.

**Comment by nblumhardt** [comment]
(Re-titling this as we're investigating possible causes outside the HTTP stack now.)

**Comment by nblumhardt** [comment]
5.1.2871-pre includes some GC setting changes that we think will have an impact on this.

**Comment by nblumhardt** [comment]
Several interesting bugs were uncovered during this investigation. I've just split the three biggest out into their own tickets, which will be part of the 5.1 release very soon.

I'm going to close this general one in favour of those; we can open a new ticket if there are still cases not captured in the individual tickets.
