### ISSUE TITLE
Long values in chart parts push edit panel to the side

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#780]
If you've got a value chart part with a long value, it looks like we push the edit panel off to the side. We should either truncate the value or shrink it to fit.

<img width="721" src="https://user-images.githubusercontent.com/6721458/50935998-b8983980-14b9-11e9-9bce-4c69859f6396.png">

**Comment by nblumhardt** [comment]
Fixing with a simple max-height that matches the non-expanded window height: ![image](https://user-images.githubusercontent.com/342712/51150559-8ec48580-18b2-11e9-9e0f-79e2e50fb007.png)
