### ISSUE TITLE
LightningDB -30796: MDB_CORRUPTED: Located page was wrong type

### ISSUE THREAD

**Issue by SeriousM** [datalust/seq-tickets#781]
Hey cuys, I got a very serious problem over here.
For some reason the lightningdb is down and I can't modify signals, dashboard or even logout/login anymore.
Now I'm logged out and can't access my data anymore!

What steps should I take to render the system accessible again?

**Comment by SeriousM** [comment]
Seems it's somehow connected with #777. This is very terrible :(

**Comment by andymac4182** [comment]
@SeriousM You would be best to email `support@getseq.net` for support or log a ticket on https://docs.getseq.net/discuss/?sort=newest

**Comment by nblumhardt** [comment]
Hi @SeriousM, sorry to hear this has impacted you. This is consistent with the kinds of issues we've hit on Azure Files, unfortunately.

We've added a note warning against deployment on Azure Files to our [Getting Started](https://docs.getseq.net/docs/getting-started-with-docker) docs.

Closing as `wontfix` as from what we can tell, it's unlikely Seq will ever be able to run reliably over SMB. If you need a hand restoring from backup or attempting to recover the data in place, please drop us a line via support@, happy to try whatever we can to get you back up and running.

**Comment by SeriousM** [comment]
Thanks. I dropped you a line :)
