### ISSUE TITLE
Allow system RAM target to be set using absolute values

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#784]
It would be useful for some environments, like Kubernetes, to be able to limit Seq's target memory utilisation (as set by `cache.systemRamTarget`) based on an absolute value, like `500m`, instead of a percentage of the reported system total.

**Comment by SeriousM** [comment]
I would suggest that the value can be configured in Seq.json as well as an overruling environment variable to ease the configuration in docker/k8s pods.

**Comment by SeriousM** [comment]
Hi @KodrAus, is this change in any of the latest versions? (5.0.2787, 5.0.2817)
How can I use it?

**Comment by KodrAus** [comment]
Hi @SeriousM, you can use an absolute value in one of the 5.1 preview builds. Setting the system RAM target to a value greater than `1` will be treated as a target in bytes instead of a fraction of total available memory.

**Comment by SeriousM** [comment]
That's good to know, but is 5.1pre RTM? We need it on the production server and want to avoid any downtime.

**Comment by nblumhardt** [comment]
Hi @SeriousM - no, 5.1 is currently pre-release, but we're aiming for a final build within the month, if all goes to plan. We won't be able to get this into a 5.0 build any sooner, so using the pre-release build of 5.1 or waiting until it's released is the best we can do right now, sorry. HTH!
