### ISSUE TITLE
CORS "ingestion from anywhere" no longer enabled by default in Seq 5

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#786]
In Seq 4, the HTTP ingestion endpoint accepts CORS requests from anywhere by default. In v5 this was regressed, with `api.corsAllowedOrigins` required in all cases. We should review this feature and consider adding an opt-in or opt-out configuration setting when it's re-enabled.

**Comment by Sebbl22** [comment]
We would highly appreciate if this feature will return in 5.1

**Comment by nblumhardt** [comment]
Allowing wildcards like `*` in `api.corsAllowedOrigins` might be a nice, explicit way of controlling this, that would have the benefit of supporting rules like `https://*.example.com`.

**Comment by krajek** [comment]
I just stumbled on the CORS error and found this issue looking for a solution. I added `corsAllowedOrigins` with proper origin but the problem persists. Do I need to restart the service to fix the problem? Or maybe there is something more I should do?

The error message:
Access to XMLHttpRequest at 'https://seq.XXX.io/api/events/raw' from origin 'https://office.XXX.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Entry in the Seq.json:
`"corsAllowedOrigins": ["https://office.XXX.io"]`

The events are logged from a web app, maybe that matters.

**Comment by nblumhardt** [comment]
Hi @krajek - yes, if you've just added the entry to Seq.json you'll need to `seq restart` before it will take effect.

**Comment by nblumhardt** [comment]
In the next Seq 5.1 preview, ingest-from-anywhere will be back, in its original form.

**Comment by nblumhardt** [comment]
Moving this to the first 5.1 patch milestone, as the fix in v5.1.2976 was not sufficient.

**Comment by Sebbl22** [comment]
@nblumhardt Should this issue be opened again for tracking?

**Comment by nblumhardt** [comment]
Hi @Sebbl22 - the 5.1.3000 milestone has shipped, so as far as we were aware, this is now fixed and included in it. Unfortunately, we've had a report of issues on 5.1.3000: #838 ... though we can't reproduce the problem ourselves, yet.
