### ISSUE TITLE
Document raw post response body and status codes

### ISSUE THREAD

**Issue by SimonCropp** [datalust/seq-tickets#790]
So this has doco for the request payload, but nothing about the response payload and status codes.

https://docs.getseq.net/docs/posting-raw-events

**Comment by nblumhardt** [comment]
Thanks @SimonCropp 👍

**Comment by nblumhardt** [comment]
Done in the v5.1 beta docs: https://docs.getseq.net/v5.1/docs/posting-raw-events

**Comment by SimonCropp** [comment]
awesome. thanks
