### ISSUE TITLE
Feature Request: allow delete while auto-refresh

### ISSUE THREAD

**Issue by cilerler** [datalust/seq-tickets#792]
Please allow to hit the **Delete Matching Events** button, without toggle the **Auto-Refresh**.

**Comment by nblumhardt** [comment]
Hi Cengiz; do you mean auto-refresh (the little "infinity" icon-button) or just refreshing of the events display when deletion is initiated? Deleting events shouldn't turn on auto-refresh as things work today - sounds like a bug if this is happening for you. Thanks!

**Comment by cilerler** [comment]
Hi Nicholas,

Correct, **Delete Matching Events** button is disabled while **Auto-Refresh** (the little "infinity" icon-button) is on.

However, I found myself doing the same pattern over and over again...

1. click to infinity button, 
2. click to drop down open, 
3. click to delete button, 
4. click to infinity button back again

and realized it would be really _nice to have_ feature if a simple delete button does it for me...

![image](https://user-images.githubusercontent.com/385958/52183939-124f0380-27db-11e9-995e-04fc2e3288d8.png)

**Comment by nblumhardt** [comment]
Thanks for the clarification. Is there any chance of using a [retention policy](https://docs.getseq.net/docs/retention-policies) for your scenario? Seq isn't really designed with manual deletes in mind (that's why we hide it away under _Settings > Retention Policies_), and they're executed rather inefficiently.

**Comment by cilerler** [comment]
Sorry about delayed response...

I don't think it will be good enough since I'm using Seq for debugging purposes and kind of need it to clean the logs before each session start _(most of the time, not always)_  

Right now either I do use date/field filters or doing the manual delete as I described.

For that being said, I understand your point too therefore please feel free to close the issue if you think it will cause unintentional effects.

Thank you for your attention Nicolas, as usual you are right at the spot 🤗

**Comment by nblumhardt** [comment]
Thanks for the follow-up, makes sense. If your debugging sessions don't attach a GUID `SessionId` property (one option for separating them), I often drop the "FROM" calendar control and choose "NOW" to get a clean start :-) ... Will close this as `wontfix` but will keep an eye on the scenario - thanks again.
