### ISSUE TITLE
Support plug-in apps targeting `netstandard2.x` TFMs

### ISSUE THREAD

**Issue by Hinni** [datalust/seq-tickets#793]
Hi seq team,

I'm trying to update my [Seq.App.aspsms](https://github.com/Hinni/Seq.App.aspsms/) nuget with Multi-Target Framework for Seq on Windows and Docker.
But when I try to test my package it could not load Newtonsoft.Json dependency. Doesn't Seq load dependencies automatically? I don't see an error installing the app.

![image](https://user-images.githubusercontent.com/3010444/52167075-e9b10600-2715-11e9-8a39-4cf88fe811a9.png)

I also noticed that Seq is trying to load the net452 and not the .NET standard 2.0 dlls.

Are there any information or instructions available on how an app for Seq 5.0 should look like? Interesting would be of course with availability on Windows and Linux.

Thanks for your feedback
Michael

**Comment by nblumhardt** [comment]
Build 5.1.2645-pre, on its way out now, includes the ability to host apps targeting `netstandard2.x`:

![image](https://user-images.githubusercontent.com/342712/52252312-7db8e280-294d-11e9-97ad-53e8ad51c4ee.png)

(The source for this one is at https://github.com/datalust/seq-input-rabbitmq).

How is the ASPSMS app going? Still issues running on the new version? Cheers!

**Comment by Hinni** [comment]
Hello, Nicolas. Thank you for your information about the new 5.1.2645-pre release. I will try it towards the end of the week, I won't get there before.
We've been using Seq for three years now and are very happy with the product. Since early Seq 5 prereleases I also use a private instance which runs as a docker on a Synology. I'm happy that you're busy developing Seq and that I can contribute a part to it.

**Comment by Hinni** [comment]
I'm almost done with [Seq.Input.AzureEventHub](https://github.com/Hinni/Seq.Input.AzureEventHub/pull/1). When do you publish 5.1.2645-pre on docker? I want to test this package locally, before I push it to the nuget store. Cheers!

**Comment by nblumhardt** [comment]
That's awesome, Michael! Just pushed 5.1.2669-pre, which should do what you're after. Let me know if you have any trouble with it!

**Comment by Hinni** [comment]
It don't work as expected on Seq. Maybe you has some ideas. I invited you to give me some hints in my [PR #1](https://github.com/Hinni/Seq.Input.AzureEventHub/pull/1). I uploaded a first preview version to nuget.org [Seq.Input.AzureEventHub](https://www.nuget.org/packages/Seq.Input.AzureEventHub/1.0.0-pre-20190209-004).

![image](https://user-images.githubusercontent.com/3010444/52521325-ee297180-2c75-11e9-9ed3-e1b027711b48.png)

How are Seq.Apps initiated on Seq?

**Comment by nblumhardt** [comment]
Hi Michael; if you click into one of those errors, is there any detail in the exception message/stack trace?

To run the app in Seq (5.x), the package is first extracted to a local filesystem folder, e.g. `Packages/nugetfeed-x/Seq.Input.AzureEventHub/1.2.3`. Seq then spawns a child process (`Seq.Apps.GenericHost`) with its working directory set to the location of the extracted package. The child process loads up the main `SeqApp` (or `Reactor`) type using reflection, and does some basic assembly loading redirection to remain compatible with 4.x apps, which could rely on a copy of `Serilog.dll` and a few other assemblies being present locally.

Once the child process has loaded, Seq starts reading through its `STDOUT` to ingest JSON-formatted events, and through `STDERR` to collect diagnostic events like the ones in the screenshot.

Not sure how much of this info is useful, but might help with interpreting the exception message if we're lucky :-) Cheers!

**Comment by nblumhardt** [comment]
Going to close this issue, since the app is now loading, but please send any questions related to the new input that we might be able to help with 👍
