### ISSUE TITLE
Theme selection by command parameter / environment variable

### ISSUE THREAD

**Issue by SeriousM** [datalust/seq-tickets#796]
Hi,

we're using seq not only in production but as development tool in combination with docker.
We use the dark theme as it's more pleasant for the eyes and I would like to start the seq server (docker) with the dark theme per default.
Could you enable this feature please? It would make the product muck more nicer for us :)

Thank you!

**Comment by nblumhardt** [comment]
Hi Bernhard!

One option is to map a persistent volume for your development container, e.g. `-v /path/to/seq/data:/data`.

This might turn out to be made possible by the underlying mechanism by #791, if we come up with a way to execute API commands during container start-up, but it's currently a bit of a long shot.

Hope this helps,
Nick

**Comment by SeriousM** [comment]
Binding a path/volume could be possible but is pretty cumbersome if you have more than one developer.
I would love to have something like "-dark" or "--theme=dark" to overrule the current default setting.
Anyway, this issue isn't solved soon. Shall I close it?

**Comment by nblumhardt** [comment]
Thanks for the reply, Bernhard. Yes - we'll keep it in mind, but I agree we probably won't have a solution in the immediate future (....unless we were to switch the default theme..... :-)) - Closing for now; thanks!@
