### ISSUE TITLE
API key login for dashboards

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#799]
From #565. When dashboards are displayed on information radiators, it's inconvenient to log in. For some situations, loading up the dashboard using an `&apiKey=....` URL parameter (where the API key is a read-only key) is preferable.

Note that although Seq will remove the API key from the URL once the dashboard is rendered, there are still security considerations around having the API key in the URL that users should take into account.

**Comment by nblumhardt** [comment]
Dashboard URIs now support `apiKey` and `theme` arguments:

http://localhost:5341/#/dashboards?dashboardId=dashboard-14&range=2h&group=1m&refresh=10s&apiKey=PQJZfDs4paIFHIYe94Ic&theme=dark-theme&maximized

Results in:

![image](https://user-images.githubusercontent.com/342712/52612583-1e6f4b00-2ed6-11e9-85b0-0a19143f7f7e.png)

Un-maximizing the dashboard shows:

![image](https://user-images.githubusercontent.com/342712/52612598-2c24d080-2ed6-11e9-928f-b40b0dba0e36.png)

No other application screens support this mode; choosing `LOG OUT` will return the app to the login screen.

**Comment by andymac4182** [comment]
THANKS @nblumhardt !!!! 
This is awesome 😄 	😂
