### ISSUE TITLE
Cache headers missing from *.js UI assets

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#801]
Via: https://docs.getseq.net/discuss/5c651eb3f595760013035911

The UI JavaScript assets are assigned unique filenames to enable caching, but we're not setting headers appropriately to enable caching in all cases.

**Comment by andymac4182** [comment]
This explains why our Singapore server is a little slow 👍

**Comment by raybooysen** [comment]
Funny story,I raised this because I have trouble accessing in Singapore. :)
