### ISSUE TITLE
Is getseq.net/Download/Begin?version=latest documented/supported?

### ISSUE THREAD

**Issue by taspeotis** [datalust/seq-tickets#803]
Hi team,

I'm writing a PowerShell script to install Seq onto a developer's machine when they start working with us. Ideally the script would always download and install the latest version.

https://getseq.net/Download lists downloads by version, with corresponding URLs like https://getseq.net/Download/Begin?version=5.0.2497. I tried `version=latest` and it worked (and on a lark: `version=oldest` ... but that didn't work).

However I can't find any documentation that suggests this URL should be valid in the first place, or will remain valid in to the future.

Could someone please clarify it in documentation or just shoot down this idea? Thanks.

**Comment by nblumhardt** [comment]
Hi Todd! Nice spotting :-) ... yes, `.../latest` has been there for a long while now, we'll continue to support it. (IIRC, `.../latest-pre` will get the latest preview, too.)

Best regards,
Nick

**Comment by taspeotis** [comment]
Thank you for that information
