### ISSUE TITLE
Sequence equality operator in signals and queries

### ISSUE THREAD

**Issue by Moophic** [datalust/seq-tickets#811]
We're missing sequence equality operator a lot.

Current approach: `Attribute[0] = 'value1' and Attribute[1] = 'value2'`
Proposed syntax: `Attribute = ['value1', 'value2']`

This would bring additional value to many use cases.

**Comment by Moophic** [comment]
Also, having this implemented, it would be nice to have an additional buttons to add filters by exact match for array attributes and display it as a column (as is).

![image](https://user-images.githubusercontent.com/12990805/53575251-d6a91e80-3b79-11e9-9178-efff6ddef8eb.png)

**Comment by nblumhardt** [comment]
Thanks for the suggestion! We'll take a close look at this 👍

**Comment by nblumhardt** [comment]
We're hoping to cover structural equality with this change, too, since the `EventId` structure is so frequently encountered in ASP.NET Core logs:

![image](https://user-images.githubusercontent.com/342712/82284331-1e64d180-99dc-11ea-842e-1866cd876f6b.png)

**Comment by nblumhardt** [comment]
Nearly there....

![array-equality](https://user-images.githubusercontent.com/342712/82290227-c3d27200-99e9-11ea-98d5-65854b685e89.gif)

**Comment by Moophic** [comment]
Looks awesome! :)
