### ISSUE TITLE
Feature Request: Add IN operator

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#814]
Suprisingly i just noticed that `IN` is not supported, e.g. `@Level IN ('Error', 'Warning')`

**Comment by nblumhardt** [comment]
Hi Robin, thanks for the note.

Seq uses `[]` array notation for `in` - so you need to write:

```
@Level IN ['Error', 'Warning']
```

(Admittedly it's a bit of a deviation from SQL; we ended up taking this path for symmetry with cases like `'foo' in Tags` where `Tags` is an array-valued property.)

HTH,
Nick

**Comment by Suchiman** [comment]
Ah cool, is this in the documentation? i couldn't find it.

**Comment by nblumhardt** [comment]
It should be :-) but I can't find any mention of it - I'll update the documentation for 5.1 and make sure it's covered, thanks!
