### ISSUE TITLE
Misaligned query error details

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#826]
In v5.0, query error details are aligned left:

![image](https://user-images.githubusercontent.com/342712/55213004-b2eefc00-523d-11e9-8e59-4ce9028b2fad.png)

In v5.1 this has regressed and there's now an indent because of the underlying ul/li:

![image](https://user-images.githubusercontent.com/342712/55213038-cdc17080-523d-11e9-835d-a889b7047e84.png)

**Comment by tsimbalar** [comment]
wow, that's a complete show-stopper ! 😜

**Comment by nblumhardt** [comment]
:-D getting into the nitpicks while we regression-test 5.1.
