### ISSUE TITLE
Searching through archived ESENT segments slow in 5.1; convert to FLARE in place?

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#837]
We've just upgraded from 4.1 to 5.1 😀 so we have a lots of esent history and the current extent is also still esent. Now i don't have precise numbers since i didn't measure before the upgrade but it feels like searching through archived segments is an order of magnitude slower. The search Speed varies wildly but one sample size is 25k events in 5 seconds.

Interestingly, it seems to have sped up once it crossed from the current extent into the previous extent, managing over 25k events per second… to slow down again a while later.

It also seemed to get stuck for 30~60s at the transition between in-memory and on-disk i believe, it searched in a second through 500k events and then sit there, not going progressing. But this didn't reproduce reliably and when checking diagnostics page it claimed to have 1 million events in memory.

All in all, it's weird and somehow slower than before but i can't put my finger on it why. I just hope it's going to be awesome when it switches to flare 😃

**Comment by nblumhardt** [comment]
Hi @Suchiman - thanks for the note!

Indeed there's a bit of a performance hit for ESENT in v5+, noticeable if you use `@EventType` / `$nnnnnnnn` filters to speed up searches a lot.

Version 4 optimizes queries by comparing event types with an explicit `EventType` column in the underlying ESENT storage.

Version 5 uses signal indexes to achieve a similar result, but for all signals rather than just those based on event types, and version 5.1 adds the new pre-filtering optimization to extend this to more types of queries.

Unfortunately, in the process, the ESENT optimizations were dropped in order to conserve our complexity budget. In hindsight, this might not have been the best choice, given that the penalty occurs immediately after upgrading. On the plus side, once data is in the new storage engine, you should see something approach an order of magnitude improvement in the _other_ direction 😁.

Is your event history long, or is it just heavy with recent data? If it's recent data then things should naturally improve in a week or two. If the history is long, let me know, we'll put our heads together and see what kind of conversion process might be possible (we're aiming to convert old ESENT data to the new format in the next major version).

**Comment by Suchiman** [comment]
We have 120 days of history in seq with about 60 million events in total, writing around 3500 events per minute on average busy hours, of which it keeps around a day in memory. The current extent expires today so it should improve soon.

**Comment by nblumhardt** [comment]
Great - thanks for the follow-up.

(One day/500k events doesn't sound like a lot of events to get into memory - is it a tiny machine?)

**Comment by Suchiman** [comment]
It's a 2 Core 4GB VM in Azure. It used to be able to hold more events in memory, i think i'm going to have to bump the the VM size in the comming days.

**Comment by nblumhardt** [comment]
:+1: 4 GB is workable but sounds pretty lean for that amount of data retention. (Also the standard 100 IOPS HDD?)

If the number of events in RAM is down, sometimes that can mean some larger events are coming in; there are some queries in https://blog.datalust.co/which-events-are-taking-up-the-most-space-2/ (guessing you've seen it) that can help to track them down.

Keep us posted! :-)

**Comment by Suchiman** [comment]
You might have missed this part though
> checking diagnostics page it claimed to have 1 million events in memory.

**Comment by nblumhardt** [comment]
Ah, sorry 😊 .. multitasking a bit!

**Comment by nblumhardt** [comment]
Related discussion: https://docs.datalust.co/discuss/5cb4108357b3570039a0b8ff

**Comment by Suchiman** [comment]
Quite odd, just yesterday i've observed again that Seq was searching in an instant to around 526k Events back in time, then getting stuck there and not progressing for a while, then bringing up the "searching through archived segments" warning, even though it has at least a million events in memory, then continuing the search through events at a seemingly much slower rate than usual. I wonder if this might be related to #845

**Comment by nblumhardt** [comment]
Interesting - might need to dig through the diagnostic report (_Settings > Diagnostics > Download full diagnostic report_) if it's possible to send one through to support@? Thanks for the update :+1:

**Comment by nblumhardt** [comment]
The upcoming 5.1 patch will include `seq migrate` to perform an (offline, at this stage) migration from ESENT to FLARE. I think we can close this ticket, but keep #845 to track in case this change is insufficient to get you back up and running smoothly.

**Comment by taspeotis** [comment]
Thanks for the hard work as always, @nblumhardt.

**Comment by nblumhardt** [comment]
Thanks @taspeotis !

**Comment by nblumhardt** [comment]
Build 5.1.3093 is now available at https://datalust.co/download, and includes `seq migrate` for this purpose.

```shell
> seq help migrate
Seq migrate [<args>]

Move all event data to the FLARE storage engine

Arguments:
  -n, --name=VALUE           If multiple Seq instances are in use, the name of
                               the instance
  -s, --storage=VALUE        Specify the folder where data for this instance
                               is stored; C:\ProgramData\Seq(\Instance\[Name])
                                is used by default.
```

The Seq instance will need to be stopped in order for this command to be run. The process will need at least as much free disk space as the largest extent.

Migration could be slow if the disk storage is slow - it's okay to stop the process at any time with Ctrl+C if necessary. Let us know if the time per extent is prohibitive: a partial-offline migration is possible but requires some more manual steps.

Once the process is complete, Seq will need to index the newly-migrated extents. This could take hours depending on storage speed, but will happen in the background. It will be best if Seq is left alone for at least an hour for things to settle.

Hope this all helps, and looking forward to hearing how it goes!
