### ISSUE TITLE
Completely collapse signal groups

### ISSUE THREAD

**Issue by nskerl** [datalust/seq-tickets#841]
Signal groups are great, but when we have a large number of items within a group and a significant number of items are selected, the group collapse doesn't actually reclaim much real estate.  

I would prefer that the group completely collapse and change color at the top level to indicate _one or more_ items within the group have been selected.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, we'll take a look at this 👍

**Comment by nblumhardt** [comment]
Hi Nathan, just looking at this after reviewing the earlier "double-click" suggestion, we realize we're having trouble imagining the kind of groups that would cause this limitation to surface. Is it possible you could provide a bit of scenario info (here or to support@datalust.co ) that describes the kinds of signals/groups you hit this with? Many thanks!

**Comment by nblumhardt** [comment]
See also #853

**Comment by nblumhardt** [comment]
Thinking back to this, negatable signals should address the underlying cause, so we'll close this and leave the latter ticket open.
