### ISSUE TITLE
UNC Feeds no longer working

### ISSUE THREAD

**Issue by wokket** [datalust/seq-tickets#842]
G'day guys,

We've been using an internal file share configured as a feed via UNC (`\\internal.server\SeqFeed`)  to work around some proxy issues, We've just updated to V5 and that feed no longer honours the file share component of the path, instead looking at the local file system as it returns the error:

`Could not find a part of the path 'C:\SeqFeed\Searched.Package.nupkg'.`

It's been a while since we went to install a new App so unfortunately I can't tell you exactly when this behaviour changed :(

**Comment by KodrAus** [comment]
Thanks for the report @wokket, we’ll dig into this and let you know what we find.

**Comment by KodrAus** [comment]
Hi @wokket, it looks like this regressed when we moved from full framework to .NET Core as part of the original 5.0 release, where UNC paths are now being rooted incorrectly as local paths.

We've added this to our next patch milestone. As a workaround in the meantime, you could set up a hosted internal NuGet feed, or create a local feed on your Seq server.

**Comment by KodrAus** [comment]
Hi @wokket,

Are you running `5.0` or `5.1`? We updated our .NET SDK between these releases that might've made a difference for this.

**Comment by wokket** [comment]
Hi, we're on V5.1.3 exhibiting the problem.  We skipped the 5.0 versions so I can't comment whether the regression occurred on the major or minor increment.

**Comment by KodrAus** [comment]
Thanks for the extra info @wokket :+1: we’ll keep digging.

**Comment by KodrAus** [comment]
Hi @wokket , just an update: we've got a pre-release build of `5.1` that should fix this issue. If you're interested in giving it a go in your environment then drop us a line at support@datalust.co and I'll pass it along!

**Comment by nblumhardt** [comment]
We'll ship this shortly in the upcoming 5.1 patch
