### ISSUE TITLE
Visualize hierarchical logging/distributed tracing

### ISSUE THREAD

**Issue by ngbrown** [datalust/seq-tickets#844]
My services include [hierarchical RequestId](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/HierarchicalRequestId.md) information.  I would like to visualize it with a timeline or flame chart.
An example is https://www.jaegertracing.io/docs/1.10/

I don't know if plugins are allowed to make changes to the UI. If they are, then this would be a good plugin.

**Comment by nblumhardt** [comment]
Thanks :+1: - I think it's time we investigated/started assembling a position or plan-of-attack for hierarchical request ids/tracing.

**Comment by nblumhardt** [comment]
Note #1011, which calls attention to OpenTelemetry.

**Comment by ngbrown** [comment]
Since I created this issue, .NET Core 3.0/3.1 has now added support for more formats, namely `ActivityIdFormat.W3C`. Evidently this will be [the default format for .NET 5.0](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.defaultidformat).  I still use `ActivityIdFormat.Hierarchical` in my services.

When the request comes from the browser, I generate/rotate a random root activity id every time the displayed url changes.  This is then passed on in any requests to the back end and all the services add to the hierarchy for any nested requests.

When I want to trace a stream in my logs, starting from a log entry of interest, I click on the green filter checkmark for the `RequestId`, then I have to manually edit the query to use a `LIKE` and the wildcard (%), and run the query again:

```
RequestId LIKE '|e94fd8c4-42891a2d35276580.%'
```

Ideally this feature would do all that automatically.  It would automatically find the root activity id, start the top level query, and then show a timeline graph.

It would show the whole hierarchy of requests in a timeline sort of like the overview pane of the network tab in Chrome Dev tools.  Or a flame graph (like on Chrome's performance tab) if that's better.  The horizontal axis would be time (with at least relative ms/seconds displayed). The vertical axis would be top level parent activity Id at the top, and each layer down would be a nested activity id from any service feeding it's logs into Seq.

Then, I can click on any segment of the graph, and see everything from that level down. (Again, using the LIKE and wildcard in the correct level).  Maybe a Ctrl+Click on a segment would filter to only that service, not including the nested calls.

For colors on the bars, I think re-using the same color for the same service (I use `ApplicationName`) would be helpful.  If there are any errors or warnings, the graph could show warning/error icons or colors on those sections automatically.

I haven't used any of the other products available on the market for hierarchical RequestId or OpenTelemetry, but the above is what I would expect out of that sort of feature.
