### ISSUE TITLE
The results of SQL query with a large number of columns are hidden

### ISSUE THREAD

**Issue by adamchester** [datalust/seq-tickets#851]
If you create a SQL query with a large number of columns, then display the results in a data grid, the results pane doesn't allow you to scroll right. This makes it difficult to quickly visualise the data in your query.

The work around is to export to CSV and use Excel or something to view the data.

**Comment by nblumhardt** [comment]
![overflow-data](https://user-images.githubusercontent.com/342712/82514059-00bc7700-9b58-11ea-86a8-86bf7ec7ca6b.gif)
