### ISSUE TITLE
An SQL query with conflicting filter and timestamps produces unhandled error

### ISSUE THREAD

**Issue by adamchester** [datalust/seq-tickets#852]
If you create a SQL query that contains something like:

```sql
@Timestamp >= DateTime('2019-04-01 00:00:00') and @Timestamp <= DateTime('2019-04-30 23:59:59')
```

in addition to a timestamp filter such as:

![image](https://user-images.githubusercontent.com/570470/57995910-e5172e80-7b07-11e9-88b4-891ee1341b84.png)

It results in an error similar to above.

The expected result is a decent message suggesting you've created a conflicting query, or perhaps just return zero results (without an error message).

**Comment by nblumhardt** [comment]
Thanks, Adam 👍
