### ISSUE TITLE
Negatable Signals

### ISSUE THREAD

**Issue by penenkel** [datalust/seq-tickets#853]
I often use signals to group events of a certain type/category/use-case. Depending on what I'm working on, I then want to see either *only* those events belonging to the signal or all events *excluding* those.

As far as I can tell there is currently no way to apply a signal negated, so that it excludes all events that it matches. 

I would appreciate if such a functionality could be added.

**Comment by nblumhardt** [comment]
Thanks for the suggestion. We've had this in the backs of our minds for some time 👍 

The main implementation challenge is to find an obvious/accessible UI for it. Some options like double-clicking to exclude suffer from discoverability problems; a "-" somewhere on the signal itself would be confusing without a "+", and within signal groups (where signals are generally mutually exclusive, and selections are unioned,) deselecting a signal is equivalent to excluding it, as long as another signal within the group is already selected, so there's some potential quirkiness to consider.

Ideas most welcome!

**Comment by nblumhardt** [comment]
Implementing this may have the side-effect of covering #860 as well, since retention policies are based on signal expressions. 🤔
