### ISSUE TITLE
Implement the HEALTHCHECK directive in the datalust/seq container

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#863]
[`HEALTHCHECK`](https://docs.docker.com/engine/reference/builder/#healthcheck) adds an additional mechanism to detect failed services. It seems like a worthwhile addition if it can be added without substantial overheads.

**Comment by nblumhardt** [comment]
We'll investigate this in future

**Comment by baumheld** [comment]
Since the HEALTHCHECK directive is baked into tho Dockerfile, shouldn't it show `(healthy)` when doing `docker ps`?

![image](https://github.com/datalust/seq-tickets/assets/141740877/84d3ebf2-f608-451e-abef-9d1dd72fc3c1)

**Comment by nblumhardt** [comment]
Hi! The `datalust/seq` image doesn't use `HEALTHCHECK` currently.

You can build a derived image with one using something similar to:

```
HEALTHCHECK CMD /seqsvr/Client/seqcli node health -s http://localhost/
```

If you decide to give this a shot, it'd be interesting to hear how it all comes out.

Best regards,
Nick

**Comment by nblumhardt** [comment]
In UDP mode, no; using TCP an external TCP health check should be possible (would need some investigation).

**Comment by mloskot** [comment]
For the sake of users who search for the `healthcheck`, it can be achieved with curling at [/health](https://datalust.co/docs/server-http-api#health) endpoint:

```yaml
healthcheck:
  test: ["CMD", "curl", "-f", "-s", "http://localhost:5341/health"]
```
