### ISSUE TITLE
Enhanced filtering and sorting of API Keys

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#868]
We have like 150+ API keys and are constantly adding more as we change our serilog sinks to Seq. The existing search box helps us by finding API Keys by name.

Additionaly, it would be great to have the following features:

- [x]  Filter API Keys by "Applied properties". This would help us to identify all "production" or "qa" API Keys and see theri ingestion rates.

- [x] Filter by "Level" to quickly identify "incorrectly" set levels, e.g. "Debug" with a "production" property

- [x]  Sort by "Events arrived", "Events accepted" and "Ingested data". We once had an incorrectly configured application which logged too many / large events and hence clogged our disks. With sorting by "Ingested data", it would be easier to identify the responsible app.

Maybe you could look into these features for one of the next releases.

**Comment by nblumhardt** [comment]
Thank you for the suggestions.

"Filter API Keys by Applied Properties" is already implemented, at least insofar as typing either the property name, or value, into the filter box will identify them.

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/67545539-d24ef880-f73c-11e9-9766-eddd00bb1380.png)

**Comment by Sebbl22** [comment]
Very nice, thank you!
