### ISSUE TITLE
Add a built in property for IP Address

### ISSUE THREAD

**Issue by bleevo** [datalust/seq-tickets#871]
Allow a query to be written that returns all messages for the remote users IP

`RemoteIPAddress = CurrentUserIP`

So you dont have to lookup your IP address

**Comment by nblumhardt** [comment]
Hi Chris, thanks for the suggestion - we'll give this some thought.

Best regards,
Nick

**Comment by nblumhardt** [comment]
Hi Chris,

We've looked into options for implementing this and decided that, for now, having the client application enrich events with their IP, machine name, or other identifying properties, should provide a better user experience than what we can achieve using IP address. (Let me know if you'd like details on how this might be set up with Serilog etc.)

We wouldn't rule out implementing this in the future, but as it won't make the cut for our next major release we'll close the ticket for now.

Thanks again for the feedback!
Nick
