### ISSUE TITLE
Logging to seq when the seq server is offline throws exceptions and bring the app offline

### ISSUE THREAD

**Issue by THammond9** [datalust/seq-tickets#881]
Much like the title says, the app is fine when the seq server is online but when the server goes offline for any reason the application starts throwing exceptions and then the application goes down. I do not want logging to bring down the application and I cannot find anything in the documentation that shows how to suppress these exceptions. I am guessing this is some kind of bug then since I cannot imagine that it would be intended to bring down applications in this scenario.

Using
MVC 5
NLog

> protected void Application_Error(object sender, EventArgs e)

is implemented but does not seem to matter. The exception below is being written to the internal nlog error file.

> Error has been raised. Exception: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at Seq.Client.NLog.SeqTarget.PostBatch(IEnumerable`1 events) in C:\projects\seq-client\src\Seq.Client.NLog\Client\NLog\SeqTarget.cs:line 98
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)

**Comment by nblumhardt** [comment]
Thanks for the note! It looks like you're using the outdated `Seq.Client.NLog` package; there has been quite a bit of improvement in its replacement `NLog.Targets.Seq`: https://github.com/datalust/nlog-targets-seq

Any chance you can switch to the (very similar, but much improved) replacement?

Best regards,
Nick

**Comment by nblumhardt** [comment]
(Also/if not, do you have a log of the exception caught in `Application_Error()`? It should show more frames than the one logged internally by NLog.)

**Comment by THammond9** [comment]
Sorry I got to this page from google and did not check that this was correct package. Actually we are using Seq.Client.NLog v 2.3.24. Just to confirm this is not the most current package? I see that there seems to some development on this package since we originally added it. There is no exception logged in Application_Error(), just the internal error for nlog.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. No, _Seq.Client.NLog_ is the older package; it's had some bug fixes, but the majority of effort now goes into _NLog.Targets.Seq_, which has the advantage of fully supporting structured logging with [message templates](https://messagetemplates.org).

**Comment by THammond9** [comment]
I just have one more question: In the new package, is it expected that when the seq server is offline exceptions will be thrown, bringing down the application that is logging? If the reported behavior is still expected then if would just save me some time trying to test something that may still not be addressed in the new package.

**Comment by snakefoot** [comment]
@THammond9 NLog puts a great effort in suppressing all exceptions during logging. This is also happens for external targets like the SeqTarget.

BUT if you are using the config setting `throwExceptions="true"` then you are running in unit-testing-mode (NOT recommended for production systems). This means all exceptions will trickle up and take down the host-application if you are not careful.

**Comment by THammond9** [comment]
Thank you for answering this for me.` throwExceptions="false"` is set but _Seq.Client.NLog v 2.3.24_ still throws exceptions when the seq server is offline. I just wanted to make sure the if I change to _NLog.Targets.Seq_ that the expected behavior is that exceptions will not be thrown if the server is offline. Again, thank you for clarifying this point for me. I will change to this new package and test that the app is not affected if seq is offline.

**Comment by nblumhardt** [comment]
Hi @THammond9, did you have success with _NLog.Targets.Seq_? Cheers!

**Comment by THammond9** [comment]
I haven't been able to test yet. I probably won't get to it until later next week but based on the replies above I am cautiously optimistic that the application won't crash.

**Comment by nblumhardt** [comment]
Thanks for the reply; yes, it'd be extremely surprising for it to crash (although I'd also have said that regarding the earlier package!)

I'll re-open just so that we remember to check in.

**Comment by nblumhardt** [comment]
Hi again :-) ... Any luck with this, @THammond9 ?

**Comment by THammond9** [comment]
Have not had a chance test this yet, but I think I will get to it tomorrow or Thursday.

**Comment by THammond9** [comment]
HI, I am trying to test this issue but it seems that when I updated the package to _NLog.Targets.Seq_ the existing target configuration in the nlog config no longer works. Specifically, the `minlevel` and `levels` attributes do not seem to work. If I intentionally throw an error the message appears in seq but Info level messages do not appear.

The nlog config file looks like this:

```xml
<nlog
  xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  throwExceptions="true"
  throwConfigExceptions="true"
  internalLogFile="c:\Logs\nLog-err.txt"
  internalLogLevel="Warn">
  <targets>
      <target 
        xsi:type="File" 
        name="GeneralLogger" 
        archiveEvery="Day" 
        autoFlush="true" 
        createDirs="true" 
        concurrentWrites="true" 
        maxArchiveFiles="30"
        fileName="C:/Logs/debug/NLog/${shortdate}.log" 
        layout="${shortdate}|${time} |${threadid}|${level}|${message}|${callsite}}|${exception:format=tostring}" />

      <target 
        xsi:type="File" 
        name="GeneralErrorLogger" 
        archiveEvery="Day" 
        autoFlush="true" 
        createDirs="true" 
        concurrentWrites="true" 
        maxArchiveFiles="30"
        fileName="C:/Logs/debug/NLog/${shortdate}.log" 
        layout="${shortdate}|${time} |${threadid}|${level}|${message}|${exception:format=tostring}|${callsite}|${callsite-linenumber}" />
        <target name="seq" xsi:type="Seq" serverUrl="http://<ip address>:5341" apiKey="API Key">
            <property name="iis-site-name" value="${iis-site-name}"/>
            <property name="SourceContext" value="${logger}"/>
            <property name="EnvironmentUserName" value="${windows-identity}"/>
            <property name="MachineName" value="${machinename}"/>
            <property name="Base Directory" value="${basedir}"/>
            <property name="Stack Trace" value="${stacktrace}"/>
        </target>
    </targets>
  <rules>
    <logger name="*" levels="Trace,Debug,Info" writeTo="GeneralLogger"/>
    <logger name="*" levels="Warn,Error,Fatal" writeTo="GeneralErrorLogger"/>
    <logger name="*" minlevel="Info" writeTo="seq"/>
 [and also this was tried:]
    <logger name="*" level="Info,Warn,Error,Fatal" writeTo="seq"/>
  </rules>
  <extensions>
    <add assembly="NLog.Targets.Seq"/>
  </extensions>
</nlog>
```

**Comment by nblumhardt** [comment]
Thanks for the follow-up!

Using a process of elimination might work best; if you're able to replace your _NLog.config_ with the tested example here:

https://github.com/datalust/nlog-targets-seq/blob/dev/sample/Example/NLog.config

then add back in the other sinks, properties, and so on, then the problematic configuration item should become clear.

Does that sound like a workable plan of attack?

Best regards,
Nick

**Comment by THammond9** [comment]
Thanks, I was able to start logging info level messages to seq.

**Comment by nblumhardt** [comment]
👏 

Once `throwExceptions="false"` is set, if you run into any further issues please let us know. Happy (N)Logging! 😁
