### ISSUE TITLE
UI Improvement - Retention - Make "All Events" more visible

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-tickets#891]
Hi,

maybe just a suggestion for a UI improvement, when configuring the Retention policies.

<img width="583" alt="image" src="https://user-images.githubusercontent.com/160544/65939590-a767d200-e426-11e9-8985-aa658acda566.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/160544/65939613-afc00d00-e426-11e9-84c3-9cd67390a3b5.png">

When the "Delete" drop-down list is open, it's not super clear that the first item means "All Events". I know it's also written underneath, bu maybe it would be helpful to have a name for that option in the list.

something like : 

<img width="421" alt="image" src="https://user-images.githubusercontent.com/160544/65939728-01689780-e427-11e9-845d-b3092b1c58cb.png">

it's not very nice, but it's a bit more explicit :P 

(seen on Firefox on MacOS)

**Comment by nblumhardt** [comment]
Thanks @tsimbalar , we'll do this 👍

**Comment by nblumhardt** [comment]
The (very, very early) 6.0 preview now at https://datalust.co/download and `datalust/seq:preview` on Docker Hub now include this. Would be great to get your feedback on how this turned out, if you have a chance to take a look. Thanks again!

**Comment by tsimbalar** [comment]
Just took a look, and this looks fine 👍 

<img width="568" alt="image" src="https://user-images.githubusercontent.com/160544/68106487-0e731d80-fee2-11e9-8c1b-2ffa8ca4d66c.png">


Just a doubt, maybe it has always been this way ... I see that when creating a new Retention policy, those are the defaults : 

<img width="640" alt="image" src="https://user-images.githubusercontent.com/160544/68106525-29459200-fee2-11e9-96b1-25870a920acc.png">


i.e. by default, delete ALL events NOW .

Looks like there might be a risk of shooting oneself in the foot here 🤔  

Is there any legit scenario where a policy that deletes events **after 0 days and 0 hours** should be acceptable ? In that case it sounds more like a "if you want to delete events, do it this other way" suggestion would be better ? 

maybe that's a completely separate issue though, and not so much of a problem ... I'll let you triage this the way you want it :P

**Comment by nblumhardt** [comment]
You're right - it's a bit of a risky default. A better duration picker would help, here, but we'll look at changing it to, say, 30, to avoid the worst footgun in the meantime 👍
