### ISSUE TITLE
Attached properties for custom inputs

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-tickets#892]
Slightly related to https://github.com/datalust/seq-tickets/issues/832 

I'm currently making good use of the "HTTP Health Checks" (https://www.nuget.org/packages/Seq.Input.HealthCheck/)  and "Certificates Check" (https://www.nuget.org/packages/Seq.Input.CertificateCheck/) apps.

I'm building a generic dashboard to show the results of those healthchecks , and it would be great if there was a way to easily identify all the events that come from the same app. (i.e. a different instance of the app, but the same app), for instance if all the events generated by the apps had extra properties like `appId` or some sort of identifier that allows to group them.

I'm currently using the Message Template, but we could imagine that : 
- this template changes some day if I update an app
- an app may generate multiple kinds of messages with different templates.

Thanks !

**Comment by nblumhardt** [comment]
Thanks for the note, Thibaud. This is part of something we've been discussing as a reorganization of inputs and API keys, where a custom input would get the same options (attached properties, filters, etc.) that individual (HTTP) API keys currently get.

I'll slip this into our 6.0 list as a touch point to make sure we consider it before shipping the next major version, but depending on how the release comes together, it may need to slip to a later milestone.

Thanks again!

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/81247485-78b97600-905d-11ea-8500-70c81bc1e12f.png)

**Comment by nblumhardt** [comment]
This is done - and sparked a big unification of inputs across unauthenticated HTTP, API keys, and plug-ins. More on that to come :-)

**Comment by nblumhardt** [comment]
Marking this as a duplicate of #832, which evolved to incorporate this :-)
