### ISSUE TITLE
Seq Nuget client not correctly following links 

### ISSUE THREAD

**Issue by benPearce1** [datalust/seq-tickets#893]
I am receiving a `404` response when attempting to install a Nuget package from https://f.feedz.io/octopus-deploy/dependencies/nuget/index.json.
Using the v2 Nuget feed (https://f.feedz.io/octopus-deploy/dependencies/nuget) also produces a `404` response.

The specific package that I am trying to install on my Seq installation is `Seq.App.VictorOps`. 

Seq version `5.1.3200` gives the error: `Response status code does not indicate success: 404 ().`
The same package from the same feed is installing successfully on `5.1.3000`.

It appears that the NuGet client within Seq is failing to follow the links in the response as it is trying to download the package from `/octopus-deploy/dependencies/nuget/v3/registration-gz-semver2/seq.app.victorops/0.1.0.json` 
The link in the response that should be used is `/octopus-deploy/dependencies/nuget/v3/registration-gz-semver2/seq.app.victorops/0.1.0/index.json`.
The `version.json` request URL is a convention used by Nuget.org.

The above feeds are public so you can use these for testing.

**Comment by nblumhardt** [comment]
Thanks for the report, @benPearce1! Makes sense, we'll take a look 👍

**Comment by KodrAus** [comment]
Hi @benPearce1 :wave:

It would be great to support `feedz.io` package feeds. Do you need to use the V2 protocol, or are you able to use V3? We do have a little more work to do in the V3 implementation to support `feedz.io` specifically, but it should just be a matter of following more of the hypermedia protocol.

**Comment by benPearce1** [comment]
Hi @KodrAus,

Not forced to use either the v2 or the v3, but they are both failing with a 404.

**Comment by nblumhardt** [comment]
Fixed for the v3 protocol in the upcoming 6.0-pre build. We will reevaluate v2 support in the future but haven't investigated it and would prefer to concentrate our effort on the newer protocol version. Perspectives/feedback welcome on this :-)

Thanks again for the report! An MSI/image will be available in the next couple of weeks.

**Comment by nblumhardt** [comment]
Just checked the v2 failure, it's a 404 on:

```
https://f.feedz.io/octopus-deploy/dependencies/FindPackagesById()?id='Seq.App.VictorOps'
```

Note the missing `nuget` element in the path. Adding a trailing `/` to the v2 feed base URL fixes it.

I think we can make a fairly safe change here and consider v2 feed URLs as referring to "directories" even without the trailing slash. Will reopen.

**Comment by droyad** [comment]
Awesome thanks. I just checked and MyGet also doesn't have a trailing `/` in the URL they advertise for v2

**Comment by KodrAus** [comment]
Hi @benPearce1 @droyad :wave:

Just an update here that we've got a preview build (`6.0.3342-pre`) out now that should support `feedz.io` 🎉
