### ISSUE TITLE
Resource limits  - Helm Chart - Configuration

### ISSUE THREAD

**Issue by tanwarsatya** [datalust/seq-tickets#908]
During identifying a memory usage issue in Kubernetes deployment we had to enable the resource limits for seq container. It would be easier/beneficial to have those options expose via configuration in helm chart.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, this sounds very reasonable - we'll take a look.

**Comment by KodrAus** [comment]
Hey @tanwarsatya :wave:

The chart values include a comment block with some example resource limits in them, that should be picked up by the chart if you comment them out. Does this cover what you need?

**Comment by KodrAus** [comment]
I'll go ahead and close this one for now, but please feel free to re-open or create new issues if something new comes up!
