### ISSUE TITLE
Presence of "Require authentication for HTTP/S ingestion" checkbox is misleading when authentication is not enabled

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#910]
In _Settings > API keys_, the checkbox "Require authentication for HTTP/S ingestion" should only be shown when authentication is enabled. If authentication is not enabled (via _Settings > Users_ at initial setup, or _Settings > System_ otherwise), this setting has no effect.

**Comment by CrossBound** [comment]
For what it's worth I totally agree, it was confusing to me when I first started using Seq.
