### ISSUE TITLE
Firefox: can't create user as passwords never match (built-in password manager in use)

### ISSUE THREAD

**Issue by zbecknell** [datalust/seq-tickets#914]
**Problem**

When attempting to create a user in Settings > Users > Add User the `Repeat password` field never matches, keeping the save button disabled.

No browser errors were observed.

Reproduced on both Windows and Mac with Firefox 70 and 71.

**Workaround**

Use Chrome to create the user.

**Comment by nblumhardt** [comment]
Thanks for the report, @zbecknell :+1:

Which Seq version are you using? I can't repro with Seq 5.1.3200 and Firefox 71 on Windows:

![image](https://user-images.githubusercontent.com/342712/70361262-a773ca80-18cc-11ea-9859-c0d8e14c3683.png)

but I do remember there being issues in some earlier Seq versions. I also am not using Firefox's built-in password manager; if you are, that might be the difference 🤔 ..?

**Comment by zbecknell** [comment]
Yes, that's the difference.  In a private window (where the password manager doesn't try to autofill), the password properly validates, so it's the built-in password manager causing some shenanigans.

**Comment by nblumhardt** [comment]
Thanks for the follow-up; it looks like [as of Firefox 67](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#Preventing_autofilling_with_autocompletenew-password) the browser should support `autocomplete="new-password" on these fields to disable autofill; we'll take a look 👍
