### ISSUE TITLE
Seq only saving around 15% of total logs sent to it

### ISSUE THREAD

**Issue by akilin** [datalust/seq-tickets#917]
I was playing around with dockerized seq, and noticed that it only saved a small part of total logs sent to it, without reporting any issues.
Minimal repo with steps to reproduce can be found at the end of this post.

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.File($"log{DateTime.UtcNow.ToString("yyyy-dd-M--HH-mm-ss")}.txt")
    .WriteTo.Seq("http://localhost:5341")
    .CreateLogger();

Serilog.Debugging.SelfLog.Enable(Console.Error);
int counter = 0;
while (counter < 1_000_000)
{
    Log.Information("count is {c} {g}", counter++, counter / 10_000);
}
Log.CloseAndFlush();

```
The code above when executed writes logs to file and seq.
Once the app is done running - file contains 1_000_000 rows as expected, while seq only has 12-20% of that.
select count(*) from stream => 185357 (this number varies between runs, but usually is between 120-200k).
No errors are thrown/written to console.
Diagnostics info can be found inside repo, file `seq-diagnostics-8d79c5e01ed3e68.txt`.

Steps to reproduce:
clone the repo https://github.com/akilin/demo-seq-losing-logs
startup seq in docker: `docker-compose up -d`
run the app: `dotnet run`

**Comment by nblumhardt** [comment]
Hi! Thanks for your ticket. Since the reason for this behavior is a property of the Seq sink for Serilog, I'll answer over on https://github.com/serilog/serilog-sinks-seq/issues/130 - thanks!
