### ISSUE TITLE
Seq Service Administration app doesn't read current settings

### ISSUE THREAD

**Issue by augustoproiete** [datalust/seq-tickets#918]
I have the Seq storage on the `D` drive w/ path set to `D:\ProgramData\Seq\Logs` with the following settings:

```json
{
  "diagnostics": {
    "internalLogPath": "D:\\ProgramData\\Seq\\Logs"
  },
  "api": {
    "listenUris": [
      "http://my-company:5341/"
    ],
  },
}
```

However, when I launch the `Seq Service Administration` app (from `D:\Program Files\Seq\Admin\Seq.Administration.exe`) it presents the default installation values instead of reading from the current configuration defined in `Seq.json`:

![image](https://user-images.githubusercontent.com/177608/72736033-5b769f80-3b73-11ea-8e33-40e081939075.png)

By clicking `Next`, the current settings are overridden (Storage Path, Seq URL, ...) 😞

**Comment by nblumhardt** [comment]
Thanks, Caio - I think we need to sort this out 👍

**Comment by nblumhardt** [comment]
Finally out there in 2020.1.4018-pre :-) 🎉
