### ISSUE TITLE
API-Key not displayed in Diagnostics --> Activity

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#934]
We had recent performance problems with some Seq queries. Thanks to Seq Support and @nblumhardt we were able to solve them.

For our own diagnostics it would be great, if we could see the full query and the corresponding api key in Seq UI. Currently the api key is not displayed under Settings --> Diagnostics --> Activity
For user accounts everything is displayed as expected.

![2020-01-31 13_02_19-Clipboard](https://user-images.githubusercontent.com/10319545/73537923-f69c2e80-4429-11ea-8d2c-50b93b719997.png)
![2020-01-31 12_49_36-Netto S_A Logserver — Seq](https://user-images.githubusercontent.com/10319545/73537927-f865f200-4429-11ea-9027-7e6a140d1e20.png)

Using Seq 5.1.3200 (Windows)

**Comment by nblumhardt** [comment]
Thanks for writing this up, @Sebbl22 ! :+1:

Fixed in v6/master.
