### ISSUE TITLE
[Question] - Seq multitenant cloud instance for super simple sign up

### ISSUE THREAD

**Issue by dazinator** [datalust/seq-tickets#937]
I just wondered if you'd thought about running an instance of Seq in the cloud, where new tenants / customers could sign up and get their own URL like "foo.seq.io" to start consuming seq straightaway. You could then differentiate based on storage consumption, rate limiting, number of apps etc etc.

This thought occurred to me because I deal a lot in multi tenancy. I've created my own multi tenancy library https://github.com/dazinator/Dotnettency for aspnet core and i'd be happy to offer assistance if you ever did want to do something like this.

**Comment by nblumhardt** [comment]
Hi @dazinator - thanks for the note 👍 

At the moment we're focusing all of our energy on enhancing self-hosted availability and resource consumption, but these are foundations that we think are a big part of a multi-tenant setup down the track.

Thanks for the pointer to Dotnettency, will have to check it out :-)
