### ISSUE TITLE
Continued difficulties authenticating with Azure DevOps NuGet feeds

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#938]
@CrossBound writes:

> Sorry, this is still not working. In my case I'm attempting to authenticate against an in-house Azure DevOps server using a username and PAT.

> I'm on Seq version 5.1.3200

![image](https://user-images.githubusercontent.com/11417093/71227686-a9169880-22a5-11ea-8d2e-662726a6d191.png)

![image](https://user-images.githubusercontent.com/11417093/71227770-e5e28f80-22a5-11ea-9890-56e7eaf9c1d6.png)

![image](https://user-images.githubusercontent.com/11417093/71227865-25a97700-22a6-11ea-84e0-0a883145d59c.png)

_Originally posted by @CrossBound in https://github.com/datalust/seq-tickets/issues/741#issuecomment-567772430_

**Comment by nblumhardt** [comment]
Possibly related: https://github.com/datalust/seq-tickets/issues/893

**Comment by nblumhardt** [comment]
Hi @CrossBound, we're just looping back around to this - has the situation improved for you with Seq 5.1.3364? Thanks!

**Comment by CrossBound** [comment]
I haven't updated to version 3364 yet, but I will do that and try again.

Thanks

**Comment by CrossBound** [comment]
I'm still having this issue with version 3364.

**Comment by nblumhardt** [comment]
Thanks, appreciate your help 👍

**Comment by nblumhardt** [comment]
Just re-reading the instructions at: https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/nuget-exe?view=azure-devops

I noticed one thing; the instructions mention changing the v3 feed URL to a v2 one:

![image](https://user-images.githubusercontent.com/342712/82521914-3a4aad80-9b6b-11ea-8881-11eaaac6bef4.png)

It would be rather strange, but, if the Azure DevOps side is using different handlers for v2 and v3 URLs, switching to the v2 endpoint might be the solution.

Right back in the very beginning we tried v2 as well as v3 endpoints for this, but a lot of bugs were fixed in the Seq NuGet client between then and now. May be worth another try.

Setting up to test this again here, now.

**Comment by nblumhardt** [comment]
Hi again; just a note, I created a new Azure DevOps feed (not on-prem, however), used the v2 URL structure mentioned in the screenshot, and successfully installed a package using both Seq 5.1.3364 and Seq 2020.1.4018-pre.

Here's how my feed looks:

![image](https://user-images.githubusercontent.com/342712/82527277-62d9a400-9b79-11ea-8de2-fbd3e8e59fac.png)

Not sure this helps - but does the v2 endpoint sort things out for you?

**Comment by nblumhardt** [comment]
Just another thought - have you tried generating a PAT with all permissions? I generated one with `Packaging (Read & Write)` for my test.

**Comment by nblumhardt** [comment]
I'm going to pull this from the initial 2020.1 milestone as I don't think we'll be able to commit to getting the fix in without some more diagnosis around the issue; keen to hear whether any of the above sheds some light on it! Fingers crossed :-)

**Comment by nblumhardt** [comment]
Assuming this one is no longer causing issues; let us know if the above didn't help 👍
