### ISSUE TITLE
Make new (log)lines appear more clearly when auto-refreshing

### ISSUE THREAD

**Issue by EssentialNRG** [datalust/seq-tickets#939]
When auto refresh is enabled log lines appear with a fade-in effect. This effect makes it difficult to see which lines are newly added and which lines were already in the list.

I think this can easily be enhanced by changing the effect to something like this: https://community.home-assistant.io/t/community-hass-io-add-on-log-viewer/64377

So make the line appear directly, but keep the background highlighted for a little while.

**Comment by nblumhardt** [comment]
Thanks for the suggestion - would definitely be nice to show these with a bit more obvious indicator :+1:

**Comment by EssentialNRG** [comment]
I saw that there are some style overrides available. So I tried to implement this with a couple of CSS lines. Have come up with this so far. IMHO, this way it is way more readable which lines have been newly added.

.stream-view .content .event-list.autorefreshing>.event {
	opacity: 1 !important;
	background: lightgreen;
	transition: background-color 2s ease-out;
}
.stream-view .content .event-list.autorefreshing > .event.entered {
	opacity: 1 !important;
	background: transparent;
}

**Comment by nblumhardt** [comment]
Included in 2020.3.

We're also trying out a new algorithm for the auto-refresh interval in this release: when new events appear, we'll check again in 0.5s to make the UI more responsive. When no new events appear in an interval, we'll fall back to the current 2s polling.

Still some opportunity to tune both parts, but it's a good start :-)

![appear](https://user-images.githubusercontent.com/342712/94506936-e73be200-0251-11eb-8aee-a7e011715ff0.gif)
