### ISSUE TITLE
Allow changing the auto-refresh interval to a shorter interval

### ISSUE THREAD

**Issue by EssentialNRG** [datalust/seq-tickets#940]
Currently the interval for auto-refresh is set to about 2 seconds.

It would be nice if you could change this interval temporarily to a shorter interval (e.g. 500ms or 1 sec).

**Comment by nblumhardt** [comment]
Thanks for the suggestion. Would this be so that you can see new entries faster, or are you envisaging "smoother" scrolling in of events?

**Comment by EssentialNRG** [comment]
This would be so the new entries are shown faster. 
Smooth scrolling would be nice, but that is really just a nice to have.

**Comment by nblumhardt** [comment]
Thanks for the info 👍

Ideally we'll come up with some kind of adaptive mechanism; will give this some thought.

**Comment by nblumhardt** [comment]
Included in 2020.3; check out https://github.com/datalust/seq-tickets/issues/939#issuecomment-700394672 to see it in action.
