### ISSUE TITLE
Allow streaming SQL results

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#941]
I often need to run / graph events over longer timeperiods using `group by time`, which gets over 100x slower once it goes past the 4 days worth of events the 32GB memory affords us. This usually leads to timeouts when i try to run queries over 2+ days of uncached events.

As a workaround, i'm using the time slice cache. This works like so:
You create the desired query for the in memory range, execute it, then you extend the range by one day and re-execute, this time it will skip computing the data for the in memory segments as it got cached in the time slice cache and it just evaluates the one additional uncached segment. Rinse and repeat to put increasingly larger time ranges into the time slice cache while extending the time range the query covers.

All this is very manual and it would be cool if Seq could basically evaluate one time group at a time, return the results and evaluate the next time group.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, this is also something that we agree would be very worthwhile, especially since for timeseries we already have per-slice execution as you've suggested. We'll give this one more thought, too.

**Comment by nblumhardt** [comment]
We've made huge improvements to timeseries execution performance in 2020.1; much of this relies on parallelization and so returning results incrementally is trickier; we're triaging and will close this in the expectation that it's soon going to be less of an issue, feedback once we've published a new preview would be much appreciated, though.
