### ISSUE TITLE
Allow actually cancelling SQL queries

### ISSUE THREAD

**Issue by Suchiman** [datalust/seq-tickets#942]
SQL queries can be visually cancelled in the Seq UI but they'll continue to run until the timeout.

**Comment by nblumhardt** [comment]
Thanks, this would be a great improvement and isn't _too_ far from the capabilities already available server-side (queries are cancellable, but we don't expose anything in the API to facilitate this). We'll give it some thought :+1:

**Comment by nblumhardt** [comment]
Hi! As of 2020.1.4018-pre (just published), long-running queries (and a few other server tasks) can be cancelled from _Settings_ > _Diagnostics_ > _Activities_; it's step 1 of several, but should at least ease up situations where an expensive query is causing problems. HTH!

**Comment by nblumhardt** [comment]
This will work via the "cancel" button next to the filter box for SQL-style queries and event searches in 2020.4 🎉
