### ISSUE TITLE
Alert for different log levels? 

### ISSUE THREAD

**Issue by sgrassie** [datalust/seq-tickets#944]
Sorry, I've not been able to figure this out from either the documentation or playing around.

Given a dashboard component which shows a count of different log levels, grouped by component, like this:

```
select count(*) as count
from stream 
where (App = 'Example') and @Level in ['Error', 'Fatal']
group by Component
```
The condition on the alert only allows for `count > 0`, and not `count > 0 and @Level = 'Fatal'`.

How can I make an Alert just for the Fatal errors, without having to have a separate dashboard component just for Fatal errors?

**Comment by nblumhardt** [comment]
Hi Stuart, thanks for getting in touch.

For this to work, the values used in the alert condition need to be groups in the query.

Alerts are based on `having` clauses under the hood, so this might make it a bit easier to visualize; here's my take on it:

```sql
select count(*) as count
from stream 
where App = 'Example' and @Level in ['Error', 'Fatal']
group by Component, @Level
having count > 0 and @Level = 'Fatal'
```

I.e. the query would need to be:

```sql
select count(*) as count
from stream 
where App = 'Example' and @Level in ['Error', 'Fatal']
group by Component, @Level
```

for that alert condition to work.

Does this help?

Best regards,
Nick

**Comment by sgrassie** [comment]
Thanks Nick, that's embarassingly obvious now!

**Comment by nblumhardt** [comment]
You're welcome, thanks for the follow-up, Stuart 👍
