### ISSUE TITLE
Seq UI accessible from outside the machine where Seq is configured

### ISSUE THREAD

**Issue by pfaustinopt** [datalust/seq-tickets#954]
Is it possible to use the following configuration `listenUris=https://example.mydomain.net:8111` to access the Seq UI via the Internet?

I have attempted to apply this configuration, but when I try to access `https://example.mydomain.net:8111` via the Internet I always get a 403 error. This error also shows when I try to access this endpoint on the machine where Seq is configured.

What am I doing wrong?

**Comment by pfaustinopt** [comment]
I've noticed that I stop having access once I set this:
```
"ingestionPort": 8111,
```

**Comment by nblumhardt** [comment]
Closing this as we've resolved it in another thread - not using `ingestionPort` is the correct way to go in this case :+1: - thanks!
