### ISSUE TITLE
Running dockerized Seq on raspberry pi

### ISSUE THREAD

**Issue by akilin** [datalust/seq-tickets#955]
Hi, this is not really an issue, more like a question.

I am attempting to run Seq on a Raspberry Pi, and it is failing on start (possibly dew to pi running on ARM, but I know too little about this to say for sure).

```
docker run --name seq --rm -it -e ACCEPT_EULA=Y -p 80:80 datalust/seq:latest
standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size
```

Do you have any suggestions on how i can make it work?

**Comment by nblumhardt** [comment]
Hi! This won't be possible because of the executable format, unfortunately - Seq doesn't target ARM, which would need specific (fairly extensive) support in Seq and the libraries it uses. HTH!

**Comment by akilin** [comment]
thank you for quick response
