### ISSUE TITLE
ForContext with word Include doesn't include as a property

### ISSUE THREAD

**Issue by Spinks90** [datalust/seq-tickets#957]
I'm using **Serilog** and **Serilog.Sinks.Seq 4.0** (The latest version which is at time of reporting this issue).

Any word starting with **Include** seems to get excluded on the events of Seq. Here sample code
`
bool includeForecasted = false;
Log.ForContext("IncludeForecasted", includeForecasted).Information("This is a test message");`

However, if you change the word **Include** with anything else, it is included as property correctly. E.g.
`bool includeForecasted = false;
Log.ForContext("BlaForecasted", includeForecasted).Information("This is a test message")`
This code would work totally fine.

**Comment by nblumhardt** [comment]
Hi Paul, thanks for your message.

![image](https://user-images.githubusercontent.com/342712/78721318-a4681400-796a-11ea-9956-88818bdda0d5.png)

Might need to create a minimal repro. If it's a console app - are you missing `Log.CloseAndFlush()`?
