### ISSUE TITLE
Add documentation for Now() function

### ISSUE THREAD

**Issue by CrossBound** [datalust/seq-tickets#960]
I was looking at documentation trying to figure out how to make a relative data query. I thought it didn't exist until I came across this article https://docs.datalust.co/discuss/56c1900e4085c50d00c67141 which led me to this issue https://github.com/datalust/seq-tickets/issues/361.

Sounds like this has been implemented but there doesn't appear to be any mention of the Now() function on this page https://docs.datalust.co/docs/built-in-properties-and-functions.

Maybe an update to documentation is needed?

**Comment by nblumhardt** [comment]
Done, added to https://docs.datalust.co/v2020.1/docs/built-in-properties-and-functions (2020.1 isn't too far from done :-)) - thanks for the catch!
