### ISSUE TITLE
Set initial username/password during installation

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#973]
On Windows, it would be preferable to accept and configure the admin username/password during the setup process, instead of requiring it to be set through the browser on first run.

**Comment by nblumhardt** [comment]
![image](https://user-images.githubusercontent.com/342712/83835798-170c2a80-a735-11ea-89d8-a93333ee60fc.png)

The flow here is:

 * Seq Administration hashes the password and stores the result in _Seq.json_'s `firstRun.adminPasswordHash` field
 * On first run, Seq copies this hash directly into the admin user record

Only the hash is stored on the filesystem, which should minimize the chance of password leakage.

**Comment by Verbient** [comment]
Hi @nblumhardt how could we add the password later on, if we have not configured it during SEQ install

**Comment by Verbient** [comment]
I figured out. I had to clear the browsing history and saved passwords and post that seq showed up the password form only once. Subsequent browsing to the seq site does not ask for password. Is there a way to logout?
