### ISSUE TITLE
Storage View

### ISSUE THREAD

**Issue by KodrAus** [datalust/seq-tickets#978]
Right now, we just keep ingestion metrics for the last day in memory in 2020.1's new ingestion page. Since admins can't easily just look at the extents folders on-disk anymore to get an idea of ingestion over time we could look at surfacing this data using `flaretl` or in the new ingestion page.

**Comment by nblumhardt** [comment]
We've re-cast this as "Storage View", and expect to surface how much data is stored at each point in time for the entire event store.

**Comment by larenelg** [comment]
Hope everyone's doing okay, wherever you are! ❤️

We're almost done with Storage View :) here's a sneaky screenshot

We'll have a preview coming week of 9 Nov, 2020, excited to share it with you all!

![Seq 2020.4 storage view, listing retention policies, and showing stored data volume in a 30-day window.](https://user-images.githubusercontent.com/7476736/98200560-94082e00-1f79-11eb-9ba9-5a8f8b52ea1b.png)
