### ISSUE TITLE
Support yyyy-MM-dd HH:mm:ss in events result list

### ISSUE THREAD

**Issue by larenelg** [datalust/seq-tickets#983]
Currently, we show event timestamp on the left in `dd MMM yyyy HH:mm:ss.fff`

Please let us know if being able to toggle to `yyyy-MM-dd HH:mm:ss` format would be useful, and why?

**Comment by andymac4182** [comment]
This would be great since it matches what I get from other systems logs that are text based. Also it is the same no matter where the system is built.

**Comment by Sebbl22** [comment]
+1 because it's the format I'm used to work with

**Comment by CrossBound** [comment]
I would like to see this because of personal preference (easier to read).

**Comment by colinangusmackay** [comment]
Allowing the user to generally specify their own date format would be ideal.
