### ISSUE TITLE
Bug in 2020.1: Line break in signal property does not work

### ISSUE THREAD

**Issue by erikbra** [datalust/seq-tickets#986]
Entering a filter with the following condition does not work (enter inserted with shift-enter):

```
Not(ExceptionMessage == "Error in the app:
This is the description")
```

![image](https://user-images.githubusercontent.com/1628994/86000808-5402ce80-ba0e-11ea-9043-54913b3ce86d.png)

You get the following error message:

![image](https://user-images.githubusercontent.com/1628994/86000777-4a796680-ba0e-11ea-974e-c60a7d982a27.png)

Deleting the line break solves the issue.

**Comment by nblumhardt** [comment]
Hi Erik, thanks for letting us know.

**Comment by nblumhardt** [comment]
Double-quoted strings should continue to preserve newlines in 2020.1 search expressions.

**Comment by nblumhardt** [comment]
All string literals will accept embedded newlines in the next 2020.1 patch.
