### ISSUE TITLE
Integrated Windows Authentication not working anymore with Seq 2020.1.4212

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#988]
Hi,
when trying to login with Integrated Windows Authentication, a HTTP 500 message is received.
![grafik](https://user-images.githubusercontent.com/10319545/86239228-34e77680-bb9f-11ea-88a6-b108051e9448.png)

Integrated Windows Authentication worked fine in Seq 5.1.3364. 
I tested with Internet Explorer and Firefox (with appropriate configuration settings).

Login by manually entering domain user and password works fine.

**Comment by nblumhardt** [comment]
Thanks for the report, we'll investigate 👍

**Comment by nblumhardt** [comment]
We've reproduced this and will have a fix coming in the next day or so; thanks!

**Comment by nblumhardt** [comment]
Fixed, build is now in testing.
