### ISSUE TITLE
Reduced query performance in Seq 2020.1.4212

### ISSUE THREAD

**Issue by Sebbl22** [datalust/seq-tickets#990]
Hi,
we upgraded to Seq 2020.1.4212 from 5.1.3364. Since then, we see a massively reduced query performance. That is especially noticeable in our dashboard queries, which are often cancelled with this message:
> The server is currently processing several long-running queries; your request was cancelled to prevent I/O exhaustion, please try again shortly.
 
There are no background tasks running, except "Sample system memory", "manage event cache resources" and "monitor alerts and trigger notifications".

We have 24 GB of system memory, but only 0,124 days in RAM since some of our events are very large (Raw ingestion payload limit 10485760, raw event body limit 524288).

In the earlier Seq version, the first dashboard request would take very long (as expected) since a lot of data has to be read from disk. Once loaded, all subsequent refreshes would load very fast. 
In the current Seq version, on the first dashboard request, some dashboard queries would display the above mentioned message and eventually load after some refresh-intervals. The subsequent refreshes also take much longer to complete and also sometimes display the I/O exhaustion message.

Since the Seq update, a lot of Warnings and Errors are logged, which were not present before (Reader generation was cancelled, aborting disk read, Waited xxx so far for one of x disk reader slots):
![grafik](https://user-images.githubusercontent.com/10319545/86242425-010f4f80-bba5-11ea-9f04-8184426d52aa.png)

Our AV-Software is configured to exclude the Seq data directory.

Is there anything I can do to get query performance back to pre-upgrade speed? I was expecting better performance, since they were explicitly mentioned in the blog post for 2020.1

Thank you

**Comment by nblumhardt** [comment]
Thanks for the report - query perf should improve across the board in 2020.1, so this isn't at all expected. Running with very large events could be exercising some code path we haven't considered, however 🤔 

There's also a chance that some underlying issue is preventing e.g. correct cache function. If you can send the diagnostic report from _Settings > Diagnostics_, or as much info from it as possible, through to `support@` we can dig in deeper. Thanks!

**Comment by nblumhardt** [comment]
Hi @Sebbl22 - hope you've had a good week.

Has this improved, now that the other issues impacting search have been resolved?

Best regards,
Nick

**Comment by Sebbl22** [comment]
Hi @nblumhardt,
query performance seems to be good now. Unfortunately, I don't know for sure, what caused the inital problems.
This issue can be closed.

**Comment by nblumhardt** [comment]
Great to hear, thanks Sebastian!
