### ISSUE TITLE
Support the `secure` cookie attribute for `Seq-Session`

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#999]
Seq should add the `secure` attribute to its session cookie when possible to do so. The `secure` attribute instructs the browser to send the cookie over HTTPS only, and not over unencrypted HTTP requests to the same domain.

This ticket proposes a new setting, `api.assumeHttps`, that will enable HSTS and set the `secure` attribute on all cookies regardless of the protocol by which a request is being served, and independently from `api.redirectHttpToHttps`, which also influences this behavior.

**Comment by larenelg** [comment]
You can now restrict the Seq cookie (`Seq-Session`) to https via the `api.assumehttps` configuration setting. You can set this through server configuration (needs `seq restart` for it to take affect):

```
seq config set -k api.assumehttps -v True
seq restart
```

Or via the environment variable `SEQ_API_ASSUMEHTTPS` (overwrites server configuration):

```
docker run --name https-seq -e ACCEPT_EULA=Y -e SEQ_API_ASSUMEHTTPS=true -p 5341:80 datalust/seq
```

It's important to note that you will no longer be able to login to your Seq instance over http when this variable is set (e.g. in a local development environment).
